### PR TITLE
History export

### PR DESCRIPTION
**Pull request by Changaco**
Implements #796.

### CODE REVIEW

**Comment by whit537** [comment]
Gimme at least one test. :baby_chick:

**Comment by whit537** [comment]
This gives us a nice function for generating exports, but only exposes a fraction of it in the UI. We can merge this and move on to other things, but we could do a lot better at exposing the available functionality in the UI.

**Comment by whit537** [comment]
I need a test to merge this. I'll reticket exposing the rest in the UI if you want to let this close #796.

**Comment by Changaco** [comment]
I couldn't figure out a good UI quickly, and I had higher priority issues to work on, so I moved on.

**Comment by Changaco** [comment]
Tests added.

**Comment by whit537** [comment]
lgtm. Fine to merge when Travis is green.

**Comment by whit537** [comment]
Reticketed #3255.

**Pull request merged**
