### PR TITLE
move cached value computation into triggers

### PR DESCRIPTION
**Pull request by whit537**
&#x2B11; #3994

&larr; #4037 — #4023 &rarr;

#### Punchlist 

- [ ] remake against `master` once #4037 lands

### CODE REVIEW

**Comment by whit537** [comment]
Here are the four given values:

| i | name | property&nbsp;of | description |
|---:|:--------|:-------|:-------------|
| 1 | **payment&nbsp;instruction** | participant | amount of money the participant intends to pay a given team, weekly |
| 2 | **ownership** | participant | a team owned by the participant |

All the other numbers we care about can be computed from those four:

| i | name | property&nbsp;of | function |
|---:|:--------|:-------|:-------------|
| 1 | _giving_ | participant | sum of **payment instructions** from the given participant |
| 2 | _ngiving_to_ | participant | number of **payment instructions** from the given participant |
| 3 | _receiving_ | team | sum of **payment instructions** to the given team |
| 4 | _nreceiving_from_ | team | number of **payment instructions** to the given team |
| 5 | _distributing_ | team | *receiving* |
| 6 | _ndistributing_to_ | team | 1 |
| 7 | _taking_ | participant | sum of _receiving_ for all **ownerships** |
| 8 | _ntaking_from_ | participant | count of **ownerships** |

-------------

**given values** are bold
*computed values* are in italics

**Comment by whit537** [comment]
```
payment_instruction
    giving
    ngiving_to
    receiving
    nreceiving_from
receiving
    distributing
    taking
ownership
    taking
    ntaking_from

giving              payment_instruction
ngiving_to          payment_instruction
receiving           payment_instruction
nreceiving_from     payment_instruction
distributing        receiving
ndistributing_to
taking              receiving           ownership
ntaking_from        ownership
```

Key: https://github.com/gratipay/gratipay.com/pull/4023#issuecomment-219128785.

**Comment by whit537** [comment]
screen shot 2016-06-02 at 1 10 10 pm

```
digraph G {
    "giving" -> "payment_instruction" [dir=back]
    "ngiving_to" -> "payment_instruction" [dir=back]
    "receiving" -> "payment_instruction" [dir=back]
    "nreceiving_from" -> "payment_instruction" [dir=back]
    "distributing" -> "receiving" [dir=back]
    "taking" -> "receiving" [dir=back]
    "taking" -> "ownership" [dir=back]
    "ntaking_from" -> "ownership" [dir=back]
}
```

http://www.webgraphviz.com/

**Comment by aandis** [comment]
How does this relate to https://github.com/gratipay/gratipay.com/issues/3727? For example -

| i | name | property&nbsp;of | function |
|---:|:--------|:-------|:-------------|
| 1 | _giving_ | participant | sum of **payment instructions** from the given participant *not including broken payments.*|

**Comment by aandis** [comment]
https://github.com/gratipay/gratipay.com/issues/3727#issuecomment-193297891 for reference.

**Comment by whit537** [comment]
Hmm ... good question.

**Comment by whit537** [comment]
@aandis Over here @kaguillera and I are thinking that we should only tackle migration of existing cached values functionality in this PR. Then when we get to #3727 we would approach it by modifying the triggers that we introduce on this PR. Sound right to you?

**Comment by aandis** [comment]
:+1:

**Comment by whit537** [comment]
Hmm ... the present reality is already a bit more complicated:

screen shot 2016-06-13 at 10 18 04 am

```
digraph G {
    "is_funded" -> "last_bill_result" [dir=back]
    "funded payment instruction" -> "is_funded" [dir=back]
    "funded payment instruction" -> "amount" [dir=back]
    "giving" -> "funded payment instruction" [dir=back]
    "ngiving_to" -> "funded payment instruction" [dir=back]
    "receiving" -> "funded payment instruction" [dir=back]
    "nreceiving_from" -> "funded payment instruction" [dir=back]
    "distributing" -> "receiving" [dir=back]
    "taking" -> "receiving" [dir=back]
    "taking" -> "ownership" [dir=back]
    "ntaking_from" -> "ownership" [dir=back]
}
```

**Comment by whit537** [comment]
Closing in favor of a new PR against master, since we want this code _before_ team preliminaries (#4037).

**Comment by whit537** [comment]
New PR is #4063.

**Pull request closed without merging**
