### PR TITLE
turn on subscriptions

### LINKED ISSUE #3432: turn subscriptions back on in UI
Ok, that sounds stupid but I can't find the donation widget anywhere in the site.

I am using Firefox 36.0.4 on linux. I browsed the site with the console open but did not see any js error popping up.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/15039098-turn-subscriptions-back-on-in-ui?utm_campaign=plugin&utm_content=tracker%2F85909&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F85909&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by whit537**
Closes #3432.

### CODE REVIEW

**Comment by whit537** [comment]
I'm leaving the work of convert Profile > Giving to Profile > Subscriptions to another PR: #3468.

**Comment by whit537** [comment]
Ready for review, @rohitpaulk et al.

**Comment by whit537** [comment]
Now that #3469 is deployed, this is our only blocker to https://github.com/gratipay/gratipay.com/issues/3419#issuecomment-103870467.

**Comment by rohitpaulk** [comment]
I don't have time today for a complete review - I tested this on a backup and from the outside, seems to work fine. One quick problem I see - When I cancel a tip, the notification says -

> Payment changed to $0.00 per week. Thank you so much for supporting Gratipay!

**Comment by whit537** [comment]
@rohitpaulk Okay. I *reeeeeeaaaallly* want to get #3419 out the door so we can respond to all of these users that are waiting to hear from us. If you're not able to review this tomorrow then we should either a) deploy w/o a full review, or b) revise #3419 to say we're still working on this.

**Comment by rohitpaulk** [comment]
I say go ahead and deploy :)

**Comment by whit537** [comment]
Okay! :dancer:

**Pull request merged**
