### PR TITLE
Send an email to project owner when application is submitted

### LINKED ISSUE #4430: Send email with link to review ticket
When someone claims packages or otherwise applies for a project, they should get an email with a link to the review ticket. It shouldn't just be in the web page and then disappear.

### PR DESCRIPTION
**Pull request by mattbk**
Closes #4430.

Plain text seems to work, but no tests yet.

### CODE REVIEW

**Comment by mattbk** [comment]
Need to space out information as in approval email:
```
To:       mattbk <foo@bar.com>
Subject:  Project Application Approved!
Body:

    Greetings!
    
    We've approved your application for the 'aaa' project on Gratipay. For details, please refer to our review ticket:
    
    some-github-issue
    
    Thanks for using Gratipay! :-)
    
    Something not right? Reply to this email for help.
    
    ----
    
    Sent by Gratipay, LLC, https://gratipay.com/
    716 Park Road, Ambridge, PA, 15003, USA
```

**Comment by rohitpaulk** [comment]
Looks good to me. @mattbk do you have a screenshot handy? One quick look and we can get this moving

**Comment by mattbk** [comment]
image


image

**Comment by rohitpaulk** [comment]
I'm happy once Travis is

**Pull request merged**
