### PR TITLE
link to Review Teams howto from Team application

### LINKED ISSUE #3677: Clarify team application process and parameters on application page
Reticketed from https://github.com/gratipay/applications/issues/17#issuecomment-129905354, which I think is a great, civil discussion about how the team application process is perceived and fuzzy and open to misunderstanding.

In particular, 
- team application guidelines should be spelled out explicitly on the [team application page](https://gratipay.com/new), and
- legal reasons behind requiring applications should be explained in the site documentation, not solely on blog posts.

I ask that discussion of the application policies be kept in a separate ticket at [inside.gratipay.com](https://github.com/gratipay/inside.gratipay.com/issues?utf8=%E2%9C%93&q=is%3Aissue++sort%3Aupdated-desc+) and this ticket be retained for implementation or rejection of this change.  Hopefully this will avoid confusing the two subjects.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/25656539-clarify-team-application-process-and-parameters-on-application-page?utm_campaign=plugin&utm_content=tracker%2F85909&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F85909&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by whit537**
Closes #3677 and https://github.com/gratipay/inside.gratipay.com/issues/311.

### CODE REVIEW

**Comment by whit537** [comment]
We ready to merge this and close those two tickets, @mattbk?

**Comment by mattbk** [comment]
Looks good.

**Comment by whit537** [comment]
@mattbk Can I let you merge this? :-)

**Comment by whit537** [comment]
!m @mattbk

**Pull request merged**
