### PR TITLE
Re-add link to ~user widgets

### LINKED ISSUE #3924: Re-add widget menu item
The widget menu item should be added back for ~~Teams only, not~~ for individual ~users.

(Change in direction at https://github.com/gratipay/gratipay.com/pull/4172).

------------

https://gratipay.com/about/me/widgets/ was removed when widgets broke after Gratipay 2.0.

Can be done after the [Widgets for Gratipay 2.0](https://github.com/gratipay/grtp.co/milestones/Widgets%20for%20Gratipay%202.0) milestone is closed.
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/31089481-re-add-widget-menu-item?utm_campaign=plugin&utm_content=tracker%2F85909&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F85909&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by mattbk**
Also add a link to widget docs. Closes #3924.

### CODE REVIEW

**Comment by mattbk** [comment]
Since https://github.com/gratipay/gratipay.com/pull/4172 is already merged and this is just adding the link and some text, I'll self-merge once Travis is green (forgot to `make pytest` locally again :unamused:).

**Comment by whit537** [comment]
> I'll self-merge

Look what I've started. 😞

**Comment by mattbk** [comment]
Feel free to revert and merge again.

**Comment by whit537** [comment]
No, that's fine. If wanna make a big deal out of it I need to stop self-merging my _own_ stuff first. :)

**Pull request merged**
