### PR TITLE
Add team receiving page

### PR DESCRIPTION
**Pull request by rohitpaulk**
https://github.com/gratipay/gratipay.com/issues/3705, https://github.com/gratipay/gratipay.com/issues/3779

### CODE REVIEW

**Comment by rohitpaulk** [comment]
Screenshots: 

screen shot 2015-12-12 at 8 28 45 pm

Payment distribution:

screen shot 2015-12-12 at 8 28 55 pm

**Comment by rohitpaulk** [comment]
I'm made the team pages visible to only admins and the team's owner. My reasoning here is that the values we are exposing aren't polished enough to show to the general public. For example, the below graph would make sense to the owner of a team who is aware of charging in arrears - but to others, it'd just look like the number of payments reduced drastically over a week. 

screen shot 2015-12-12 at 9 48 19 pm

Here are a few pages generated from our DB (team names hidden): 

screen shot 2015-12-12 at 9 45 33 pm
screen shot 2015-12-12 at 9 45 04 pm

**Comment by rohitpaulk** [comment]
The estimated next week's payment for Gratipay looks out of line though... 

screen shot 2015-12-12 at 9 45 56 pm

Probably a bug somewhere, I'm going to write a few simple test cases to see if something pops up

**Comment by rohitpaulk** [comment]
The values of unfunded dues are pretty high for most teams, that's due to https://github.com/gratipay/gratipay.com/issues/3818

**Comment by mattbk** [comment]
Nice!

**Comment by rohitpaulk** [comment]
Rebased on master after https://github.com/gratipay/gratipay.com/pull/3787

**Comment by rohitpaulk** [comment]
> The values of unfunded dues are pretty high for most teams, that's due to #3818

Fixed that in #3876, lets look if these values look better after those changes...

**Comment by rohitpaulk** [comment]
Before: 

screen shot 2015-12-12 at 9 45 56 pm

After:

screen shot 2015-12-16 at 9 26 27 pm

**Comment by rohitpaulk** [comment]
The estimated payment is definitely closer, but still pretty high. The last bar in "Dollars received per week" is ~$275.

**Comment by rohitpaulk** [comment]
Everything looks right from my side, I guess we'll find out how good this 'estimated' value is tomorrow :)

**Comment by rohitpaulk** [comment]
I'm going to run a script to generate the estimated values for all teams - And I'll write another one to compare them once we run Payday.

**Comment by whit537** [comment]
@rohitpaulk My main concern after once read-through of this PR is that hiding the receiving amount sets a precedent. If we would rather have team receiving be public then we should make it that way from the outset.

**Comment by rohitpaulk** [comment]
> If we would rather have team receiving be public then we should make it that way from the outset.

There's a reason behind this, mentioned at https://github.com/gratipay/gratipay.com/pull/3873#issuecomment-164165342

> I've made the team pages visible to only admins and the team's owner. My reasoning here is that the values we are exposing aren't polished enough to show to the general public. For example, the below graph would make sense to the owner of a team who is aware of charging in arrears - but to others, it'd just look like the number of payments reduced drastically over a week.

Once I've worked on #3851, I'll work on https://github.com/gratipay/gratipay.com/issues/3705#issuecomment-164167705 and then this will be ready to be shown to the public. 

(said the same over at https://github.com/gratipay/gratipay.com/issues/3705#issuecomment-164168024)

**Comment by rohitpaulk** [comment]
I'm not confident that this is a good enough user experience for the public - but it certainly is for a team owner. And we know from our own experience that huge PRs don't make it till production, hence the attempt to make incremental improvements :)

**Comment by whit537** [comment]
> I'm not confident that this is a good enough user experience for the public - but it certainly is for a team owner.

Right, but it doesn't seem right to roll this out as a private page and then *automatically* make it a public page at some point in the future. If we roll it out as private that'll become the default by default, and we'll have to add a switch to opt in to sharing it publicly once that's ready. I don't think we want that, because openness should be the default for Teams on Gratipay. I'm disinclined to even offer private receiving as an option, actually.

> And we know from our own experience that huge PRs don't make it to production,

Well, that's true. :disappointed: 

> hence the attempt to make incremental improvements :)

In the past, of course, we've simply "released early and often" even if the UX is half-baked (at best). If we want to start raising the bar on what we're willing to release, then one pattern we could try is to make PRs against PRs—PR inception! <:-) That keeps our batch size small for the primary review queue so we can process it efficiently, while giving us a chance to aggregate work units for release based on user-centric concerns. See https://github.com/saxifrage/cityasacampus/pull/364 for an example.

The three options I'm seeing are:

 - Deploy this as-is. Team receiving pages are private by default.
 - Make Team receiving pages public, and then deploy. They're confusing for the general public.
 - Block this on #3851 and https://github.com/gratipay/gratipay.com/issues/3705#issuecomment-164167705, using PRs against this PR as necessary.

How do you think we should proceed, @rohitpaulk?

**Comment by rohitpaulk** [comment]
I'm against option 3, PRs against PRs don't really solve the core problem, which is PRs going stale. Everything works fine as long as we're moving fast - but if someone decides to create the second PR (on top of one) 3 months later, it's still going to be difficult to rebase and update the base PR. What PRs against PRs does solve, is huge PRs that are difficult to review. Since we make our commits oh-so-atomic, I don't think that's a big problem for us :)

Although I think that option 1 is the way to go, both option 1 and 2 are fine with me. Thoughts, @mattbk @webmaven @techtonik @rorepo @kzisme?

**Comment by whit537** [comment]
> I'm against option 3, PRs against PRs don't really solve the core problem, which is PRs going stale. Everything works fine as long as we're moving fast - but if someone decides to create the second PR (on top of one) 3 months later, it's still going to be difficult to rebase and update the base PR.

Agreed.

> both option 1 and 2 are fine with me. 

I'm fine with option 2 if no-one else objects. To soften the blow we could add a note to the chart like we used to have about "minimum charge upped to $10 in week 8" or whatever. There may still be a `note` CSS class hanging around for this occasion.

This PR is good work and we should get it out there! :-)

**Comment by mattbk** [comment]
I see option 1 as a "beta" to allow team owners to give feedback on how accurate it seems ("truthiness," not actual math). If it's deployed privately with a statement that it will be made public in the future (when we decide it's out of beta), it should end up being opt-out, rather than opt-in.

**Comment by whit537** [comment]
> it should end up being opt-out, rather than opt-in.

Why opt-*anything*? Options are confusing.

> I see option 1 as a "beta" to allow team owners to give feedback on how accurate it seems ("truthiness," not actual math).

I could maybe see that if we turned it off entirely for a while to rework it based on feedback before releasing publicly.

**Comment by whit537** [comment]
> If we roll it out as private that'll become the default by default, and we'll have to add a switch to opt in to sharing it publicly once that's ready.

@mattbk @rohitpaulk I haven't seen you directly address this. Do you admit this consequence of option 1 yet accept it? Or do you not admit this consequence? Or ... ?

**Comment by rohitpaulk** [comment]
> I haven't seen you directly address this

I think this depends on how we present it... As long as we make it clear (by adding a note, as @mattbk suggested) that we intend to make it public in the near future, we won't be deceiving anyone. If we face significant pushback on the same, it's probably a sign that we should reconsider providing anonymous receiving options.

> I see option 1 as a "beta" to allow team owners to give feedback on how accurate it seems ("truthiness," not actual math). If it's deployed privately with a statement that it will be made public in the future (when we decide it's out of beta), it should end up being opt-out, rather than opt-in.

> Why opt-anything? Options are confusing.

Shouldn't we consider deciding this based on the feedback that we receive from team owners? Rather than forcing this upon them - why not open this to them and see what they have to say?

**Comment by rohitpaulk** [comment]
This is blocked on https://github.com/gratipay/gratipay.com/pull/3876

**Comment by rohitpaulk** [comment]
Rebased on master at @ec2c732d822cb446dd8c43540c5a7c3a9ea8522a. Previous head was @673475357000a7f0bf8e5fd4a6fff58843734a0f

**Comment by rohitpaulk** [comment]
#3980 and #3981 are out, this is no longer blocked.

**Comment by rohitpaulk** [comment]
Rebased on master.

**Comment by rohitpaulk** [comment]
Did a bit of browsing through on a recent backup, the charts look okay to me.

**Comment by whit537** [comment]
Alright, this is super-rough but [we know that](https://github.com/gratipay/gratipay.com/pull/3873#issuecomment-164165342). I'm merging in order to [keep our velocity up](https://github.com/gratipay/gratipay.com/pull/3873#issuecomment-165449001). I've reticketed #3992 for further iteration, still on Finish Team Basics.

!m @rohitpaulk

**Comment by whit537** [comment]
(P.S. Also this is read-only so it's low-risk.)

**Pull request merged**
