### PR TITLE
Move to Amazon SES

### PR DESCRIPTION
**Pull request by rohitpaulk**
https://github.com/gratipay/inside.gratipay.com/issues/515

Steps before deploy:

- [x] Add `AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY` and `AWS_DEFAULT_REGION` env vars
- [x] Confirm that we're ready to send emails through SES. (https://github.com/gratipay/gratipay.com/pull/3995#issuecomment-214470511)

Steps after deploy: 

- [ ] Remove `MANDRILL_KEY` env var
- [ ] Send yourself an email and verify

### CODE REVIEW

**Comment by rohitpaulk** [comment]
screen shot 2016-04-25 at 11 45 53 pm

🎉

**Comment by rohitpaulk** [comment]
https://github.com/gratipay/gratipay.com/pull/3995#issuecomment-214468273 was using my credentials, now I'm going to create an IAM user to use on Heroku and make sure it only has the permissions necessary.

**Comment by rohitpaulk** [comment]
So I created an IAM user named `emails_production`, and attached the following policy to it. 

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "Stmt1461608394000",
            "Effect": "Allow",
            "Action": [
                "ses:SendEmail",
                "ses:SendRawEmail"
            ],
            "Resource": [
                "*"
            ]
        }
    ]
}
```

I used these credentials on my local, and tried sending to `rohitpaulk@live.com` (a verified email on SES) and  `rohitpaul@iitrpr.ac.in` (a non-verified email on SES).

**Comment by rohitpaulk** [comment]
Hmm, looks like the JS tests are failing because we haven't mocked the mailer... i.e. They were working before only because they hit Mandrill.

**Comment by whit537** [comment]
@kaguillera and I are picking up with this ...

**Comment by whit537** [comment]
https://github.com/gratipay/gratipay.com/issues/3978 would help with cc57080bd4d1a9c8ed446a96225b904e3c4f6529.

**Comment by rohitpaulk** [comment]
I think the best way to move forward for now is to disable that one JS test, and create two tickets - 

- [ ] Mock mailer in JS tests + turn the disabled test back on
- [ ] Improve how emails are handled in development process

**Comment by rohitpaulk** [comment]
^ That's the quickest way out, not necessarily the best :)

**Comment by whit537** [comment]
@rohitpaulk Yeah, that's the impression I'm getting. I think we will spend a little time looking for a better fix before we bail and go the easy route ...

**Comment by whit537** [comment]
We're trying to determine whether "until April 27" is inclusive or not. 💅 

https://mandrill.zendesk.com/hc/en-us/articles/217467117

**Comment by whit537** [comment]
Looks like it's inclusive. 😌 

screen shot 2016-04-27 at 12 53 28 pm

**Comment by rohitpaulk** [comment]
^ That's an assumption 😛 They could be gathered around a terminal ready to hit `terraform destroy` right now

**Comment by whit537** [comment]
What was the failing test testing? Why was it added in the first place?

**Comment by whit537** [comment]
@rohitpaulk Sure. 👅  We'll keep checking ...

**Comment by whit537** [comment]
Test entered in #3986.

**Comment by whit537** [comment]
I'm trying to determine whether implementing #3978 will be an acceptable fix for the js failure here. I think it will be!

**Comment by rohitpaulk** [comment]
I can barely keep my eyes open, had a long day today. I hope I've left enough information here for the both of you to land this :)

**Comment by whit537** [comment]
In other words, the test over there is to make sure our JavaScript plumbing is correct (we were fixing a regression where we modified part of our JavaScript API without fully propagating the change through the rest of our JavaScript). The js test doesn't need to care whether the mail is sent out through a mailer or dumped to the console, only that it's sent (or "sent," pseudo-sent) one way or another.

**Comment by whit537** [comment]
@rohitpaulk Yeah, man. I think we're good. Thanks for all your work here! :-)

**Comment by whit537** [comment]
Okay! I think our plan over here is to implement #3978 on this branch. That should fix the js failure and also make the dev experience better.

**Comment by whit537** [comment]
Getting a different error locally:

```
  verify email
    1) should not throw error on clicking resend


  6 passing (43s)
  1 failing

  1) verify email should not throw error on clicking resend:

      Uncaught AssertionError: 'Internal Server Error' == 'The verification code for alice@gratipay.com is bad.'
      + expected - actual

      -Internal Server Error
      +The verification code for alice@gratipay.com is bad.
      
      at WebdriverIO.<anonymous> (tests/js/test_verify_email.js:26:24)
```

**Comment by whit537** [comment]
Blaaaaaaaaaaaam.

```
pid-65363 thread-140735282885376 (MainThread) Renderers (*ed are unavailable, CAPS is default):
pid-65363 thread-140735282885376 (MainThread)   json_dump        
pid-65363 thread-140735282885376 (MainThread)   jsonp_dump       
pid-65363 thread-140735282885376 (MainThread)   stdlib_template  
pid-65363 thread-140735282885376 (MainThread)   stdlib_format    
pid-65363 thread-140735282885376 (MainThread)   jinja2           
pid-65363 thread-140735282885376 (MainThread)   STDLIB_PERCENT   
pid-65363 thread-140735282885376 (MainThread) Won't log to Sentry (SENTRY_DSN is empty).
pid-65363 thread-140735282885376 (MainThread) AWS not configured! Mail will be dumped to the console here.
------------------------------------------------------------------------------
To:       whit537 <chad@zetaweb.com>
Subject:  Connect to whit537 on Gratipay?
Body:

    Greetings!
    
    We've received a request to connect chad@zetaweb.com to the whit537 account on Gratipay. Sound familiar?
    
    Follow this link to finish connecting your email:
    
    http://localhost:8537/~whit537/emails/verify.html?email2=[]~~&nonce=[]
    
    Something not right? Reply to this email for help.
    
    ----
    
    Sent by Gratipay, LLC, https://gratipay.com/
    716 Park Road, Ambridge, PA, 15003, USA

------------------------------------------------------------------------------
pid-65363 thread-140735282885376 (MainThread) 200 OK                               /~/whit537/emails/modify.json ./~/%username/emails/modify.json.spt
```

**Comment by whit537** [comment]
`make jstest` passes locally now. Waiting for Travis ...

**Comment by whit537** [comment]
@kaguillera and I are gonna configure AWS locally as a pseudo-staging environment to satisfy ourselves that our `boto` usage is kosher, then we'll deploy this!

**Comment by whit537** [comment]
Free Tier requires a credit card:

screen shot 2016-04-27 at 1 56 58 pm

**Comment by whit537** [comment]
Dug http://docs.aws.amazon.com/ses/latest/DeveloperGuide/mailbox-simulator.html out of cc57080bd4d1a9c8ed446a96225b904e3c4f6529 ...

**Comment by whit537** [comment]
How about a separate sandbox account under our main AWS account?

**Comment by whit537** [comment]
> How about a separate sandbox account under our main AWS account?

Looks like we've already got an `emails_development` user account.

> So I created an IAM user named `emails_production`, and attached the following policy to it.

We've recreated the policy as a "customer managed policy" rather than an "inline policy" (on the user) and have applied it to both `emails_development` and `emails_production`. We've generated an access key for `emails_development` that we'll now use to test ...

**Comment by whit537** [comment]
Yesssssssssss.

screen shot 2016-04-27 at 2 23 50 pm

**Comment by whit537** [comment]
Let's go over DNS. We don't get the "via" message from Mandrill.

screen shot 2016-04-27 at 2 24 42 pm

**Comment by whit537** [comment]
DNS configured (`include:amazonses.com` added to SPF, three `*.dkim.amazonses.com` `CNAME`s added).

**Comment by whit537** [comment]
Alright, might need a little more config ([`MAIL FROM`](https://docs.aws.amazon.com/ses/latest/DeveloperGuide/mail-from.html)?), but I think we're good enough to get this out the door ... before Mandrill's `terraform destroy`! 😱

**Comment by whit537** [comment]
Envvars converted from `AWS_*` to `AWS_SES_*` in prod, releasing ...

**Comment by whit537** [comment]
> Remove `MANDRILL_KEY` env var

... not just at Heroku, but also https://github.com/gratipay/gratipay.com/pull/3995/commits/e9234f1178179d79b9a677cd30e87bdb856e3d7b. 😳

**Comment by whit537** [comment]
Scratch that. Just at Heroku. (I was worried that https://github.com/gratipay/gratipay.com/pull/3995/commits/e9234f1178179d79b9a677cd30e87bdb856e3d7b was premature.)

**Pull request merged**
