### PR TITLE
Clean up UX some more

### PR DESCRIPTION
**Pull request by whit537**
Part of #4305, follows on #4410.

- [x] ~~asterisk-out email addresses, ya?~~—let's wait for demand, these are all public in the npm registry
- [x] still getting a fouc on claim form?
- [x] add a nice mail icon for current selection in dropdown
- [x] add a nice dropdown arrow icon
    - [x] highlight that instead of name on hover when closed
- [x] implement status icons
    - [x] primary &rarr; feature
    - [x] verified &rarr; success
    - [x] unverified &rarr; [none]
    - [x] unlinked &rarr; warning
    - [x] other &rarr; failure
- [x] implement `disabled` (for emails linked to other accounts)
    - [x] disable Apply button when there are no "Ready to link" emails
- [x] if only one email, treat differently?
    - [x] no ~~radio~~ dropdown?
    - [x] no i?
- [x] double-check .details (grep it)
- [x] make the Sign In button bigger, too
- [x] cross-browserize
- [x] ~~seeing an off-by-one in hover state while scrolling?~~ &hellip; bumped to https://github.com/gratipay/gratipay.com/issues/4415

### CODE REVIEW

**Comment by whit537** [comment]
91e6e45a77f9ac1acb6691c2a7dc6b8e54f0f07d:

zkyncq4eb3

**Comment by whit537** [comment]
aad63cef5f5ffe839d661f16972b7ae7dcf344ed:

190vjs9tox

**Comment by whit537** [comment]
Actually, I'm not sure the status icons work here. On the project listing there is a profile pic to take most of the visual weight. Here we don't have that, so the status icons pop ... too much, I think.

screen shot 2017-04-17 at 3 48 22 pm

**Comment by whit537** [comment]
Okay. a79240d7c89ae94c16a0b9f7008abe3d82321603 implements status icons for the most important statuses. Unlinked accounts don't have an icon.

screen shot 2017-04-17 at 4 06 57 pm

On a different account:

screen shot 2017-04-17 at 4 08 58 pm

**Comment by whit537** [comment]
Actually, how about `warning` for half-linked? 3dd13da6950e763042af83b23f3367c2bc1bee67

screen shot 2017-04-17 at 4 39 08 pm

**Comment by whit537** [comment]
4b9fb97f86d9411b01bfa6958c60b2e35f8dbac8:

eiddbk5wia

**Comment by whit537** [comment]
Started hacking on disabling items in e7b90e3bcd81c2329b812e1c629c65a4ed5788df, will pick up with that next time.

screen shot 2017-04-17 at 5 39 12 pm

**Comment by whit537** [comment]
Re: af443c98a60d49d25881b56afff306efc9debb0d, looks like `text-overflow: ellipsis` can violate the padding.

screen shot 2017-04-18 at 11 31 50 am

**Comment by whit537** [comment]
???

mjvgecw9jc

**Comment by whit537** [comment]
Opacity generates a new stacking context.

https://philipwalton.com/articles/what-no-one-told-you-about-z-index/

**Comment by whit537** [comment]
I tried obfuscating emails in 47eeb4c3d0fbd2a82fd5e639bbba5691effd0779, but it looks weird. In addition to being public info, this view is also only for auth'd users.

screen shot 2017-04-19 at 7 52 53 am

**Comment by whit537** [comment]
Let's punt on treating single emails differently. A select is still a select with only one item.

**Comment by EdOverflow** [comment]
> I tried obfuscating emails in 47eeb4c, but it looks weird. In addition to being public info, this view is also only for auth'd users.

I agree that there is no real need for obfuscation in this particular instance, but I just wanted to say that I prefer the asterisks over the dashes. 😉

**Comment by whit537** [comment]
Haven't checked in IE but working in recent Chrome, FF, Safari. Haven't checked on mobile but let's do that on a different PR.

**Comment by whit537** [comment]
Aright, macro in 89c5789fc1a69eb6aac6c993b41fbf681b8150cb ... derp, broken. :-/

Sooo ... fix that, then I'm looking at enlargening the button for the npm package page. There's already a class `large` in `buttons.scss` that's not used anywhere that I can see. But there *is* a `larger` class that's used but not defined. :man_facepalming:

**Comment by whit537** [comment]
> not used anywhere

Sike, we're using it for the "Apply to accept payments" button.

I think I'm going to hack this in `pages/package.scss` to avoid cross-contamination with the sign-in dropdown in the header.

**Comment by whit537** [comment]
... which means we don't need the macro.

**Comment by whit537** [comment]
Well, maybe it helps.

**Comment by whit537** [comment]
cd2f10cec13123eaa5b8726f3c36cb88ecbfab79

--------------------------

gzfcuzt0v3

**Comment by whit537** [comment]
> seeing an off-by-one in hover state while scrolling?

**Steps**:

1. Load a package with lots of emails, such as kine.
1. Open select.
1. Scroll and move mouse until you see the mouse hovering over one item but the adjacent element (above? always above?) highlighted instead.

**Expected**

Item under mouse is always highlighted.

**Actual**

Adjacent is highlighted.

**Comment by whit537** [comment]
Eff it. Bumping to https://github.com/gratipay/gratipay.com/issues/4415.

Ready for review!

**Comment by whit537** [comment]
Rebased, was cd2f10cec13123eaa5b8726f3c36cb88ecbfab79.

**Comment by whit537** [comment]
Rebased to pick up 47ad781406bbc5d1bec5e12f5fc8bcb08a950177 in #4410, was 1c6ad4b00dece589872eabaedfa146ee14542238.

**Pull request merged**
