### PR TITLE
Add route to record exchange spt

### PR DESCRIPTION
**Pull request by rohitpaulk**
#3295 

- [x] Add route to `record-an-exchange.spt`
- [x] Add route to MassPay calls to `record-an-exchange.spt`

### CODE REVIEW

**Comment by rohitpaulk** [comment]
screenshot from 2015-04-21 19 02 53

**Comment by whit537** [comment]
Remind me what this helps us with? Is there a relevant ticket?

**Comment by rohitpaulk** [comment]
@whit537 - Sure. #3295 is the ticket.  

Before we start filling the `route` values for previous exchanges, we should make sure that no new exchanges are created with a NULL `route`. As of now, `record-an-exchange.spt` is the only place where this happens (MassPay uses it, so that too).  That's what this PR aims to fix.

**Comment by whit537** [comment]
Cool, thanks for the context.

**Comment by whit537** [comment]
> Before we start filling the `route` values for previous exchanges

#2779

**Comment by rohitpaulk** [comment]
This can wait, it's not blocking our move away from Balanced.

**Comment by whit537** [comment]
!m @rohitpaulk 

Yay! :dancer:

**Pull request merged**
