### PR TITLE
enable 1.0 payouts indefinitely

### PR DESCRIPTION
**Pull request by whit537**
To complement https://medium.com/gratipay-blog/39c07bd031b.

### CODE REVIEW

**Comment by mattbk** [comment]
😛

**Comment by whit537** [comment]
Rebased and ready for review!

cc: @rohitpaulk @rorepo @yifeiwu et al.

**Comment by kaguillera** [comment]
LGTM

**Comment by whit537** [comment]
!m @kaguillera 

Thanks! :-)

**Pull request merged**
