### PR TITLE
Fix paypal link in about/features/payroll. Fixes #3887

### LINKED ISSUE #3887: about/features/payroll PayPal link is wrong
https://gratipay.com/about/features/payroll

> WHAT PAYOUT METHODS DO YOU SUPPORT? 
> We are able to deliver funds to Team owners via PayPal. In fact, you must connect a PayPal account to your ~user account via [your Gratipay settings page](https://gratipay.com/about/me/settings/) before you can apply for a Team.

Link should go to http://gratipay.com/about/me/routes.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/29679422-about-features-payroll-paypal-link-is-wrong?utm_campaign=plugin&utm_content=tracker%2F85909&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F85909&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by aandis**

### CODE REVIEW

**Comment by techtonik** [comment]
Can't merge this until Builds are failing for master.

**Comment by rohitpaulk** [comment]
Wasn't the master builds issue fixed? /me checks..

**Comment by rohitpaulk** [comment]
Issue - https://github.com/gratipay/gratipay.com/issues/3885

**Comment by rohitpaulk** [comment]
That seems to suggest that the issue would've happened only in the first week of jan...

**Comment by rohitpaulk** [comment]
Ah - the loop runs twice, so that means two weeks

**Comment by rohitpaulk** [comment]
@aandis - Can you send in a separate PR for #3885? We'll rebase this on that once it's merged.. 

Fix should be straightforward - feel free to use https://github.com/liberapay/liberapay.com/commit/73626e70bf63d417df41d129b8adf4ee99bdf31d

**Comment by techtonik** [comment]
@rohitpaulk are you sure the fix is straightforward? Maybe tests are broken, because `iter_payday_events` is broken on a year's boundary?

**Comment by aandis** [comment]
@rohitpaulk I am still getting acquainted with the codebase. I'll give it a shot. ;)

**Pull request merged**
