### PR TITLE
Add sign-in modal

### PR DESCRIPTION
**Pull request by rohitpaulk**
Part of #1052 

- [x] Review and merge #4523 (extract modal component)
- [x] Change base of this PR from `extract-modal` to `master`

Screenshots: 

gratipay-sign-in

### CODE REVIEW

**Comment by whit537** [comment]
Sentry has an awesome blur effect on the background when the modal is up. Don't have a screenshot handy but will keep an eye out ...

**Comment by rohitpaulk** [comment]
We should also open the modal automatically on a 401 page...

**Comment by rohitpaulk** [comment]
> We should also open the modal automatically on a 401 page...

Done in https://github.com/gratipay/gratipay.com/pull/4525/commits/985296e2d514dcb1da8a32af3ef287a0b50d05d4

**Comment by rohitpaulk** [comment]
Going to deploy to staging..

**Comment by rohitpaulk** [comment]
Deployed to staging. Actual signing in/up won't work because we haven't configured Github properly, but the modal should work. 

401 page: http://gratipay-staging.herokuapp.com/about/me/emails
Homepage: http://gratipay-staging.herokuapp.com/

**Comment by mattbk** [comment]
Works for me and passes tests locally.

**Comment by mattbk** [comment]
Why do we want this again?

**Comment by rohitpaulk** [comment]
@mattbk This was extracted out of #1052. https://github.com/gratipay/gratipay.com/issues/1052#issuecomment-309198597 for reference

**Comment by rohitpaulk** [comment]
(Added that to the PR description too)

**Comment by mattbk** [comment]
Gotcha. I thought I remembered something like that.

**Comment by mattbk** [comment]
Probably.

**Comment by whit537** [comment]
@mattbk Awesome, in that case let me know when this is good from a UX/functional point of view and I will skim the code again and merge. :-)

**Comment by mattbk** [comment]
It works for me and looks fine.

**Comment by whit537** [comment]
Rebased, was 985296e2d514dcb1da8a32af3ef287a0b50d05d4.

**Comment by rohitpaulk** [comment]
@whit537 Have you had a look at this yet?

**Comment by whit537** [comment]
@rohitpaulk Yes! Just ran out of time on the road the other day. ☺️

**Comment by rohitpaulk** [comment]
!m @whit537 

I'm turning the staging app off.

**Pull request merged**
