### PR TITLE
Start shutting the site down

### PR DESCRIPTION
**Pull request by whit537**
Pursuant to https://github.com/gratipay/inside.gratipay.com/issues/1196, this PR announces the shutdown and puts the site into read-only mode (more or less). I plan to self-merge this today once ready if no-one else is around.

- [x] write blog post announcing shutdown
- [ ] clobber homepage with link to blog post
- [ ] ~~turn off sign-ups~~
- [ ] ~~turn off new payments~~

### CODE REVIEW

**Comment by mattbk** [comment]
Chad. I don't mean to get all grown-up on you, but you owe it to the users to write a more explicit shutdown announcement than a Hitchhiker's Guide reference.

**Comment by whit537** [comment]
@mattbk I figured that would go in a blog post that we would link from the homepage. Sound right?

**Comment by whit537** [comment]
Redid that first commit (ripped out tests and css/js as well). Now it looks like this:

screen shot 2017-11-01 at 10 30 05 am

**Comment by whit537** [comment]
Here's a blog post draft:

[Gratipay, Year Five and a Half](https://medium.com/@whit537/gratipay-year-five-and-a-half-cbfba8f50981)

Title is patterned on the yearly reports we published until this year, will include a subtitle with the punchline.

[Gittip, Year One](https://gratipay.news/gittip-year-one-f1217a9f0bf0)
[Gittip, Year Two](https://gratipay.news/gittip-year-two-a220308d4ec9)
[Gratipay, Year Three](https://gratipay.news/gratipay-year-three-73b5ba84c32d)
[Gratipay, Year Four](https://gratipay.news/gratipay-year-four-95863e3f0b64)

I'm hoping to work up a graphic based on the volume/users charts.

screen shot 2017-11-01 at 12 59 19 pm

**Comment by whit537** [comment]
Title switched to "The End of Gratipay" to be more direct.

**Comment by whit537** [comment]
screen shot 2017-11-01 at 3 29 11 pm

**Comment by whit537** [comment]
Dropped the levity, @mattbk. ^^^

**Comment by whit537** [comment]
Gar, weird error on Travis. Can't repro locally. Cache purge?

**Comment by whit537** [comment]
Cache purged, still failing.

**Comment by whit537** [comment]
😡 

screen shot 2017-11-01 at 4 02 39 pm

screen shot 2017-11-01 at 4 02 35 pm

**Comment by whit537** [comment]
I just pushed a no-op commit to see if this fails on master as well.

**Comment by whit537** [comment]
Okay! https://travis-ci.org/gratipay/gratipay.com/builds/295928402?utm_source=github_status passed. So it's some change introduced by code changes?

**Comment by whit537** [comment]
Got it!

**Comment by whit537** [comment]
Rebased post-#4678.

**Comment by whit537** [comment]
@Changaco Do you have a page on Liberapay explaining what migration entails?

screen shot 2017-11-01 at 4 52 01 pm

**Comment by whit537** [comment]
> Do you have a page on Liberapay explaining what migration entails?

Not seeing one in https://github.com/liberapay/liberapay.com/pull/773. Will proceed without for now, we can link later.

**Comment by whit537** [comment]
9b7a7532f9e9b0536b3a496a26e308f500dda58b

screen shot 2017-11-01 at 4 58 51 pm

**Comment by Changaco** [comment]
> Do you have a page on Liberapay explaining what migration entails?

We list what will and won't be imported on the first page of the migration process, but we don't have a public page with a general explanation.

**Comment by Changaco** [comment]
I forgot to clarify that the user actually has to log in on Gratipay before clicking the "Migrate to Liberapay" button.

**Comment by Changaco** [comment]
I've added the message "Oops, you need to go back to Gratipay and log in before starting the migration." on the Liberapay side when the data is missing.

**Comment by Changaco** [comment]
If nobody else does it first I'll open a PR to fix the issue on the Gratipay side tomorrow. Right now I have to sleep.

**Comment by whit537** [comment]
> a PR to fix the issue on the Gratipay side

https://github.com/gratipay/gratipay.com/pull/4680

**Pull request merged**
