### PR TITLE
make a 1.0 payout form

### LINKED ISSUE #3743: implement an application process for one-off 1.0 payouts
To complement the Team application process we already have. Let's get this before the 1.0 refund announcement (#3539).

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/26351936-implement-an-application-process-for-one-off-1-0-payouts?utm_campaign=plugin&utm_content=tracker%2F85909&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F85909&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by whit537**
Closes #3743. Currently this is stubbed out with an "email us" (https://github.com/gratipay/gratipay.com/issues/3539#issuecomment-136907133).

### CODE REVIEW

**Comment by whit537** [comment]
We have 148 ~users with a `status_of_1_0_balance` of `resolved`. Anyone who never received money on Gratipay 1.0 should also be marked as resolved.

**Comment by whit537** [comment]
We'll need to add a `pending-review` status to the `status_of_1_0_balance` type.

**Comment by whit537** [comment]
I think what we want to do is replace `status_of_1_0_balance` with a `1_0_balance` column. The question is, how do we populate that column?

**Comment by whit537** [comment]
`*ahem*`

`s/1_0_balance/balance_1_0/g`

Python identifiers can't begin with a digit. :)

**Comment by whit537** [comment]
We'll still need the `status*` field to track the payout process per-user.

**Comment by whit537** [comment]
Once we have `balance_1_0` we can set `status_of_1_0_payout` to `resolved where balance_1_0 = 0`.

**Comment by whit537** [comment]
# `balance_1_0 == 0`

screen shot 2015-09-02 at 10 36 46 am

**Comment by whit537** [comment]
# `balance > 0 and status == 'unresolved'`

screen shot 2015-09-02 at 10 38 00 am

**Comment by whit537** [comment]
### `balance == 0 and status == 'pending-payout'`

screen shot 2015-09-02 at 10 41 23 am

**Comment by whit537** [comment]
### `balance > 0 and status == 'pending-approval'`

screen shot 2015-09-02 at 10 48 33 am

**Comment by whit537** [comment]
### `balance > 0 and status == 'rejected'`

screen shot 2015-09-02 at 10 56 16 am

**Comment by whit537** [comment]
Alright, so what's the definition of a 1.0 balance? Who has a 1.0 balance and who doesn't?

**Comment by whit537** [comment]
Anyone who received money on Gratipay before 153 and hasn't withdrawn it has a 1.0 balance. Note that it's possible to have a balance and *not* have a 1.0 balance, because we charged in advance. I personally have $5.94 on my Gratipay account right now because of minimum payin, but that's not a 1.0 balance.

**Comment by whit537** [comment]
We do have 35 `transfers` post-Gratipocalypse, mostly from `final-gift`s but two are `take-over`s.

**Comment by whit537** [comment]
We closed the `final-gift` loophole in #3454.

**Comment by whit537** [comment]
We have 2,808 ~users that received money under Gratipay 1.0:

```sql
=> select count(*) from (select distinct on (tippee) tippee from transfers where "timestamp" < '2015-05-07'::timestamptz) as _;
┌───────┐
│ count │
├───────┤
│  2808 │
└───────┘
(1 row)

```

**Comment by whit537** [comment]
Those 2,808 may have given their money to someone else on Gratipay. That's what I did: I had a balance of $149.46 on the day of the Gratipocalypse, which I gave to new Teams over the course of the next eight weeks. In the ninth week, we started charging my card to cover my payments.

**Comment by whit537** [comment]
I suppose that this has been another loophole: giving one's balance away to new Teams. Strictly speaking, we shouldn't have allowed non-upgraded users to use their balance to fund 2.0 payments. But that's water under the bridge: we're not going to pull the money back that we've paid out to Teams.

**Comment by whit537** [comment]
Are we going to continue allowing this loophole? How would we close it?

**Comment by whit537** [comment]
Once we have `balance_1_0` we could subtract that from `balance`, either in `participants` or just during payday.

**Comment by whit537** [comment]
Alright, so we should be able to compute `balance_1_0` by iterating backwards through `payments` and `transfers` for the 2,808 1.0 tippees.

**Comment by whit537** [comment]
2,259 of the 1.0 tippees currently have a balance.

**Comment by whit537** [comment]
We have 4,721 participants with a balance, which I guess means that 1,913 have a balance because of charging in advance?

**Comment by whit537** [comment]
I like the idea of decrementing `participants.balance` by the amount of `balance_1_0`.

**Comment by whit537** [comment]
We have 219 `participants` with a 1.0 balance who are also in the `payments` table.

**Comment by whit537** [comment]
I'm gonna work on computing 1.0 balances in a separate PR and then circle back here: #3747.

**Comment by whit537** [comment]
@stevepiercy How do the above screenshots look, re: https://github.com/gratipay/gratipay.com/issues/3539#issuecomment-137004127?

**Comment by whit537** [comment]
Decided at https://github.com/gratipay/gratipay.com/pull/3747#issuecomment-137625962 to write this form using `participants.balance`, without worrying too much about escrow due to minimum payins. We're going to try to refund that money earlier than October 8 as part of #3675.

Escrow due to minimum payouts is not a problem here because anyone with escrow due to minimum payouts will already be owner of a Team.

**Comment by stevepiercy** [comment]
@whit537 LGTM :shipit:

**Comment by whit537** [comment]
Cool, thanks @stevepiercy. :-)

**Comment by whit537** [comment]
- [ ] deal with the < 50¢ case
 - [ ] email notifications

**Comment by whit537** [comment]
```
=> select status_of_1_0_balance, count(*) from participants group by status_of_1_0_balance order by count desc;
┌───────────────────────┬────────┐
│ status_of_1_0_balance │ count  │
├───────────────────────┼────────┤
│ unresolved            │ 112808 │
│ resolved              │    154 │
│ pending-payout        │      5 │
└───────────────────────┴────────┘
(3 rows)
```

**Comment by whit537** [comment]
Local:

```sql
=# select status_of_1_0_payout, count(*) from participants
group by status_of_1_0_payout order by count desc;
┌──────────────────────┬────────┐
│ status_of_1_0_payout │ count  │
├──────────────────────┼────────┤
│ completed            │ 110792 │
│ pending-application  │   2164 │
│ pending-payout       │      9 │
└──────────────────────┴────────┘
(3 rows)
```

**Comment by whit537** [comment]
Looks like $127,590.64 for the 2,164 that are `pending-application`.

**Comment by whit537** [comment]
Pooped out, sorry. :-(

**Comment by whit537** [comment]
Alright, so this PR is important because this is where we're defining 1.0 money, which will be the basis for the refund we do on October 8 (#3539).

To date we've been assuming that all balances are entirely 1.0 balances. We've been paying people out using a `status_of_1_0_balance` field in the database to keep track: `unresolved`, `pending-payout`, and `resolved`. With this PR we're recognizing that the situation is more complex: *not* all balances are 1.0 balances, because of minimum payins charged in advance. ... should we land charging in arrears first, then? I thought I'd considered this, but I'm not finding "arrears" on this PR ...

**Comment by whit537** [comment]
Charging in arrears is https://github.com/gratipay/gratipay.com/pull/3675.

**Comment by whit537** [comment]
Rebased on master.

**Comment by whit537** [comment]
Double-checked the rebase in https://github.com/gratipay/gratipay.com/tree/c161aadc93e9abcbf1850efd42a4a8f125c300ae (`1p` branch) because it looked weird. Turns out a rebase when there's a merge commit inlines all of the merged commits into the rebase.

**Comment by whit537** [comment]
> write a test for the trigger

Inspired by https://github.com/gratipay/gratipay.com/pull/3675#commitcomment-13097620, I short-circuited the trigger function and ran the test suite: it passed. Test needed!

**Comment by whit537** [comment]
screen shot 2015-09-07 at 1 51 12 pm

**Comment by whit537** [comment]
Okay! We need some email notifications and then I think we're good here.

**Comment by whit537** [comment]
What emails do we need to send? Every time the status changes?

**Comment by whit537** [comment]
I think we just need notifications for `rejected` and `pending-payout`. PayPal sends a notification for payouts (cf. #3526)

**Comment by whit537** [comment]
screen shot 2015-09-07 at 4 13 31 pm

**Comment by whit537** [comment]
screen shot 2015-09-07 at 5 29 32 pm

**Comment by whit537** [comment]
screen shot 2015-09-07 at 5 30 00 pm

**Comment by whit537** [comment]
Last thing on my plate is to require a PayPal route as part of all this. After that I think I'm ready for review.

**Comment by whit537** [comment]
screen shot 2015-09-07 at 6 12 50 pm

**Comment by whit537** [comment]
Alright, ready for review.

**Comment by whit537** [comment]
So the plan is to deploy this code, and then run `sql/1.0/all.sql` to set `status_of_1_0_payout` properly.

**Comment by whit537** [comment]
Alright, let's do this.

**Pull request merged**
