### PR TITLE
Remove errant class

### PR DESCRIPTION
**Pull request by whit537**
Forgot to push this commit before we merged https://github.com/gratipay/gratipay.com/pull/4353.

### CODE REVIEW

**Comment by whit537** [comment]
Forgot this commit, @mattbk. 😊

**Comment by whit537** [comment]
@mattbk Once we have this I will deploy this and https://github.com/gratipay/gratipay.com/pull/4353.

**Comment by mattbk** [comment]
image

**Comment by whit537** [comment]
Green, @mattbk! 💃

**Pull request merged**
