### PR TITLE
add Dwolla as a payment network

### PR DESCRIPTION
**Pull request by whit537**
This will let us start doing manual transfers with Dwolla, as a step towards #726.

### CODE REVIEW

**Comment by whit537** [comment]
@webmaven Want to review this one? ;-)

cc: @rohitpaulk @rorepo

**Comment by whit537** [comment]
Ping @webmaven.

**Comment by rohitpaulk** [comment]
:)

**Comment by whit537** [comment]
Thanks, @rohitpaulk. :-)

**Comment by webmaven** [comment]
@whit537 sorry, you caught me during a lull of online activity. :sleeping: :zzz:

**Comment by whit537** [comment]
:-)

**Pull request merged**
