### PR TITLE
kill pledging

### PR DESCRIPTION
**Pull request by whit537**
With the move to Teams we no longer support pledging to arbitrary social network accounts. Incorporates #3402, works towards #3399.

### CODE REVIEW

**Comment by whit537** [comment]
Ready for review/merge, @rohitpaulk @techtonik et al.

**Comment by whit537** [comment]
3ba5d0d c2cf25a are failing at Travis because of a pyflakes violation. Presumably 1eb481e will fail with the same.

**Comment by whit537** [comment]
Yup. Should be fixed in e67a9e1.

**Comment by whit537** [comment]
Hmm ... how do I run pyflakes globally locally?

**Comment by whit537** [comment]
`make pyflakes`

**Comment by techtonik** [comment]
Not LGTM on killing the code that is useful for potential forks.

**Comment by whit537** [comment]
@techtonik Don't worry, we use version control. ;-)

**Comment by techtonik** [comment]
Right, but how somebody is supposed to find that? The branch info is erased and there is no like "feature tagging" to know which revisions still fully supported this feature.

**Comment by techtonik** [comment]
And before killing the DB, I'd like to dump my data from it, for example, to know how generous I am and see which project won't be able to receive my donations anymore because of this pivoting.

**Pull request merged**
