### PR TITLE
Remove some test projects

### PR DESCRIPTION
**Pull request by mattbk**
Because of the bug at #4295, sometimes we get projects that can't be removed through the UI because the slug breaks the project URL. This PR removes some of those projects.

### CODE REVIEW

**Comment by whit537** [comment]
Can you test this against a local db? I'd expect statements to need ending semicolons, e.g.

**Comment by mattbk** [comment]
Yeah, I didn't test with multiple statements, oops. :disappointed:

**Comment by whit537** [comment]
Actually, nevermind. I just went ahead and applied your SQL manually.

```
gratipay::MAROON=> select * from teams where slug='/www.evil.com/user_ip.php?gratipay';
┌────────────────────────────────────┬─────┬───────────────────────────────┬──────────────────────────────────
│                slug                │ id  │             ctime             │             slug_lower           
├────────────────────────────────────┼─────┼───────────────────────────────┼──────────────────────────────────
│ /www.evil.com/user_ip.php?gratipay │ 394 │ 2016-12-23 00:26:55.540964+00 │ /www.evil.com/user_ip.php?gratipa
└────────────────────────────────────┴─────┴───────────────────────────────┴──────────────────────────────────
(1 row)

gratipay::MAROON=> delete from teams where slug='/www.evil.com/user_ip.php?gratipay';
DELETE 1
gratipay::MAROON=> delete from teams where slug='//www.google.com/?><x>';
DELETE 1
gratipay::MAROON=> delete from teams where slug='//www.google.com/?';
DELETE 1
gratipay::MAROON=>
```

**Comment by mattbk** [comment]
!m @whit537

**Comment by whit537** [comment]
!m @mattbk

**Pull request closed without merging**
