### PR TITLE
Clarify that social logins are also social account creators

### PR DESCRIPTION
**Pull request by mattbk**
As noted at https://github.com/gratipay/gratipay.com/pull/4268#issuecomment-269844784 and https://github.com/gratipay/gratipay.com/issues/1167#issuecomment-269845813, I think it's confusing that there's no "register" or "create account" instructions, only "sign in."

I'm torn between "register," which sounds technical yet accurate and "create account," which makes sense unless you think about the social media _accounts_ that can be used to sign in. "Wait, am I creating a Twitter account?" "Create account" is also longer and breaks the UI in the sidebar especially.

### CODE REVIEW

**Comment by mattbk** [comment]
Food for thought on why I don't want to use "Sign in or Sign up": [it's visually confusing](http://uxmovement.com/buttons/why-sign-up-and-sign-in-button-labels-confuse-users/).

**Comment by mattbk** [comment]
screen shot 2016-12-31 at 10 29 38 pm

**Comment by mattbk** [comment]
Alternative wording if we're not tied to "Sign in":

screen shot 2016-12-31 at 10 33 49 pm

**Comment by mattbk** [comment]
- `min-width: 165px` if "Log in or Sign up" is used (insert at https://github.com/gratipay/gratipay.com/blob/4b5b0b3e287424a3e5b4179d49eddac44064f7e4/scss/components/sign_in.scss#L101).
- `min-width: 176px` if "Sign in or Register is used.
- Sidebar looks okay regardless, probably because the dropdown menu isn't connected to the button, and has rounded corners to help separate it.

Although with translations, these pixel values won't match up anyway.

**Comment by nobodxbodon** [comment]
How about using "Login with", like in below:

screen shot 2017-01-01 at 11 38 15 pm

**Comment by mattbk** [comment]
Foursquare still has a different "Sign up for Foursquare" link.

That Zoho screenshot leaves me wondering how I create an account in the first place.  It's the same issue I see with Gratipay.

**Comment by mattbk** [comment]
Knew I should have waited...

**Comment by mattbk** [comment]
Where is it getting "Log in" from? Before it was "Sign in." Cache?

```
=================================== FAILURES ===================================
_____________ Tests.test_homepage_renders_copy_correctly_for_anon ______________
self = <test_homepage.Tests testMethod=test_homepage_renders_copy_correctly_for_anon>
    def test_homepage_renders_copy_correctly_for_anon(self):
        assert self.css('#content h1').html == 'Projects'
>       assert self.css('#header .sign-in button').html.strip()[:7] == 'Log in or Sign up'
E       AssertionError: assert 'Log in ' == 'Log in or Sign up'
E         - Log in 
E         + Log in or Sign up```

**Comment by mattbk** [comment]
> Where is it getting "Log in" from?

Compares only part of the string because there is HTML after. So set the string length equal to the length of your test string.

**Comment by whit537** [comment]
I like using a consistent nomenclature for signing up, in, and out, so I'd rather not introduce "log *" or "register."

How about Medium's "Sign in / Sign up"?

screen shot 2017-01-19 at 10 51 22 am
screen shot 2017-01-19 at 10 52 05 am

Or even "Sign in/up"? Is that too terse?

screen shot 2017-01-19 at 10 54 36 am
screen shot 2017-01-19 at 10 54 52 am

Or if we want to be geeky, "Sign {in,up}". :)

screen shot 2017-01-19 at 10 55 07 am

**Comment by mattbk** [comment]
I copied Medium. It's less of a big deal than I originally thought, because there's only one button, not two.

**Pull request merged**
