### PR TITLE
Fix cached values

### PR DESCRIPTION
**Pull request by rohitpaulk**

### CODE REVIEW

**Comment by whit537** [comment]
Ready for review yet, @rohitpaulk? :)

**Comment by rohitpaulk** [comment]
Not yet, @whit537. I've been busy lately, will get back to this as soon as I can.

**Comment by whit537** [comment]
What's left to do? I can spend some time on this ...

**Comment by rohitpaulk** [comment]
@whit537 - 
- Update `Participant#update_giving`, and revive related tests. 
- Update `fake_payday.sql`

**Comment by rohitpaulk** [comment]
^ That's the functionality part. Once that's done, expose giving/receiving in the UI for participants, and only `receiving` for teams.

**Comment by whit537** [comment]
!m @rohitpaulk 

Thanks, I'll take a look.

**Comment by whit537** [comment]
P.S. In Python, methods are spelled `Participant.update_giving`, not `Participant#update_giving`. ;-)

**Comment by whit537** [comment]
Rebased on master.

**Comment by whit537** [comment]
Hrm ... we're still using `set_tip_to` extensively in the test suite. It's about time to nix `set_tip_to`, I think,

**Comment by whit537** [comment]
Rebased on master.

**Comment by whit537** [comment]
Rebased on master to pick up #3655.

**Comment by whit537** [comment]
I don't want to touch tips in absorptions/take_over, because one ~user could take over another and then migrate to a Team: we'd want the tips from both ~users to make their way through to the Team.

**Comment by whit537** [comment]
We've [standardized our nomenclature](https://github.com/gratipay/inside.gratipay.com/issues/117). How does that apply here? What are the values we're caching? Do we want both sum and count for each variable? What would that be?

**Comment by whit537** [comment]
```
                sum           count        sharing bit
                ----------------------------------------------
current  ~user  giving        —            anonymous_giving
                receiving     npatrons     anonymous_receiving
                taking        —

         Team   receiving     nsupporters  —
                payroll       nmembers     —       

target   ~user  giving        nrecipients  anonymous_giving
                taking        nteams       anonymous_taking

         Team   receiving     ngivers      —
                distributing  nmembers     —
```

Look right?

**Comment by whit537** [comment]
Are we just giving up on the JSON APIs? 2.0 is a breaking change from 1.0. We simply don't have the same semantics anymore. We don't have a `receiving` or an `npatrons` to show for ~users. Right? Does that mean we should 404 all old-fashioned endpoints? Or are we okay with changing the endpoints in subtly non-backwards-compatible ways?

**Comment by whit537** [comment]
I *don't* think we should pretend that `npatrons` is what I'm calling `nteams` above: the count of the number of teams a ~user is taking from.

**Comment by whit537** [comment]
We shouldn't silently masquerade the value of `nteams` as the value of `npatrons`.

**Comment by whit537** [comment]
Rebased on master.

**Comment by whit537** [comment]
Rebased on master again.

**Comment by whit537** [comment]
Tests are passing and we've stared at this for months. I've merged this and will pick up with further rationalizations on a new PR.

!m @rohitpaulk

**Pull request merged**
