### PR TITLE
Fix Travis

### PR DESCRIPTION
**Pull request by Changaco**
For #2839 and [IRC](https://botbot.me/freenode/gratipay/2015-02-17/?msg=32186931&page=1).

### CODE REVIEW

**Comment by Changaco** [comment]
Ready for review.

**Comment by rohitpaulk** [comment]
1b212b9 (second commit) looks fine, I'm doubtful about fb11677. 

I did a few tests for this on my fork - I added the below commands to `before_install` to see what they output.

For a push to master: 
```
$ echo "`git rev-parse --abbrev-ref HEAD`"
> HEAD
$ echo "${TRAVIS_BRANCH}"
> master
```

For a pull request: 

```
$ echo "`git rev-parse --abbrev-ref HEAD`"
> HEAD
$ echo "${TRAVIS_BRANCH}"
> to-test-travis
```

So our if condition is useless, since it uses `git rev-parse --abbrev-ref HEAD`. I guess it should work if we used `TRAVIS_BRANCH` instead. What do you think, @Changaco?

**Comment by rohitpaulk** [comment]
I'd also mentioned this earlier on https://github.com/gratipay/gratipay.com/issues/2806#issuecomment-58930269

**Comment by Changaco** [comment]
@rohitpaulk Done.

**Comment by Changaco** [comment]
Actually, no, that's not correct.

**Comment by Changaco** [comment]
http://docs.travis-ci.com/user/ci-environment/

> `TRAVIS_BRANCH`: For builds not triggered by a pull request this is the name of the branch currently being built; whereas **for builds triggered by a pull request this is the name of the branch targeted by the pull request** (in many cases this will be **master**).

I've modified the commit to also check `"${TRAVIS_PULL_REQUEST}" = "false"`:

> `TRAVIS_PULL_REQUEST`: The pull request number if the current job is a pull request, "false" if it's not a pull request.

**Comment by rohitpaulk** [comment]
Aah yh you're right, I was looking at the build triggered by the push, not the PR.

**Pull request merged**
