### PR TITLE
Add lang="en" to the html start tag.

### PR DESCRIPTION
**Pull request by EdOverflow**

### CODE REVIEW

**Comment by clone1018** [comment]
What if the user is browsing Gratipay using another language https://github.com/gratipay/gratipay.com/tree/master/i18n/core

**Comment by EdOverflow** [comment]
Thanks for the informative response. Does anyone have any suggestions as to how the `lang` attribute could be implemented?

**Comment by Changaco** [comment]
@EdOverflow https://github.com/liberapay/liberapay.com/blob/147/templates/base.html#L2

**Comment by EdOverflow** [comment]
Ah, nice! Thank you @Changaco.

**Pull request closed without merging**
