### PR TITLE
Strip npm description of markdown

### PR DESCRIPTION
**Pull request by kaguillera**
This PR is to resolve the issue #4461. It is currently just a work in progress.

### CODE REVIEW

**Comment by kaguillera** [comment]
Ok I may have rushed a bit. In order to do this PR I had to install bleach and upgrade six from six-1.8.0. I have never added a package to the repo so I will need a little guidance here. @whit537

**Comment by whit537** [comment]
Per IRL convo it looks like we have six-1.8.0.txt specified more than once in requirements.txt. We can take out the additional mentions.

**Comment by kaguillera** [comment]
Ok so this PR is being blocked by a number of issues with installing bleach so I am opening a new PR #4586 to upgrade setuptools and virtualenv for the Gratipay repo that should resolve these issues.

**Comment by JessaWitzel** [comment]
Hey @kaguillera , I'm trying to follow the threads of the npr bugfixes and it looks like your updates got merged. Is that what you needed to unblock you here?

**Comment by whit537** [comment]
Closing per https://github.com/gratipay/inside.gratipay.com/issues/1196.

**Pull request closed without merging**
