### PR TITLE
Add teams opt in + payroll

### PR DESCRIPTION
**Pull request by rohitpaulk**
(Branched off #3450)

#3433.

### CODE REVIEW

**Comment by whit537** [comment]
!m @rohitpaulk

**Comment by rohitpaulk** [comment]
Rebased on master.

**Comment by rohitpaulk** [comment]
I have to leave for ~2 hours. If anyone wants to pick this up in the meantime, here's what's left: 

- [ ] Constrain payday to members who have `is_active` set to `true`.
- [ ] Add UI options to toggle `is_active`. (place accept/reject links below the existing teams listing we have on the profile page)
- [ ] Migrate the existing payroll members to the new table.
- [ ] Ask people to accept the invitations! :dancer:

**Comment by rohitpaulk** [comment]
Here's how I thought we'd handle `is_active` - 

**NULL** - Invited. (default when a new row is inserted)
**TRUE** - Invitation Accepted.
**FALSE** - Invitation Declined/Membership Cancelled.

**Comment by whit537** [comment]
!m @rohitpaulk

**Comment by rohitpaulk** [comment]
Rebased on master.

**Comment by rohitpaulk** [comment]
Blocked on #3433.

**Comment by webmaven** [comment]
@rohitpaulk, does it make sense to bring this branch back to a mergeable state even though it is currently blocked?

**Comment by rohitpaulk** [comment]
> @rohitpaulk, does it make sense to bring this branch back to a mergeable state even though it is currently blocked?

Rebasing *could* get ugly - I'd rather take this branch as a reference and repeat the whole process. 

I don't think it makes sense to do it right now though, best to pick it up once we have an idea of when it's going to be 'unblocked' :)

**Comment by webmaven** [comment]
@rohitpaulk, understood. If that is the case, should this PR just be closed?

**Comment by rohitpaulk** [comment]
> If that is the case, should this PR just be closed?

I'm fine with closing it as long as the branch history is retained :)

**Comment by whit537** [comment]
!m @rohitpaulk @webmaven

**Pull request closed without merging**
