### PR TITLE
Refactor test_billing_exchanges

### PR DESCRIPTION
**Pull request by whit537**
&#x2B11; #3994

&larr; #4102 ([diff](https://github.com/gratipay/gratipay.com/compare/takes-payday...takes-test-refactor)) — #4111 &rarr;

Makes way for some MassPay tests in #4111.

#### TODO

- [x] rebase once #4102 lands

### CODE REVIEW

**Comment by whit537** [comment]
Rebased on latest #4102, previous head was 61189512b479af68e318eecb137f9b17b60b1d6a.

**Comment by rohitpaulk** [comment]
Rebasing on master since #4102 is merged..

**Comment by rohitpaulk** [comment]
screen shot 2016-09-01 at 6 14 22 pm

**Comment by rohitpaulk** [comment]
Changes look good, waiting for Travis to merge

**Comment by whit537** [comment]
👍

**Pull request merged**
