### PR TITLE
Respect non-searchable users choice when doing a lookup

### PR DESCRIPTION
**Pull request by nashe**
This aims to fix the report [H1-118699](https://hackerone.com/reports/118699): don't search using LIKE on the non-searchable users, but only display them in the list if it's an exact match.

Some tests were removed since I'm now testing searchable users with/without an exact match and non-searchable users with/without an exact match.

### CODE REVIEW

**Comment by nashe** [comment]
Travis is greeting me with a nice:
> The repository at gratipay/gratipay.com was not found.

And their sign-in button just freezes. I'll wait a little bit but I think everything's fine anyway.

**Comment by whit537** [comment]
Golly! I think we saw that behavior a while ago. I forget where, not finding it in search atm ... maybe @rohitpaulk remembers?

**Comment by nashe** [comment]
@whit537 It's finally working on my side, sounds like just temporary issues.

**Comment by whit537** [comment]
Perhaps related to https://github.com/gratipay/gratipay.com/pull/4077#issuecomment-234244581?

**Comment by nashe** [comment]
I guess, yes.

**Comment by whit537** [comment]
@nashe I'm good to merge if you're good with 75aac2c9fe96ae68ac99150f805575fc90243cb8.

**Comment by nashe** [comment]
It's obviously more readable now 👍

**Comment by whit537** [comment]
Deploying ...

**Comment by whit537** [comment]
Deployed! :-)

**Comment by nashe** [comment]
Thanks for your rectification!

**Pull request merged**
