### PR TITLE
Add npm to /search

### PR DESCRIPTION
**Pull request by whit537**
Add npm packages to /search results.

~~Add live search over npm packages at `/on/npm/`, linking over to `/on/npm/foo/`. Try really really hard to use Libraries.io in some way so we can say "Powered by Libraries.io" and start building that partnership.~~
### Todo
- [ ] while searching, [hit](https://github.com/nodesource/npmsearch#api) npmsearch.com in addition to local index
- [ ] mix the results into results from our local index (compare scores?)

### CODE REVIEW

**Comment by whit537** [comment]
Hmm ... do we do this in `/on/npm/` or add it to `/search`?

**Comment by whit537** [comment]
npm itself uses https://www.constructor.io/.

**Comment by aandis** [comment]
> How's that sound, @aandis? Note ordering of development priorities on #4148 (second todo subsection).
Cool I'll look into npmsearch's api. Catching up on #4151 since that seems to be priority.

**Comment by whit537** [comment]
Closing because we want to search over packages in our own database, rather than an external service. Will get to that eventually under https://github.com/gratipay/inside.gratipay.com/issues/987.

**Pull request closed without merging**
