### PR TITLE
Add script to queue emails from file

### PR DESCRIPTION
**Pull request by rohitpaulk**
For https://github.com/gratipay/gratipay.com/issues/3352#issuecomment-94435599. 

- [X] Create script to queue emails
- [x] Create email spt

### CODE REVIEW

**Comment by rohitpaulk** [comment]
I have a file with the list of emails (on my local) that I pulled from mandrill.

**Comment by whit537** [comment]
How about:

Subject: Sorry for the email hiccup!

> Last week we started sending out email notifications for credit card charges. Yesterday [Earlier today?] we [accidentally](https://github.com/gratipay/gratipay.com/issues/3352) sent you a second notification. Don't worry, though: We didn't charge you twice, we just notified you twice. You can double-check your [transaction history here](https://gratipay.com/about/me/history/). Sorry for the error!

**Comment by rohitpaulk** [comment]
We're sending this **3 days** after the incident. All the emails were sent out between 3 PM and 8 PM my time (IST) on 18th April.

**Comment by rohitpaulk** [comment]
screenshot from 2015-04-21 14 52 32
screenshot from 2015-04-21 14 52 54

**Comment by rohitpaulk** [comment]
Okay, I'm proceeding with this.

**Comment by whit537** [comment]
Looks good to me, @rohitpaulk. Go for it. I'll be preoccupied for the next couple days but will be periodically checking GitHub notifications if something goes awry.

**Comment by rohitpaulk** [comment]
Failure due to JS tests, merging.

**Comment by rohitpaulk** [comment]
I'm not authorized to push to transfiex, so I commented that part out when deploying. 

Tested the email script on myself, looks fine. 

screenshot from 2015-04-22 11 49 19

**Comment by rohitpaulk** [comment]
Okay, emails queued :)

**Pull request merged**
