### PR TITLE
Use local pip packages on heroku

### PR DESCRIPTION
**Pull request by rohitpaulk**
https://github.com/gratipay/gratipay.com/issues/3260

### CODE REVIEW

**Comment by rohitpaulk** [comment]
I don't know if there's a better way to handle this, but I've tested this on a new heroku app and it works.

**Comment by whit537** [comment]
What's the motivation here? What indicates that we *aren't* using local packages already? The `-f ./vendor/` doesn't give us that?

**Comment by whit537** [comment]
I guess this is an indication ... :-)

screen shot 2015-10-12 at 9 00 08 am

**Comment by rohitpaulk** [comment]
Yep, I found that over at https://github.com/gratipay/gratipay.com/issues/3260#issuecomment-147205823

**Comment by rohitpaulk** [comment]
> The -f ./vendor/ doesn't give us that?

It does, but we don't get to choose how heroku does `pip install`. I left a comment - https://github.com/gratipay/gratipay.com/issues/3260#issuecomment-147209248

> So heroku says -
> ```To add a local dependency in requirements.txt, specify the relative path to the directory containing setup.py:
> ./path/to/distribution```
> 
> ^ It's either that, or we maintain a custom buildback that instructs pip to fetch packages from `vendors`. First option sounds better to me, trying it out..

**Comment by whit537** [comment]
Gotcha, I had missed #3260, sorry.

**Comment by techtonik** [comment]
This is basically a revert of https://github.com/gratipay/gratipay.com/pull/3292 which was needed to install platform-dependent wheels.

**Pull request merged**
