### PR TITLE
Make a list of suspicious accounts

### PR DESCRIPTION
**Pull request by mattbk**
Part of #557. This covers the logic; it’s mostly a duplicate of
`dashboard/index` with the buttons removed (admins can mark/unmark
`suspicious` on the profile itself).

Obviously needs to be put into a site template for ~users to see, and
only needs the list, not the other frame.

### CODE REVIEW

**Comment by mattbk** [comment]
`/about/fraud/suspicious`
screen shot 2016-11-12 at 5 56 48 pm

Haven't added to a menu. The other page in `/fraud` isn't in a menu either, AFAICT.

**Comment by mattbk** [comment]
Almost deleted the dashboard version, but I figure that's something that could be modified in other ways.

**Comment by mattbk** [comment]
I suppose I need to add a menu item before this can be reviewed.

**Comment by mattbk** [comment]
We don't have a root page for `/fraud`; what would we put there? Maybe suggestions on how to let us know about potential fraud, including a link to http://inside.gratipay.com/howto/review-accounts? This is the type of thing that the community can pitch in for.

That would probably make the suspicious list a tab on the fraud page.

**Comment by mattbk** [comment]
image

image

**Comment by mattbk** [comment]
Ready for review, @whit537, @kaguillera et alii.

**Comment by whit537** [comment]
Nav layout breaking for me when bolded:

screen shot 2016-11-21 at 4 18 15 pm

**Comment by mattbk** [comment]
> Nav layout breaking for me when bolded:

Would "Fraud" be sufficient?

**Comment by whit537** [comment]
I think conceptually it could be grouped with Security and also AML (maybe under "Safety"?), _but_ ...

The primary [motivation](https://github.com/gratipay/gratipay.com/issues/557#issue-10413440) here is to give suspicious users some way of discovering that they've been marked suspicious, correct?

> The principle is that untrusted users are announced as such so that false positives have a chance to discover this and attempt to redeem themselves. We can't be like PayPal, an infuriatingly opaque black box if you're a false positive.

Is a listing of suspicious accounts the best way to do that? How will suspicious users know to look there? I realize the suspicious listing was my suggestion, but https://github.com/gratipay/gratipay.com/issues/557#issuecomment-12837123 seems like a better solution to the problem:

> notify the user (if possible) and put a note on their profile

That way the suspicious user doesn't have to work so hard to discover the problem.

I think we should abort this PR and go for the notify/note solution. 🐭

**Comment by mattbk** [comment]
> I think we should abort this PR and go for the notify/note solution. 

Fine by me. I learned some things, at least.

**Pull request closed without merging**
