### PR TITLE
Add homepage pagination

### PR DESCRIPTION
**Pull request by rohitpaulk**
https://uxplanet.org/pagination-best-practices-76fbd3f5a78d

### CODE REVIEW

**Comment by rohitpaulk** [comment]
[Video on slack](https://gratipay.slack.com/files/rohitpaulk/F5FRK7NQG/pagination.mov)

**Comment by rohitpaulk** [comment]
Ok, I think I've exhausted my design skills 😛 Here's what I have: 

**First page, desktop:** 

screen shot 2017-05-23 at 4 43 24 pm

**Middle pages, desktop:**
 
screen shot 2017-05-23 at 4 43 35 pm

**Fewer number of links, desktop:** 

screen shot 2017-05-23 at 4 43 48 pm

**Mobile**
screen shot 2017-05-23 at 4 44 18 pm

**Comment by rohitpaulk** [comment]
Going to deploy to staging so that people can test...

**Comment by rohitpaulk** [comment]
From @EdOverflow on Slack: 

>  I would make the buttons 50vw and add a little height. Makes it easier for mobile users.

**Comment by rohitpaulk** [comment]
Deployed on http://gratipay-staging.herokuapp.com/?status=approved&page=2

**Comment by rohitpaulk** [comment]
> I would make the buttons 50vw and add a little height

I'm worried this will make the buttons look disproportionately sized in comparison to the other links/buttons on the page - worth trying though. Also, got to find an example of another site that does this

**Comment by mattbk** [comment]
The list numbers restart on each page, is there a way around this?

**Comment by rohitpaulk** [comment]
> The list numbers restart on each page, is there a way around this?

As in, the numbers restart when you switch tabs?

**Comment by rohitpaulk** [comment]
Oh I think I get what you mean - the numbers on each item. That definitely looks weird, will fix

**Comment by rohitpaulk** [comment]
List numbers issue fixed. 

screen shot 2017-05-24 at 4 49 02 am

(the list numbers are 41, 42 etc. now - they used to be 1, 2, 3 before)

**Comment by rohitpaulk** [comment]
That... seems to have broken other pages, will take a look

**Comment by rohitpaulk** [comment]
Screenshots: 

**Desktop 1**

screen shot 2017-05-25 at 10 49 46 pm

**Desktop 2**

screen shot 2017-05-25 at 10 49 57 pm

**Mobile 1**

screen shot 2017-05-25 at 10 51 16 pm

**Mobile 2**

screen shot 2017-05-25 at 10 51 27 pm

**Comment by whit537** [comment]
@rohitpaulk Lookin' good! Should we implement the recommendations [under](https://uxplanet.org/pagination-best-practices-76fbd3f5a78d) "Should I use a list of number or Next/Previous buttons for pagination?"?

1-hk-w0arwt_tx2khi9vu90q

**Comment by rohitpaulk** [comment]
Also, got to use i18n for previous, next etc.

**Comment by rohitpaulk** [comment]
I tried adding a bit of brown to the `...` fillers, here's a before and after: 

**Before**

screen shot 2017-05-26 at 11 09 58 pm

**After**

screen shot 2017-05-26 at 11 09 45 pm

**Comment by rohitpaulk** [comment]
Done, deployed to [staging](http://gratipay-staging.herokuapp.com/)

Screenshots: 

screen shot 2017-05-26 at 11 23 33 pm

screen shot 2017-05-26 at 11 23 57 pm

screen shot 2017-05-26 at 11 24 03 pm

**Comment by nashe** [comment]
This really improves the homepage experience, !m @rohitpaulk 🍻

**Pull request merged**
