### PR TITLE
mobile first

### PR DESCRIPTION
**Pull request by whit537**
Following on from #2938, this PR inverts our design to be [mobile first](http://www.lukew.com/resources/mobile_first.asp).

> Over the 4 years we have slowly moved away from device specific breakpoints in favour of content specific breakpoints, i.e. adding a breakpoint when the content is no longer easy to consume.

http://responsivedesign.is/articles/why-you-dont-need-device-specific-breakpoints

> - Pick major breakpoints by starting small, then working up
> - Pick minor breakpoints when necessary
> - Optimize text for reading
> - Never completely hide content

https://developers.google.com/web/fundamentals/layouts/rwd-fundamentals/how-to-choose-breakpoints

### CODE REVIEW

**Comment by whit537** [comment]
Rebased on master now that #2938 has landed.

**Comment by whit537** [comment]
Rebased on #3064.

**Comment by whit537** [comment]
Rebased on master.

**Comment by whit537** [comment]
"Mobile first" means using `min-width` media queries instead of `max-width`: start with the smallest screen size and then work our way up. Right now we start with the large size and constrain our way down. My plan for this PR is to perfectly invert the media queries, leaving everything looking exactly the same from the outside. That'll take some work but I think in terms of an incremental strategy it's the best way forward. The path I've started down is to make UI changes as part of the process, and I think that sets the plow too deep. We don't need another mega-PR like #2938.

**Comment by whit537** [comment]
Rebased on master, having previously left off to go do #3078 #3068 #3071 #3072. I left off b58a9a84329eb78cd3da0dd9a9eb9988d8e21dd3. It doesn't apply cleanly so I'm debating whether to try to apply it or just redo it.

**Comment by whit537** [comment]
Here's an IA that I did:

ia

**Comment by whit537** [comment]
I feel stuck on this because IA needs to get cleaned up first. The slew of #30* PRs cleaned up the IA for the About pages. In #3220 I'm looking at IA for the whole of Gratipay.com.

**Comment by Changaco** [comment]
If you feel stuck it means that you've deviated from the plan:

> My plan for this PR is to perfectly invert the media queries, leaving everything looking exactly the same from the outside.

**Comment by whit537** [comment]
> If you feel stuck it means that you've deviated from the plan:

Indeed. I'll see if I can rein this back in ...

**Comment by whit537** [comment]
[IRC](https://botbot.me/freenode/gratipay/2015-03-30/?msg=35408488&page=2)

**Comment by whit537** [comment]
Didn't end up landing this on the [Redesign](https://github.com/gratipay/gratipay.com/milestones/Redesign) milestone, and now it's drifted. Closing.

**Pull request closed without merging**
