### PR TITLE
New payroll

### PR DESCRIPTION
**Pull request by rohitpaulk**
#3433

### CODE REVIEW

**Comment by whit537** [comment]
After talking with @copiesofcopies, we're going to need to implement #3397 before we can start processing payroll for teams. Does this PR address that?

**Comment by rohitpaulk** [comment]
No, it doesn't.

**Comment by whit537** [comment]
Okay, let's work on landing this for next week.

**Comment by rohitpaulk** [comment]
Blocked on #3397.

**Comment by rohitpaulk** [comment]
Rebased on master.

**Comment by rohitpaulk** [comment]
Closing, #3495 is branched off of this.

**Pull request closed without merging**
