### PR TITLE
add github ribbon on the homepage

### PR DESCRIPTION
**Pull request by nobodxbodon**
https://github.com/gratipay/inside.gratipay.com/issues/959
github ribbon screenshot from 2017-01-04 21 35 04

### CODE REVIEW

**Comment by whit537** [comment]
You good with e804b7cebe241c616110bec94718a210b854c534, @nobodxbodon?

**Comment by whit537** [comment]
sxt60hxzar

**Comment by nobodxbodon** [comment]
Looks great. Thanks. I suppose color can be adjusted in the homepage optimizing project, if necessary, as 100 people may have 101 tastes about that :)

**Comment by whit537** [comment]
The value in the ribbon is in being instantly recognizable, and black is the most common one across the web, in my experience. I was the last one to commit here, so if you're good, go ahead and merge and I will deploy!

**Comment by whit537** [comment]
(And their green clashes with our green, as I mentioned in the commit message.)

**Comment by whit537** [comment]
Deployed!

**Pull request merged**
