### PR TITLE
Fix bug with closing account w/ closed project

### PR DESCRIPTION
**Pull request by whit537**
Part of #3602, should've happened in #4287.

### CODE REVIEW

**Comment by whit537** [comment]
Ready for review, @mattbk, et al. Should fix https://github.com/gratipay/gratipay.com/issues/3602#issuecomment-272272626.

**Comment by whit537** [comment]
The second build for the first commit pulled the second commit, so it passed when it shouldn’t have.

**Comment by whit537** [comment]
I can repush but you can probably get the picture with the first build on the commit. ;-)

**Comment by whit537** [comment]
The push build on the second commit also failed, but that was due to a spurious test failure (https://github.com/gratipay/gratipay.com/pull/4290). Restarted ...

**Comment by mattbk** [comment]
- Closed a team
- Closed the owner account

Success!

**Comment by whit537** [comment]
Huzzah! Now we just need Travis ...

**Pull request merged**
