### PR TITLE
Temporarily disable route changes during migration

### PR DESCRIPTION
**Pull request by whit537**
Ping @rohitpaulk @techtonik @clone1018 et al. This addresses https://github.com/gratipay/gratipay.com/issues/3391#issuecomment-100399161.

### CODE REVIEW

**Comment by whit537** [comment]
I plan to merge this myself tomorrow if someone else doesn't get to it first or throw a blocker.

**Comment by rohitpaulk** [comment]
Why have you disabled the bank account form? The only immediate requirement is to disable the credit card form, correct?

**Comment by whit537** [comment]
Good question. It's still unclear at this point what we're going to do with funds escrowed under our old business model, and if a user attaches a bank account they can close their account and withdraw their funds apart from payday. By turning off bank accounts we close that hole.

**Comment by whit537** [comment]
And now, having stated that publicly, I'm going to proceed with merging and deploying this PR.

**Comment by techtonik** [comment]
LGTM.

**Comment by whit537** [comment]
!m @techtonik

**Pull request merged**
