### PR TITLE
Fixing fakedata

### PR DESCRIPTION
**Pull request by kaguillera**
Redid `fake_data.py` mainly so that I can finish #4128 but I think that it badly needed an update to catch up with the changes in direction that we have taken. 

So here is what I have done. So please review @aandis , @rohitpaulk , @whit537  and let me know if there are any problems/changes to be made. 

No rush since we may have more important things on the table.

### CODE REVIEW

**Comment by whit537** [comment]
No rush but this is also easy to merge, since it only touches fake data.

👍 

!m @kaguillera 💃

**Comment by kaguillera** [comment]
it is not ready. there is some bugs that I have to work out still

**Comment by whit537** [comment]
Oh! Okay, then. :-)

**Comment by kaguillera** [comment]
I know that it is only fake data but I believe that it has to be realistic enough for anyone who wants to development on gratipay but does to have access to actual snapshots of production

**Comment by kaguillera** [comment]
So working on this today and thought I had it, but now the `fake_payments` are being created before the `fake_payday` is inserted into db thus this is causing an `IntegrityError` 😱

**Comment by kaguillera** [comment]
Ok I am finally ready for this to be reviewed. There are other things I would like to do to `fake_data.py` but this will do for now especially for finishing https://github.com/gratipay/gratipay.com/pull/4128. 
I would like to put back creating `fake_takes` and its associated data but with our new approach. I will do that in another PR(s)

**Comment by whit537** [comment]
Tests are failing, eh?

**Comment by kaguillera** [comment]
screen shot 2016-11-21 at 1 33 09 pm

According to this it is an `test_rs_syncs_a_readme` that is failing...I wasn't me... 😱

**Comment by whit537** [comment]
Ah, that's related to #4176 and the like. Maybe a rebase will get rid of it? Need a rebase anyway before merging ...

**Comment by kaguillera** [comment]
Cool will look into it. I am guess I will see 250+ commits though 😦

**Comment by whit537** [comment]
> I am guess I will see 250+ commits though 😦

:-)

Take good notes and maybe can catch out the error this time?

**Comment by kaguillera** [comment]
Ok nothing strange but I don't know what to do. Since I did not make any changes to any files I can't push anything so how to I get travis to rerun the rebased branch?

**Comment by whit537** [comment]
@kaguillera Once you rebase locally on master, try force-pushing to update the remote branch here. Travis should re-run.

**Comment by kaguillera** [comment]
tanx @whit537

**Comment by kaguillera** [comment]
Ready for review

**Comment by whit537** [comment]
Woo-hoo! !m @kaguillera 💃

**Comment by kaguillera** [comment]
Closing 🙇

**Comment by whit537** [comment]
@kaguillera PRs are closed automatically when they're merged. :)

**Pull request merged**
