### PR TITLE
Vault new cards at Braintree

### PR DESCRIPTION
**Pull request by rohitpaulk**
#3377, #3287

- [x] Backwards compatibility for invalidation
- Fix credit card page and verify for following cases: 
  - [x] No credit card attached
  - [x] Card attached (balanced)
  - [x] Card attached (braintree)
  - [ ] Updates card (from balanced to braintree)
  - [x] Updates card (from braintree to braintree)
- [x] Fix receipt page

### CODE REVIEW

**Comment by rohitpaulk** [comment]
https://developers.braintreepayments.com/javascript+python/guides/credit-cards#options

Looks like Braintree only requires the `postal_code`, and none of the other address fields.

**Comment by whit537** [comment]
Per https://github.com/gratipay/gratipay.com/issues/3387#issuecomment-100373415, let's limit the scope of this PR to vaulting new cards on Braintree instead of Balanced. We want to deploy that ASAP, don't want to block it on `billing.exchanges` work.

**Comment by whit537** [comment]
Per https://github.com/gratipay/gratipay.com/issues/3387#issuecomment-100384080 let's please double-vault to avoid a race condition unless we can think it through again from the top to ensure there isn't one.

**Comment by whit537** [comment]
And !m @rohitpaulk. Happy to be [rustlin' dogies](https://github.com/gratipay/gratipay.com/issues/3377#issuecomment-100380277) with you, friend. :-)

**Comment by rohitpaulk** [comment]
!m @whit537 :)

**Comment by rohitpaulk** [comment]
@whit537 - I haven't gotten to the Braintree tests, but this is ready for you to look at and start testing manually.

**Comment by whit537** [comment]
Awesome, thank you.

**Comment by whit537** [comment]
In terms of timing on this, I think we should wait to deploy until the old cards are migrated to Braintree. Sound right, @rohitpaulk?

**Comment by rohitpaulk** [comment]
> In terms of timing on this, I think we should wait to deploy until the old cards are migrated to Braintree. Sound right, @rohitpaulk?

Nope, this is ready to deploy now - it's backwards compatible with balanced cards.

**Comment by rohitpaulk** [comment]
@whit537 - I'd look at this as a better alternative to #3392.

**Comment by whit537** [comment]
Took a first read through the code. What happens if someone fills out the credit card form after Balanced initiates the export but before Braintree completes it?

**Comment by rohitpaulk** [comment]
If they're filling out the cc form - the new details will be sent to Braintree and **if** there was an old card(Braintree or Balanced), it'll be deleted.

**Comment by whit537** [comment]
> the new details will be sent to Braintree

And then what happens when Braintree imports the old details, which will be included in the snapshot that Balanced took before the user posted the cc form?

**Comment by rohitpaulk** [comment]
Once braintree is done importing, we'll only use the accounts for those who have **not** updated their card details, and delete the others.

**Comment by whit537** [comment]
Interesting. I guess I need to run this code and look at the sandbox to understand how that's possible. I guess when we start saving cards now we'll be generating new Braintree customer ids, right? I guess Braintree will create a second customer record for those customers when it does the import. Presumably Balanced sent along some info that will show up in the customer records at Braintree that will allow us to connect them with participants in our database, and we can deduplicate based on that. Is that it?

**Comment by whit537** [comment]
Two more points:

 - Bring back bank accounts opens up the hole mentioned at https://github.com/gratipay/gratipay.com/pull/3392#issuecomment-100478987 again.
 - Should we include the braintree sandbox login in a comment so devs can inspect as needed?

**Comment by whit537** [comment]
Regression: https://app.getsentry.com/gratipay/gratipay-com/group/65471207/.

**Comment by whit537** [comment]
Steps to reproduce: visit https://gratipay.com/about/me/routes/credit-card.html.

**Comment by whit537** [comment]
P.S. Does Braintree vault for us automatically or do we have to explicitly ask for cards to be stored permanently?

**Comment by rohitpaulk** [comment]
> I guess when we start saving cards now we'll be generating new Braintree customer ids, right?

Yes.

> I guess Braintree will create a second customer record for those customers when it does the import. 
> Presumably Balanced sent along some info that will show up in the customer records at Braintree that will allow us to connect them with participants in our database, and we can deduplicate based on that.

I'm assuming that we'll be provided with a mapping between `balanced_customer_href`'s and `braintree_customer_id`s. We search for a participant via the `balanced_customer_href` and update their `braintree_customer_id` and  card route **only if** they don't have a braintree card route already.

**Comment by rohitpaulk** [comment]
> Bringing back bank accounts opens up the hole mentioned at #3392 (comment) again.

As long as people can close their accounts (and use their bank account as the disbursement strategy), isn't that hole always open?

> Should we include the braintree sandbox login in a comment so devs can inspect as needed?

Hmm, we didn't do that for Balanced. I think it'd be best to wait for someone to ask.

> Does Braintree vault for us automatically or do we have to explicitly ask for cards to be stored permanently?

Automatically :dancer:

**Comment by whit537** [comment]
> Hmm, we didn't do that for Balanced. I think it'd be best to wait for someone to ask.

Balanced did sandboxing differently. But yeah we can wait.

> [I]sn't that hole always open?

Yeah, but it's wider if people can connect new accounts.

>Automatically

Cool.

**Pull request merged**
