### PR TITLE
team preliminaries

### PR DESCRIPTION
**Pull request by whit537**
&#x2B11; #3994

#4045 &rarr;

#### Punchlist 

- [x] remove all instances of the word "payroll"
- [x] drop `payroll` table (it was never used)
- [x] ~~rename `process_draws` to `process_unclaimed`~~ https://github.com/gratipay/gratipay.com/pull/4037#issuecomment-226743945
- [x] ~~move value computations into triggers—https://github.com/gratipay/gratipay.com/pull/4023#issuecomment-218822304~~ new PR ...
- [x] `payments` &rarr; `_payments_for_debugging` (in `Payday.payin`)
- [x] rebase once #4062 lands

Remake of #4009.

### CODE REVIEW

**Comment by whit537** [comment]
Rebased on master. Preview head was 9d6a8d6ac0305808f8203c9fe468061729ce32f9.

**Comment by whit537** [comment]
Alright, picking up from https://github.com/gratipay/gratipay.com/pull/4023#issuecomment-218892612, let's get a commit on here that converts existing cached values into triggered computations ...

**Comment by whit537** [comment]
```
payment_instruction
    giving
    ngiving_to
    receiving
    nreceiving_from
receiving
    distributing
    taking
ownership
    taking
    ntaking_from

giving              payment_instruction
ngiving_to          payment_instruction
receiving           payment_instruction
nreceiving_from     payment_instruction
distributing        receiving
ndistributing_to
taking              receiving           ownership
ntaking_from        ownership
```

Key: https://github.com/gratipay/gratipay.com/pull/4023#issuecomment-219128785.

**Comment by whit537** [comment]
screen shot 2016-06-02 at 1 10 10 pm

```
digraph G {
    "giving" -> "payment_instruction" [dir=back]
    "ngiving_to" -> "payment_instruction" [dir=back]
    "receiving" -> "payment_instruction" [dir=back]
    "nreceiving_from" -> "payment_instruction" [dir=back]
    "distributing" -> "receiving" [dir=back]
    "taking" -> "receiving" [dir=back]
    "taking" -> "ownership" [dir=back]
    "ntaking_from" -> "ownership" [dir=back]
}
```

http://www.webgraphviz.com/

**Comment by whit537** [comment]
Alright, ticked off the last little item on this PR, and made a new PR for the cached values work: #4045.

**Comment by whit537** [comment]
Marking this ready for review, @rohitpaulk @aandis et al.

**Comment by whit537** [comment]
Blocking on #4062.

**Comment by whit537** [comment]
Rebased on master, previous head was 53da3c64e30bab2f922926ef84c9903f860f92bf.

**Comment by whit537** [comment]
Rebased on master (d6ae1bc), previous head was d3f34b33a17950523c8f6f87c6b6bd1d04aff03a.

**Comment by whit537** [comment]
Rebased again to drop 7f54ee4aa1170d6fd16fa0731cd0b9ae6924edd8 because of the way the takes proposal is changing at https://github.com/gratipay/gratipay.com/issues/3994#issuecomment-221896610. Previous head was 234ba4ca29f9d7cdceb43ee3d32f4ab4c971f45a.

**Comment by whit537** [comment]
Reopen to kick Travis. Failure was spurious (https://github.com/gratipay/gratipay.com/issues/4066).

**Comment by whit537** [comment]
Rebased to not touch the `takes` table. Now all this PR does is remove the word "payroll" from our codebase, and clarify a variable name. Previous head was 92430d18de2d02675a0b27ca9f59120be98562dd.

**Comment by whit537** [comment]
Ready for review @rohitpaulk @aandis.

**Comment by whit537** [comment]
Ping @aandis @rohitpaulk. I'd like to start another push on #3994, and this is a prerequisite.

**Comment by aandis** [comment]
Looks good to me.

**Pull request merged**
