### PR TITLE
Changed suggested pricing to flat 5%

### PR DESCRIPTION
**Pull request by yifeiwu**
Is this good?

### CODE REVIEW

**Comment by whit537** [comment]
Hmmm ... where is Travis?

**Comment by whit537** [comment]
"[My Pull Request isn’t being built](http://docs.travis-ci.com/user/pull-requests/#My-Pull-Request-isn%E2%80%99t-being-built)"

**Comment by whit537** [comment]
> So when you create or update a pull request, and Travis CI doesn’t create a build for it, make sure the pull request is mergeable.

GitHub sez this PR is mergeable. Hmmm ...

**Comment by yifeiwu** [comment]
Hmm, might be because my branch was not updated.

**Comment by whit537** [comment]
Hey, look at that! Weird. :-)

**Comment by whit537** [comment]
I was actually just running the tests locally, too. Green both places! :)

Gonna review the code and TTW ...

**Comment by whit537** [comment]
Thanks for the contribution, @yifeiwu! There's some additional work that needs to be done on this but this is a good start. If you'd like to keep hacking on Gratipay, may I add you as a collaborator on the repo? That way you can work on branches in the main repo instead of a fork.

**Comment by yifeiwu** [comment]
Sure thing chad, would love to be of help!

**Pull request merged**
