### PR TITLE
Bring back account closing

### LINKED ISSUE #3461: bring back account closing
Turned off in #3454, in order to avoid leaking payments under our old Gratipay 1.0 terms of service, about which there were some [legal concerns](https://medium.com/gratipay-blog/gratipocalypse-42fd0ec0d9e8).

##### Notify

 - [ ] https://gratipay.freshdesk.com/helpdesk/tickets/2082
 - [ ] https://gratipay.freshdesk.com/helpdesk/tickets/2147
 - [ ] https://gratipay.freshdesk.com/helpdesk/tickets/2161
 - [ ] https://gratipay.freshdesk.com/helpdesk/tickets/2162
 - [ ] https://gratipay.freshdesk.com/helpdesk/tickets/2166
 - [ ] https://gratipay.freshdesk.com/helpdesk/tickets/2330
 - [ ] https://gratipay.freshdesk.com/helpdesk/tickets/2352
 - [ ] https://gratipay.freshdesk.com/helpdesk/tickets/2090
 - [ ] https://gratipay.freshdesk.com/helpdesk/tickets/2414
 - [ ] https://gratipay.freshdesk.com/helpdesk/tickets/2579
 - [ ] https://gratipay.freshdesk.com/helpdesk/tickets/2597

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/16208287-bring-back-account-closing?utm_campaign=plugin&utm_content=tracker%2F85909&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F85909&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by whit537**
Closes #3461.

### CODE REVIEW

**Comment by whit537** [comment]
Alright, so we no longer have bank withdrawals as a disbursement option. Do we try to add PayPal, which would require [finding a one-off API](https://developer.paypal.com/docs/api/), or do we simply remove bank withdrawal and leave it at that?

**Comment by whit537** [comment]
I think we just remove bank withdrawal for now. We don't have a lot of time.

**Comment by whit537** [comment]
The "final gift" disbursement strategy doesn't really make sense anymore since we're moving away from indefinite escrow (#1383). Once we start charging in arrears (#3378), then the only reason to have money in escrow will be pending or failed payouts.

**Comment by whit537** [comment]
And that means we no longer have disbursement strategies as part of account closing.

**Comment by whit537** [comment]
I mean, unless we wanted to try to implement async PayPal payouts at some point. I don't think we need to care about that though, because we now require a payout route in order to receive money, and we're moving to a system in which the only way to have escrow is if your payout route has failed. I guess we should just make sure there are no *pending* payouts during account closing, since a pending payout could fail, and then what?

**Comment by whit537** [comment]
Anyway, ripping out disbursement strategies entirely ...

**Comment by whit537** [comment]
Alright, what's next? I guess we need to clear subscriptions instead of tips. And what about team ownership now?

**Comment by whit537** [comment]
We have a couple options with teams: either we automatically close teams when the owner closes their account, or we make the owner go through a separate "close team" workflow first. We certainly want a "close team" workflow anyway. Do we want to make team owners jump through that hoop or otherwise confirm somehow that closing their account will close their team? Probably.

**Comment by whit537** [comment]
Do we release team slugs/names immediately upon team closing?

**Comment by whit537** [comment]
Ooooh, that's right ... we don't have any team membership, only owners. :-(

**Comment by whit537** [comment]
Ready for review, @rohitpaulk @rorepo et al.

**Comment by whit537** [comment]
Gonna go ahead and self-merge, as this has been out for 10 days and we need to start landing some 2.0 cleanup so we can stay on track for [August 20](https://github.com/gratipay/gratipay.com/issues/3539).

**Comment by mattbk** [comment]
General question, is it supposed to work live on the site once you merge?  Or is there another step?  I'm not hip on how git works.

**Comment by rohitpaulk** [comment]
@mattbk - There is a deploy step after the merge. All deploys are logged in https://botbot.me/freenode/gratipay/, you could compare the timestamps to see if a merged PR has actually been deployed :)

**Comment by mattbk** [comment]
Thanks! 

On July 16, 2015 12:42:02 PM CDT, Paul Kuruvilla <notifications@github.com> wrote:
>@mattbk - There is a deploy step after the merge. All deploys are
>logged in https://botbot.me/freenode/gratipay/, you could compare the
>timestamps to see if a merged PR has actually been deployed :)
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/gratipay/gratipay.com/pull/3601#issuecomment-122032046

-- 
Sent from a phone that, although intelligent, is not street smart.

**Pull request merged**
