### PR TITLE
remove payout from payday

### PR DESCRIPTION
**Pull request by whit537**
We only support PayPal now, which we process in a separate step from payday proper.

### CODE REVIEW

**Comment by whit537** [comment]
Ping @rohitpaulk @rorepo @kzisme et al.

**Comment by whit537** [comment]
Hmm ... this surely breaks tests ...

**Comment by rohitpaulk** [comment]
> Hmm ... this surely breaks tests ...

Nope, all tests related to balanced have been deleted.

**Comment by whit537** [comment]
Welllllllll, shucks. Huzzah! :-)

**Pull request merged**
