### PR TITLE
Fix payday stats

### PR DESCRIPTION
**Pull request by rohitpaulk**
https://github.com/gratipay/gratipay.com/issues/3847 and https://github.com/gratipay/gratipay.com/issues/3841

### CODE REVIEW

**Comment by rohitpaulk** [comment]
Ran this on a backup - 

Before: 

screen shot 2015-10-24 at 2 57 39 pm

After:

screen shot 2015-10-24 at 2 57 23 pm

**Comment by whit537** [comment]
> After:
>
screen shot 2015-10-24 at 2 57 23 pm


Nice!

**Comment by rohitpaulk** [comment]
I removed a commit which had a few comments on it - We decided to consider both users and teams active even if they only received/accrued `dues`, and didn't actually exchange money within Gratipay.

**Comment by rohitpaulk** [comment]
Deployed, ran `branch.py`.

**Comment by rohitpaulk** [comment]
Removed `branch.py` in https://github.com/gratipay/gratipay.com/commit/b35692f08fadf05b77f67df1ae793f685949cb3c

**Comment by whit537** [comment]
!m @rohitpaulk

**Pull request merged**
