### PR TITLE
Convert Throttle to a 400

### PR DESCRIPTION
**Pull request by whit537**
https://sentry.io/gratipay/gratipay-com/issues/236526695/

### CODE REVIEW

**Comment by whit537** [comment]
e58fd184129eaf284d17149e1097e2c1b89acbee is a naive fix. Ideally, though, we'd make `Throttled` a subclass of `Response` since it'll always only ever wanna be a 400 (what other `Throttled`s are lurking?). The complication is i18n of the error message, which we only have easy access to in simplate context.

**Comment by whit537** [comment]
What other places could leak `Throttled`?

**Comment by Changaco** [comment]
> The complication is i18n of the error message, which we only have easy access to in simplate context.

That's what [`LazyResponse`](https://github.com/gratipay/gratipay.com/blob/2063/gratipay/utils/__init__.py#L270) is for. I have lots of those [in Liberapay](https://github.com/gratipay/gratipay.com/blob/2063/gratipay/utils/__init__.py#L270).

**Comment by whit537** [comment]
I reviewed all of our `email_queue.put` calls and confirmed that this is the only place we need to catch this.

**Comment by whit537** [comment]
Alright, ready to review @rohitpaulk @mattbk @nobodxbodon et al.

**Pull request merged**
