### PR TITLE
updated copy re: arrears

### LINKED ISSUE #3794: Text incorrect at about/me/routes/credit-card
> To minimize processing fees, we charge your credit card at least $10 at a time (anything extra stays in Gratipay to use in future weeks). Read More

Should reflect the charging in arrears, so remove the bit about "extra."

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/26838743-text-incorrect-at-about-me-routes-credit-card?utm_campaign=plugin&utm_content=tracker%2F85909&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F85909&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by whit537**
Closes #3794.

### CODE REVIEW

**Comment by whit537** [comment]
How's it look, @mattbk?

**Comment by mattbk** [comment]
Looks good.

**Comment by whit537** [comment]
@mattbk Click the merge button! :dancer:

**Comment by whit537** [comment]
Added another commit to pick off #3791 as well.

**Comment by whit537** [comment]
Woo-hoo! !m @mattbk 

Tip: good form is to also click "Delete branch" after merging. I'll give you the honors? :-)

**Pull request merged**
