### PR TITLE
Make fake packages

### PR DESCRIPTION
**Pull request by whit537**
Redux of #4433 that doesn't aim for inclusion in #4305, but rather blocks on #4305.

### CODE REVIEW

**Comment by whit537** [comment]
Don't forget to sort out that name collision though.

**Comment by whit537** [comment]
Mondo rebase, was 174e8406833e0b97515840b7c19e7ca734e62380.

**Comment by rohitpaulk** [comment]
Conflicts.. Looks like one of my changes, I'll resolve.

**Comment by whit537** [comment]
Rebased, was 4910223b92806753c925b7a7d1c482e54a4a7319.

**Comment by whit537** [comment]
Ready for review, @rohitpaulk @kaguillera et al.!

**Comment by kaguillera** [comment]
Simple enough. LGTM

**Comment by whit537** [comment]
Rebased! Was dccf8ae58e072e90740aeba5d9d2782377f5f245.

**Comment by kaguillera** [comment]
Closing

**Pull request merged**
