### PR TITLE
Implement SameSite cookies. 🍪

### PR DESCRIPTION
**Pull request by EdOverflow**
`SameSite` attribute set to `Lax`.

https://tools.ietf.org/html/draft-west-first-party-cookies-07

### CODE REVIEW

**Comment by whit537** [comment]
Build failures?

**Comment by EdOverflow** [comment]
@whit357 I am not entirely sure how to solve this. This is not a priority so maybe I should have just opened an issue for SameSite cookies.

**Comment by whit537** [comment]
Looks like a `SyntaxError`:

```
    set_cookie(cookies, SESSION, token, expires=new_expires, samesite)
SyntaxError: non-keyword arg after keyword arg
```

Are you familiar with the distinction between keyword and non-keyword arguments in Python?

**Comment by EdOverflow** [comment]
Oh, whoops! I see the issue now.

**Comment by EdOverflow** [comment]
It turns out there isn't a `samesite` morsel object in https://docs.python.org/2/library/cookie.html#morsel-objects.

**Pull request closed without merging**
