### PR TITLE
Our first "Unclaimed" PayPal payout

### PR DESCRIPTION
**Pull request by whit537**
I guess this is pending? We'll have to check again later ...

### CODE REVIEW

**Comment by rohitpaulk** [comment]
From https://www.paypal.com/us/webapps/helpcenter/helphub/article/?solutionId=FAQ2038&topicID=&m=ARA

> An unclaimed payment is a payment that your recipient hasn’t accepted yet. There are a few reasons why your payment might be unclaimed.

> A payment might be unclaimed because:
> - The recipient hasn’t signed up for a PayPal account yet.
> - You sent money to an email address that the recipient hasn’t added to their PayPal account. As soon as they add the address to their account, the money will show up in their balance.
> - The recipient is still deciding whether they want to accept your payment. (This can happen if you don’t have a Confirmed address.)

> To find out why your payment is unclaimed, contact the person you sent money to. After 30 days, an unclaimed payment is automatically canceled and the money is returned to you.

**Comment by whit537** [comment]
Looks like it hasn't been claimed yet.

To: []

> Chad Whitacre here from Gratipay. We sent you a payment via PayPal last week, and it's currently "unclaimed." I'm writing to make sure that we sent the payment to the right place. Can you please confirm? Thanks! :)

**Comment by whit537** [comment]
Hrm. This PR is ready for review, anyway. :)

**Comment by whit537** [comment]
Found the ticket for this: #3528. Moving convo there ...

**Pull request merged**
