### PR TITLE
preen layout

### PR DESCRIPTION
**Pull request by whit537**
Gonna leave this one sit a few days. We need to stop having me merge my own pull requests!

Ping @mattbk @rohitpaulk @techtonik @kzisme @kaguillera @clone1018 et al.

Who wants to merge this one? :-)

### CODE REVIEW

**Comment by whit537** [comment]
Closes #3739, while also fixing a bunch of other little things.

screen shot 2015-09-02 at 11 02 22 pm

**Comment by whit537** [comment]
Tested on OS X in Chrome, Safari, and Firefox:

screen shot 2015-09-02 at 11 16 18 pm

**Comment by whit537** [comment]
screen shot 2015-09-03 at 12 59 03 am

**Comment by techtonik** [comment]
@whit537 it is hard to review, because it is not really clear what was there before. And this gives me an idea - what if we add site screens to repository, so that every PR with design changes has a visual annotation of changes?

https://help.github.com/articles/rendering-and-diffing-images/

**Comment by whit537** [comment]
> it is not really clear what was there before.

Just look at https://gratipay.com/, no?

**Comment by whit537** [comment]
> And this gives me an idea - what if we add site screens to repository, so that every PR with design changes has a visual annotation of changes?

This is an interesting idea. I think we'd want to automate it to prevent it from becoming unwieldy—there are so many app states to consider that the number of screenshots involved would be quite large.

**Comment by whit537** [comment]
Rebased on master.

**Pull request merged**
