### PR TITLE
Add coinbase payin support

### PR DESCRIPTION
**Pull request by rohitpaulk**
Work in progess.

This is a redo of #2053 

> This pull request is too big. Gittip can only chew things in small bites. We need to break this up into smaller PRs.

- [x] Add UI to link coinbase account
- [x] Store coinbase result in DB
- [x] Set `is_funded` correctly by including `last_coinbase_result` too in `participant.py`. 
- [x] Same as above, in fake_payday.sql
- [x] What are the fees for coinbase transactions?
- [ ] Modify payday to first try a credit card, and then a coinbase account if that fails. If #2299 lands before this, this will have to include changes from there. 
- [ ] Modify the missing credit card warnings to display coinbase as an option.
- [ ] Update docs/about/faq wherever needed.

### CODE REVIEW

**Comment by seanlinsley** [comment]
It doesn't look like this has been worked in a while, so I'm marking it as blocked.

**Comment by rohitpaulk** [comment]
I'd like to work on this, but I'll need help on integrating the coinbase calls into payday. https://github.com/gratipay/gratipay.com/pull/2914 was a step in this direction, I'm not sure what's next.

cc: @Changaco

**Comment by Changaco** [comment]
I didn't know this was waiting for me. This PR has the same problems as #2824. We don't want to keep adding columns like `last_coinbase_result` to `participants`. We need to generalize the code to handle any number of payment methods. I already have a local branch for that but I haven't done much work on it yet.

**Comment by techtonik** [comment]
>
> We don't want to keep adding columns like last_coinbase_result to
> participants.
>
Does anybody use tools to see (or dump) the current structure of DB
visually? Some time ago looked for some command line tool that outputs into
.png in a predictable way, but didn't find any that worked for me.

**Comment by rohitpaulk** [comment]
> I didn't know this was waiting for me.

That's my fault, I should've asked you once more after we implemented #2914. 

> We need to generalize the code to handle any number of payment methods.

Yes, that makes sense.

**Comment by rohitpaulk** [comment]
Closing this (https://github.com/gratipay/gratipay.com/issues/3245).

**Pull request closed without merging**
