### PR TITLE
Tweak deploy confirmation

### PR DESCRIPTION
**Pull request by whit537**
I want it at the end, actually. 😁 

Follow-on from #4202.

### CODE REVIEW

**Comment by whit537** [comment]
Rebased (was fa8388730082e2a4a7361c03d13312bbd1ebf17d). Should be an easy one, @clone1018 @kaguillera @rohitpaulk ...

**Comment by clone1018** [comment]
Great feature, will merge after tests (how can they fail?!).

**Comment by clone1018** [comment]
"but we merge back to `master` without squashing."

**Comment by whit537** [comment]
👍

Review 2! :-)

**Pull request merged**
