### PR TITLE
Update gravatar size in URL

### LINKED ISSUE #3196: Blurred (GitHub?) avatars on profile pages
Some profile pictures (avatars) appear blurry for me. Judging from a few samples, mostly pictures imported from Github seem to be affected. Take mine as an example:
https://gratipay.com/korakinos/
https://github.com/korakinos

Among the samples I took, almost all avatars from Twitter weren't blurred, except, strangely, for one. As I don't know if the person appreciates linking, I'll just post the username: InquilineKea

A similar issue in the past was [issue 887](https://github.com/gratipay/gratipay.com/issues/887). Only back then, Twitter images were blurred.

*(Off topic: Gratipay is awesome. Thank you all so much for your efforts!)*

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/8758712-blurred-github-avatars-on-profile-pages?utm_campaign=plugin&utm_content=tracker%2F85909&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F85909&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by ESWAT**
Fixes #3196. We fetch the 160px-sized image instead of the old 128px one.

### CODE REVIEW

**Comment by Changaco** [comment]
That's not enough, the URLs already in the DB need to be updated too.

**Comment by Changaco** [comment]
Added the necessary `branch.sql`. Ready for review.

**Comment by jonathan-s** [comment]
@Changaco @ESWAT Though it seems like this wasn't enough. My gravatar image comes in at 80x80 and is incredibly blurry: https://gratipay.com/Jonathan%20Sundqvist/

**Comment by techtonik** [comment]
@jonathan-s it may happen that avatar is only fetched once when a profile is created, but.. it may also be fetched when you update the details. Can you try it?

**Comment by jonathan-s** [comment]
I changed the image of the gravatar for that reason. Thinking that the
image was low res. Though the same result ensued. My profile pic on day
github has a high res picture. Which obviously changed as well.

On Monday, May 4, 2015, anatoly techtonik <notifications@github.com> wrote:

> @jonathan-s <https://github.com/jonathan-s> it may happen that avatar is
> only fetched once when a profile is created, but.. it may also be fetched
> when you update the details. Can you try it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gratipay/gratipay.com/pull/3227#issuecomment-98618191>
> .
>


-- 
Sent from Gmail Mobile

**Comment by whit537** [comment]
Reticketed as #3381.

**Pull request merged**
