### PR TITLE
Sign in to migrate

### PR DESCRIPTION
**Pull request by whit537**
Per https://github.com/gratipay/gratipay.com/pull/4679#issuecomment-341246316.

### CODE REVIEW

**Comment by Changaco** [comment]
Looks like this was merged but not deployed.

**Comment by rohitpaulk** [comment]
Deployed.

screen shot 2017-11-02 at 7 24 07 pm

**Comment by whit537** [comment]
Seeing it now:

screen shot 2017-11-02 at 2 43 09 pm

**Comment by whit537** [comment]
Derp I'm a dork. 😊 

!m @Changaco @rohitpaulk

**Pull request merged**
