### PR TITLE
Exchange routes

### LINKED ISSUE #1681: wrong credit card on receipt
From @tomaslundborg via support@gittip.com:

> when you change your card, all the receipts, historically, are changed, so it looks like the new card has payed for all of them. no trace of the old card, that payed for the historic ones. 

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/1328938-wrong-credit-card-on-receipt?utm_campaign=plugin&utm_content=tracker%2F85909&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F85909&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Changaco**
Closes #1681 and #2446. Unblocks #2824 and #3245.

### CODE REVIEW

**Comment by rohitpaulk** [comment]
How does https://github.com/gratipay/gratipay.com/commit/b6d7f65efc4237a393a3d53b6eab1d5989dbb3a0 solve #1681? 

From #2443 - 

> Even if we start logging additional information about exchanges it won't fix the past receipts (#1681). If we want to fix those we'll have to do lots of Balanced API queries to retrieve the information.

We don't seem to be doing anything about previous exchanges here - shouldn't we be linking all of them to the respective route(s)?

**Comment by Changaco** [comment]
b6d7f65efc4237a393a3d53b6eab1d5989dbb3a0 solves #1681 in that we won't be showing the wrong credit card anymore. However you're right, I haven't written a script to backfill the `route` column, so we won't be showing the right credit card either. The issue for that is #2779.

**Comment by Changaco** [comment]
Rebased on master and added a couple of small commits.

**Comment by whit537** [comment]
Is "Exchange Routes" a term we're exposing in the UI? Or is that just internal?

**Comment by rohitpaulk** [comment]
> Or is that just internal?

Internal, as far as I've seen.

**Comment by whit537** [comment]
Okay. I bring it up because "exchange" in a financial context often means "foreign exchange," so I'm not sure it's the best user-facing term to use.

**Comment by rohitpaulk** [comment]
I guess I'm the only person who's reviewed this - It is a big change and probably deserves more eyeballs on it, but I'm merging this in coz it's a blocker.

**Comment by rohitpaulk** [comment]
One thing I just noticed - we haven't modified `record-an-exchange.spt`.

**Comment by rohitpaulk** [comment]
Reticketed as #3295

**Comment by Changaco** [comment]
`branch.py` done. I had to modify it a little:

```diff
@@ -1,3 +1,7 @@
+from __future__ import print_function
+
+import traceback
+
 import balanced
 
 from gratipay import wireup
@@ -56,8 +60,16 @@ with db.get_cursor() as cursor:
             print("processing participant %i/%i" % (i, total))
         customer = customer_from_href(p.balanced_customer_href)
         if p.last_bill_result != None:
-            card = customer.cards.one()
-            insert_exchange_route(p.id, 'balanced-cc', card.href, p.last_bill_result)
+            try:
+                card = customer.cards.one()
+                insert_exchange_route(p.id, 'balanced-cc', card.href, p.last_bill_result)
+            except Exception as e:
+                print('cc', p.id, p.last_bill_result)
+                traceback.print_exc()
         if p.last_ach_result != None:
-            ba = customer.bank_accounts.one()
-            insert_exchange_route(p.id, 'balanced-ba', ba.href, p.last_ach_result)
+            try:
+                ba = customer.bank_accounts.one()
+                insert_exchange_route(p.id, 'balanced-ba', ba.href, p.last_ach_result)
+            except Exception as e:
+                print('ba', p.id, p.last_ach_result)
+                traceback.print_exc()
```

There were 54 exceptions, all `NoResultFound`.

**Comment by Changaco** [comment]
Heroku deployment done.

I'm going to run the second part of `branch.sql` now, and #3249 too. Since gratipay/postgres.py#43 still isn't merged there will be a small downtime.

**Comment by Changaco** [comment]
Final step: updated `schema.sql` in 99205511fc92c347bbb2b2c894b2838e53596a01.

**Comment by whit537** [comment]
!m @Changaco @rohitpaulk [IRC](https://botbot.me/freenode/gratipay/2015-03-30/?msg=35393778&page=1)

**Pull request merged**
