### PR TITLE
Add link to example contributing.md

### PR DESCRIPTION
**Pull request by mattbk**

### CODE REVIEW

**Comment by whit537** [comment]
Ready for review? :-)

**Comment by mattbk** [comment]
Haven't tested it yet, just threw in what I thought would work.

**Comment by whit537** [comment]
Okay.

/me waits for the :hand: sign ...

**Comment by mattbk** [comment]
Set for review. Took a little to get running with the crypto stuff in master now. Upgrading Python to 2.7.11 let me install everything though.

**Comment by whit537** [comment]
Rebased and added 4ad94f335950dc66ffedd5e646f3afdaa6bcf11e to clean up whitespace.

**Pull request merged**
