### PR TITLE
Shellcheck - shellscript syntax improvement

### PR DESCRIPTION
**Pull request by PeterDaveHello**
Use shellcheck - https://github.com/koalaman/shellcheck for shellscript static analyse, and then improve the codes for a better style and safer way, will try to send another PR to integrate with CI later.

### CODE REVIEW

**Comment by nobodxbodon** [comment]
Greetings! Out of curiosity, did you find here because of the github ribbon on the site?

**Comment by whit537** [comment]
@PeterDaveHello Ready to rebase?

**Comment by PeterDaveHello** [comment]
@whit537 done!

**Pull request merged**
