### PR TITLE
Fix build breakage introduced in npm syncing

### PR DESCRIPTION
**Pull request by whit537**
Should address at least some of https://github.com/gratipay/gratipay.com/pull/4172#issue-187266655.

### CODE REVIEW

**Comment by whit537** [comment]
I don't like that our tests could silently pass if one of our dependencies goes missing at Travis, but I'm not sure of the best way to address that.

**Comment by whit537** [comment]
Ready for review and merge, @nobodxbodon @kaguillera.

**Comment by nobodxbodon** [comment]
LGTM. I wonder how review process works? The committer waits for at least one contributor giving green light?

**Comment by whit537** [comment]
@nobodxbodon Yeah, if it looks good to you then you can go ahead and merge! :-)

**Comment by nobodxbodon** [comment]
Sorry about the premature merging. I just realized that I overlooked the python parts. As I'm not that familiar with Travis, @kaguillera please review again.
@whit537 how could Travis miss any of our dependencies? Does that mean our code base replies on some thirty-party library that's not recognized by Travis?

**Comment by whit537** [comment]
> how could Travis miss any of our dependencies? Does that mean our code base replies on some thirty-party library that's not recognized by Travis?

We are [installing](https://github.com/gratipay/gratipay.com/blob/53c7b5cca05355d666aff9701e1bd9cbc5381297/.travis.yml#L12-L14) the necessary dependencies at Travis. My concern was that if that dependency installation started failing for some reason, we wouldn't notice right away, because we would simply start silently skipping said tests at Travis.

**Comment by kaguillera** [comment]
@nobodxbodon as you said it looks good to me. @whit537 as far as I see it will only ignore those test are associated with ijson and marky. That seems appropriate.

**Comment by rohitpaulk** [comment]
Umm shouldn't we be ensuring that those dependencies are installed on Travis? We've got full root access, what prevents us from doing so?

**Comment by whit537** [comment]
@rohitpaulk They _are_ [installed](https://github.com/gratipay/gratipay.com/blob/53c7b5cca05355d666aff9701e1bd9cbc5381297/.travis.yml#L12-L14) on Travis today. My point was just that if the deps installation ever breaks (e.g., the places we're installing from change), then we wouldn't notice because the tests would just be skipped and Travis would still be green. No?

**Comment by rohitpaulk** [comment]
I just read through the entire thread - what I meant to say is "Why make this change?". If tests are failing for anyone, the right way to fix it is to install the dependencies (which we could include in our bootstrap scripts) - not to skip tests.

**Comment by rohitpaulk** [comment]
> we wouldn't notice because the tests would just be skipped and Travis would still be green. No?

Exactly, this is the part that I don't like

**Comment by nobodxbodon** [comment]
> If tests are failing for anyone, the right way to fix it is to install the dependencies (which we could include in our bootstrap scripts) - not to skip tests. 

+1 is there a way to config Travis so missing dependency leads to failure instead of skipping? Feels like a common need to me.

**Comment by whit537** [comment]
> the right way to fix it is to install the dependencies

Yeah, but yajl and npm are so heavy. 😞  Options:

- Allow for the non-yajl `ijson` (less performant).
- Move this back out into [`gdr.rocks`](https://github.com/gratipay/gdr.rocks).

**Pull request merged**
