### PR TITLE
Fix payment table semantics

### PR DESCRIPTION
**Pull request by rohitpaulk**
https://github.com/gratipay/gratipay.com/pull/3414#commitcomment-11203627

### CODE REVIEW

**Comment by rohitpaulk** [comment]
I'd really like to fix `_check_balances` before we retry #3415. I don't have the time to fix it now, but I should be able to within 3-4 hours.

**Comment by whit537** [comment]
I'm ready to merge if you're okay with 46f047b0bdc3b4aa642a4ae6fc8d1c0f03665527, @rohitpaulk.

**Comment by whit537** [comment]
To be clear: this wasn't the reason why we have no `payments`, correct?

**Comment by whit537** [comment]
This bug is unrelated to that, yes?

**Comment by rohitpaulk** [comment]
> this wasn't the reason why we have no payments, correct?
> This bug is unrelated to that, yes?

Yes, and yes. :)

**Comment by whit537** [comment]
k :)

**Pull request merged**
