### PR TITLE
Mark dead letters dead and skip them

### PR DESCRIPTION
**Pull request by whit537**
Root cause fix for https://github.com/gratipay/gratipay.com/issues/4393.

### CODE REVIEW

**Comment by whit537** [comment]
Ready for review @rohitpaulk et al.! :-)

**Comment by whit537** [comment]
Kicked Travis because #4391.

**Comment by whit537** [comment]
Rebased, was f6b671e314655ceb3b18ce946e981164c66d6e9b.

**Comment by whit537** [comment]
Ping @rohitpaulk et al. Can we get this one in next? Our mail queue is trivially DOSable until this is in.

**Comment by rohitpaulk** [comment]
After this change, we'll have to recover manually from intermittent outages (earlier retries happened automatically for every error, whether intermittent or not). One solution to avoid this could be retrying with exponential backoff and only bailing after that. 

I'm fine with merging this and reticketing the above though, given the DOSability

**Comment by whit537** [comment]
I think we want to move in the direction of an email queue page on our dashboard where we can get some good visibility into the status of the queue, and retry failed messages, etc. I believe failed messages will still hit Sentry so in terms of notification about queue problems we should still be good.

**Comment by whit537** [comment]
So I guess that's a +1 for merge-and-reticket. ☺️

**Comment by whit537** [comment]
Rebasing, was 0fd53f1f539c7b18f6c14c86632e901c292575d0.

We're getting [bit](https://sentry.io/gratipay/gratipay-com/issues/242242031/) by this again. Planning to self-merge since it's affecting production and @rohitpaulk has already basically approved.

**Comment by whit537** [comment]
Eff, man. None of our charge notifications went out last week. We suck. 😞

**Comment by whit537** [comment]
Nor our suspicious notifications. 😭

**Comment by whit537** [comment]
Does that mean we have to do whatever dance we did last time to apologize for the late arrival? I'm not sure I wanna take the time to do that. 😞

**Comment by whit537** [comment]
screen shot 2017-04-24 at 12 17 21 pm

**Comment by whit537** [comment]
P.S. Noticed this because of Sentry's weekly report.

screen shot 2017-04-24 at 12 24 19 pm

**Comment by whit537** [comment]
Revisiting https://github.com/gratipay/gratipay.com/issues/4393#issuecomment-290062941 ...

>1. Extract addresses from verification messages in `email_queue`.
>1. Remove duplicate verifications from `email_queue`.
>1. Reset `emails.verification_start` for affected addresses.
>1. Remove the verifications with bad addresses.

Queue dumped with:

```
gratipay::MAROON=> \copy (select * from email_queue order by id) to queue.csv with csv;
COPY 89
gratipay::MAROON=>
```

**Comment by whit537** [comment]
Duplicate verifications removed with:

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import absolute_import, division, print_function, unicode_literals

import csv
import re
from collections import defaultdict


address_to_messages = defaultdict(list)


for row in csv.reader(open('queue.csv')):
    message_id = row[0]
    template = row[2]
    if template != 'verification': continue
    address = re.match(r"^.*S'email'\\012p\d\\012V(.*)\\012p.*$", row[3]).groups()[0]
    address_to_messages[address].append(message_id)

delete = []
for address, messages in sorted(address_to_messages.items()):
    keep = messages.pop()
    delete.extend(messages)

print("DELETE FROM email_queue WHERE id = ANY('{{{}}}'::int[]);".format(','.join(delete)))
```

**Comment by whit537** [comment]
```
gratipay::MAROON=> DELETE FROM email_queue WHERE id = ANY('{11259,11252,11231,11240,11257,11235,11265}'::int[]);
DELETE 7
```

**Comment by whit537** [comment]
I'm trying to extract the email addresses from the context field by unpickling but I'm getting `EOFError` from `pickle.loads`.

**Comment by whit537** [comment]
Gonna guess that `\012` is a newline ... maybe that's Postgres?

```
(Pdb) l
 13     for i, row in enumerate(csv.reader(open('queue.csv'))):
 14         message_id = row[0]
 15         template = row[2]
 16         if i == 4:
 17             import pdb; pdb.set_trace()
 18  ->         foo = pickle.dumps({'email': 'foo@example.com'})
 19             context = pickle.loads(row[3])
 20         #address_to_messages[address].append(message_id)
 21     
 22     raise SystemExit
 23     
(Pdb) n
> /Users/whit537/personal/gratipay/gratipay.com/dupes.py(19)<module>()
-> context = pickle.loads(row[3])
(Pdb) foo
'(dp0\nVemail\np1\nVfoo@example.com\np2\ns.'
(Pdb) row[3]
"(dp0\\012S'email'\\012p1\\012Va@a.com\\012p2\\012sS'include_unsubscribe'\\012p3\\012I00\\012sS'link'\\012p4\\012Vhttps://gratipay.com/~mattbk/emails/verify.html?email2=YUBhLmNvbQ~~&nonce=12915a91-af5c-4339-9429-ed22589daea0\\012p5\\012s."
(Pdb) print foo
(dp0
Vemail
p1
Vfoo@example.com
p2
s.
(Pdb) print row[3]
(dp0\012S'email'\012p1\012Va@a.com\012p2\012sS'include_unsubscribe'\012p3\012I00\012sS'link'\012p4\012Vhttps://gratipay.com/~mattbk/emails/verify.html?email2=YUBhLmNvbQ~~&nonce=12915a91-af5c-4339-9429-ed22589daea0\012p5\012s.
(Pdb)
```

**Comment by whit537** [comment]
I lucked out dumping @mattbk there. 😥

**Comment by whit537** [comment]
Converting to newline does it.

**Comment by whit537** [comment]
Only verifications include an email address in the context. For the rest we need to fetch it from `participant.email_address` based on `email_queue.participant`.

**Comment by whit537** [comment]
Redumped: 

```
gratipay::MAROON=> \copy (select q.*, p.email_address from email_queue q join participants p on q.participant = p.id) to queue.csv with csv;
COPY 82
```

**Comment by whit537** [comment]
```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import absolute_import, division, print_function, unicode_literals

import csv
import pickle
from collections import defaultdict


all_affected = set()
verifications = defaultdict(list)


for i, row in enumerate(csv.reader(open('queue.csv'))):
    message_id = row[0]
    template = row[2]
    if template.startswith('suspicious-'):
        print("skipping, don't want", template)
        continue
    address = pickle.loads(row[3].replace(r'\012', '\n')).get('email', row[5])
    if not address:
        print('skipping, no address:', template)
        continue
    all_affected.add(address)
    if template == 'verification':
        verifications[address].append(message_id)

delete = []
for address, messages in sorted(verifications.items()):
    keep = messages.pop()
    delete.extend(messages)


print()
print("DELETE FROM email_queue WHERE id = ANY('{{{}}}'::int[]);".format(','.join(delete)))
print()

to_verify = sorted(verifications.keys())
print("SELECT * FROM emails WHERE address = ANY('{{{}}}'::text[]) ORDER BY verification_start;"
      .format(','.join(to_verify)))
print()

print("UPDATE emails SET verification_start=now() WHERE address = ANY('{{{}}}'::text[]);"
      .format(','.join(to_verify)))
```

**Comment by whit537** [comment]
Parsing email addresses with `pickle` instead of `re` turns up two more dupes.

```
gratipay::MAROON=> DELETE FROM email_queue WHERE id = ANY('{11243,11234}'::int[]);
DELETE 2
gratipay::MAROON=>
```

**Comment by whit537** [comment]
Verification times reset.

**Comment by whit537** [comment]
57 addresses affected (for mail from support@).

**Comment by whit537** [comment]
Okay! I think we're ready to deploy this. Doing so should mark dead letters dead, and send the rest. Then we can follow up with apologies via Freshdesk.

**Comment by whit537** [comment]
... or maybe even an `emails/branch.html`?

**Pull request merged**
