### PR TITLE
spruce up the Team explorer

### LINKED ISSUE #3704: spruce up the Team explorer
Do #3703 first.

 - [ ] ~~Include images (#3701)~~
 - [ ] ~~put status in subnav~~
 - [ ] show all Teams to anon (right now anon can't browse or can't see unreviewed or something)
 - [ ] include cached values

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/26020900-spruce-up-the-team-explorer?utm_campaign=plugin&utm_content=tracker%2F85909&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F85909&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by whit537**
Closes #3704.

### CODE REVIEW

**Comment by whit537** [comment]
I want to use the whole width for the Teams table so we can show more columns.

screen shot 2015-08-31 at 6 27 51 pm

**Comment by whit537** [comment]
I want something like the GitHub issue browser. I prefer their interface, with filters and sorts tailored to their specific dataset, to a clumsy generic table sort/filter interface.

**Comment by whit537** [comment]
Along with that, a presentation that isn't strictly tabular.

**Comment by whit537** [comment]
... which is nevertheless information dense.

**Comment by whit537** [comment]
screen shot 2015-08-31 at 6 40 21 pm

**Comment by whit537** [comment]
From https://github.com/gratipay/gratipay.com/issues/3704#issuecomment-136409310:

> A list of "trending" (most active) Teams would be another way to do it, "Activity" would need to be defined.

Could be a sort, perhaps the default sort, the I think it's going to be out of scope for this PR since defining and implementing Activity will be a fair chunk of work.

**Comment by whit537** [comment]
screen shot 2015-08-31 at 6 45 58 pm

**Comment by whit537** [comment]
Failing tests already!? :(

**Comment by whit537** [comment]
*sigh*

**Comment by whit537** [comment]
screen shot 2015-08-31 at 8 33 59 pm

**Comment by whit537** [comment]
screen shot 2015-08-31 at 8 36 54 pm

**Comment by whit537** [comment]
screen shot 2015-08-31 at 8 37 35 pm

**Comment by whit537** [comment]
screen shot 2015-08-31 at 9 36 00 pm

**Comment by whit537** [comment]
screen shot 2015-08-31 at 10 24 55 pm

**Comment by rohitpaulk** [comment]
:+1: :+1:

**Pull request merged**
