### PR TITLE
Update Medium Icon

### LINKED ISSUE #4336: Update Medium icon in footer
We're [way behind](https://blog.medium.com/the-story-behind-medium-s-new-logo-4cd3e143dfcf).

screen shot 2017-02-16 at 8 35 41 am

### PR DESCRIPTION
**Pull request by dmk246**
Closes #4336.

### CODE REVIEW

**Comment by whit537** [comment]
Will merge when green ...

**Comment by dmk246** [comment]
@whit537 I think I see green....wooooohoooo !

**Comment by whit537** [comment]
Good work, @dmk246! 😄  💸  💃  🌻

**Comment by dmk246** [comment]
Happy dance! So excited! Thank you @whit537 and @kaguillera for all your help and patience!

**Comment by kaguillera** [comment]
!m @dmk246 💃  💃  💃  💃  💃

**Pull request merged**
