### PR TITLE
Search

### PR DESCRIPTION
**Pull request by Changaco**
This PR implements search over profile statements as well as user and community names. It doesn't modify the homepage because that will be done later (#2809).

### CODE REVIEW

**Comment by clone1018** [comment]
Hey @Changaco, why didn't you put the form for searching in the navbar?

**Comment by Changaco** [comment]
Rebased on master.

**Comment by Changaco** [comment]
@clone1018 Because that's more complicated.

**Comment by clone1018** [comment]
@Changaco Can you elaborate? Form tags inside nav bars aren't anything new.

**Comment by clone1018** [comment]
I'm going to merge this because it's a great feature and we can always improve. 

Thanks @Changaco, deploying now.

**Pull request merged**
