### PR TITLE
Remove stray end tag.

### PR DESCRIPTION
**Pull request by EdOverflow**

### CODE REVIEW

**Comment by whit537** [comment]
Blech, spurious build failure, sorry. Build restarted.

**Comment by EdOverflow** [comment]
Can I merge this into the `master` branch?

**Comment by whit537** [comment]
@EdOverflow We try hard not to self-merge unless there's really no-one else paying attention for days on end. The thing to do in this situation is to ping a couple people using the GitHub "Reviewers" widget in the right sidebar.

That said, let me get to this one here ...

**Comment by EdOverflow** [comment]
OK, I will ensure not to self-merge in future.

**Pull request merged**
