### PR TITLE
Rise to the ACME challenge

### PR DESCRIPTION
**Pull request by whit537**
StartSSL is hosed, so we need a new TLS cert vendor (https://github.com/gratipay/gratipay.com/issues/4327). Let's Encrypt suggests itself, but we need a way to pass verification challenges for multiple domains. Let's build a way!

### CODE REVIEW

**Comment by whit537** [comment]
Appears to be a hang-up with a (root?) path part starting with `.`. Investigating ...

**Comment by whit537** [comment]
Aspen isn't matching the hidden directory, so it's falling into the [project &rarr; ~user fallthrough](https://github.com/gratipay/gratipay.com/blob/2046/www/%25team/%25sub.spt).

**Comment by whit537** [comment]
screen shot 2017-02-09 at 8 29 44 pm

----------------------------

screen shot 2017-02-09 at 8 29 52 pm

----------------------------

screen shot 2017-02-09 at 8 29 59 pm

**Comment by whit537** [comment]
Ready for review, @clone1018 et al.

**Comment by clone1018** [comment]
Good solution! Waiting on travis.

**Pull request merged**
