### PR TITLE
Update dnt.spt

### PR DESCRIPTION
**Pull request by kzisme**
Fix for #2460 - Added links to improve clarity for two other services.

### CODE REVIEW

**Comment by techtonik** [comment]
> So, what would be the best approach the cover all the other social media/analytic services that don't support DNT? Here is a current list that I found: http://donottrack.us/implementations

I'd just list those that we use and that may track users. Just to be clear. On the hand, being too paranoid is also bad. So, need to explain possible consequences and let people decide if tracking is useful for them. If those flags are only relevant to paranoids, then for them they may be useless, because NSA tracks everybody regardless of DHT flags. =)

**Comment by kzisme** [comment]
That is a sensible approach - I just wanted to get some other opinions as well.  

So, aside from the listed services we have listed so far, but are there any other services  that we use that I can l look into a write a paragraph about for some clarifying information?

**Comment by techtonik** [comment]
We need a way to refer to services as data, so that all links to them can be easily found. Perhaps a certain tag for simplates like **service:Twitter** meaning that it is "Twitter used by Gratipay" and not just Twitter in general.

**Comment by techtonik** [comment]
With such tags in place, we can just grep the sources and get list of all the services to revise.

**Comment by whit537** [comment]
We call these "`elsewhere`s" (see the db schema).

**Comment by techtonik** [comment]
@whit537 The Gravatar falls out of this category, no?

**Comment by whit537** [comment]
Correct.

**Pull request merged**
