### PR TITLE
Replace missed instances of "team" with "project"

### PR DESCRIPTION
**Pull request by mattbk**
On the frontend at least.

### CODE REVIEW

**Comment by mattbk** [comment]
Ready for review. @JessaWitzel?

**Comment by JessaWitzel** [comment]
I approve yours @mattbk ! I also added two of my own. Do we need to be concerned about the translation templates?

**Comment by mattbk** [comment]
I don't think so. That seems to be handled elsewhere: https://github.com/gratipay/gratipay.com/tree/team-to-project-misc/i18n

**Comment by mattbk** [comment]
Nice catch on the emails.

**Comment by whit537** [comment]
💃

**Pull request merged**
