### PR TITLE
Integrate initial package claiming PRs

### PR DESCRIPTION
**Pull request by whit537**
This is an integration branch/PR for the initial implementation of package claiming. Part of #4427.

### Specs

See https://github.com/gratipay/gratipay.com/issues/4297#issuecomment-273900610.

### Mocks

From https://github.com/gratipay/gratipay.com/issues/4297#issuecomment-273854209 (click for full-size):

[](https://cloud.githubusercontent.com/assets/134455/22119370/5fdd84ec-de49-11e6-88b4-251d7ee4057a.png) [](https://cloud.githubusercontent.com/assets/134455/22119371/5fe28a3c-de49-11e6-8c3b-9957c1a95835.png) [](https://cloud.githubusercontent.com/assets/134455/22119372/5fe68bf0-de49-11e6-836b-96715821defe.png)

### PRs (in merge order)

Numbers are [workflow steps](https://github.com/gratipay/gratipay.com/issues/4297#issuecomment-273900610).

- [x] (1), (2) add sign in w/ copy to `/on/npm/foo/` for anon: #4306 #4307 #4308 #4323
- [x] stub out `Package` to hold Python API: #4155
- [x] (3)—(6) add confirmation form to `/on/npm/foo/` for auth when unclaimed: #4309
- [x] (7), (8) implement `Package.send_confirmation_email`: #4335
- [x] (9) add `/on/npm/react/claim` endpoint to receive email link: #4397
- [x] (10)—(11) implement `/on/npm/foo/` as project page when claimed: #4398
- [x] (12)—(16) implement `/on/npm/foo/edit` as project edit page when claimed: #4404

#### &c.

- [x] minor refactor: #4422
- [x] some UX cleanups: #4406
- [x] style the claim form: #4410 
- [x] more UX cleanups: #4411
- [x] **verify that we can give to a package**—the 💟  of the matter! ... #4423
- [x] on `verify.html`, show packages newly linked if germane: #4424
- [x] work PayPal into the workflow somehow: #4428
- [x] fix an egregious bug at low widths: #4435

### Todo

- [x] think through merging/takeover—anything special here? like, start verification workflow, then merge accounts, then finish verification.—looks like we already do [something](https://github.com/gratipay/gratipay.com/blob/2069/tests/py/test_take_over.py#L185-L206) &hellip; 9b7d1471693ed0876e7cf492fa7e71fa8eae421c
- [x] what about linking an existing project to an existing npm package? &hellip; sounds like an admin thing; bump for now, handle through email support
- [x] make sure finishing a verification terminates competing verifications (otherwise `get_emails` can include an email it shouldn't)
- [x] think through PayPal requirement—are we accounting for that somewhere here that I'm not seeing?
- [x] ~~consider notifying other package maintainers when someone claims a package~~ &hellip; bumped: #4425
- [x] ~~indicate to a participant when they have a claim open~~ &hellip; bumped: #4426
- [x] ~~check it on a phone~~ &hellip; bumped: #4432
- [ ] account for deleted packages: #4448

### Landing

- [x] change base back to `master`
- [ ] merge and deploy!

### CODE REVIEW

**Comment by nobodxbodon** [comment]
Could you share the plan of this project?

Besides, I guess you haven't started paying for gomockingbird? Shall we apply to [balsamiq](https://github.com/gratipay/inside.gratipay.com/issues/928#issuecomment-274296971) earlier than later?

**Comment by whit537** [comment]
> Could you share the plan of this project?

Not sure what you mean. I updated the todo in the ticket description. Not enough?

> Besides, I guess you haven't started paying for gomockingbird?

Nope.

> Shall we apply to balsamiq earlier than later?

Not a priority for me. a) Balsamiq appears to be desktop-only, which is of limited utility for us since we can't share links, b) I think we have what we need from Mockingbird for now, and c) I think we can hack Mockingbird by deleting cookies/localstorage.

**Comment by nobodxbodon** [comment]
> Not sure what you mean. I updated the todo in the ticket description. Not enough?

Maybe just me, but I don't find a easy way to tell which part a dev (me perhaps) can pick up without worrying about stepping on your toe.

> a) Balsamiq appears to be desktop-only, which is of limited utility for us since we can't share links, 

they offer choices in application including web version:
screen shot 2017-01-24 at 2 50 44 pm

> c) I think we can hack Mockingbird by deleting cookies/localstorage.

Seriously?

**Comment by whit537** [comment]
> Maybe just me, but I don't find a easy way to tell which part a dev (me perhaps) can pick up without worrying about stepping on your toe.

I think we should get you unblocked and focusing on https://github.com/gratipay/finances/pull/35. I'm happy to do the bulk of the work here but I will need you @mattbk @JessaWitzel etc. for review. Let's work with who we have.

> they offer choices in application including web version:

Go for it!

> Seriously?

😊

**Comment by whit537** [comment]
@nobodxbodon at https://github.com/gratipay/gratipay.com/issues/4297#issuecomment-275050681:

> When there are multiple contact emails for one package, indicating there are more than one devs, do we send notification emails out to all of them in case the package is claimed by one of the email?

Good idea!

**Comment by whit537** [comment]
We'll also need to account for the case where an email is attached to a different Gratipay account. They won't be able to use it in that case.

**Comment by whit537** [comment]
Todo reordered to reflect merge order.

**Comment by whit537** [comment]
Picking up from https://github.com/gratipay/gratipay.com/issues/4297#issuecomment-275438361:

> I was wondering the same thing. Which email/person do we allow to claim the package.

We pull email addresses from the maintainers and authors in package.json on npm.

**Comment by nobodxbodon** [comment]
In case you missed https://github.com/gratipay/gratipay.com/issues/4297#issuecomment-275050681, shall we notify all the contacts after step 8 of [spec](https://github.com/gratipay/gratipay.com/issues/4297#issuecomment-273900610), and states so to the claimer in the email something like "we'll notify all the other coauthors of the package in this email list after you confirm claiming"?

**Comment by kaguillera** [comment]
1. Is any one of the Co-authors of a package allowed to claim the packages?
2. What if the co-author is a new-comer claims the package before the real starter of the package gets a chance to. 

That was really what I was trying to ask ealier

**Comment by whit537** [comment]
What's up with the failures here? I seem to recall expecting this ...

**Comment by whit537** [comment]
Still looking for the perfect process here. I keep switching the todo order. Currently working stepwise through the workflow.

I've got the confirmation flow (3-8) half roughed-in. I think at this point I'm going to go back over and clean up and merge https://github.com/gratipay/gratipay.com/pull/4155 so that we have a `Package` object from which to hang API, and then pick up again with #4309. At some point we also could/should rebase this on `master` to pick up recent changes there.

**Comment by whit537** [comment]
&hellip;

**Comment by whit537** [comment]
> Is any one of the Co-authors of a package allowed to claim the packages?

[No](https://www.youtube.com/watch?v=B-kC1SEx31g#t=18m19s) ([under](https://github.com/gratipay/inside.gratipay.com/issues/969#issuecomment-276659027)):

> The thing that seems the most canonical representation from what I've seen around probably is whatever the owners are of the actual npm package vs. what's in the package.json.

Sent a follow-up in private email to clarify:

> Looking at [the registry](https://registry.npmjs.com/mysql), I see three options:
>
> 1. **_npmUser**—scoped to version
> 1. **maintainers**—scoped to package
> 1. **author**—scoped to package
>
> My hunch based on our convo is that the _npmUser for the latest version is the best one to use for linking (though the _ suggests that this is a private API, and a spot check shows it is missing for some versions, maybe very old ones?). Does that sound right to you?

**Comment by whit537** [comment]
Alright, based on that and considerations at https://github.com/gratipay/gratipay.com/pull/4309#issuecomment-278430672 I've added another prereq:

>  update schema for a single (nullable) email & sync from the latest version's `_npmUser`

**Comment by whit537** [comment]
Okay! Shelving work on #4309. I had thought of two PRs right after that one (implementing `.send_confirmation_email`), and then confirmation link post-back). But now it seems I should dial back to working on npm syncing prereqs.

**Comment by whit537** [comment]
Scratch that! 💃

> Taking a look at a few packages, it is definitely the maintainers field that I had in mind, as the corresponds to the users who have the rights to publish the package, which is the most likely to align to the folks who would manage any funds, imo

**Comment by whit537** [comment]
But we _do_ want to drop `authors`.

**Comment by whit537** [comment]
Back into #4309!

**Comment by whit537** [comment]
Squashed and rebased onto #4343, was 5bab99a967a36374a4e8272b20f81db5f96f7f1c.

**Comment by whit537** [comment]
Base changed to #4343.

**Comment by mattbk** [comment]
+1 from https://twitter.com/_developit/status/836413846067810304.

**Comment by whit537** [comment]
> an API to look up the opencollective for a given npm module, or the reverse

... and with that, we've come full circle. ;-)

> automated gittip based on npm installs / git clones. I say I want to give $100/month and it divides it automatically.

https://github.com/OpenCollective/OpenCollective/issues/178

**Comment by whit537** [comment]
I've got a local rebase which *slightly* changes Checkpoint 1 (9ea1b0cfe4ab48e71db3c08b6a5ee83cdf00c419). It's failing in the ttw tests, however. Investigating ...

**Comment by whit537** [comment]
Still investigating ...

**Comment by whit537** [comment]
Ah! `local.env` misconfig.

**Comment by whit537** [comment]
Rebased, was 9ea1b0cfe4ab48e71db3c08b6a5ee83cdf00c419.

**Comment by whit537** [comment]
I am getting the sense that we may need to have me self-merge some PRs if we're to keep up our momentum here. I propose to do so tomorrow unless someone objects.

**Comment by whit537** [comment]
Okay! Looong email pre-req chain is in! Back to #4335! 💃 👍

**Comment by whit537** [comment]
Rebased onto #4391 in anticipation of its merge. Enough wasting time restarting Travis! 😖

**Comment by whit537** [comment]
The marketing announcement once we land this feature could/should frame it as an improved application process for npm packages. "One click."

**Comment by whit537** [comment]
I think we may need to implement bulk claiming here though. I'm building it out for such under the hood, easy enough. And I don't think we'll want to return to this once we've moved on, we'll want to focus on demand-side concerns (invoicing, email auth, etc.).

**Comment by rohitpaulk** [comment]
screen shot 2017-04-03 at 11 15 55 am

Needs to be rebased against `master`, yh?

**Comment by whit537** [comment]
Done! Was e17ea8152ed98a3180e84c4ad650f9c966df233a.

**Comment by whit537** [comment]
@mattbk in [Slack](https://gratipay.slackarchive.io/gratipay/page-83/ts-1491343293045480):

> Is there a review process for npm? On your other screenshot, I noticed it had the "in review" tag. If npm can act as a voucher for projects, do we need to put them through our own (7-day) review?

**Comment by whit537** [comment]
I think we should still put package-projects through our review process, because it's actually pretty trivial to create an npm package. Hopefully though this will make it easier to apply for multiple projects at once, and we can review all together vs. separately. Basically this is a streamlined way to apply for a project, but otherwise the process is the same. Eh?

**Comment by mattbk** [comment]
That sounds fine to me. We can leave grouped reviewing as a manual process for now. Being swamped with reviews sounds like a good problem to have.

**Comment by whit537** [comment]
I'm pretty close on review url adaptations. Will pick up tomorrow ...

**Comment by whit537** [comment]
@dowski I didn't make any more progress on https://github.com/gratipay/gratipay.com/pull/4397 today, and I want to keep you topped up in case you have any spare cycles tonight and tomorrow. I'm putting this whole PR into `Review`. The whole chain under "Todo (in merge order)" in the description is ready for a first pass. 🙇

**Comment by dowski** [comment]
@whit537 Roger that. Going to review some more this evening.

**Comment by dowski** [comment]
#4405 from the checklist looks merged already. Should it be checked in the list?

**Comment by whit537** [comment]
Ah, good catch. That was actually merged into #4404 (not here), so I've just removed it from the checklist.

**Comment by whit537** [comment]
Reticketed select improvements as https://github.com/gratipay/gratipay.com/issues/4415.

**Comment by whit537** [comment]
> bulk-add from `/on/npm/` based on verified email addresses

Reticketed as https://github.com/gratipay/gratipay.com/issues/4416.

> add packages to fake data

Reticketed as https://github.com/gratipay/gratipay.com/issues/4417.

**Comment by whit537** [comment]
Rebased on latest master, primarily to pick up #4414; was baf8248083660c70cdd64ae9cb84012b47f7333c.

**Comment by whit537** [comment]
Okay! Remaining open PRs in the chain are topped up, rebased, and ready for review! I'm going to forge ahead with new work.

**Comment by whit537** [comment]
> think through PayPal requirement—are we accounting for that somewhere here that I'm not seeing?

No, we're not. And while I'm fine with #1383 in principle, I'm not ready to make a change there until we can afford some proper fintech counsel (cf. https://github.com/gratipay/inside.gratipay.com/issues/842). We need to enforce the PayPal constraint here.

**Comment by whit537** [comment]
> consider notifying other package maintainers when someone claims a package

This is complicated because our current infrastructure assumes that an email address is linked to a participant. Either we need to create stub participants for all relevant emails (we do something similar for social accounts, but then I guess we want to be able to "promote" the stubs? does that get us into #1052?) or undo that assumption so we can mail without having a participant.

**Comment by mattbk** [comment]
> consider notifying other package maintainers when someone claims a package

Isn't it the package maintainers' responsibility to trust each other? At MVP stage, shouldn't we just trust that they all trust each other?

**Comment by whit537** [comment]
> Isn't it the package maintainers' responsibility to trust each other? At MVP stage, shouldn't we just trust that they all trust each other?

I guess so. You okay with that, @kaguillera?

**Comment by whit537** [comment]
Talked with @kaguillera IRL, agreed to bump these two:

> consider notifying other package maintainers when someone claims a package
> indicate to a participant when they have a claim open

Reticketed as #4425 and #4426 respectively.

**Comment by whit537** [comment]
Text overflows poorly at low width.

screen shot 2017-04-26 at 8 34 15 pm

**Comment by whit537** [comment]
Flight deck shifted to https://github.com/gratipay/gratipay.com/issues/4427, since we want to land this but the `Claim packages` project is likely at least a bit wider in scope than what we want to include here.

**Comment by whit537** [comment]
Alright! I am done making new PRs on here. I made #4435 for low-hanging fruit on low-width display. There are deeper interaction negligencies on mobile that I've bumped to #4432. Given that this PR doesn't even include any discover mechanisms apart from direct URL access, I don't think we should load this up further with non-essential fixes. Let's get this integrated, merged, and out the door!

I'm going to consolidate recent merges into another checkpoint and then check it out locally. That'll leave us with two big commits and then the three remaining PRs. 👍

**Comment by whit537** [comment]
Rebased, was 364634355781ce7512cfda27ea41217cb9954e25.

**Comment by whit537** [comment]
Alright, this rebase doesn't look right.

364634355781ce7512cfda27ea41217cb9954e25 (old) has a pretty complex [`PackageLinking.check`](https://github.com/gratipay/gratipay.com/blob/364634355781ce7512cfda27ea41217cb9954e25/tests/py/test_email.py#L733-L764) method.

771c40ffdea51be52de987f901d26d5902db78f2 (new) does [not](https://github.com/gratipay/gratipay.com/blob/771c40ffdea51be52de987f901d26d5902db78f2/tests/py/test_email.py#L734-L741).

**Comment by whit537** [comment]
Zoiks! Lost it locally? 😳

```
[gratipay] $ co 364634355781ce7512cfda27ea41217cb9954e25
fatal: reference is not a tree: 364634355781ce7512cfda27ea41217cb9954e25
[gratipay] $
```

**Comment by whit537** [comment]
[Not encouraging](http://stackoverflow.com/questions/18878489/retrieving-orphaned-commit-object-after-push-force):

> Anyone who doesn't have `C` can't recover `C` at all (even if it's in origin's object store).

**Comment by whit537** [comment]
Alright, yeah, looks like I effed up. Reading through my [reflog](https://gist.github.com/whit537/19267955917d166799b0df309aaed42f), I'm pretty sure what happened is that I didn't update my local `projects/claim-packages` branch before rebasing it on `master`. I [rebased](https://gist.github.com/whit537/19267955917d166799b0df309aaed42f#file-reflog-L50) f50cf4efd098d317573d31585c1475a8ec0c0cd1, which is [old](https://github.com/gratipay/gratipay.com/commits/f50cf4efd098d317573d31585c1475a8ec0c0cd1). Therefore, when I force-pushed, I pushed off all of the lovely merge commits that @dowski had made. I still have the important parents of the merge commits locally, and GitHub still has the now-orphaned merge commits themselves. But it appears that there is no way for me to get recover those commits that are orphaned at GitHub back into my local repo.

Sorry. 😞

I asked @kaguillera and he doesn't have them. I believe that @dowski is just reading code on GitHub and doesn't have a local working copy. It's possible that @mattbk or someone else has them—possible, but unlikely.

I think what I'm going to do for now is redo the last merge commit and push that up here, and then try again. If someone comes up with 364634355781ce7512cfda27ea41217cb9954e25 locally we can revisit.

**Comment by whit537** [comment]
@mattbk and @clone1018 don't have it. [[slack](https://gratipay.slackarchive.io/gratipay/page-91/ts-1493410576362657)]

Given that all these commits are getting squashed anyway (and the merge commits are simply tossed away in the process), it's not actually that big a deal.

**Comment by whit537** [comment]
[New plan](https://objectpartners.com/2014/02/11/recovering-a-commit-from-githubs-reflog/)!

> Next, use Github’s Refs API to create a new branch pointing to that commit:

**Comment by whit537** [comment]
😍 

```
Status: 201 Created
[...]

{
  "ref": "refs/heads/recovery",
  "url": "https://api.github.com/repos/gratipay/gratipay.com/git/refs/heads/recovery",
  "object": {
    "sha": "364634355781ce7512cfda27ea41217cb9954e25",
    "type": "commit",
    "url": "https://api.github.com/repos/gratipay/gratipay.com/git/commits/364634355781ce7512cfda27ea41217cb9954e25"
  }
}
```

```sh
#!/bin/sh
curl -i \
     -H "Accept: application/json" \
     -H "Content-Type: application/json" \
     -X POST \
     -d '{"ref":"refs/heads/recovery", "sha":"364634355781ce7512cfda27ea41217cb9954e25"}' \
     https://whit537:personal-access-token@api.github.com/repos/gratipay/gratipay.com/git/refs
```

**Comment by whit537** [comment]
Oh heck yeah.

```
[gratipay] $ gf
remote: Counting objects: 8, done.
remote: Total 8 (delta 0), reused 0 (delta 0), pack-reused 8
Unpacking objects: 100% (8/8), done.
From github.com:gratipay/gratipay.com
 * [new branch]      recovery   -> origin/recovery
[gratipay] $
```

Back on track! 💃

**Comment by whit537** [comment]
Okay! Have cleaned up locally—and made a `tmp` branch for recovery!—and am ready to try again ...

**Comment by whit537** [comment]
Yeah, this looks better. Now rebasing 68 commits, was 34 previously.

**Comment by whit537** [comment]
Okay, pushing ...

```
[gratipay] $ git branch -v
  backfill-remaining-exchanges 063a8cf Start looking at the exchange side
  master                       8f6dac5 Bump version to 2071
* project/claim-packages       eb5921f [ahead 8, behind 76] Checkpoint 2
  tmp                          3646343 Merge pull request #4423 from gratipay/project/claim-packages-heart
[gratipay] $
```

**Comment by whit537** [comment]
Alright, rebasing remaining PRs went off without a hitch (conflicts there are what tipped me off to the problem initially).

**Comment by whit537** [comment]
Awesome. All PRs are in!

I guess we should spend some effort on syncing npm before we deploy this, though. :-/

**Comment by whit537** [comment]
The snapshot of npm we have in the Gratipay database is six months old. We need to update that and also build in a mechanism for constantly updating it.

**Comment by whit537** [comment]
Rebased and squashed, was 70b391e5c241558d3658bb52d3e6729c9108ee4f.

**Comment by whit537** [comment]
Okay, friends! I believe we are ready to land this sucker!

**Comment by whit537** [comment]
@clone1018 and I are going to merge and deploy this.

**Comment by whit537** [comment]
Rebased, was 8a2e258d07d399d6152f59057120d4c0a1624818.

**Comment by whit537** [comment]
Travis is running super-slow.

**Comment by whit537** [comment]
Finally green! Ready!?

**Pull request merged**
