### PR TITLE
Fix regression from #3975

### PR DESCRIPTION
**Pull request by whit537**
https://sentry.io/gratipay/gratipay-com/issues/185206514/

https://github.com/gratipay/inside.gratipay.com/issues/900#issuecomment-262647421

### CODE REVIEW

**Comment by whit537** [comment]
This doesn't indicate actual data corruption, and it isn't affecting user experience, so I'm going to leave this sit for now (not self-merge). I will hopefully see about a test or two after supper.

**Comment by whit537** [comment]
`CHECK_DB_EVERY` is set to 10 minutes in production.

**Comment by whit537** [comment]
So I expect 6 or 7 more entries in Sentry when I get back. :-)

**Comment by whit537** [comment]
Actually, this may go deeper. I'm struggling to get a test together.

**Comment by whit537** [comment]
I'm looking at a local backup, finding some patterns ... not *all* balances are failing the check, for one.

**Comment by whit537** [comment]
I've whittled down to a failing case with the fewest exchanges.

**Comment by whit537** [comment]
Okay, I think I've got it. `transfers` are selected (or `payments`?) but not the `exchanges` to offset them.

**Comment by whit537** [comment]
Alright! Ready to go. :-)

cc: @kaguillera @rohitpaulk @aandis @nobodxbodon @JessaWitzel et al.

**Comment by kaguillera** [comment]
LGTM...I have no complaints
If no one else has any concerns by Friday I will merge.

**Comment by clone1018** [comment]
Looks good to me.

**Comment by clone1018** [comment]
Updating branch (with GitHub) and waiting for tests. I remember us talking about rebasing instead but I'm not setup for that right now

**Comment by clone1018** [comment]
ok I merged and deleted the branch.

**Pull request merged**
