### PR TITLE
renamed file team.js to project.js and replaced team with project in …

### PR DESCRIPTION
**Pull request by jacqueline-homan**
…the code

### CODE REVIEW

**Comment by whit537** [comment]
This adds the new file but doesn't remove the old one. We'll need another commit with that deletion.

My guess is at that point the test suite might fail, giving us some more to work on here—we shall see! :-)

**Comment by jacqueline-homan** [comment]
How do I remove the old one?

**Comment by whit537** [comment]
https://www.google.com/search?q=git+remove+file ;-)

**Comment by jacqueline-homan** [comment]
Hey, it looks like all the checks have passed.

**Comment by whit537** [comment]
Oops! @jacqueline-homan merged this too soon. She and I are on a private video call, and I've made #4330 to back this out until it's more fully baked.

**Pull request merged**
