### PR TITLE
Revise the New Project form

### PR DESCRIPTION
**Pull request by mattbk**
Derived from https://github.com/gratipay/gratipay.com/issues/4123.

Stubbing this out, need to be on front of a local install before I can do more (aside from learning Aspen).

- [x] Make sure Homepage is URL (turned off for the moment).
- [x] Enable ~~team~~ project editing while retaining those fields for ~~teams~~ projects that already exist.
- [x] Fix tests that I'm sure will be broken.
- [x] Remove notice about tip migration, per https://github.com/gratipay/inside.gratipay.com/issues/536 —done in #4219

### CODE REVIEW

**Comment by whit537** [comment]
🌻 💃

**Comment by mattbk** [comment]
Hmm. 
screen shot 2016-09-24 at 8 34 45 pm

**Comment by mattbk** [comment]
I'm reversing what I said over at https://github.com/gratipay/gratipay.com/issues/4123#issuecomment-248948644 (and not only because it's less work to leave all the fields in place).

Although if we leave the onboarding and TWYW fields (as optional), we'll need to adjust what "Approved" means, and tie approval only to TOS+fit; this still applies:

> We should keep track of those projects that are already "open work" approved, so we can grandfather them in when we get to that (which I suppose could just be a list on a ticket somewhere, rather than dumping it into the database right now).

In light of https://github.com/gratipay/gratipay.com/pull/4135, though, we might as well **keep** open work as the beginning of the levels idea, and add an `open_work` database field so we can show/rank those teams on the homepage.

This is happening at the same time as we're moving toward #BackTheStack (corporate sponsorship of projects), but I think it's important to keep this long tail going.

**Comment by mattbk** [comment]
So it could be something [like](https://github.com/gratipay/gratipay.com/issues/4123#issuecomment-248038645):

- Basics (required)
    - Team name
    - Image
    - Product or service
    - Homepage
    - Agree to public review
        - _Include why this is, link to TOS/brand guidelines._
    - Agree to TOS
- Open work fields (optional)
    - _Include short sentence explaining open work, with links. Open work criteria will be reviewed after project is approved, but is no longer required for a project to be approved._
    - Onboarding URL
    - Todo URL
- TWYW fields (optional)
    - _TWYW doesn't exist yet under Gratipay 2.0. Check this box if you're interested in being notified._
    - Agree to ~~Payroll~~ TWYW payouts

**Comment by whit537** [comment]
Rebased on latest master. Previous head was 2b458cda2089e51e6f62dce482528d115c32bbe0.

@JessaWitzel Wanna work on this one together with @mattbk? :-)

**Comment by whit537** [comment]
> TWYW fields (optional)

I think we should kill this part entirely, because we're so far away from [bringing that back](https://github.com/gratipay/gratipay.com/issues/3433).

> Todo URL

Let's drop this per https://github.com/gratipay/gratipay.com/issues/4166.

That should leave onboarding as the only optional field, ya?

**Comment by JessaWitzel** [comment]
How can I help?

**Comment by mattbk** [comment]
@JessaWitzel, it looks like the onboarding field needs to go back in (revert part of https://github.com/gratipay/gratipay.com/pull/4130/commits/565dac0a3c314db01ebd4fe669cc097148e6f3ba), and then the other checklist items in the first post, if you agree with them. I'm not the greatest with tests. Feel free to jump in and make commits.

**Comment by whit537** [comment]
Bringing over from #4166:

> The three separate checkboxes. Why not implicitly tick them (with the wording "When you click on 'Apply', you agree to x, y and z" when the user clicks on 'Apply'? Reference: http://ux.stackexchange.com/questions/55571/auto-agreement-to-the-tos-by-clicking-sign-up-button-in-sign-up-form

**Comment by whit537** [comment]
>> TWYW fields (optional)
>
I think we should kill this part entirely, because we're so far away from [bringing that back](https://github.com/gratipay/gratipay.com/issues/3433).

This takes us down to two checkboxes. I think the public review thing is unusual enough that it's worth elevating to its own checkbox. We could tweak the wording of the second to say "_other_ terms of service." Nobody reads the terms because they assume there won't be any surprises, but we have some weird stuff in ours.

**Comment by mattbk** [comment]
Is this PR necessary if we have #4214?

I'm a little confused as to what needs to be done now.

**Comment by JessaWitzel** [comment]
@whit537  are projects different than teams?

**Comment by mattbk** [comment]
Teams are being renamed to projects.

**Comment by whit537** [comment]
Rebased; was 565dac0a3c314db01ebd4fe669cc097148e6f3ba.

**Comment by whit537** [comment]
Cool. We'll just need to remove this branch from `.travis.yml` as part of our final merge to `master`.

**Comment by whit537** [comment]
Base changed to `remove-todo-url` (#4214) since that is scheduled to land in #4221 first.

**Comment by whit537** [comment]
Of course that means Travis won't see us again ... :/

**Comment by whit537** [comment]
Rebasing on `remove-todo-url` to resolve conflicts ...

**Comment by whit537** [comment]
Rebased; was 046ae6453c6337a7795b51f2444eed8b65995d2e.

**Comment by whit537** [comment]
(Rebased again to pick up c2644b5d076c6936f58adc9541e11ec0ba3871d9.)

**Comment by whit537** [comment]
Okay! We have Travis here now. :-)

**Comment by mattbk** [comment]
Looks like @whit537 got the wording changed on the checkboxes. I just re-added onboarding_url. Looking back to see what else needs to be done...

**Comment by whit537** [comment]
@mattbk I made one more small commit, sorry. I'll step off your toes now ... :o)

**Comment by mattbk** [comment]
> Nobody reads the terms because they assume there won't be any surprises, but we have some weird stuff in ours.

I think this is an argument against pre-checking the boxes. We want to make people think as much as possible when applying in order to avoid problems down the road.

**Comment by mattbk** [comment]
> tests/py/test_stats.py::TestHtml::test_200 FAILED

**Comment by whit537** [comment]
Same error as at https://github.com/gratipay/gratipay.com/pull/4157#issuecomment-265231655.

**Comment by whit537** [comment]
@mattbk I made a PR to work on the faker issue: https://github.com/gratipay/gratipay.com/pull/4224.

**Comment by whit537** [comment]
Interesting! Why did that work?

**Comment by whit537** [comment]
More under #4224 ...

**Comment by mattbk** [comment]
I figured it might work or fail randomly, which would be hard to debug.

**Comment by whit537** [comment]
Returning from #4224 ... aaaaaaaand we're green again here for some reason? ¯\\\_(ツ)\_/¯

**Comment by whit537** [comment]
Rebased, was ee74ad12842915b4ce3c93235b967992f291acdc.

**Comment by mattbk** [comment]
Aaaa! What happened?

**Comment by whit537** [comment]
@mattbk Which part? The Travis fail? :(

&rarr; https://github.com/gratipay/gratipay.com/pull/4225

**Comment by whit537** [comment]
Sike! Different Travis fail instead. 😩

**Comment by whit537** [comment]
I've seen it before but don't find a ticket right now ...

**Comment by whit537** [comment]
Rebuild! Whack-a-bug!

**Comment by mattbk** [comment]
That's much better!

**Comment by whit537** [comment]
Rebased on new base, was 040015541db2d375f8e36843ee47c8de6a0b8ee8.

**Comment by whit537** [comment]
This is next in line to land, @mattbk! Let's do it!

**Comment by whit537** [comment]
> Fix tests that I'm sure will be broken.

✅

**Comment by whit537** [comment]
I'm gonna review here ...

**Comment by mattbk** [comment]
`onboarding_url` tests were pulled out and should go back in.

**Comment by whit537** [comment]
@mattbk I'd like to work on this so we can make our deadline for #4221 tomorrow.

**Comment by whit537** [comment]
> I think this is an argument against pre-checking the boxes.

Okay, let's get that off the critical path here. I've reopened and rescoped #4166.

**Comment by whit537** [comment]
> `onboarding_url` tests were pulled out and should go back in.

👍

**Comment by mattbk** [comment]
Ready for review.

**Comment by whit537** [comment]
Blech, alright, you beat me to this by hours, sorry. 😞

I think we should actually drop the `onboarding_url` from this form and from the edit form as well, for the following reasons:

1. Having optional fields makes it harder to fill out the form, which slows people down.
1. We're not going to be doing anything with the onboarding URL anymore right now (a binary field doesn't really help with [ranking](https://github.com/gratipay/gratipay.com/pull/4130#issuecomment-252741754)).
1. It's going to be a couple years before we can bring back payouts (#4072).
1. Maintaining the `onboarding_url` would add friction to #4148 and the [loop](https://github.com/gratipay/inside.gratipay.com/issues/637#issuecomment-263431528) we're trying to get going.

I'd be fine to keep the db field around (unlike `todo_url`; #4214) so we can use it in the future if we want to. My current thinking is that at [badging system](https://github.com/gratipay/gratipay.com/issues/3963#issuecomment-265886032)?) could work well—but that is a feature that we'd want to develop in it's own right. The task today is to simply, strip-down, and focus the product. I think `onboarding_url` is extraneous and should be deactivated for now.

Waddya think, @mattbk?

**Comment by whit537** [comment]
> I think we should actually drop the `onboarding_url` from this form and from the edit form as well

Path of least resistance would be to keep it on the project profile for now, since we're not otherwise editing that page. I'd be fine either way on that one.

**Comment by mattbk** [comment]
Let me see what I can do tonight.

**Comment by mattbk** [comment]
I left it in the database. Everything else is pulled out.

**Comment by whit537** [comment]
Hmm ... Travis failures?

**Comment by whit537** [comment]
They're all choking on oniguruma when installing marky-markdown (except for one which is weird).

**Comment by whit537** [comment]
Did oniguruma just put out a new version?

**Comment by whit537** [comment]
Version 6.1.1 worked in the one build that worked.

https://travis-ci.org/gratipay/gratipay.com/builds/182613635

screen shot 2016-12-09 at 11 07 17 am

**Comment by whit537** [comment]
https://github.com/travis-ci/travis-ci/issues/4771 😖

**Comment by whit537** [comment]
Fail!


# Latest

```
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: 522 status code downloading tarball
gyp ERR! stack     at Request.<anonymous> (/home/travis/.nvm/v0.10.36/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:246:14)
gyp ERR! stack     at Request.emit (events.js:117:20)
gyp ERR! stack     at Request.onResponse (/home/travis/.nvm/v0.10.36/lib/node_modules/npm/node_modules/request/request.js:1085:10)
gyp ERR! stack     at ClientRequest.g (events.js:180:16)
gyp ERR! stack     at ClientRequest.emit (events.js:95:17)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (http.js:1693:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:122:23)
gyp ERR! stack     at Socket.socketOnData (http.js:1588:20)
gyp ERR! stack     at TCP.onread (net.js:528:27)
```


# Earliest

```
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: node-v0.10.36.tar.gz local checksum 6fd25f1e62f2e0d257a8c1ad8df2da088ebd4b1cd9e188a2fca510a31a559de7 not match remote b9d7d1d0294bce46686b13a05da6fc5b1e7743b597544aa888e8e64a9f178c81
gyp ERR! stack     at deref (/home/travis/.nvm/v0.10.36/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:299:20)
gyp ERR! stack     at IncomingMessage.<anonymous> (/home/travis/.nvm/v0.10.36/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:340:13)
gyp ERR! stack     at IncomingMessage.emit (events.js:117:20)
gyp ERR! stack     at _stream_readable.js:944:16
gyp ERR! stack     at process._tickCallback (node.js:442:13)
```

**Comment by whit537** [comment]
Alright, so it looks like it's a problem downloading the tarball, not building it. Backing out 5bc1bc05ec03c99100580a6a32b398cc69c182eb &hellip;

**Comment by whit537** [comment]
https://github.com/nodejs/node-gyp/issues/693 ?

**Comment by whit537** [comment]
| build | error | 
|:---------|:--------------|
| [182606728](https://travis-ci.org/gratipay/gratipay.com/builds/182606728) | node-v0.10.36.tar.gz local checksum [] not match remote [] |
| [182606710](https://travis-ci.org/gratipay/gratipay.com/builds/182606710) | node-v0.10.36.tar.gz local checksum [] not match remote [] |
| [182613462](https://travis-ci.org/gratipay/gratipay.com/builds/182613462) | node-v0.10.36.tar.gz local checksum [] not match remote [] |
| [182613635](https://travis-ci.org/gratipay/gratipay.com/builds/182613635) |  |
| [182622559](https://travis-ci.org/gratipay/gratipay.com/builds/182622559) | Completion callback never invoked! |
| [182622533](https://travis-ci.org/gratipay/gratipay.com/builds/182622533) | node-v0.10.36.tar.gz local checksum [] not match remote [] |
| [182623387](https://travis-ci.org/gratipay/gratipay.com/builds/182623387) | node-v0.10.36.tar.gz local checksum [] not match remote [] |
| [182635391](https://travis-ci.org/gratipay/gratipay.com/builds/182635391) | 522 status code downloading tarball |

**Comment by whit537** [comment]
http://status.npmjs.org/ shows green

**Comment by whit537** [comment]
The local checksum is different in all of the checksum failed cases, while the remote is the same in all cases.

**Comment by whit537** [comment]
Why are we using such an ancient version of node?

**Comment by whit537** [comment]
It's probably the system version on whatever Ubuntu we get there? Let's try installing a more recent version ...

**Comment by whit537** [comment]
> we are having issues with our download service right now. hoping to have it sorted out very soon

https://github.com/nodejs/node-gyp/issues/693#issuecomment-266059352

**Comment by whit537** [comment]
The build passed! But not because of 4295843d352edd78d98a551a99c89f6e62e0a6f2; I only see `python` in the "Build system information" there (and it seems multiple languages aren't directly supported: https://github.com/travis-ci/travis-ci/issues/4090). Gonna push that off and see if we still pass.

**Comment by whit537** [comment]
The build passed! But not because of 4295843d352edd78d98a551a99c89f6e62e0a6f2; I only see `python` in the "Build system information" there (and it seems multiple languages aren't directly supported: https://github.com/travis-ci/travis-ci/issues/4090). Gonna push that off and see if we still pass.

**Comment by whit537** [comment]
Still passing! Merging while we have a chance. ;-)

**Comment by whit537** [comment]
!m @mattbk

**Pull request merged**
