### PR TITLE
Fix search css regression

### PR DESCRIPTION
**Pull request by whit537**
From #4305 

screen shot 2017-05-09 at 8 53 53 pm

### CODE REVIEW

**Comment by whit537** [comment]
[slack](https://gratipay.slackarchive.io/gratipay/page-98/ts-1494380758634183)

**Comment by whit537** [comment]
cc: @clone1018 @mattbk for review and merge.

**Comment by whit537** [comment]
IRL @clone1018 showing me working on his 'top too.

**Comment by clone1018** [comment]
@mattbk I've pulled this locally and tested it. I'm going to merge it after travis says ok

image

**Pull request merged**
