### PR TITLE
first step of 835 for payment_instructions

### PR DESCRIPTION
**Pull request by whit537**
Part of #835.

- [x] rebase once #4059 lands

### CODE REVIEW

**Comment by whit537** [comment]
Removing `Review` in order to take care of some preliminaries first: #4057, #4060, and #4059.

**Comment by whit537** [comment]
Rebased on `deslug-api` (#4059). Previous head was 37a5b6bea58fd35a238007cf1b7fb7b07836d7dc.

Blocking on #4059.

**Comment by rohitpaulk** [comment]
Rebased on `master` (@f697ef3f15be513549692e55fac7f233e7ea0513). Previous head was @1833bf712ba7a5c6c6631e95b287f86a99abf155

**Comment by rohitpaulk** [comment]
Deploying..

**Comment by rohitpaulk** [comment]
Argh my local env is borked....

**Comment by rohitpaulk** [comment]
Fixed. Now deploying 🚀

**Comment by rohitpaulk** [comment]
New columns have been added.

**Comment by rohitpaulk** [comment]
Tried changing a tip, and the writes are working 💃 

screen shot 2016-06-17 at 2 02 10 am

**Pull request merged**
