### PR TITLE
Rename release.sh to deploy.sh

### PR DESCRIPTION
**Pull request by whit537**
More accurate, no? Hopefully non-controversial. 🐭

### CODE REVIEW

**Comment by whit537** [comment]
Ready for review @rohitpaulk @clone1018 @kaguillera @JessaWitzel et al.

**Comment by kaguillera** [comment]
Simple enough but it needs rebasing.

**Comment by whit537** [comment]
@kaguillera I think we are okay with using the "Update branch" button to merge instead of rebase?

**Comment by kaguillera** [comment]
Fair enough, I was not sure how using the web based git would affect the code. I feel more secure with CLI

**Comment by whit537** [comment]
Yeah, I actually prefer rebase as well. I just have an up-in-the-air state locally, deep in on #4205. :-)

Otoh, you have the power to checkout and rebase this PR branch! :)

**Comment by kaguillera** [comment]
I was actually wondering about that because I think that I noticed that you have done that before

**Comment by whit537** [comment]
Yeah, just grab the branch name from the top under the title, then use that to `git checkout release-deploy`, do the rebase/force-push dance just like you would on one of your own PRs. Team PRs! :-)

screen shot 2016-11-23 at 11 53 16 pm

**Comment by kaguillera** [comment]
Understood

**Pull request merged**
