### PR TITLE
New png images lossless re-compression

### PR DESCRIPTION
**Pull request by PeterDaveHello**
cc #3962
```
 www/assets/flags.png                  | Bin 179370 -> 142915 bytes
 www/assets/heartcoin-illustration.png | Bin 105095 -> 64845 bytes
 www/assets/npm-n.png                  | Bin 699 -> 127 bytes
```

### CODE REVIEW

**Comment by whit537** [comment]
Thanks for the PRs, @PeterDaveHello! Would you like to join us [in Slack](http://inside.gratipay.com/appendices/chat)? :)

**Comment by PeterDaveHello** [comment]
@whit537 sure! BTW, I just rebase this branch with the latest master branch instead of the merge with master so that we can have a cleaner and clearer git commit history.

**Comment by whit537** [comment]
Sure thing, I'd have done that myself if the PR branch was in our repo, which is our usual practice. :)

Care to join our team so you can make branches in the main repo instead of your fork? If so, go ahead and make an [onboarding ticket](http://inside.gratipay.com/big-picture/welcome) for yourself.

**Comment by whit537** [comment]
P.S. If you're interested in optimization, check out #4262.

**Comment by PeterDaveHello** [comment]
@whit537 cool! Hope this won't be too short - https://github.com/gratipay/inside.gratipay.com/issues/965 :smile:

**Comment by PeterDaveHello** [comment]
@whit537 I'm on the Slack channel now :smile:

**Pull request merged**
