### PR TITLE
Fix nmasspays check during payday

### PR DESCRIPTION
**Pull request by whit537**
Addresses https://github.com/gratipay/inside.gratipay.com/issues/1013#issuecomment-283656746.

### CODE REVIEW

**Comment by whit537** [comment]
Actually, withdrawing from review until I can update nmasspays as well.

**Comment by whit537** [comment]
Lol, this test suite passes because it doesn't actually `assert` anything. 💩

**Comment by whit537** [comment]
Alright, ready for review now, @nobodxbodon @rohitpaulk et al.

**Comment by whit537** [comment]
Bump.

**Comment by whit537** [comment]
Rebased, was d5c8181be92aa34e07e082af346f185b44c60ed4.

**Comment by whit537** [comment]
I don't know why this is saying "out-of-date." 😕

**Comment by whit537** [comment]
Hrm ... now it's not. ¯\_(ツ)_/¯

**Comment by whit537** [comment]
Okay. I may self-merge this as well to keep things going.

**Comment by mattbk** [comment]
> Okay. I may self-merge this as well to keep things going.

:+1:

**Pull request merged**
