### PR TITLE
Make the global background color explicit

### PR DESCRIPTION
**Pull request by whit537**
Per https://twitter.com/alejandrogonzo/status/894742963430899712 ...

### CODE REVIEW

**Comment by whit537** [comment]
Ready for review, @mattbk @rohitpaulk et al. ...

**Comment by rohitpaulk** [comment]
LGTM

**Comment by mattbk** [comment]
LGTM

**Comment by whit537** [comment]
y u no merge 👀

**Comment by clone1018** [comment]
LGTM

**Comment by whit537** [comment]
!m @rohitpaulk @mattbk @clone1018 💃

**Pull request merged**
