### PR TITLE
Fix handling of exchange routes

### PR DESCRIPTION
**Pull request by Changaco**
For https://github.com/gratipay/gratipay.com/issues/2779#issuecomment-89053807 etc.

### CODE REVIEW

**Comment by whit537** [comment]
Test?

**Comment by Changaco** [comment]
Sleep first. :-)

**Comment by whit537** [comment]
!m @Changaco 

:sleeping:

:-)

**Comment by Changaco** [comment]
Tests added.

**Comment by whit537** [comment]
I've confirmed [in Sentry](https://app.getsentry.com/gratipay/gratipay-com/group/60437761/) that the route is not `None` for the FD1867 case.

**Comment by whit537** [comment]
What is it about `ExchangeRoute` that `assert route` evaluates false?

**Comment by whit537** [comment]
```python
    def __bool__(self):
        return self.error != 'invalidated'
```

https://github.com/gratipay/gratipay.com/blob/1818/gratipay/models/exchange_route.py#L11-L12

**Comment by whit537** [comment]
Running tests locally ...

**Pull request merged**
