### PR TITLE
Relicense as MIT

### PR DESCRIPTION
**Pull request by whit537**
https://github.com/gratipay/inside.gratipay.com/issues/1161

### CODE REVIEW

**Comment by whit537** [comment]
You cool with this @clone1018?

**Comment by clone1018** [comment]
I like the MIT license. Are there any special processes going from public domain to MIT?

**Comment by whit537** [comment]
> Are there any special processes going from public domain to MIT?

According to @massonpj in irl convo there are not.

**Comment by Changaco** [comment]
This might not have gone over well if Gratipay was a library or app that other projects depend on and which is packaged by third parties, but since it isn't you probably won't hear anyone complaining.

**Comment by mattbk** [comment]
Is that because the MIT license requires derivatives to also be MIT license? I'm new at this stuff.

**Comment by Changaco** [comment]
@mattbk No, the MIT license isn't a [copyleft](https://en.wikipedia.org/wiki/Copyleft) license.

**Comment by mattbk** [comment]
Thanks @Changaco, you made me read it again, slowly. :grin:  :+1:

**Comment by whit537** [comment]
Rebased. Good to merge, @clone1018?

**Comment by whit537** [comment]
💃

**Comment by massonpj** [comment]
Hi all. Thanks @whit537 for introducing this. I am happy to help if anything is needed. We'd like to support your work, but would only be able to if the projects carry an OSI approved license, not public domain (https://opensource.org/faq#public-domain) or CC0 (https://opensource.org/faq#cc-zero).

**Comment by whit537** [comment]
Thanks, @massonpj.

If you're referring to our [own code](https://github.com/gratipay/), then we're almost there: this PR is merged and relicenses our main repo, `gratipay.com`. We have [two more minor repos outstanding](https://github.com/gratipay/inside.gratipay.com/issues/1161#issuecomment-328992725), should be easy now that this PR is in.

If you're referring to projects that we would support with funds collected via the new form on [our homepage](https://gratipay.com/), then that's fine, we can definitely enforce that restriction there.

If you're referring to the [almost 800 projects](https://gratipay.com/browse/projects?status=approved) that are already on Gratipay under our old model (weekly micro-payments direct to the project), we might need to drop to a phone call to sort that out. Should we schedule a call? Maybe we drop to email to schedule? chad@gratipay.com

**Comment by massonpj** [comment]
Hey @whit537,

Great to hear you're migrating gratipay code to an OSI approved license--we love that--and thus makes it easy for us to support the project as a whole. 

We'll also be happy to promote/support your new forum for projects that carry an OSI approved license. 

Regarding the others from the old model, yeah we'd have to delineate those, and quarantine them from any OSI branding, promotion, support. But it's not a problem at all. If we can work with Microsoft and Adobe to support their open source efforts, while avoiding their proprietary stuff, we can make it work here too. 

We do not want to be a burden/hassle to work with, but yeah let's get on a call. I will email you to set that up.

**Comment by whit537** [comment]
Sounds good, @massonpj. Got your mail and looking forward to chatting on Tuesday!

**Pull request merged**
