### PR TITLE
Tinker with comments and copy

### PR DESCRIPTION
**Pull request by whit537**
Part of #4539, follows #4550.

- "sign-in" is a noun, verb is "sign in"
- order of functions is per order in algorithm
- usual Python style is actually two spaces between functions
- ... and no space between docstring and first import

### CODE REVIEW

**Comment by whit537** [comment]
Boo red! 😕

**Comment by whit537** [comment]
Let's try that ...

**Comment by rohitpaulk** [comment]
Oh... what did I merge this into

**Comment by whit537** [comment]
`dash-over-underscore` #4550, which it looks like @aandis merged into #4539. ☺️

!m @rohitpaulk @seanlinsley

**Pull request merged**
