### PR TITLE
Missing cache headers fix

### PR DESCRIPTION
**Pull request by dmk246**
Developing a fix for a HackerOne ticket [#185833](https://hackerone.com/reports/185833) dealing with Incomplete or No Cache-control and Pragma HTTP Header Set! :sparkles:

### CODE REVIEW

**Comment by whit537** [comment]
!m @dmk246

Hopefully we can deploy this tomorrow! 💃  🌻

**Comment by whit537** [comment]
@dmk246 Looks like Travis is failing. Can you look into it and fix it up?

**Comment by dmk246** [comment]
@whit537 .... do I see green checks?! Haha :)

**Comment by whit537** [comment]
Rebased, was 00adfef287cce6ad25616a3faefaa3625c172364.

**Comment by whit537** [comment]
Ready to merge and deploy once Travis is green ...

**Comment by whit537** [comment]
Congrats @dmk246! Your first pull request, merged and deployed! 💃  🌻  🎉  🚀  ✨  🍰

**Comment by dmk246** [comment]
NO WAYYYYY....
You have no idea how excited I am right now!!! Wooohoooo! Okay...this calls for a mini dance party at our desks! Ready ...set ...GO! :)

**Comment by kaguillera** [comment]
😱  Did I miss the mini dance party???

!m @dmk246

**Comment by whit537** [comment]
mini dance party

**Comment by dmk246** [comment]
OH MY GOODNESS!!!!!!!! I am dying over here ... this is great!!! 
You guys are all super awesome!!!!  This made my day!!!! 
Thanks for dancing with me guys!!!  
......and thanks everyone for being so supportive!!!  You guys rock!! :)

**Pull request merged**
