### PR TITLE
Team images

### LINKED ISSUE #3701: have an image for Teams
And backfill existing teams.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/26020800-have-an-image-for-teams?utm_campaign=plugin&utm_content=tracker%2F85909&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F85909&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by whit537**
Closes #3701.

### CODE REVIEW

**Comment by whit537** [comment]
Includes #3749.

**Comment by whit537** [comment]
screen shot 2015-09-03 at 12 08 08 am

**Comment by whit537** [comment]
My thought was that we could store and serve from Postgres, and put MaxCDN in front using the main site as an origin server, as we do with assets.

**Comment by whit537** [comment]
screen shot 2015-09-03 at 12 34 45 am

screen shot 2015-09-03 at 12 35 16 am

screen shot 2015-09-03 at 12 35 27 am

**Comment by whit537** [comment]
- [ ] upload an image when creating a Team
 - [ ] limit upload size to 500 kB
 - [ ] process image (crop to square and resize to 160x160)
 - [ ] backfill images for existing Teams
 - [ ] put images behind CDN in production
 - [ ] show image on Team pages

**Comment by whit537** [comment]
It's not unlikely that we'll need an Aspen upgrade in order to work with uploaded files.

**Comment by whit537** [comment]
Should we use the new FormData functionality to [post files via ajax](http://portfolio.planetjon.ca/2014/01/26/submit-file-input-via-ajax-jquery-easy-way/)? Doesn't work [in IE9](http://caniuse.com/#feat=xhr2).

**Comment by whit537** [comment]
I'm close to a commit on this. I need to teach the test suite how `valid_data` can have a file upload in it.

**Comment by whit537** [comment]
Alright, debugged with @dmk246. The Aspen test client isn't smart enough to set `filename` and `Content-Type` for file uploads.

**Comment by whit537** [comment]
Serving the images out of Postgres is even slower than I expected. It's taking 2 seconds to serve a 44 kB image locally. O.o

**Comment by whit537** [comment]
Should we use a push zone instead?

**Comment by whit537** [comment]
I mean, S3 is standard for this. I was looking to use MaxCDN since we already have an account there.

**Comment by whit537** [comment]
Okay! It's looking like [large objects](http://www.postgresql.org/docs/9.3/static/largeobjects.html) are sufficiently performant, over against [`bytea`](http://www.postgresql.org/docs/9.3/static/datatype-binary.html). I have an implementation, and it performs better in one-off tests (ms vs. ~2 s for one request). I'm trying to get some actual benchmarks ...

**Comment by whit537** [comment]
Needed wrk >= 3.0.3 to pick up https://github.com/wg/wrk/issues/53 (current is 4.0.0). Benchmarks forthcoming ...

**Comment by whit537** [comment]
### filesystem (control)

```
$ wrk -c1 -t1 http://localhost:8537/assets/banner.jpg
Running 10s test @ http://localhost:8537/assets/banner.jpg
  1 threads and 1 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.81ms    1.55ms  41.55ms   98.40%
    Req/Sec   531.80     59.16   595.00     71.00%
  5301 requests in 10.01s, 228.39MB read
Requests/sec:    529.40
Transfer/sec:     22.81MB
$ wrk -c1 -t1 http://localhost:8537/assets/banner.jpg
Running 10s test @ http://localhost:8537/assets/banner.jpg
  1 threads and 1 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.82ms    3.26ms  69.33ms   99.28%
    Req/Sec   568.38     66.00   606.00     94.00%
  5664 requests in 10.02s, 244.03MB read
Requests/sec:    565.51
Transfer/sec:     24.37MB
$ wrk -c1 -t1 http://localhost:8537/assets/banner.jpg
Running 10s test @ http://localhost:8537/assets/banner.jpg
  1 threads and 1 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.58ms  155.95us   6.63ms   89.52%
    Req/Sec   572.21     45.96   606.00     96.81%
  5398 requests in 10.01s, 232.57MB read
Requests/sec:    539.04
Transfer/sec:     23.22MB
$
```

### `bytea` (8113217e6780f0f0d0ef6b9ebc8fcc6d935ceb79)

```
$ wrk -c1 -t1 http://localhost:8537/heee/image.jpg
Running 10s test @ http://localhost:8537/heee/image.jpg
  1 threads and 1 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.66s    11.49ms   1.67s    50.00%
    Req/Sec     0.00      0.00     0.00    100.00%
  6 requests in 10.10s, 1.57MB read
Requests/sec:      0.59
Transfer/sec:    158.89KB
$ wrk -c1 -t1 http://localhost:8537/heee/image.jpg
Running 10s test @ http://localhost:8537/heee/image.jpg
  1 threads and 1 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.64s    39.05ms   1.68s    66.67%
    Req/Sec     0.00      0.00     0.00    100.00%
  6 requests in 10.10s, 1.58MB read
Requests/sec:      0.59
Transfer/sec:    160.45KB
$ wrk -c1 -t1 http://localhost:8537/heee/image.jpg
Running 10s test @ http://localhost:8537/heee/image.jpg
  1 threads and 1 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.64s    54.01ms   1.69s    83.33%
    Req/Sec     0.00      0.00     0.00    100.00%
  6 requests in 10.10s, 1.58MB read
Requests/sec:      0.59
Transfer/sec:    160.49KB
$
```

### large objects (4ec58fb7e5f138aec50e819c654a628477c4e3b8)

```
$ wrk -c1 -t1 http://localhost:8537/haaa/image.jpg
Running 10s test @ http://localhost:8537/haaa/image.jpg
  1 threads and 1 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     4.76ms    1.92ms  47.31ms   97.03%
    Req/Sec   207.27     24.00   232.00     82.00%
  2069 requests in 10.02s, 89.35MB read
Requests/sec:    206.42
Transfer/sec:      8.91MB
$ wrk -c1 -t1 http://localhost:8537/haaa/image.jpg
Running 10s test @ http://localhost:8537/haaa/image.jpg
  1 threads and 1 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     4.44ms  329.97us   9.92ms   88.79%
    Req/Sec   218.15      7.03   232.00     69.00%
  2176 requests in 10.02s, 93.97MB read
Requests/sec:    217.08
Transfer/sec:      9.37MB
$ wrk -c1 -t1 http://localhost:8537/haaa/image.jpg
Running 10s test @ http://localhost:8537/haaa/image.jpg
  1 threads and 1 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     4.44ms  355.22us   9.57ms   89.96%
    Req/Sec   218.50      6.70   232.00     80.00%
  2179 requests in 10.02s, 94.10MB read
Requests/sec:    217.47
Transfer/sec:      9.39MB
$
```

**Comment by whit537** [comment]
| method | req/sec |
|------|---------:|
| filesystem | 545.0 |
| `bytea` | 0.6 |
| large objects | 213.0 |

**Comment by whit537** [comment]
Conclusion: large objects are plenty fast enough to support my original strategy of using the main web app as an origin server, with a MaxCDN pull zone in front of it in production (a la assets).

**Comment by whit537** [comment]
Processing images introduces complex dependencies. I'm thinking of writing a separate service to do this for us, parking it at `www.gratipay-image-processing.com` or whatever. You would `POST` images to it and get back a ZIP file of cropped and resized images.

**Comment by whit537** [comment]
Or we can pay someone else to do it: https://www.google.com/search?q=image+processing+as+a+service.

**Comment by whit537** [comment]
https://6px.io/
https://www.imgix.com/pricing
http://www.blitline.com/

https://www.google.com/trends/explore#q=imgix%2C%20blitline%2C%206px

**Comment by whit537** [comment]
$10/mo or $75/mo, and how would it help developers?

**Comment by whit537** [comment]
B-friggin'-lam.

screen shot 2015-09-10 at 2 04 27 am

**Comment by whit537** [comment]
P.S. I ended up putting together a little service for this: http://gip.rocks/.

**Comment by whit537** [comment]
Do we really need images behind a CDN yet?

**Comment by whit537** [comment]
Script to populate the db: https://gist.github.com/whit537/78bea2109bd18d1266ab. Testing it out, lookin' a little busy:

screen shot 2015-09-10 at 3 30 22 am

**Comment by rohitpaulk** [comment]
I think this would look a lot cleaner if we removed the icons...

**Comment by whit537** [comment]
Glad to see that `skip.rocks` is already registered, heading off any buyer's remorse for what could've been "Some Kinda' Image Processor." ;-)

**Comment by whit537** [comment]
Rebased on master. Old HEAD was 5183722ec1c3361c2b3113e03fedd7e0dc533698.

**Comment by whit537** [comment]
Rebased on master.

**Comment by whit537** [comment]
> I think this would look a lot cleaner if we removed the (status)icons...

Is it enough to move them off of the Team images?

screen shot 2015-09-10 at 10 18 49 am

**Comment by whit537** [comment]
@sils1297 Will this PR adequately address https://github.com/gratipay/team-review/issues/36#issuecomment-137971240? :)

screen shot 2015-09-10 at 10 31 43 am

**Comment by sils1297** [comment]
@whit537 actually I was rather thinking about having the background banner customized, with an image like http://www.whatcanidoforcoala.org/static/themes/coala/img/background.jpg (probably with the coala on the other side), giving the whole page a more custom touch. This would be more of a logo.

**Comment by whit537** [comment]
@sils1297 Okay, reticketed as https://github.com/gratipay/gratipay.com/issues/3767! :)

**Comment by whit537** [comment]
I've got images for 36 out of 100 Teams, which means it'll probably take me a couple more hours to get the rest.

http://paulgraham.com/ds.html

**Comment by whit537** [comment]
I may actually try to press @hurlothrumbo into service for this one ...

**Comment by whit537** [comment]
Rebased on master (old HEAD 941569429c4d4465e173f8cc53764df9e2f87581).

**Comment by whit537** [comment]
Looks like we can purge individual files from the pull zone cache:

https://docs.maxcdn.com/#purge-cache

**Comment by whit537** [comment]
screen shot 2015-09-11 at 12 15 04 am

**Comment by whit537** [comment]
screen shot 2015-09-11 at 12 20 05 am

**Comment by whit537** [comment]
screen shot 2015-09-11 at 12 26 47 am

**Comment by whit537** [comment]
I want to get this out tonight. I think I'm going to focus on backfilling images, and reticket the CDN.

**Comment by whit537** [comment]
Okay! I have images for all approved and under review Teams. I don't think I'm going to bother with images for rejected Teams: I don't like the idea of choosing an image for them since we're not giving them a chance to edit it themselves. Better to just leave them as-is, I think.

**Comment by whit537** [comment]
I'm bumping on the CDN.

**Comment by whit537** [comment]
Now that I have all these images, I want to not have any more Teams created *without* images, so I don't have to go chase them down anymore. :)

**Pull request merged**
