### PR TITLE
Homepage server tabs

### PR DESCRIPTION
**Pull request by rohitpaulk**
https://github.com/gratipay/gratipay.com/issues/4313#issuecomment-301209391

Partly solves #4313, minus the AJAXness

### CODE REVIEW

**Comment by rohitpaulk** [comment]
Preview (low quality gif)

homepage

**Comment by mattbk** [comment]
Would storing the "Featured" projects and only refreshing daily or weekly save any time as well?

**Comment by mattbk** [comment]
I can confirm that this works for me, but have not tested with a large number of teams.

**Comment by rohitpaulk** [comment]
> Would storing the "Featured" projects and only refreshing daily or weekly save any time as well?

Yes, it would. I'm not very optimistic on the gains though. All we'll avoid is a DB call (which we haven't proven to be an expensive query or so). Out of the homepage request + the other 10 image requests being made, the proportion of time saved by caching the result of that one DB call doesn't seem like it'll be much.

Why I think it is sufficient to do just those two steps is: Every request to the homepage (or any other page that loads 200 teams) fires 200 other requests for team images (which in turn make DB calls), and itself takes a while to send data down the wire. The gains here are real, and proven on a similar environment.

A couple of other things I thought of but haven't proven that they'll be worth it: 

- Use ETag caching for team images
- Collapse all image requests into 1 (either by moving images to an external service that supports HTTP2 + caching, or by using a custom format and splitting on client side)

**Comment by whit537** [comment]
Another option for images: put a CDN in front of it while using Gratipay.com as the origin, as we do with CSS/JS assets.

**Comment by whit537** [comment]
[slack](https://gratipay.slackarchive.io/gratipay/page-100/ts-1494883039396305)

**Pull request merged**
