### PR TITLE
automate the weekly tweet

### PR DESCRIPTION
**Pull request by whit537**
Every week during [payday](http://inside.gratipay.com/howto/run-payday) we send out a tweet like this:

> Week 136—2,924 users exchanged $10,581: https://gratipay.com/about/stats.

https://twitter.com/Gratipay/status/553248050957664257

We want to automate that.

### CODE REVIEW

**Comment by whit537** [comment]
API for tweeting is here:

https://dev.twitter.com/rest/reference/post/statuses/update

**Comment by whit537** [comment]
But it looks like we can't pin the tweet programmatically. :-/

https://twittercommunity.com/t/pin-a-tweet-with-the-twitter-api/13048

**Comment by benhc123** [comment]
Yes, that might need to stay manual.

**Comment by galuszkak** [comment]
If it isn't posible through API to pin tweet then, we can always bypass this writing script to pin tweet through CasperJS or something similar.

**Comment by whit537** [comment]
I'll see about using this during payday this week. We don't need to wait for tweet pinning before we land this.

**Comment by whit537** [comment]
I'm getting a 403 with the latest commit and creds from a test app I made.

**Comment by benhc123** [comment]
This might be more trouble than it's worth in terms of effort integrating with the Twitter API.

**Comment by whit537** [comment]
There is no more weekly tweet.

**Comment by tshepang** [comment]
Will it be re-instated? Why (or why not)?

**Comment by whit537** [comment]
@tshepang I believe we shouldn't reinstate it, but we should talk about that. Reticketed as https://github.com/gratipay/inside.gratipay.com/issues/236.

**Pull request closed without merging**
