### PR TITLE
Use released honcho version

### PR DESCRIPTION
**Pull request by techtonik**
The fix needed for 1813762f should be already there.

### CODE REVIEW

**Comment by techtonik** [comment]
@Changaco, can you clarify why the build fails? The failure seems related to https://github.com/gratipay/gratipay.com/issues/3025

**Comment by Changaco** [comment]
We can't use a honcho version from upstream, they don't support `honcho run PROCESS` like https://github.com/gratipay/honcho does.

**Comment by techtonik** [comment]
Bad day.

https://honcho.readthedocs.org/en/latest/using_procfiles.html#no-honcho-run-target

I don't get it. What's the difference between running a command (which is implemented) and running a process (which is Gratipay fork)?

**Comment by techtonik** [comment]
/me is reading http://blog.daviddollar.org/2011/05/06/introducing-foreman.html

**Comment by techtonik** [comment]
https://stackoverflow.com/questions/21129788/what-is-the-difference-between-foreman-start-and-foreman-run-rails-server

Ok. `process` is `command configured in Procfile`.  `foreman start` is used to exec process. `foreman run` is used to run shell command in the same conditions. Why extend `foreman run` to run processes?

@whit537 ?

**Pull request closed without merging**
