### PR TITLE
New banner image for @timothyfcook!

### PR DESCRIPTION
**Pull request by whit537**
Follow-on from #3755.

### CODE REVIEW

**Comment by whit537** [comment]
Good to merge, @timothyfcook?

**Comment by whit537** [comment]
screen shot 2016-12-30 at 5 24 59 pm

-----------------------

screen shot 2016-12-30 at 5 25 10 pm

**Comment by timothyfcook** [comment]
Let's do it! Merge away @whit537 . Happy with the result? Not bad for a quick upgrade.

**Comment by whit537** [comment]
Very happy, especially for the quick turn around! Way to get something done on yer day off! 💃 

!m @timothyfcook 
!m [anonymous illustrator]
!m *

**Comment by whit537** [comment]
Merging when green ...

**Comment by whit537** [comment]
Deployed! 💃 

https://gratipay.com/

screen shot 2016-12-30 at 5 44 33 pm

**Comment by nobodxbodon** [comment]
After seeing this screenshot with the team logo, excuse me I can't help asking, what's the problem with the banner before?

screen shot 2016-12-30 at 5 24 59 pm

**Comment by whit537** [comment]
> what's the problem with the banner before?

I'll let @timothyfcook speak for himself since he was the main advocate against the banner, but what I see is:

1. We have [three brand colors](http://inside.gratipay.com/big-picture/brand#toc-3): green, brown, and gold. We're converging on green as the main color, with brown in the logo and accents, and gold in calls to action. The old banner was basically gold, but really the gold should be used sparingly because it's so bright.
1. The old banner was distractingly busy, because it was a photograph.

**Comment by timothyfcook** [comment]
Yep!

1. Poor contrast for the different feature element that overlay on top of the old banner
2. Skeumorphic sort of look with the woodgrain
3. Photo background was out-of-sync with the otherwise clean/flat design of the site and site colors.

**Pull request merged**
