### PR TITLE
Extract a modal component

### PR DESCRIPTION
**Pull request by rohitpaulk**
Preparation for https://github.com/gratipay/gratipay.com/issues/1052#issuecomment-309198597. This seems like a good enough chunk to review, hence split into a separate PR.

### CODE REVIEW

**Comment by rohitpaulk** [comment]
Screenshots: 

**Desktop - Before**

screen shot 2017-06-17 at 4 51 19 pm

**Desktop - After**

screen shot 2017-06-17 at 4 51 25 pm

**Mobile - Before**

screen shot 2017-06-17 at 16 52 00

**Mobile - After**

screen shot 2017-06-17 at 16 51 49

**Comment by mattbk** [comment]
I can only assume this works, because #4525 works.

**Comment by whit537** [comment]
Rebased, was 43ac69fe002d9f9e8d59920cfc85e0340c9c4221.

**Comment by whit537** [comment]
Ready to merge when green ...

**Pull request merged**
