### PR TITLE
stop charging failed cards

### LINKED ISSUE #3531: get our decline rate under control
From: Braintree

> Hi Chad, 
>
I hope this e-mail finds you well. We just received notification that our risk department flagged your Gratipay account as a result of a large amount of transactions being declined in your Braintree Gateway.
>
Of the 386 transactions recently processed, 222 have been declined. This is a huge concern for our Risk team and sponsoring bank, and our goal is to work with you to decrease the amount of declines on your merchant account so that you can resume normal processing.
>
In order to complete their review, the risk department is requesting: 
>
1. An explanation for the large amount of declines.
2. The last three months’ bank statements showing beginning and ending balances to ensure that you are supportive of the increased risk exposure brought about by a large decline ratio.
3. Any processing statements you may have from your most recent merchant processing relationship
4. Itemized invoices complete with customer contact information and any applicable shipping documents for transactions [], [], and []
>
Funds are currently not on hold at this time. If I can be of any assistance whatsoever, please don’t hesitate to email me or call me directly at [].
>
Thank you in advance,

https://gratipay.freshdesk.com/helpdesk/tickets/2295

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/20695881-get-our-decline-rate-under-control?utm_campaign=plugin&utm_content=tracker%2F85909&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F85909&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by whit537**
Closes #3531.

### CODE REVIEW

**Comment by whit537** [comment]
I think the fix for this is actually pretty trivial, simply constraining the participants query in payday.sql with `AND error = ''`. We should have a test, though, and I don't see that we demonstrate the working case first yet.

**Comment by whit537** [comment]
@rohitpaulk Looks like you accidentally committed `gratipay.{js,css}`, ya?

**Comment by rohitpaulk** [comment]
Ah, right. Force pushing that off...

**Comment by whit537** [comment]
I'm good to merge (once Travis is green) if you're okay with 8a6f517088d5df499b87a0a7a26292f2336bf1c9.

**Comment by whit537** [comment]
Interesting, I'm not seeing that locally.

**Comment by whit537** [comment]
Hrm ... I now get the error Travis gets, plus a bonus error. O.O

**Comment by whit537** [comment]
```
___________________________ TestNewTeams.test_migrate_tips_to_subscriptions ____________________________
Traceback (most recent call last):
  File "/Users/whit537/personal/gratipay/gratipay.com/tests/py/test_teams.py", line 133, in test_migrate_tips_to_subscriptions
    assert subscriptions[0].subscriber == 'alice'
AssertionError: assert 'bob' == 'alice'
  - bob
  + alice
```

**Comment by whit537** [comment]
Gah, the Travis error is because my commit was bad, one sec ...

**Pull request merged**
