### PR TITLE
Add Travis caching

### PR DESCRIPTION
**Pull request by techtonik**
Container-based builds allow to cache files
http://docs.travis-ci.com/user/caching/

For `pip` packages there is `cache: pip`, but it doesn't work,
because we have a custom `install:` section. See
travis-ci/travis-ci#3239 for details.

### CODE REVIEW

**Comment by Changaco** [comment]
Reposting https://github.com/gratipay/gratipay.com/pull/3263#issuecomment-82887700:

> I don't see how that would help. Almost all of the dependencies are in the `vendor/` dir, pip doesn't download them. It's compiling the C(++) libs that slows down our builds, we could try caching `env/lib/python2.7/site-packages`.

**Comment by techtonik** [comment]
We maybuild wheels from vendor/ first and cache wheels dir.

**Comment by techtonik** [comment]
I don't get why build failed.

**Comment by Changaco** [comment]
That second build demonstrates that caching `$HOME/.cache/pip` is useless, the build time is similar to the first one.

**Comment by techtonik** [comment]
It is not over yet. Last commit catched #3265

**Comment by techtonik** [comment]
Caching `$HOME/.cache/pip` is useless for now, but I will improve that after #3265 is merged in and I can continue with fixes.

**Comment by Changaco** [comment]
> Caching `$HOME/.cache/pip` is useless for now

Caching it is useless as long as we have the deps in `vendor/`.

**Comment by techtonik** [comment]
Aaand? What's the problem with merging now? =/

**Comment by techtonik** [comment]
@Changaco @whit537 I need help.

**Comment by techtonik** [comment]
Ok. Latest requirements_tests.txt change conflicts with recently merged https://github.com/gratipay/gratipay.com/pull/3265 I thought that GitHub somehow manages to show conflicts. Will rebase shortly.

**Comment by Changaco** [comment]
Your approach seems flawed to me: complicated and inefficient. Simply caching `env/lib/python2.7/site-packages` (and `env/bin` too?) should work.

**Comment by techtonik** [comment]
@Changaco, caching site-packages may work, but it feels like a non-obvious low level hack to me.

Nevertheless, its almost done.  Now either `honcho` or `pip` need to be upgraded to pass over last error.

**Comment by techtonik** [comment]
This won't work due to - https://github.com/pypa/pip/issues/855

Sigh.

**Comment by techtonik** [comment]
Need a wrapper script to implement cache properly. `pip` alone won't be enough and other solutions look cryptic. Need to upgrade `pip` and `honcho` anyway.

**Pull request closed without merging**
