### PR TITLE
Send an email when a ~user is marked suspicious

### LINKED ISSUE #557: Email notify users when they are marked suspicious
Send an email notification when possible to users when we mark them suspicious.

----------------

## Original

This might be controversial.

I want to have a page at `/about/fraud/untrusted/` which simply lists all participants with  `is_suspicious is true`. As our fraud system evolves (#556), so will this listing. The principle is that untrusted users are announced as such so that false positives have a chance to discover this and attempt to redeem themselves. We can't be like PayPal, an infuriatingly opaque black box if you're a false positive.
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/316745-add-a-page-that-shows-untrusted-users?utm_campaign=plugin&utm_content=tracker%2F85909&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F85909&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by mattbk**
Closes #557.

Stubbed out for now, I ran into a bit of issue with updating my database schema, may be because of recent upgrade...

> Notes:
> - tests https://github.com/gratipay/gratipay.com/blob/fdc132287f2c28486b2b68bad28d11b516ad1e97/tests/py/test_email.py
> - sending https://github.com/gratipay/gratipay.com/blob/b7449e318a29c53dd3a0570bf45b68a664c2249f/www/%25team/set-status.json.spt#L39
> - should be tripped when `is_suspicious` is set, probably in https://github.com/gratipay/gratipay.com/blob/7a9cc3cd93dbebfb8cd949cdae2e3221c544a461/www/~/%25username/toggle-is-suspicious.json.spt ?

todo
- [x] send one email if suspicious turned on, another if turned off ([example](https://github.com/gratipay/gratipay.com/blob/b7449e318a29c53dd3a0570bf45b68a664c2249f/www/%25team/set-status.json.spt#L42))
- [ ] tests ([example](https://github.com/gratipay/gratipay.com/blob/fdc132287f2c28486b2b68bad28d11b516ad1e97/tests/py/test_email.py#L52))
- [ ] write email copy
    - [ ] update tests
- [ ] document

### CODE REVIEW

**Comment by mattbk** [comment]
I still don't know why it's botched...

**Comment by mattbk** [comment]
Confirm that an email is queued when I change the suspicious box.

**Comment by mattbk** [comment]
tmp_18876-screenshot_20170410-190736271250389

**Comment by mattbk** [comment]
Should be ready for review when green. I couldn't find a good example script for telling people they are suspicious.

See also #3058 for the possibility of expanding the email text to cover suspension for other reasons than fraud.

**Comment by mattbk** [comment]
Still not sure how that first commit got in there, but this version only changes four files, so I'll leave it alone.

**Comment by kaguillera** [comment]
LGTM...Updating branch by merging in master. Will merge into master once it is green

**Pull request merged**
