### PR TITLE
Remove symlinks - fixes #3318

### LINKED ISSUE #3318: Do not use symlinks
symlinks are not available on all filesystems. This causes issues with Vagrant on Windows, such as #3165

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/10618491-do-not-use-symlinks?utm_campaign=plugin&utm_content=tracker%2F85909&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F85909&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by techtonik**
The tests start to fail on my machine, but it seems that the reason is the test suite logic, not the same as in #3165.

### CODE REVIEW

**Comment by techtonik** [comment]
Rebased and ready for review. Ping @whit537 @rohitpaulk.

**Comment by techtonik** [comment]
@whit537?

**Comment by techtonik** [comment]
Ping @whit537 @rohitpaulk

**Comment by whit537** [comment]
When I hit: http://localhost:8537/about/me/history/

I'm redirected to: http://localhost:8537/whit537/

Instead, I should be redirected to: http://localhost:8537/whit537/history/

**Comment by techtonik** [comment]
@whit537 argh, I was testing with the wrong container.

**Comment by techtonik** [comment]
@whit537 fixed! Check it out.

**Comment by whit537** [comment]
!m @techtonik

**Pull request merged**
