### PR TITLE
Suspicious email cleanups

### PR DESCRIPTION
**Pull request by whit537**
Follows on #4401.

### CODE REVIEW

**Comment by whit537** [comment]
Ping @mattbk @kaguillera. Eh?

**Comment by kaguillera** [comment]
picky..picky but sure it looks good so I will merge when Travis say it is green

**Comment by mattbk** [comment]
Just missed my commit! :(

It's okay, all I did was make "We've" into "We have" in the other email.

**Comment by kaguillera** [comment]
Next time I will wait a little longer.

**Comment by mattbk** [comment]
No worries! If it bugs me I can open another PR.

**Comment by whit537** [comment]
I considered that, but decided the asymmetry was fine since the "true" case is more formal, and the "false" case also has the second sentence to balance the abbreviation in the first.

**Pull request merged**
