### PR TITLE
Update tests for new mixins

### LINKED ISSUE #4122: fill out the test suite for the mixins, prune old tests
Reticketed from #3994.

### PR DESCRIPTION
**Pull request by whit537**
Closes #4122.

### CODE REVIEW

**Comment by whit537** [comment]
Testing with (e.g.):

```
[gratipay] $ envtest tests/py/test_team_membership.py --cov gratipay.models.team.mixins.membership --cov-report=annotate
```

**Comment by whit537** [comment]
I don't know what tests I thought we should prune. Ready for review!

**Comment by whit537** [comment]
Rebased on master. Previous head was a10aa3d6672f9d4d660e2fea06d3dee250136861.

@aandis @rohitpaulk This is a fairly straightfoward holdover from #3994. Could we review and get this in before proceeding with #4148?

**Comment by whit537** [comment]
Bump for review. Previous head was 9cd08fd9e108c000a78a78af3d1a581a8194c1ce.

**Comment by whit537** [comment]
Wanna review this one, @kaguillera? :-)

**Comment by kaguillera** [comment]
LGTM

**Comment by whit537** [comment]
Rebased! Previous head was b38072eb3691f6271ade5b2c7b84d3108341417a.

@kaguillera You know what to do ... ;-)

**Comment by kaguillera** [comment]
Travis is taking really long...waiting for green to merge.

**Comment by whit537** [comment]
> No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
>Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
>The build has been terminated

Restarting!

**Comment by kaguillera** [comment]
umh this is awkward... @whit537 😕

**Comment by whit537** [comment]
?

**Pull request merged**
