### PR TITLE
revise the Team application

### LINKED ISSUE #3677: Clarify team application process and parameters on application page
Reticketed from https://github.com/gratipay/applications/issues/17#issuecomment-129905354, which I think is a great, civil discussion about how the team application process is perceived and fuzzy and open to misunderstanding.

In particular, 
- team application guidelines should be spelled out explicitly on the [team application page](https://gratipay.com/new), and
- legal reasons behind requiring applications should be explained in the site documentation, not solely on blog posts.

I ask that discussion of the application policies be kept in a separate ticket at [inside.gratipay.com](https://github.com/gratipay/inside.gratipay.com/issues?utf8=%E2%9C%93&q=is%3Aissue++sort%3Aupdated-desc+) and this ticket be retained for implementation or rejection of this change.  Hopefully this will avoid confusing the two subjects.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/25656539-clarify-team-application-process-and-parameters-on-application-page?utm_campaign=plugin&utm_content=tracker%2F85909&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F85909&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by whit537**
Closes #3677.

### CODE REVIEW

**Comment by whit537** [comment]
Rebased on master.

**Comment by whit537** [comment]
- [ ] Add a couple more checkboxes for public review and payroll agreement.
 - [ ] Add validation for URLs.
 - [ ] Test with empty URLs (for pre-existing Teams).

**Comment by whit537** [comment]
Right direction, @mattbk et al.?

screen shot 2015-08-19 at 9 02 33 pm
screen shot 2015-08-19 at 9 02 41 pm

**Comment by mattbk** [comment]
I like it.

**Comment by whit537** [comment]
I propose that we land this without "[How to Review Team Applications](https://github.com/gratipay/inside.gratipay.com/issues/311)," and then once we write that we link "publicly reviewed" there instead of to the applications issue tracker.

screen shot 2015-08-20 at 10 45 12 am

**Comment by whit537** [comment]
Empty URLs are fine, we just don't show those links:

screen shot 2015-08-20 at 10 46 16 am

**Comment by whit537** [comment]
Here's what it looks like with the links filled out:

screen shot 2015-08-20 at 10 50 13 am

**Comment by whit537** [comment]
I keep waffling about the "Issues" term. Waddya think?

 - Issues
 - TODO
 - Tracker
 - Tickets
 - Work Available

**Comment by whit537** [comment]
I like something more general, like TODO or Work Available, because it leaves open the specific tooling in use.

**Comment by mattbk** [comment]
"Work Available" is clear.

**Comment by whit537** [comment]
"To-do" is [a pretty common term](https://www.google.com/search?q=to-do) (I don't think it's limited to geeks, is it? TODO would be, but To-do I think is okay). And it's what I used for the field name, `todo_url`. :-)

**Comment by mattbk** [comment]
I would avoid TODO because it looks like an acronym to non-coders.

**Comment by whit537** [comment]
@mattbk How about if it's spelled "To-do" instead (see my previous comment)?

**Comment by whit537** [comment]
Also, I think Onboarding comes before To-do conceptually.

**Comment by whit537** [comment]
screen shot 2015-08-20 at 11 05 48 am

**Comment by whit537** [comment]
S'okay?

**Comment by whit537** [comment]
"Work Available" is so ... verbose.

**Comment by whit537** [comment]
Also, "Work Available" could sound too much like "Job Openings," whereas "To-do" makes it clearer that we're talking about specific work items people can start doing *now*.

**Comment by whit537** [comment]
Gonna look at i18n and then hit "Review" ...

**Comment by whit537** [comment]
We should try to extract `{onboarding,todo}_url`s from the `getting_involved` of existing Teams before we drop that column.

**Comment by whit537** [comment]
Another though: Teams are in between. On the one hand a Team page should appeal to ~users who want to *give* payments to the Team, and on the other to ~users who want to do work and *take* payroll. Out of scope for this PR but something to keep in mind when we're able to circle back around to #3248.

**Comment by whit537** [comment]
Okay! I think this PR is ready for final review. Deployment notes:

 - [ ] find URLs to backfill for existing teams

**Comment by whit537** [comment]
@mattbk et al. Wanna help me fill out [this CSV](https://demo.sandstorm.io/grain/nGSMwdxYGNw26J2MramcTg)? :)

/me starts at the bottom ...

**Comment by mattbk** [comment]
Can you give me access?

**Comment by whit537** [comment]
@mattbk I would expect that you can simply click and start editing. No?

**Comment by whit537** [comment]
I looked for a "sharing" setting and didn't see it ...

**Comment by mattbk** [comment]
I get "Unauthorized [403]" and I am logged in with github.

**Comment by whit537** [comment]
Interesting! Okay, one sec ...

**Comment by whit537** [comment]
Try this? https://demo.sandstorm.io/shared/R2Q574YpMAGntRLfAc9GH_S0nhClBu45Dx_Pmug4-sn

**Comment by whit537** [comment]
"Demo expires in in 49 minutes." Hurry! :dancer:

**Comment by mattbk** [comment]
I charged through a bunch of them, but have to run now.

**Comment by whit537** [comment]
!m @mattbk

**Comment by whit537** [comment]
Moved to http://pad.totalism.org/p/backfill-gratipay-urls.

**Comment by whit537** [comment]
Hmmm ... I think we should keep the `revenue_model`, `getting_involved`, and `getting_paid` columns around, but only make them visible to the Team owner on the edit page (#3545), in case they want to copy/paste some of that text over to the main textarea.

**Comment by whit537** [comment]
Done! https://gist.github.com/whit537/acc4bf816f18eb9e9088

**Comment by whit537** [comment]
I manually updated eight `homepage`s that didn't have a protocol prefixed (one is a `mailto:`!).

**Comment by whit537** [comment]
I added a little script to that gist, for generating SQL updates from the CSV.

**Comment by whit537** [comment]
Alright. Going for it ...

**Pull request merged**
