### PR TITLE
bring back takes in payday

### PR DESCRIPTION
**Pull request by whit537**
&#x2B11; #3994

&larr; #4024 — #4026 &rarr;

#### Punchlist 

- [x] rewrite `process_takes`
- [x] insert a `process_baselines` before `process_takes`
- [ ] include members in MassPay; see `get_ready_payout_routes_by_network`
- [ ] clean up test suite (depends on `take_over` in #4023)
- [ ] remake against `master` once #4024 lands

### CODE REVIEW

**Comment by whit537** [comment]
I'm looking at baselines () here. ~owners can claim takes just like any other ~user. Should we just depend on that instead of implementing the baseline?

**Comment by mattbk** [comment]
> ~owners can claim takes just like any other ~user. Should we just depend on that instead of implementing the baseline?

I like that, although maybe it should be set up so that no other takes are available until the owner takes at least one? (Temporal dependency rather than set initial $ dependency)

**Comment by whit537** [comment]
> maybe it should be set up so that no other takes are available until the owner takes at least one? (Temporal dependency rather than set initial $ dependency)

Since takes are proportional rather than absolute, there's no need for a temporal consideration; cf. point 2 under [benefits](https://github.com/gratipay/gratipay.com/issues/3994#issuecomment-217340995). The problem with this is related to what @Changaco [identified](https://github.com/gratipay/gratipay.com/issues/3994#issuecomment-217419201) in terms of volatility in income for participants. Based on the user examples I cited in benefit (3), I think team owners will appreciate the stability of an absolute rather than a proportional baseline.

**Comment by whit537** [comment]
> I think team owners will appreciate the stability of an absolute rather than a proportional baseline.

This goes for Team Gratipay, even. We need ~$150/wk just to keep the lights on. If income dips down to $120 in a given week, then it should all go to ~Gratipay for operations. No?

**Comment by whit537** [comment]
```
[gratipay] $ grep xfail tests/py/test_billing_payday.py 
    @pytest.mark.xfail(reason="haven't migrated transfer_takes yet")
    @pytest.mark.xfail(reason="Don't think we'll need this anymore since we aren't using balanced, "
    @pytest.mark.xfail(reason="haven't migrated transfer_takes yet")
    @pytest.mark.xfail(reason="haven't migrated_transfer_takes yet")
    @pytest.mark.xfail(reason="haven't migrated take_over_balances yet")
[gratipay] $
```

**Comment by mattbk** [comment]
> We need ~$150/wk just to keep the lights on. If income dips down to $120 in a given week, then it should all go to ~Gratipay for operations.

That's the best argument for an absolute baseline.

**Comment by whit537** [comment]
###### on `UPDATE` of `teams.baseline`

 - for the owner:
  - `taking`
 - for all members:
  - `taking`
 - for the team:
  - `distributing`
  - `surplus`

**Comment by whit537** [comment]
Scrapping for parts. https://github.com/gratipay/gratipay.com/issues/3994#issuecomment-229949952

**Comment by whit537** [comment]
Redo: #4102.

**Pull request closed without merging**
