### PR TITLE
constraint payments.schema > 0 in the schema

### PR DESCRIPTION
**Pull request by whit537**
This could've gone in #3430.

### CODE REVIEW

**Comment by whit537** [comment]
Eh, @rohitpaulk? We were doing the same for `transfers`.

**Comment by whit537** [comment]
We don't. I copied and pasted from `schema.sql` and didn't stop to understand what that meant.

**Comment by whit537** [comment]
> If the constraint is marked NOT VALID, the potentially-lengthy initial check to verify that all rows in the table satisfy the constraint is skipped. The constraint will still be enforced against subsequent inserts or updates (that is, they'll fail unless there is a matching row in the referenced table, in the case of foreign keys; and they'll fail unless the new row matches the specified check constraints). But the database will not assume that the constraint holds for all rows in the table, until it is validated by using the VALIDATE CONSTRAINT option.

http://www.postgresql.org/docs/9.4/static/sql-altertable.html

**Comment by whit537** [comment]
Removed in 8a1a4d2d131c4889ddc28cb5c2e62029fe36ca82. Better, @rohitpaulk?

**Comment by rohitpaulk** [comment]
Purrrfect. :) Let's wait for Travis, and merge this in :dancer:

**Comment by whit537** [comment]
k

**Pull request merged**
