### PR TITLE
Cleanup billing code

### PR DESCRIPTION
**Pull request by rohitpaulk**
Also fixes https://github.com/gratipay/gratipay.com/issues/3811

### CODE REVIEW

**Comment by rohitpaulk** [comment]
We should run `update_giving` on all users with failing cards..

**Comment by rohitpaulk** [comment]
I'm going to try this script on a backup and call it a day

**Comment by rohitpaulk** [comment]
Hmm, doesn't seem to be working...

**Comment by rohitpaulk** [comment]
The participant's `giving` values are updated properly, but the `receiving` values on teams are still the same

**Comment by rohitpaulk** [comment]
Aha, the problem was coz I was updating through the `current_payment_instructions` view - the rows were updated, but results weren't being returned.

**Comment by rohitpaulk** [comment]
Script works on my local, marking this as ready for review

**Comment by whit537** [comment]
Looks good to me, @rohitpaulk. Can I let you merge and deploy?

**Comment by rohitpaulk** [comment]
Ran the script.

```
285 participants with failing cards
Updating (285/285)
Done!
```

**Comment by rohitpaulk** [comment]
Removed branch.py, released again.

**Comment by whit537** [comment]
!m @rohitpaulk

**Pull request merged**
