### PR TITLE
be up front that team applications are public

### PR DESCRIPTION
**Pull request by whit537**
Quick fix for #3613.

screen shot 2015-07-10 at 9 53 50 pm

### CODE REVIEW

**Comment by whit537** [comment]
How's that, @mattbk @remy? A little better?

**Comment by remy** [comment]
LGTM. (and pretty much how I drive UI tweaks on @jsbin too!).

**Comment by whit537** [comment]
Thanks @remy. :)

**Comment by mattbk** [comment]
Looks good to me.

**Pull request merged**
