### PR TITLE
Tighten up the banner on the homepage

### PR DESCRIPTION
**Pull request by whit537**
Follow-on from #4267.

- Drops the old banner JPG and renames the new PNG
- Tweaks the homepage copy and positioning
- Brings back "About" in the top nav

----------------

screen shot 2016-12-30 at 9 06 43 pm

### CODE REVIEW

**Comment by whit537** [comment]
Eh, @mattbk @timothyfcook et al.?

**Comment by timothyfcook** [comment]
@whit537 the copywriting needs some love... "helps companies and others"... what about...

"Gratipay helps you support the open source projects you love."
or just a call to action:
"Support the open source projects you love."

**Comment by mattbk** [comment]
I like @timothyfcook's call to action. Be imperative.

Also glad that "About" is back.

This totally belongs somewhere else:

Since I'm looking at it...the current tagline is targeted at givers, but the "Apply to join" button is targeted at receivers. If I'm a potential giver, I don't want to "apply" to anyone. Maybe we need two buttons, e.g. "Give" (links to a create account page--which we don't seem to have? All we have is "sign in," not "create account"--_nowhere_ is it clear and obvious that you can create an account just by signing in with your social account!)and "Receive" (links to the application) although those may be too simplistic. Related: the news item says "easier to join Gratipay" which should be "easier to receive donations."

**Comment by EdOverflow** [comment]
Why not a complete redesign? I would love to see an awesome landing page, which explains the platform on one page. We could make the projects appear randomly on the landing page in form of a grid. Something like this:

land

**Comment by whit537** [comment]
> Why not a complete redesign?

Go for it! :-) Personally I'm going to keep working on https://github.com/orgs/gratipay/projects/4?fullscreen=true, though. ;-)

**Comment by whit537** [comment]
> just a call to action

?

screen shot 2016-12-31 at 7 59 00 am

**Comment by whit537** [comment]
Or even ... ?

screen shot 2016-12-31 at 8 18 38 am

**Comment by timothyfcook** [comment]
"Pay for open source" is pretty solid. Only caveat is that it makes it sound somewhat obligatory?

"Support open source" would be more voluntary / call to action.

Either one probably works. 

I prefer the smaller font.

**Comment by mattbk** [comment]
> Why not a complete redesign? I would love to see an awesome landing page, which explains the platform on one page. We could make the projects appear randomly on the landing page in form of a grid.

@EdOverflow, you might want to toss some ideas around with @JessaWitzel at https://github.com/gratipay/gratipay.com/pull/4234.

I've seen a lot of redesign tickets, I'm sure there are still some good ideas that were never implemented.

**Comment by whit537** [comment]
Rebased, was 6da2071b75400993ad8306a3ae8931289cb7c48e.

**Pull request merged**
