### PR TITLE
Make search search teams as well

### PR DESCRIPTION
**Pull request by mattbk**
Closes https://github.com/gratipay/gratipay.com/issues/3872.

Stubbing out a barely working version.

- [x] search by team name 
- [x] search by `product_or_service`
- [x] display team logo in result
- [x] display `product_or_service` the same way ~user statements are

### CODE REVIEW

**Comment by mattbk** [comment]
Not the greatest. I toyed with copying the table on the front page, but that would involve moving the sidebar as well.

screen shot 2016-12-02 at 10 36 50 pm

**Comment by mattbk** [comment]
Per last commit, should look like 
screen shot 2016-12-03 at 9 37 27 pm
but looks like (project description intentional)
screen shot 2016-12-03 at 9 38 11 pm

The project name is not big, and there is no line at the bottom of the row. CSS?

**Comment by mattbk** [comment]
Cleaning the environment. Search of `product_or_statement` is not working as expected.

**Comment by mattbk** [comment]
I'll probably make the project name results display the same as the project description results for consistency and differentiation from ~user results.

**Comment by mattbk** [comment]
Ready for review.

**Comment by JessaWitzel** [comment]
I would love to review this but when I checkout the branch and run it locally there is no data so I cannot test the search function. What should I do?

**Comment by mattbk** [comment]
Have you run "make fake" as mentioned in the readme?

**Comment by whit537** [comment]
Added to #4221 since right now we're [lying](https://github.com/gratipay/gratipay.com/issues/3872#issuecomment-220036875). Also https://github.com/gratipay/gratipay.com/pull/4157#issuecomment-264349584.

**Comment by mattbk** [comment]
[Slack](http://gratipay.slackarchive.io/gratipay/-/1481585460.000476/1481647798.000582/1481598787000527/)

**Comment by whit537** [comment]
Can we do something about the styling? Don't need to go overboard (the search feature needs an overhaul), but maybe at least reuse the "username" tile styling for projects?

screen shot 2016-12-14 at 11 58 35 am

**Comment by whit537** [comment]
Also, if we're not going to do excerpts for project descriptions like we do for participant statements, then I think we should just drop project descriptions from both the fields searched and the results display. Even just searching over project names is enough to undo the lie we're currently caught in. :-)

**Comment by JessaWitzel** [comment]
From what I'm seeing this does include an excerpt from the product description? Am I missing something?

**Comment by JessaWitzel** [comment]
Also I like that the styling is different so that you can see the entire project name. Do you mean that you want the same tile look @whit537 ?

**Comment by mattbk** [comment]
If you look at the CSS, you can see that I tried styling them similar to the front page, but it doesn't seem to work.

The project list includes the first 100 characters of the description, not a search-style excerpt as it does for ~user profiles. I was trying for a minimum working product.

**Comment by whit537** [comment]
Well, our search experience is really, really rough right now. I'm looking for how to not make it too much worse while also getting this out the door quickly. I think our best bet is to maintain parallelism in the UI with the user results. I think we should have "FOUND A MATCHING PROJECT NAME" with a little tile like we have under "MATCHING USERNAMES." We should drop the description since for users that's a separate section of the page. I don't think we should bother adding a section for matching project descriptions in the interest of expediency.

screen shot 2016-12-14 at 12 16 54 pm

**Comment by whit537** [comment]
> Also I like that the styling is different so that you can see the entire project name.

Not a bad point, but I think we should address that outside of this PR in a search overhaul.

**Comment by whit537** [comment]
I'm gonna make some commits ...

**Comment by mattbk** [comment]
Project searches both project name and description, and returns both.

What if I'm searching for something like "python" because I want to support Python projects? A logo and a project name don't tell me anything about a project. 

I previously had separate sections for project name and project description, then combined them because for the searcher, it probably doesn't matter.

**Comment by whit537** [comment]
It's funny, I'm just landing a 3-month project with COS to write a test suite for private search, and over here we have zero tests. :P

**Comment by mattbk** [comment]
I also disagree that projects should be presented in the same way as ~users. That's confusing. Ideally all projects should be presented as on the front page, even on ~user pages that are listing projects.

E.g., 
image

**Comment by whit537** [comment]
@mattbk All valid points, I just think we don't want to block https://github.com/orgs/gratipay/projects/5?fullscreen=true on fixing search, because search is so horribly broken. I think we should just search over project names with a UI section parallel to USERNAMES, because that's the absolute simplest thing we can do here. I want to land https://github.com/orgs/gratipay/projects/5?fullscreen=true!

**Comment by whit537** [comment]
I thought I did a write-up somewhere about changing search but I'm not finding it right now ...

**Comment by mattbk** [comment]
I guess my point is that this PR already does more than you want...

**Comment by whit537** [comment]
Right, but it also doesn't do enough. I'm not comfortable deploying the project presentation currently on this PR. Yes, the homepage styling is better, but the homepage listing doesn't include project descriptions. Rather than go further down that rabbit-hole, I think we should dial back to the bare minimum: PROJECT NAME tiles like USERNAME.

screen shot 2016-12-14 at 12 36 10 pm

**Comment by whit537** [comment]
I look at this:

screen shot 2016-12-14 at 12 36 10 pm

and I am reminded of this GIF from [this](https://vimeo.com/108328246) video ([slack](http://gratipay.slackarchive.io/gratipay/-/1481598235.000507/1481736155.000613/1481657884000585/)). 😁 

giphy

**Comment by whit537** [comment]
We've also got a wider space to work with on the homepage because we don't have the sidebar there, so it's not even as simple as duplicating the homepage listing over here.

**Comment by whit537** [comment]
6f290841c0c19825775c4b105a9fb31705c698f6:

screen shot 2016-12-14 at 12 55 07 pm

**Comment by whit537** [comment]
@mattbk Is fbc616d710d39f26ecda570d12e5b29640ed90c8 any consolation? 🐭

**Comment by whit537** [comment]
Alright, I can live with this if you can, @mattbk @JessaWitzel.

**Comment by whit537** [comment]
Meaning, I'm good for us to merge, if you can accept my commits. 🙇

**Comment by whit537** [comment]
Project pic confirmed working in search:

screen shot 2016-12-14 at 1 11 57 pm

**Comment by whit537** [comment]
Rebased, was db3e33949a34d971653a8f94b25e927ee5810d8c.

**Comment by whit537** [comment]
> I am reminded of this GIF

Okay now I feel bad. 😞

**Comment by whit537** [comment]
Sorry. 😞

**Comment by mattbk** [comment]
It was a little harsh, considering this sat in review for almost a week with no comments and all of a sudden it has to be finished immediately.

**Comment by JessaWitzel** [comment]
Testing in local environment and the new code does not function as well as the old code. If I search for Joseph a project comes up but if I search for oseph it does not and if I search for Jos it does not. This is the most basic functionality I am looking for. I am confused about what you meant, @whit537 , when you said "Right, but it also doesn't do enough" because I do not see where you specifically pointed out what it doesn't do. I wonder if there is something I should be looking for that I am not. 

I prefer the old styling so that I can see a project description but without having any skin in the game I don't think it's that important.

**Comment by mattbk** [comment]
At 8e2cd048a4765a76ec14b413eb15ed8063ba4566:

screen shot 2016-12-14 at 6 56 39 pm
screen shot 2016-12-14 at 6 56 55 pm
screen shot 2016-12-14 at 6 57 11 pm
screen shot 2016-12-14 at 6 57 19 pm

**Comment by mattbk** [comment]
At head:

screen shot 2016-12-14 at 6 58 49 pm
screen shot 2016-12-14 at 6 59 13 pm
screen shot 2016-12-14 at 6 59 34 pm

**Comment by mattbk** [comment]
Even this I think would be better than a ~user avatar:

screen shot 2016-12-14 at 7 17 28 pm

**Comment by JessaWitzel** [comment]
That's not what happens in my local. My branch is up to date. Why is it different for us? 
image
image

**Comment by mattbk** [comment]
It's the difference between Joseph and Joseph18x. Joseph will return on "oseph" but Joseph18x won't. It must be searching beginning and ends of the string, but not the middle.

Works the same way on both 8e2cd048a4765a76ec14b413eb15ed8063ba4566 and head for me now.

**Comment by whit537** [comment]
Interesting. Username search behaves the same way.

screen shot 2016-12-15 at 9 28 40 am

screen shot 2016-12-15 at 9 28 32 am

**Comment by Changaco** [comment]
It's a trigram search, it can match in the middle but it seems to favor the edges.

spectacle m27799

**Comment by Changaco** [comment]
[PostgreSQL: Documentation: 9.4: pg_trgm](https://www.postgresql.org/docs/9.4/static/pgtrgm.html)

**Comment by mattbk** [comment]
THANK YOU! That was going to keep bugging me.

**Comment by whit537** [comment]
> it can match in the middle but it seems to favor the edges.

So are we okay with the behavior as-is, @JessaWitzel @mattbk? Or is searching in the middle of a username important enough to explicitly work around? And if it is important enough to work around, do we want to make that in scope on this PR?

**Comment by whit537** [comment]
Progress on restyling:

screen shot 2016-12-15 at 11 52 17 am

**Comment by whit537** [comment]
I'm trying to wrestle the text part into the details field. Once I've got that neat I think we'll be back to review here.

screen shot 2016-12-15 at 12 06 49 pm

**Comment by whit537** [comment]
Heck to the yeah! 💃  👍 

kolfbdil8q

**Comment by whit537** [comment]
Works in Chrome and Safari, borked in Firefox.

**Comment by mattbk** [comment]
I like it. Thanks for digging in.

**Comment by whit537** [comment]
Got it!

**Comment by whit537** [comment]
I have the text description integrated with the homepage listing style, and it's working for both username search (showing the beginning of the statement) as well as user statement matches (showing the relevant excerpt as before). It works responsively, and doesn't break the homepage (though as a side-effect, the details on the homepage now overflow hiddenly with ellipsis rather than float dropping). I've tested in Chrome, Safari, and Firefox on macOS.


image

---------------------

image

---------------------

image

-----------------

image

------------------

image

**Comment by whit537** [comment]
Back over to you for review, @JessaWitzel @mattbk!

**Comment by whit537** [comment]
Here it is on some backup data. It's interesting that `zero` doesn't match https://gratipay.com/Zerodark-theme/. More trigrams!

------------------

ryrcx4ofti

**Comment by whit537** [comment]
Oops! 😊 

--------------------

image

**Comment by whit537** [comment]
Fixed in 4da29819ffb91b5dd3678b7c13df7d717b563297.

**Comment by whit537** [comment]
From [slack](http://gratipay.slackarchive.io/gratipay/-/1481645349.000567/1481830028.000675/1481816884000652/):

> I think it's important enough to find a work around.
> But it can be on a different PR

👍

I'll let you reticket if you like. :-)

**Comment by mattbk** [comment]
I approve.

> It's interesting that `zero` doesn't match https://gratipay.com/Zerodark-theme/. More trigrams!

Probably because `zero` is not a large enough proportion of the project name string?

**Comment by whit537** [comment]
> I approve.

💃 

> Probably because `zero` is not a large enough proportion of the project name string?

Yeah, searching for `zerod` matches it.

**Comment by mattbk** [comment]
Woo!

!m @jessawitzel

**Comment by whit537** [comment]
Deployed! Huzzah! 💃

!m @mattbk @JessaWitzel *

image

**Comment by whit537** [comment]
Announced: https://twitter.com/Gratipay/status/809875073192620032

**Pull request merged**
