### PR TITLE
Remove mention of bank account on error 400

### PR DESCRIPTION
**Pull request by mattbk**
We only have payouts through PayPal right now, so in order to remove confusion we shouldn’t tell people to attach a bank account when they can’t.  https://github.com/gratipay/gratipay.com/issues/3654

### CODE REVIEW

**Comment by whit537** [comment]
@mattbk The *.po translation files are updated automatically underneath [`release.sh`](https://github.com/gratipay/gratipay.com/blob/1874/release.sh). We shouldn't modify them directly here in this PR.

**Comment by mattbk** [comment]
Okay, time to learn something new then.  
- Can I change the *.spt files, or does that mess with what messages the translation files are matched to?
- I should be able to undo the changes I made to the *.po files and keep it all in the same PR, right?

**Comment by whit537** [comment]
> Can I change the *.spt files, or does that mess with what messages the translation files are matched to?

You should *only* change the *.spt files (not the *.po files). During [deployment](https://github.com/gratipay/gratipay.com/blob/1877/release.sh#L54-L62), we extract strings from the *.spt files themselves into `i18n/core.po`, upload that to Transifex, and then download completed 
*.po files from Transifex. This all happens in [these Makefile targets](https://github.com/gratipay/gratipay.com/blob/1877/Makefile#L94-L108). Bottom line: change *.spt files, not *.po files.

> I should be able to undo the changes I made to the *.po files and keep it all in the same PR, right?

Yes! Easiest would be to manually edit the *.po files, commit that change, and then push it up to the same branch (`error-400-bank-account`). How's your git-fu? Want/need more specific pointers than that? :)

**Comment by mattbk** [comment]
I replaced the *.po files from master but left the *.spt files modified.  I think.

**Comment by rohitpaulk** [comment]
!m @mattbk

**Comment by whit537** [comment]
@mattbk Looks like we've got tests for those error messages. Wanna try updating those as well? :)

**Comment by mattbk** [comment]
I think it worked?

**Comment by whit537** [comment]
You win! :-)

**Comment by whit537** [comment]
!m @mattbk

**Pull request merged**
