### PR TITLE
Fix `charge_volume`

### LINKED ISSUE #3070: Charges higher than total gifts
For the past three weeks our charges have been about a thousand dollars higher than total gifts.

screen shot 2015-01-07 at 11 37 20 am

### PR DESCRIPTION
**Pull request by Changaco**
Fixes #3070.

### CODE REVIEW

**Comment by whit537** [comment]
No test?

**Comment by rohitpaulk** [comment]
Looks good to me.

**Comment by rohitpaulk** [comment]
Oops, didn't refresh for a while :P

**Comment by seanlinsley** [comment]
This modifies two paydays that it almost certainly didn't mean to. In the future we should follow a script like what I did below for any production data modifications that are moderately complex.

```sh
psql gratipay -f ../backups/2015-01-07.psql
psql gratipay -c "\copy (select * from paydays order by id) to 'p1.csv' WITH (FORMAT CSV, HEADER TRUE, FORCE_QUOTE *);"
git checkout fix-charge_volume
psql gratipay -f branch.sql 
psql gratipay -c "\copy (select * from paydays order by id) to 'p2.csv' WITH (FORMAT CSV, HEADER TRUE, FORCE_QUOTE *);"
git diff p1.csv p2.csv
```

```diff
diff --git a/p1.csv b/p2.csv
index b8abdcf..219943b 100644
--- a/p1.csv
+++ b/p2.csv
@@ -96,7 +96,7 @@ id,ts_start,ts_end,nparticipants,ntippers,ntips,ntransfers,transfer_volume,ncc_f
 "123","2014-03-20 13:29:39.564753-05","2014-03-20 16:30:07.167712-05","27548","1623","5349","5349","12664.49","379","1419","514","11183.69","479.42","102","-6012.52","0.00","124","173","293.86","2664","0"
 "124","2014-03-27 08:00:49.09408-05","2014-03-27 11:10:50.573562-05","27860","1638","5367","5367","12747.74","395","1438","525","11254.43","484.78","104","-6235.15","0.00","125","174","338.90","2696","0"
 "125","2014-04-03 09:52:58.237632-05","2014-04-03 13:17:57.194351-05","28146","1657","5327","5327","12770.27","422","1444","510","11001.22","472.91","105","-5828.38","0.00","133","177","390.53","2715","0"
-"126","2014-04-10 07:08:41.406646-05","2014-04-10 10:58:42.058049-05","28379","1665","5325","5325","12770.78","439","1453","516","11079.68","476.96","111","-6201.57","0.00","131","182","381.59","2723","0"
+"126","2014-04-10 07:08:41.406646-05","2014-04-10 10:58:42.058049-05","28379","1665","5325","5325","12770.78","439","1453","518","11358.18","476.96","111","-6201.57","0.00","131","182","381.59","2723","0"
 "127","2014-04-17 10:32:51.59449-05","2014-04-17 12:29:26.131433-05","28650","1665","5336","5336","12399.97","448","1456","502","10625.45","459.57","97","-6951.54","0.00","133","135","363.70","2718","0"
 "128","2014-04-24 09:14:59.494671-05","2014-04-24 11:19:52.779422-05","29015","1691","5446","5446","13120.14","460","1477","544","11685.49","502.99","105","-6614.89","0.00","132","135","360.59","2758","0"
 "129","2014-05-01 09:30:33.651436-05","2014-05-01 11:38:49.95375-05","29320","1718","5510","5510","13275.02","478","1481","569","12019.00","520.20","99","-6398.65","0.00","136","146","380.22","2802","0"
@@ -117,7 +117,7 @@ id,ts_start,ts_end,nparticipants,ntippers,ntips,ntransfers,transfer_volume,ncc_f
 "146","2014-08-14 11:03:33.575643-05","2014-08-14 13:51:57.458134-05","32438","1791","5066","5300","12961.75","0","1723","477","11003.42","463.04","114","-7339.02","0.00","0","234","1166.70","2898","3"
 "150","2014-08-21 13:29:53.206122-05","2014-08-21 14:26:04.999344-05","32767","1800","5133","5354","13317.50","500","1758","500","11463.34","483.29","108","-7109.88","0.00","0","220","890.25","2892","3"
 "151","2014-08-28 14:01:15.49764-05","2014-08-28 14:18:01.167168-05","33064","1839","5243","5469","13291.28","466","1769","527","11635.37","496.39","115","-6810.18","0.00","0","225","828.89","2950","3"
-"152","2014-09-04 12:00:30.935981-05","2014-09-04 15:41:24.558507-05","33307","1846","5229","5462","13342.69","399","1853","515","11587.52","491.39","114","-8197.02","0.00","0","226","846.24","2962","3"
+"152","2014-09-04 12:00:30.935981-05","2014-09-04 15:41:24.558507-05","33307","1846","5229","5462","13342.69","399","1853","514","11577.52","490.80","114","-8197.02","0.00","0","226","846.24","2962","3"
 "154","2014-09-11 09:41:25.36366-05","2014-09-11 09:54:04.954961-05","33488","1826","5194","5424","13273.81","410","1866","500","11363.02","480.36","110","-8483.10","0.00","1","230","913.41","2929","3"
 "155","2014-09-18 08:56:34.307214-05","2014-09-18 09:44:34.819309-05","33697","1823","5221","5451","12986.51","422","1865","468","10776.10","453.73","115","-6629.64","0.00","1","230","895.07","2931","3"
 "156","2014-09-25 10:52:19.512312-05","2014-09-25 11:44:05.711452-05","33925","1832","5272","5509","13434.91","422","1881","508","11596.58","489.52","114","-7021.80","0.00","0","237","880.76","2942","3"
@@ -132,6 +132,6 @@ id,ts_start,ts_end,nparticipants,ntippers,ntips,ntransfers,transfer_volume,ncc_f
 "166","2014-11-27 07:33:27.944435-06","2014-11-27 08:25:01.310933-06","36144","1819","5115","5376","10301.85","524","2027","453","8164.38","373.42","112","-5176.68","0.00","0","261","798.41","2934","3"
 "169","2014-12-04 10:39:19.683009-06","2014-12-04 10:51:37.578157-06","36371","1815","5134","5392","9932.24","531","2040","454","7876.91","365.38","102","-4887.77","0.00","0","258","766.55","2921","3"
 "170","2014-12-11 13:58:28.200612-06","2014-12-11 16:27:40.670449-06","36645","1815","5073","5334","10388.05","546","2051","489","8773.06","401.88","110","-5645.24","0.00","0","261","774.68","2916","3"
-"173","2014-12-18 09:41:45.731589-06","2014-12-18 09:53:11.200186-06","36814","1807","5106","5365","10566.31","554","2064","1007","11852.52","750.36","111","-5575.44","0.00","0","259","786.36","2921","3"
-"174","2014-12-25 10:05:10.041179-06","2014-12-25 10:17:58.834771-06","37053","1814","5102","5361","10404.11","569","2074","1038","12230.42","772.71","112","-6288.75","0.00","0","259","782.88","2931","3"
-"175","2015-01-01 11:47:07.498402-06","2015-01-01 14:37:43.514035-06","37270","1813","5003","5259","10441.84","557","2050","1008","11780.33","749.71","99","-5234.57","0.00","0","256","770.56","2924","3"
+"173","2014-12-18 09:41:45.731589-06","2014-12-18 09:53:11.200186-06","36814","1807","5106","5365","10566.31","554","2064","453","8784.92","391.39","111","-5575.44","0.00","0","259","786.36","2921","3"
+"174","2014-12-25 10:05:10.041179-06","2014-12-25 10:17:58.834771-06","37053","1814","5102","5361","10404.11","569","2074","469","8754.59","395.31","112","-6288.75","0.00","0","259","782.88","2931","3"
+"175","2015-01-01 11:47:07.498402-06","2015-01-01 14:37:43.514035-06","37270","1813","5003","5259","10441.84","557","2050","451","8685.74","387.90","99","-5234.57","0.00","0","256","770.56","2924","3"
```

**Comment by seanlinsley** [comment]
@Changaco we should add a test that confirms that the database self-check succeeds, because I can reproduce the AssertionError locally.

**Comment by Changaco** [comment]
@seanlinsley I don't understand.

**Comment by seanlinsley** [comment]
This error should have been caught by the test suite.

**Comment by Changaco** [comment]
The test suite doesn't have access to real data, it can't run the checks on the production DB nor a backup of it.

However we could run the checks in `release.sh` instead of waiting for the error to show up in Sentry.

**Pull request merged**
