### PR TITLE
simplify suggestions

### PR DESCRIPTION
**Pull request by whit537**
Follow-on from #3770.

### CODE REVIEW

**Comment by whit537** [comment]
Ping @yifeiwu. Here's some failing tests to demonstrate the behavior I think we want. Up for making them pass? :-)

**Comment by whit537** [comment]
P.S. May I make you a repo contributor so you can commit directly to this PR branch? :)

**Comment by yifeiwu** [comment]
Sure thing!

**Comment by whit537** [comment]
Awesome, welcome aboard! :dancer: 

I've sent you an invite, and I've made an onboarding ticket for you at https://github.com/gratipay/inside.gratipay.com/issues/336.

**Comment by yifeiwu** [comment]
Is this 
```
def test_splh_suggests_five_dollars_and_ten_on_100(self):
    assert pricing.suggested_payment(100) == (D('5'), D('10'))
```
supposed to look like this?

```
def test_splh_suggests_five_dollars_and_ten_on_100(self):
    assert suggested_payment_low_high(100) == (D('5'), D('10'))
```

**Comment by whit537** [comment]
@yifeiwu No. There are two suggestion functions in the pricing module. One is used on the pricing page, the other in the so-called "global call to action (cta)," the big annoying gold banner that is supposed to be shown at the top of the page when one uses Gratipay without giving to Gratipay. Grep for `suggested_payment` and `suggested_payment_low_high` to see them in action.

**Comment by yifeiwu** [comment]
@whit537 Let me clarify. There's two functions--`suggested_payments` that returns a single value, while the `suggested_payment_low_high` returns two values. If we're testing the global cta method via `test_splh_suggests_five_dollars_and_ten_on_100(self)`, 
Shouldn't the test be calling the splh method instead of the `suggested_payment` method which would never return the 2 values being tested by the assert statement?

**Comment by whit537** [comment]
You're right! Sorry, I read your comment wrong. :)

I've force-pushed a new "failing tests" commit to this branch that exercises the right function in the `splh` tests.

**Comment by yifeiwu** [comment]
Hmm, the payment tests pass on my end but there's failing tests elsewhere on this branch.

**Comment by rohitpaulk** [comment]
Looks like someone added a file `get-pip.py`, and pyflakes is complaining about stuff in there.

```
env/bin/pyflakes *.py bin gratipay tasks tests
get-pip.py:110: 'setuptools' imported but unused
get-pip.py:120: 'wheel' imported but unused
make[1]: *** [pyflakes] Error 1
```

 I'm going to remove that and push to this branch..

**Comment by rohitpaulk** [comment]
@yifeiwu - Do you think this is ready for review? If so, please add the [Review](https://github.com/gratipay/gratipay.com/labels/Review) label to it :)

**Comment by yifeiwu** [comment]
@rohitpaulk Thank you so much! I've been puzzled about the build error. Kudos!

**Comment by yifeiwu** [comment]
@whit537 Chad, this looks good on my end. Close and merge?

**Comment by whit537** [comment]
Awesome, thanks @yifeiwu! :dancer:

**Comment by yifeiwu** [comment]
Big thanks to @rohitpaulk, couldn't have figured out that error otherwise!

**Pull request merged**
