### PR TITLE
Browse payments

### PR DESCRIPTION
**Pull request by kaguillera**
This is the PR for browsing the company payments for the new front page that @whit537 is currently working on. 

NB. This is blocked by a PR for fake data that I am working on. 

-----------

## Todo

- [ ] change base back to master

### CODE REVIEW

**Comment by kaguillera** [comment]
OK as usual for me I have some git issues that I will work out tomorrow ☹️

**Comment by whit537** [comment]
I'm switching to using `id` instead of `uuid` so that we can have public pages for each payment, and then we'll rename `uuid` to `secret` and use it to protect access to the invoice.

**Comment by whit537** [comment]
But I'm in the weeds on switching to a proper pytest fixture for `image.fixture` because my hack kills pdb in wrapped test functions.

**Comment by whit537** [comment]
>The following pytest features do not work, and probably never will due to different design philosophies:
>
> - Fixtures 

https://docs.pytest.org/en/latest/unittest.html#mixing-fixtures

**Comment by whit537** [comment]
screen shot 2017-10-05 at 1 04 45 pm

**Comment by whit537** [comment]
screen shot 2017-10-05 at 1 11 38 pm

**Comment by rohitpaulk** [comment]
The 'invested $x in open source' looks repetitive, no? 

How would it look if we dropped that and just showed '$2000 • 3 minutes ago • "Greetings"'?

**Comment by whit537** [comment]
Good call! :-)

screen shot 2017-10-05 at 1 15 43 pm

**Comment by whit537** [comment]
Okay! I have something was 67606a0841be580993a97d6b38ded569711c3f20

**Comment by whit537** [comment]
Off in the weeds again chasing a bug in test_pages.py, trying to hit Braintree from exchanges?!

**Comment by whit537** [comment]
Weird test interaction? Running anon alone passes, but new_participant or on_the_fence in isolation fails.

**Comment by whit537** [comment]
Yeah weird interaction, running all together passes. ¯\\\_(ツ)\_/¯

**Comment by whit537** [comment]
Let's get Travis green and then I'll push my second commit.

**Comment by whit537** [comment]
Third commit will add to homepage and I think we're done! 😍

**Comment by whit537** [comment]
Starting to push the video down. 🤔 

screen shot 2017-10-05 at 3 12 11 pm

**Comment by whit537** [comment]
screen shot 2017-10-05 at 3 40 53 pm

**Comment by mattbk** [comment]
I like it. Also works for me here.

**Comment by whit537** [comment]
Planning to merge per @mattbk's approval.

**Comment by whit537** [comment]
Merge approval because @mattbk is traveling: [slack](https://gratipay.slackarchive.io/gratipay/page-100/ts-1507322395000302).

**Pull request merged**
