### PR TITLE
Only start a browser if we have to

### PR DESCRIPTION
**Pull request by whit537**
This saves time when running a subset of tests that don't require a browser.

### CODE REVIEW

**Comment by nashe** [comment]
Looks good to me! May I merge or somebody have a suggestion?

**Comment by nashe** [comment]
(I'll do it after #4113 is merged)

**Comment by whit537** [comment]
👍

**Comment by whit537** [comment]
Rebased on master, previously 9960f97c8788c28223b4d05172a32565aad6fcff.

**Comment by whit537** [comment]
Merging per @nashe above.

**Pull request merged**
