### PR TITLE
Send email for Terms notification

### PR DESCRIPTION
**Pull request by whit537**
Includes a script that we can reuse next time we need to send out a transactional email to everyone.

### CODE REVIEW

**Comment by whit537** [comment]
Still in process. I wanna write some tests.

```
[gratipay] $ run defaults.env local.env send-branch-email
Usage: /Users/whit537/personal/gratipay/gratipay.com/env/bin/send-branch-email [username|all]
[gratipay] $
```

**Comment by whit537** [comment]
Ready for review @JessaWitzel @mattbk!

**Comment by whit537** [comment]
Gosh, I guess I should actually test the mail though. Harumph.

**Comment by JessaWitzel** [comment]
Looks good to me! As an exercise, here is how I would have written it. It's interesting how tone differs so much depending on who is writing everything. 

Hello!

We are so glad that you have joined us over at Gratipay! We know you do not receive many emails like this from us, and that is intentional. We certainly don't want to spam you because when we do email you we want you to know that it's important, plus that's just annoying.

Today we want to let you know that we have revised our Terms of Service, that all important document that governs your continued usage. If you no longer use your Gratipay account, you can <a href="https://gratipay.com/about/me/settings/close">close it here</a>.
If you want to continue to use Gratipay, please <a href="https://gratipay.news/from-teams-to-projects-45c46718507b">learn about our new Terms</a> as soon as you can.
 
 Have a great day!

**Comment by clone1018** [comment]
Would be awkward to have a username of `all` :)

**Comment by whit537** [comment]
:-P

The `username` switch is there for testing, I don't anticipate using this to mail just one participant.

**Comment by mattbk** [comment]
Please don't wait for a review from me--I am unqualified for this one.

**Comment by whit537** [comment]
Gonna see about mailing myself with this one ...

**Comment by whit537** [comment]
That means AWS locally!

**Comment by whit537** [comment]
Hey! I already have AWS keys commented out in my local.env. They're labeled "emails_development AWS user." Let's give that a shot

**Comment by whit537** [comment]
Rebased, was 03d3081fa4e4ef1207adcb0da9f618899719dd00.

**Comment by whit537** [comment]
```
[gratipay] $ run defaults.env local.env queue-branch-email whit537
Okay, just whit537.
1
spotcheck: chad@zetaweb.com (whit537=1451)
queuing for chad@zetaweb.com (whit537=1451)
[gratipay] $
```

Now where did it go? :)

**Comment by whit537** [comment]
Oh! This just enqueues it, another process has to dequeue it.

**Comment by whit537** [comment]
Those failures tho ... 😕

**Comment by whit537** [comment]
> Thanks for signing up with Amazon Web Services. Your services may take up to 24 hours to fully activate. If you’re unable to access AWS services after that time, here are a few things you can do to expedite the process:

screen shot 2016-12-16 at 2 01 51 pm

**Comment by whit537** [comment]
That's trying to sign up for a new account because I don't have the login handy for our existing account (coffee shop).

**Comment by whit537** [comment]
Both failing on `iter_payday_events`.

```
=================================== FAILURES ===================================
_____________________ TestHistory.test_iter_payday_events ______________________
self = <test_history.TestHistory testMethod=test_iter_payday_events>
    def test_iter_payday_events(self):
        now = datetime.now()
        Payday().start().run()
    
        Enterprise = self.make_team(is_approved=True)
        self.obama.set_payment_instruction(Enterprise, '10.00')  # >= MINIMUM_CHARGE!
        for i in range(2):
            with patch.object(Payday, 'fetch_card_holds') as fch:
                fch.return_value = {}
                Payday.start().run()
            self.db.run("""
                    UPDATE paydays
                       SET ts_start = ts_start - interval '1 week'
                         , ts_end = ts_end - interval '1 week';
                    UPDATE payments
                       SET timestamp = "timestamp" - interval '1 week';
                    UPDATE transfers
                       SET timestamp = "timestamp" - interval '1 week';
                """)
    
    
        obama = P('obama')
        picard = P('picard')
    
        assert obama.balance == D('0.00')
        assert picard.balance == D('20.00')
    
        Payday().start()  # to demonstrate that we ignore any open payday?
    
        # Make all events in the same year.
        delta = '%s days' % (364 - (now - datetime(now.year, 1, 1)).days)
        self.db.run("""
                UPDATE paydays
                    SET ts_start = ts_start + interval %(delta)s
                      , ts_end = ts_end + interval %(delta)s;
                UPDATE payments
                    SET timestamp = "timestamp" + interval %(delta)s;
                UPDATE transfers
                    SET timestamp = "timestamp" + interval %(delta)s;
            """, dict(delta=delta))
    
        events = list(iter_payday_events(self.db, picard, now.year))
        assert len(events) == 7
        assert events[0]['kind'] == 'totals'
        assert events[0]['given'] == 0
        assert events[0]['received'] == 20
        assert events[1]['kind'] == 'day-open'
        assert events[1]['payday_number'] == 2
        assert events[2]['balance'] == 20
        assert events[-1]['kind'] == 'day-close'
        assert events[-1]['balance'] == 0
    
        events = list(iter_payday_events(self.db, obama))
        assert events[0]['given'] == 20
>       assert len(events) == 11
E       AssertionError: assert 9 == 11
E        +  where 9 = len([{'given': Decimal('20.00'), 'kind': 'totals', 'received': 0}, {'balance': Decimal('0.00'), 'date': datetime.date(2016...: Decimal('0.61'), 'participant...'10.00'), 'recorder': None, 'balance': Decimal('10.00'), 'ref': None, 'id': 10}, ...])
tests/py/test_history.py:93: AssertionError
```

**Comment by whit537** [comment]
Restarted.

**Comment by whit537** [comment]
Same failure!

**Comment by whit537** [comment]
Got it locally.

**Comment by whit537** [comment]
Interesting that it passed before the rebase at https://github.com/gratipay/gratipay.com/pull/4232#issuecomment-267663666.

https://github.com/gratipay/gratipay.com/commits/03d3081fa4e4ef1207adcb0da9f618899719dd00

**Comment by whit537** [comment]
Does the old commit still work?

**Comment by whit537** [comment]
No!

**Comment by whit537** [comment]
Maybe something to do with https://github.com/gratipay/inside.gratipay.com/issues/942#issuecomment-267460761? Or variability due to end of the month/year closeness?

**Comment by whit537** [comment]
> Or variability due to end of the month/year closeness?

Yeah, I get green if I manually set my clock back a month.

screen shot 2016-11-18 at 3 19 03 pm

**Comment by whit537** [comment]
First gear! 😞

**Comment by whit537** [comment]
Base changed temporarily to pick up #4236.

**Comment by whit537** [comment]
Builds restarted.

**Comment by whit537** [comment]
Green!

**Comment by whit537** [comment]
Okay, so can I actually see this now?

**Comment by whit537** [comment]
Yesssssssssssss! 💃 

screen shot 2016-12-19 at 5 10 10 pm

**Comment by whit537** [comment]
I'm messing with the copy, with https://github.com/gratipay/gratipay.com/pull/4232#issuecomment-267198801 in mind. I'm wrestling with Gmail's signature comprehension robot.

screen shot 2016-12-19 at 5 24 43 pm

**Comment by whit537** [comment]
Alright @JessaWitzel, submitting this for final review. You okay with this copy and the script I added?

screen shot 2016-12-19 at 6 06 19 pm

**Comment by whit537** [comment]
I'm not sure how Little Caesar infected our email.

screen shot 2016-12-19 at 6 11 03 pm

2fc3d37e-cf4a-11e5-80d1-bbd808160d2d

**Comment by whit537** [comment]
Okay, Google. Now you're just messing with me.

screen shot 2016-12-19 at 6 14 26 pm

**Comment by clone1018** [comment]
@whit537 did you find out how pizza pizza got there?

**Comment by whit537** [comment]
No.

**Comment by whit537** [comment]
Hopefully later today! :-)

**Comment by JessaWitzel** [comment]
@whit537 I like the copy. !m

**Comment by whit537** [comment]
Yay! Okay, gonna see about reducing our pizza quotient, and then get this out there!

**Comment by mattbk** [comment]
Did you remove the pizza?

**Comment by whit537** [comment]
Nope! Lessee here ...

**Comment by whit537** [comment]
Dumping to console is a great way to test text/plain. 👍

```
[gratipay] $ run defaults.env local.env dequeue-emails
pid-75004 thread-140735128666880 (MainThread) Won't log to Sentry (SENTRY_DSN is empty).
pid-75004 thread-140735128666880 (MainThread) AWS SES is not configured! Mail will be dumped to the console here.
------------------------------------------------------------------------------
To:       whit537 <chad+localhost@zetaweb.com>
Subject:  Revised Terms of Service
Body:

    Greetings!

    Greetings!

    We have revised our Terms of Service, that all-important
    document that governs your continued use of Gratipay. If you
    no longer use your Gratipay account, you can close it here:

      https://gratipay.com/about/me/settings/close

    If you want to continue to use Gratipay, please learn about our
    new Terms as soon as you can:

      https://gratipay.news/from-teams-to-projects-45c46718507b

    Thanks, and have a great day!

    Something not right? Reply to this email for help.

    ----

    Sent by Gratipay, LLC, https://gratipay.com/
    716 Park Road, Ambridge, PA, 15003, USA

------------------------------------------------------------------------------
[gratipay] $
```

**Comment by whit537** [comment]
Starting to build up some nice tools here. :)

```
[gratipay] $ run defaults.env local.env queue-branch-email whit537
Okay, just whit537.
1
spotcheck: chad+localhost@zetaweb.com (whit537=101)
queuing for chad+localhost@zetaweb.com (whit537=101)
[gratipay] $ run defaults.env local.env list-email-queue
   1    101 branch           whit537                  chad+localhost@zetaweb.com
pid-75053 thread-140735128666880 (MainThread) Won't log to Sentry (SENTRY_DSN is empty).
pid-75053 thread-140735128666880 (MainThread) AWS SES is not configured! Mail will be dumped to the console here.
[gratipay] $ run defaults.env local.env dequeue-emails
```

**Comment by whit537** [comment]
The base email template [includes](https://github.com/gratipay/gratipay.com/blob/2024/emails/base.spt#L25) `Greeting!` in the text/plain section. 👍  🍕

**Comment by whit537** [comment]
Okay! Ready to go?

**Comment by whit537** [comment]
Do we hold this until next week, or mail it now?

**Comment by whit537** [comment]
Last call for review here. When should we schedule this for? Jan 3, or Jan 10 to give people time to dig out of holiday email in their inbox?

**Comment by JessaWitzel** [comment]
My vote is January 5th to give people time to dig out. January 10th is good too. :)

**Comment by whit537** [comment]
Okay, currently planning to send this tomorrow (Jan 5).

**Comment by whit537** [comment]
Let's go!

**Comment by whit537** [comment]
So what's the process here going to be? Something like:

- [ ] Merge to `master`.
- [ ] Deploy to Heroku; we don't need anything here in the web dyno, but we do want it in a one-off dyno for ...
- [ ] `heroku run bash`
- [ ] Test it out with just me.
- [ ] Run it! `queue-branch-email all 2> queue.log` should take less than 30 second.
- [ ] Dequeuing should be handled by the web dyno, and should take about 45 minutes.
- [ ] Monitor the dequeuing with `list-email-queue`.
- [ ] Empty out `emails/branch.spt`, commit it to `master`, and push to both Heroku and GitHub.

**Comment by whit537** [comment]
It's go time!

**Comment by whit537** [comment]
Zorb. The base for this was #4236, not master ... so I guess we're going to land that, too! :-)

**Comment by whit537** [comment]
Proceeding now that https://github.com/gratipay/gratipay.com/pull/4236 is in.

**Comment by whit537** [comment]
```
~ $ queue-branch-email kaguillera
Okay, just kaguillera.
1
spotcheck: [] (kaguillera=400325)
   1 queuing for [] (kaguillera=400325)
~ $ queue-branch-email whit537
Okay, just whit537.
1
spotcheck: chad@zetaweb.com (whit537=1451)
   1 queuing for chad@zetaweb.com (whit537=1451)
~ $
```

**Comment by whit537** [comment]
```
~ $ list-email-queue 
   1 400325 branch           kaguillera               []
   2   1451 branch           whit537                  chad@zetaweb.com
pid-19 thread-139747792283456 (MainThread) AWS SES is configured! We'll send mail through SES.
~ $
```

**Comment by whit537** [comment]
Okay! Ready? Here we go ...

**Comment by whit537** [comment]
screen shot 2017-01-06 at 1 34 27 pm

**Comment by whit537** [comment]
That was the test message, which I received. Not sure why I'm getting "via amazonses.com" but I'm not going to sweat it.

**Comment by whit537** [comment]
```
~ $ queue-branch-email all
Are you ready? [y/N]y
Are you REALLY ready? [y/N]y
... ? [y/N]y
Okay, you asked for it!
5358
spotcheck: []
spotcheck: []
spotcheck: []
spotcheck: []
spotcheck: []
But really actually tho? I mean, ... seriously? [y/N]
```

**Comment by whit537** [comment]
http://docs.aws.amazon.com/ses/latest/DeveloperGuide/e-faq-bn.html
http://docs.aws.amazon.com/ses/latest/DeveloperGuide/best-practices-bounces-complaints.html

**Comment by whit537** [comment]
> If you have an old list that you haven’t emailed to in a while, don’t email to that list through any provider that limits your bounce rates (which includes Amazon SES), unless you’ve verified the state of the addresses (e.g., by checking login activity on your site, purchase history, etc.). Otherwise, you may incur a lot of bounces from old unused email addresses while you try to clean your list, and you risk being blocked by both ISPs and Amazon SES.

https://media.amazonwebservices.com/AWS_Amazon_SES_Best_Practices.pdf

**Comment by whit537** [comment]
> Only send emails to recipients who have interacted with your site recently (for example, within the last 180 days).

> Do not use Amazon SES as a way to clean your recipient list.

http://docs.aws.amazon.com/ses/latest/DeveloperGuide/best-practices-recipients.html

**Comment by whit537** [comment]
DKIM was enabled for our domain but not for the support@gratipay.com address. I've enabled it for the address.

**Comment by whit537** [comment]
Fixed! 👍 

screen shot 2017-01-06 at 2 11 01 pm

**Comment by whit537** [comment]
> But, what if up to this point you haven’t been tracking those things?  You have a list of addresses that you have acquired over the years, but you don’t have a mechanism in place to know when each one last interacted with you, or perhaps you don’t have a record of how each of those addresses got into your system in the first place.  Maybe you haven’t even been removing addresses that bounce or complain.  Ouch!  This is going to be a problem!

https://aws.amazon.com//blogs/ses/never-send-to-old-addresses-but-what-if-you-have-to/

**Comment by kaguillera** [comment]
Just a suggestion 

https://pypi.python.org/pypi/validate_email

**Comment by whit537** [comment]
@kaguillera What are the details of their implementation? How do they determine if an address "really exists"?

**Comment by whit537** [comment]
Alright, so we definitely need to start doing this. But how much do we need to get done before sending out these emails?

**Comment by whit537** [comment]
I started poking at AWS SNS for notifications. Supposedly we can use that to `POST` to an endpoint on our website. We could use that to collect feedback into an `email_status_queue` and then process that to unverify bad emails. But that's a significant chunk of work and I don't want to block this on that.

**Comment by whit537** [comment]
This is tough to test because we need a good email to verify it with Gratipay, but then how do make it subsequently bounce in order to test that case?

I tried with https://temp-mail.org/en/ and https://requestb.in/ for the webhook `POST`. I was able to receive a subscription confirmation message, but no actual SES delivery notifications, let alone bounce/complaint.

**Comment by whit537** [comment]
We can also configure SNS to dump to SQS instead.

> You can configure the Amazon SQS message retention period to a value from 1 minute to 14 days. The default is 4 days. Once the message retention limit is reached, your messages are automatically deleted.

https://aws.amazon.com/sqs/faqs/#limits-restrictions

**Comment by mattbk** [comment]
> This is tough to test because we need a good email to verify it with Gratipay

You can add it to the database by hand.

**Comment by mattbk** [comment]
http://stackoverflow.com/a/31510470/2152245

**Comment by whit537** [comment]
"[Do Things that Don't Scale](http://paulgraham.com/ds.html)" O.o

**Comment by whit537** [comment]
I created a user in Google Apps, used it to verify an email for a Gratipay test account, and then deleted the user. Google [allows](https://support.google.com/a/answer/1397578?hl=en) restoring users for up to five days, though, so I'm not sure when we'd start getting a hard bounce. Not seeing one yet ...

**Comment by whit537** [comment]
Seeing it from personal email. Trying via SES now ...

**Comment by whit537** [comment]
Got it! Bounce notification via HTTPS. Once again I needed to configure for the address and not just the domain (as with DKIM above). Still not seeing it in the SQS queue, though ...

screen shot 2017-01-06 at 4 36 59 pm

**Comment by whit537** [comment]
P.S. and FTR, the easiest way to test is with a Google Apps "Group," because it can route to an existing account so you don't have to do a password and login dance in order to receive mail. It may also be instantly deleted whereas full user accounts are not.

**Comment by whit537** [comment]
Based on [these docs](http://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-subscribe-queue-sns-topic.html) I redid the link from SNS to SQS on the SQS side.

**Comment by whit537** [comment]
Blam!

screen shot 2017-01-06 at 5 12 58 pm

**Comment by whit537** [comment]
Alright, so here's what I propose:

- We update the participants [query](https://github.com/gratipay/gratipay.com/blob/2034/gratipay/utils/emails/queue_branch_email.py#L50-L57) to only select those who have signed in (`session_expires`) or show up in `payments` or `exchanges` within the past [180 days](https://github.com/gratipay/gratipay.com/pull/4232#issuecomment-270976120).
- We mail all of them, tracking bounces in SQS.
- We manually retrieve bad addresses from the queue, and drop them to unverified in the database.
- We reticket proper bounce handling with a webhook back to https://gratipay.com/.

Given that it is now after 5pm on Friday, it looks like we are going to be sending next week after all. :-)

Will move to a new PR since this is closed ...

**Pull request merged**
