### PR TITLE
Rip out READMEs after all

### PR DESCRIPTION
**Pull request by whit537**
Post-#4151. READMEs are too much work to keep up with and keep secure, especially when we want to add 30+ more package managers.

### CODE REVIEW

**Comment by whit537** [comment]
Ping @aandis etc. for review.

@aandis I think READMEs are too much trouble after all. 😞

**Comment by aandis** [comment]
meh. I kinda feel bad, so much work went into it. 😞  I am gonna review this tonight.

**Comment by whit537** [comment]
Well, but think about all the work we're saving ourselves by not committing to maintaining and securing README wrappers for 30+ package managers. :-0

**Comment by aandis** [comment]
Rebased on master, previous head was 74c43e3072da19c6b7b030e09cd12215831abee6

**Comment by aandis** [comment]
@whit537 this looks good to me. One minor improvement would be to define [this](https://github.com/gratipay/gratipay.com/pull/4211/files#diff-5a2a4c1e1953984d65458fe740fbaa78R48) [here](https://github.com/gratipay/gratipay.com/blob/74c43e3072da19c6b7b030e09cd12215831abee6/gratipay/sync_npm/__init__.py) instead of passing it [over](https://github.com/gratipay/gratipay.com/blob/74c43e3072da19c6b7b030e09cd12215831abee6/gratipay/sync_npm/serialize.py#L100) and [over](https://github.com/gratipay/gratipay.com/blob/74c43e3072da19c6b7b030e09cd12215831abee6/gratipay/sync_npm/upsert.py#L48)

**Comment by whit537** [comment]
> One minor improvement would be to define [this](https://github.com/gratipay/gratipay.com/pull/4211/files#diff-5a2a4c1e1953984d65458fe740fbaa78R48) [here](https://github.com/gratipay/gratipay.com/blob/74c43e3072da19c6b7b030e09cd12215831abee6/gratipay/sync_npm/__init__.py) instead of passing it [over](https://github.com/gratipay/gratipay.com/blob/74c43e3072da19c6b7b030e09cd12215831abee6/gratipay/sync_npm/serialize.py#L100) and [over](https://github.com/gratipay/gratipay.com/blob/74c43e3072da19c6b7b030e09cd12215831abee6/gratipay/sync_npm/upsert.py#L48)

@aandis The issue is that it [depends](https://github.com/gratipay/gratipay.com/blob/74c43e3072da19c6b7b030e09cd12215831abee6/gratipay/sync_npm/cli.py#L54) on state we're [loading](https://github.com/gratipay/gratipay.com/blob/74c43e3072da19c6b7b030e09cd12215831abee6/gratipay/sync_npm/cli.py#L44) from `wireup`, so we can't define it globally as we can with `log`. Do you see a way around that?

> this looks good to me.

Cool. May I let you hit the merge button when you're ready? :-)

**Comment by aandis** [comment]
> Do you see a way around that?

`sentrified(func, env)`?

**Comment by whit537** [comment]
@aandis How about cb1a53f998727b70e3f2f875e04498b479c87164? :-)

**Comment by whit537** [comment]
(We'll see if Travis likes it ...)

**Comment by aandis** [comment]
@whit537 what's the next step in this? I'll try to find some time this weekend.

**Comment by whit537** [comment]
[Deployed](http://gratipay.slackarchive.io/gratipay/-/1480708294.000904/1480710330.001005/1480710114001001/)!

**Comment by whit537** [comment]
> what's the next step in this?

This is part of the "Pay for any package on npm" project (https://github.com/gratipay/gratipay.com/issues/4148), but we need to land "[Relax Open Work Requirement](https://github.com/orgs/gratipay/projects/5?fullscreen=true)" (https://github.com/gratipay/inside.gratipay.com/issues/432) first.

**Pull request merged**
