### PR TITLE
Tinker with timing for Travis

### PR DESCRIPTION
**Pull request by whit537**
Trying to avoid spurious test failures.

https://travis-ci.org/gratipay/gratipay.com/builds/191469577

screen shot 2017-01-12 at 5 47 16 pm

### CODE REVIEW

**Comment by whit537** [comment]
Eh, @mattbk @nobodxbodon @kaguillera?

**Comment by mattbk** [comment]
Is it running one test before the previous test has finished?

**Comment by whit537** [comment]
> Is it running one test before the previous test has finished?

No, it's a webdriver test, so I guess we're not giving the browser enough time to load the list of participants to add before trying to click on the first one in the list.

**Comment by mattbk** [comment]
Let's try it and see.

**Pull request merged**
