### PR TITLE
Collect logos for promoting companies

### PR DESCRIPTION
**Pull request by whit537**
Part of https://github.com/gratipay/inside.gratipay.com/issues/1160.

- [x] fix vertical spacing
- [x] store image files in `.insert`—maybe share code w/ `Team.save_image`?
- [x] process upload in `homepage.py` (make sure it's optional)
- [x] serve images, I guess at `/browse/payments/%uuid/logo`?
- [x] ~~change base back to master~~

### CODE REVIEW

**Comment by whit537** [comment]
3a864977d53b3569318494f74621bd83cdf02868

hoe0zhyx2e

**Comment by whit537** [comment]
screen shot 2017-10-03 at 12 39 27 pm

**Comment by whit537** [comment]
Right! So ... I have this working manually, now working on adding it to the ttw and py tests.

**Comment by whit537** [comment]
Rebased, was 218eb575bfb65d23950f7d2944dd13da00bb60af.

**Comment by whit537** [comment]
Rebased, was 45c517fc250d8d586861851bfbf6f8f221be7ea0.

**Comment by whit537** [comment]
The line ∆ is huge because of fixture changes. :-/

**Comment by whit537** [comment]
Yay green! @dmk246 started looking at this today but we ran out of time. If anyone else has time before tomorrow, go for it! :D

cc: @JessaWitzel @mattbk @rohitpaulk @kaguillera @dowski et al.

**Comment by whit537** [comment]
Rebased onto #4671, was 223248d6202345d4f4398de8f529e24394bb1982.

**Comment by mattbk** [comment]
PNG uploading is working for me. 
GIF is not uploading (as expected).

**Comment by mattbk** [comment]
Cropping works.

**Comment by mattbk** [comment]
Looks good to me.

**Comment by whit537** [comment]
Planning to merge per @mattbk's approval.

**Comment by whit537** [comment]
Merge approval because @mattbk is traveling: [slack](https://gratipay.slackarchive.io/gratipay/page-100/ts-1507322395000302).

**Comment by whit537** [comment]
Rebased, was f86b304edd1a10c3b637bde6781e474931f2257a.

**Comment by whit537** [comment]
Dropping back to $10,000 in 10 days for prelaunch campaign.

screen shot 2017-10-06 at 5 58 36 pm

If we can't raise $10,000 in 10 days from our biggest fans then we're deluded.

**Pull request merged**
