### PR TITLE
Don't send "Greetings Program" in text emails

### PR DESCRIPTION
**Pull request by rohitpaulk**

### CODE REVIEW

**Comment by clone1018** [comment]
Can't we do Greetings, {slug}?

**Comment by whit537** [comment]
`Greetings, {program}!` :-P

I had thought it was a nice touch for people reading `text/plain`, who are likely to get the Tron reference. We can do away with it though if we're trying to professionalize.

**Comment by rohitpaulk** [comment]
I opened the PR coz of two support requests, I'll paste the links here later. (On phone now)

**Comment by whit537** [comment]
How about just "Greetings!"?

I'm fine to merge if you are.

**Comment by whit537** [comment]
> I opened the PR coz of two support requests, I'll paste the links here later. (On phone now)

Ah, gotcha.

!m @rohitpaulk

**Pull request merged**
