### PR TITLE
add schema and Python for countries

### PR DESCRIPTION
**Pull request by whit537**
&#x2B11; #3994

&#x2B11; #3976

&larr; #3998 — #4000 &rarr;

##### Punchlist

- [x] remove `code3` and `name` fields: https://github.com/gratipay/gratipay.com/pull/3999#issuecomment-217748706
- [x] take #4008 on board
- [ ] remake against `master` once #3998 lands

### CODE REVIEW

**Comment by whit537** [comment]
Discovered in #4005 that the official country names aren't suitable for display. E.g., "United States of America (the)" should be "United States" or "the United States" depending on context.

**Comment by whit537** [comment]
Actually, it [turns out]((https://github.com/gratipay/gratipay.com/pull/4005#issuecomment-216083680)) that we already have good names in `locale.countries` ! 👍 

So do we need the names in the `countries` table at all? Flags (788d92d19817260bc356f0961f5c605d4cbc52ec), Babel, and pretty much everything I'm finding uses the two-letter country code. Should we simplify down to a single column? Will @kaguillera let us use the 2-letter country code as the primary—and only—key?

**Comment by kaguillera** [comment]
Yes...that is cool if that is what everything uses

**Comment by whit537** [comment]
> Yes...that is cool if that is what everything uses

Hah! :D Well, on the other hand, this would mean updating all of the subsequent PRs that depend on `country_id`.

screen shot 2016-05-01 at 8 50 44 pm

**Comment by kaguillera** [comment]
I would suggest that we do that now before we have to do that further down the line...is that difficult or too much work??

**Comment by whit537** [comment]
@kaguillera I think we're okay with our own `id` field, and alpha-2 as a separate field. Do you see anything actively bad about that approach?

**Comment by kaguillera** [comment]
No...I am more inclined to that approach.

**Comment by whit537** [comment]
Rebased on #3998 at 049bd48, previous head was fd1ca952020be35c1b9db7c83aa97cd114717625.

**Comment by whit537** [comment]
We can probably drop the `name` field and maybe even `code3` since we'll be using `code2` to index into Babel for names. We'll do the same for flags, and likely any other purpose in the foreseeable future. Holding `name` especially in our database seems redundant and confusing, since we're not actually using that data in the UI as one might expect.

**Comment by whit537** [comment]
Okay, I roughed in #4008. We should look through that for insight on changes we may want to make here—it may make sense to use `code2` more thoroughly after all.

**Comment by whit537** [comment]
Okay, removed `name` and `code3` in 133388ae1b5634368883865b38a47feec5e56ea3. We're not using `name` anywhere, and `code3` was only used in the database. @kaguillera and I decided to keep the separate `id` field on principle. ☺️

**Comment by whit537** [comment]
Remade as #4027.

**Pull request closed without merging**
