### PR TITLE
Improve giving page - part 1

### PR DESCRIPTION
**Pull request by rohitpaulk**
This is cleanup before fixing #3107.

### CODE REVIEW

**Comment by rohitpaulk** [comment]
Before:
screenshot from 2015-04-11 00 43 39

After:
screenshot from 2015-04-11 00 42 54
screenshot from 2015-04-11 00 42 58
screenshot from 2015-04-11 00 43 02

**Comment by Changaco** [comment]
I don't see why you're using server-side tabs. On the history page it's because there is too much data to send at once, but here it's not the case.

**Comment by rohitpaulk** [comment]
@Changaco - Hmm, yh. I was thinking of expanding each row in the table to a bigger item with the user's avatar + buttons to edit or cancel, so wanted to reduce the amount of info we show at a time on the page.

You're right, client side tabs would definitely make more sense.

**Comment by whit537** [comment]
wfm

!m @rohitpaulk

**Pull request merged**
