### PR TITLE
fix layout

### PR DESCRIPTION
**Pull request by whit537**
#### Rough

- [x] header
- [x] footer
- [x] support gratipay notice
- [x] content pages like about pages
- [x] two-column things like charts and FAQ
- [x] profiles
- [x] community pages
- [x] all communities listing `/for/`

#### Finish

- [x] penny background
- [x] ~~signing out fails?~~ #2940
- [x] clean up logo + stats in header
- [x] figure out column story
- [x] Your Weekly Gift
- [x] sub nav
- [x] root out `slug == none`
- [x] clean up `sign-in`/`you-are` area

#### Finish Finish

- [x] min height (no empty space below footer)
- [x] refactor SCSS
- [x] harmonize markup/scss between homepage and inside pages
- [x] clean up error pages
- [x] clean up Giving
- [x] clean up Receiving
- [x] clean up History
- [x] clean up Account
- [x] clean up Events
- [x] clean up elsewhere profiles
- [x] clean up elsewhere teams
- [x] fix that gosh darn "Sign Out" button in the #header
- [x] notifications
- [x] "upgrade browser" notice
- [x] cross-browser review

#### Finish Finish Finish

- [x] i18n review
- [x] credit card & bank account forms
- [x] make giving widget in sidebar ~~AWESOME~~ okay
- [x] join/leave sidebar on community pages
- [x] responsiveness
- [ ] cross-browser review

#### Punchlist

 - [ ] "return" doesn't work from inside the `your-tip` `<input>`
 - [ ] padding is off in `your-tip` `<input>`, if I select with the mouse and go down then the text shifts

### CODE REVIEW

**Comment by rohitpaulk** [comment]
All of this looks great. What's left here?

**Comment by Changaco** [comment]
I think we're waiting for @whit537 to realize that this is good enough to be merged.

**Comment by whit537** [comment]
I'll get there, I'll get there ...

**Comment by whit537** [comment]
- [ ] fix subtle styling regressions on homepage

Old:

screen shot 2015-01-04 at 5 14 41 pm

New:

screen shot 2015-01-04 at 5 13 36 pm

**Comment by whit537** [comment]
- [ ] remove space between homepage and about links in top nav at low res (the reason for the space at higher res is alignment with the main copy)

screen shot 2015-01-04 at 5 19 57 pm

**Comment by whit537** [comment]
- [ ] "About" content should start above the fold on mobile. This means reworking the nav somehow.

screen shot 2015-01-04 at 5 48 32 pm

**Comment by whit537** [comment]
- [ ] Explore is crowded on mobile

screen shot 2015-01-04 at 6 05 30 pm

**Comment by whit537** [comment]
There's a few other things I want to flag, I'll be back ...

**Comment by whit537** [comment]
> Is this explained by different Python minor versions?

Yes. I upgraded to 2.7.9 locally and now I have `p.__dict__`. We're using 2.7.3 in production atm so I guess we should upgrade before landing this PR.

**Comment by whit537** [comment]
@clone1018 points out that only 5% of our users are on mobile, but they're our most important users, people like @weallhave24hrs and @renaantosz. We've got a sampling bias, in other words. We need to look great on mobile.

**Comment by whit537** [comment]
http://bradfrost.com/blog/post/atomic-web-design/
http://alistapart.com/article/responsive-comping-obtaining-signoff-with-mockups

**Comment by whit537** [comment]
So far Atomic Web Design is what I resonate most with for organizing a design system. I just don't get the [SMACSS categorization](https://smacss.com/book/categorizing). But *anything* is better than what we have now.

screen shot 2015-01-04 at 11 23 46 pm

**Comment by whit537** [comment]
- [ ] invert media queries (mobile first, special-case the wider layouts)

**Comment by whit537** [comment]
- [ ] reorganize scss

**Comment by Changaco** [comment]
@whit537 This PR is already too big, please stop holding it over details, merge it and make another PR to reorganize the SCSS.

**Comment by whit537** [comment]
> This PR is already too big, please don't hold it over details, merge it and make another PR to reorganize the SCSS.

Yeah, sorry. If this PR goes out as it is now, I'm going to be really embarrassed about how bad it is on mobile (I don't see the problems as just "details"), and I feel like we're reaching a point where making it not suck on mobile requires some refactoring. :-/

**Comment by whit537** [comment]
> Over the 4 years we have slowly moved away from device specific breakpoints in favour of content specific breakpoints, i.e. adding a breakpoint when the content is no longer easy to consume.

http://responsivedesign.is/articles/why-you-dont-need-device-specific-breakpoints

**Comment by whit537** [comment]
> - Pick major breakpoints by starting small, then working up
> - Pick minor breakpoints when necessary
> - Optimize text for reading
> - Never completely hide content

https://developers.google.com/web/fundamentals/layouts/rwd-fundamentals/how-to-choose-breakpoints

**Comment by Changaco** [comment]
> Yeah, sorry. If this PR goes out as it is now, I'm going to be really embarrassed about how bad it is on mobile (I don't see the problems as just "details")

A few pixels out of place is definitely a detail, what I'm embarrassed about is the other 370 open issues we have. More specifically #469 is what I've been working on, and I can't fix it until this PR is merged. #2809 is also blocked, as is almost every other issue or PR that needs to modify the UI.

> I feel like we're reaching a point where making it not suck on mobile requires some refactoring. :-/

There was no need to refactor anything in order to fix the Explore page.

**Comment by techtonik** [comment]
Is there a list of pages to review? Can we generate complete sitemap without missing teeth?

**Comment by whit537** [comment]
> A few pixels out of place is definitely a detail
> There was no need to refactor anything in order to fix the Explore page.

We're looking at different things. I am seeing way more than a few pixels out of place on the Explore page.

> More specifically #469 is what I've been working on, and I can't fix it until this PR is merged. #2809 is also blocked, as is almost every other issue or PR that needs to modify the UI.

Fair enough. After diving in a bit on a refactor I admit that it's too much to add to this PR. I've started a new PR with my initial refactoring commits from last night, and have force-pushed those commits off of this branch. Go ahead and merge this when you're ready and I'll pick up on #3063.

**Comment by whit537** [comment]
> Is there a list of pages to review? Can we generate complete sitemap without missing teeth?

```
$ find www -name \*.spt
```

**Comment by Changaco** [comment]
Did a final visual review and sneaked in a fix for a small bug unrelated to this PR. Merging.

**Pull request merged**
