### PR TITLE
improves debugging

### PR DESCRIPTION
**Pull request by whit537**
Ping @rohitpaulk.

### CODE REVIEW

**Comment by rohitpaulk** [comment]
I don't think that we should merge this into master, can't we [run it on a backup](https://github.com/gratipay/gratipay.com/issues/3415#issuecomment-102496467)?

**Comment by whit537** [comment]
We could run this on a backup, sure. Don't you think we want this change, though? Making the tables permanent makes debugging easier in development and in production.

**Comment by rohitpaulk** [comment]
Ah, makes sense.

**Comment by rohitpaulk** [comment]
Tests passing, and I don't see any typos. Merging.

**Pull request merged**
