### PR TITLE
Refresh the README ... and Makefile

### PR DESCRIPTION
**Pull request by whit537**
- brush up the welcome header
- add a codebase overview
- move some sections around
- update the initial output and screenshot
- solidify `make test`
- drop bountysource badge

### CODE REVIEW

**Comment by whit537** [comment]
Ping @mattbk @rohitpaulk et al.! :-)

**Comment by whit537** [comment]
Best part:

screen shot 2017-08-25 at 5 48 20 pm

**Comment by buddiex** [comment]
Nice one... really helpful for new guys like me

**Comment by whit537** [comment]
Rebased, was e6288d91b9e01f48ec45df362bd0f8c995617c0e.

**Comment by whit537** [comment]
Ping @mattbk @kaguillera @EdOverflow for review?

**Comment by kaguillera** [comment]
LGTM.

**Comment by whit537** [comment]
💃

**Pull request merged**
