### PR TITLE
test helpers

### PR DESCRIPTION
**Pull request by whit537**
First PR carved off of #4077.

### CODE REVIEW

**Comment by whit537** [comment]
Ready for review, @nashe et al.! I'm gonna make a separate PR to switch the test suite to using the new helpers. Seems likely to clutter this up too much if it's on here.

**Comment by whit537** [comment]
New PR to use these helpers is #4093.

**Comment by nashe** [comment]
👍

**Comment by whit537** [comment]
@nashe If you're good with this, go ahead and click the big green merge button! 💃

**Pull request merged**
