### PR TITLE
Handles missing doc in npm change stream

### PR DESCRIPTION
**Pull request by kaguillera**
This is a PR for issue #4506. Please let me know if this is what you had in mind.

### CODE REVIEW

**Comment by kaguillera** [comment]
@whit537 ready for review

**Comment by whit537** [comment]
Rebased, was b2570f1028e750e69b62fd6670ba0d368f34514e.

**Comment by whit537** [comment]
@kaguillera If you're good with 864a8396bcf32ac3d7dd56bf971d9ce230ab28e9 I'm ready to go.

**Comment by kaguillera** [comment]
Make sense. Once it is green we can merge.

**Comment by whit537** [comment]
!m @dmk246 First merge! 😄 💃  🌻

**Pull request merged**
