### PR TITLE
Implement /on/npm/foo pages

### PR DESCRIPTION
**Pull request by whit537**
Part of #4148.

# Todo

- [x] squish double-header
- [x] hide anchor links icon on headings
- [x] syntax highlight code snippets
- [x] fix tests
- [x] attend to h3-h6
- [x] do something with images
- [ ] see about the broken img src on http://localhost:8537/on/npm/react-router/

# Test

From https://github.com/gratipay/gratipay.com/pull/4135#issuecomment-262672635:

http://localhost:8537/on/npm/async/
http://localhost:8537/on/npm/iframe-resizer/
http://localhost:8537/on/npm/mongoose/
http://localhost:8537/on/npm/nodemon/
http://localhost:8537/on/npm/react/
http://localhost:8537/on/npm/react-helmet/
http://localhost:8537/on/npm/react-modal/
http://localhost:8537/on/npm/react-redux/
http://localhost:8537/on/npm/react-router/
http://localhost:8537/on/npm/react-router-redux/
http://localhost:8537/on/npm/redux/
http://localhost:8537/on/npm/redux-thunk/
http://localhost:8537/on/npm/webpack/

------------------------

Whee! 💃 

screen shot 2016-10-20 at 3 23 57 pm

### CODE REVIEW

**Comment by whit537** [comment]
😮 

screen shot 2016-10-20 at 3 26 34 pm

**Comment by whit537** [comment]
"lol" —@kaguillera 

screen shot 2016-10-20 at 3 33 29 pm

**Comment by whit537** [comment]
Rebased and squashed, previous head was f77da78d5a565ed8d91538454eaeb679d0df549a.

**Comment by whit537** [comment]
https://github.com/npm/marky-markdown#command-line-usage

**Comment by whit537** [comment]
I want to move the payment widget to above the content area, full width. The sidebar would then only be for second-level nav where that exists.

**Comment by whit537** [comment]
```
[gratipay] $ echo '# Greetings, program!' | marky-markdown /dev/stdin
<h1 id="user-content-greetings-program" class="deep-link"><a href="#greetings-program">Greetings, program!</a></h1>
[gratipay] $
```

**Comment by whit537** [comment]
Alright, it's not going to be performant enough to make a heavy JSON API request *and* shell out to render markdown on every request for an `/on/npm/foo/` page.

**Comment by whit537** [comment]
npm gives us a big download at http://registry.npmjs.org/-/all (200 MB). I'm going to explore what's in there and think about how we might use that.

```
(Pdb) pp npm['aspen']
{u'author': {u'email': u'chad@zetaweb.com', u'name': u'Chad Whitacre'},
 u'description': u'A NodeJS web framework that makes the most of the filesystem.',
 u'dist-tags': {u'latest': u'1.1.0'},
 u'maintainers': [{u'email': u'chad@zetaweb.com', u'name': u'whit537'}],
 u'name': u'aspen',
 u'repository': {u'type': u'git',
                 u'url': u'https://github.com/zetaweb/aspen.js.git'},
 u'time': {u'modified': u'2013-02-15T16:10:08.600Z'},
 u'versions': {u'1.1.0': u'latest'}}
(Pdb)
```

**Comment by whit537** [comment]
That doesn't give us readme, but it gives us everything else we want: name, description, author, maintainers. If we shove that in a table, we can use time.modified to update, including refetching and reprocessing the readme.

**Comment by kaguillera** [comment]
👍  because so far http://npmsearch.com/ does not seem to give you the flexibility to search on specific fields.
The search input is search on all of the fields that they you are allowed to return. At least that is what is seems so far

**Comment by whit537** [comment]
Alright, circled the wagons IRL and decided to try out a local `npm` table, since it'll help this (with the processed readmes), and also search (#4145), and also keying by email (to help with `/on/npm/`).

**Comment by whit537** [comment]
Okay! Circling back here now that we have npm loaded locally. We have pages from local npm! Let's find an example with a readme synced ...

screen shot 2016-10-26 at 10 22 26 pm

**Comment by whit537** [comment]
Hmmm ... we trust marky-markdown to give us safe HTML, ya? 😳

screen shot 2016-10-26 at 10 28 40 pm

**Comment by kaguillera** [comment]
We will certainly need to verify that asap.

**Comment by whit537** [comment]
@kaguillera Well, I suppose npm trusts it, and ... we trust npm, right?

**Comment by kaguillera** [comment]
I guess

**Comment by whit537** [comment]
Rebased (was db4539b1a0469db85acf124df82466e8748a2cae).

**Comment by whit537** [comment]
I'm taking a backup so I can get processed readmes to work with.

**Comment by whit537** [comment]
Still downloading the backup. I have 96 in my local db from before, though they were processed using the old code so the headings are messed up:

screen shot 2016-11-25 at 1 08 06 pm

**Comment by whit537** [comment]
Needs CSS!

**Comment by whit537** [comment]
Backup downloaded! Loading ...

**Comment by whit537** [comment]
Selectables still has the double header, even though it doesn't [on npm](https://www.npmjs.com/package/selectables) others (underscore, async, aspen) don't on Gratipay/on/npm.

**Comment by whit537** [comment]
Crunch. Reprocessed selectables and it's still bad. I'm looking for another example to see if this is isolated or what ...

```
[gratipay] $ run defaults.env local.env sync-npm process-readmes
pid-56076 thread-140735121146624 (MainThread) Won't log to Sentry (SENTRY_DSN is empty).
processing selectables
[gratipay] $
```

**Comment by whit537** [comment]
Going through the packages listed at https://github.com/gratipay/gratipay.com/pull/4135#issuecomment-262672635 ...

Bad:

https://www.npmjs.com/package/iframe-resizer
https://www.npmjs.com/package/mongoose
https://www.npmjs.com/package/nodemon
https://www.npmjs.com/package/react
https://www.npmjs.com/package/react-modal
https://www.npmjs.com/package/react-redux
https://www.npmjs.com/package/react-router
https://www.npmjs.com/package/redux-thunk

**Comment by whit537** [comment]
My target is to make the pages look good enough for all of the packages Andrew mentions.

**Comment by whit537** [comment]
I thought for sec that it might just be a css issue, that we're not hiding the right class. But I don't even _see_ the class. We did [try](https://github.com/gratipay/gratipay.com/blob/0f95ffffdb351ffc750faafadb784cf8277e5e2c/tests/py/test_markdown.py#L70-L77) ...

image

**Comment by whit537** [comment]
Okay, I think we just neglect to [call](https://github.com/gratipay/gratipay.com/blob/0f95ffffdb351ffc750faafadb784cf8277e5e2c/gratipay/sync_npm/process_readmes.py#L22) `render_like_npm` properly. We don't pass in a package, that it would do the header de-duping. This means we'll have to reprocess all readmes. Good thing we've already fetched them! :-)

**Comment by whit537** [comment]
```sql
gratipay-bak=# update packages set readme_needs_to_be_processed = true where name in ('async', 'iframe-resizer', 'mongoose', 'nodemon', 'react', 'react-helmet', 'react-modal', 'react-redux', 'react-router', 'react-router-redux', 'redux', 'redux-thunk', 'webpack');
UPDATE 13
```

```
[gratipay] $ run defaults.env local.env sync-npm process-readmes
pid-61592 thread-140735121146624 (MainThread) Won't log to Sentry (SENTRY_DSN is empty).
processing webpack
processing redux-thunk
processing redux
processing react-router-redux
processing react-router
processing react-redux
processing react-modal
processing react-helmet
processing react
processing nodemon
processing mongoose
processing iframe-resizer
processing async
[gratipay] $
```

👍 

image

**Comment by whit537** [comment]
Looks good for the test cases. 👍

Not sure why the test didn't fail at Travis, though ...

**Comment by whit537** [comment]
Yeah the commit was messed up. Redoing ...

**Comment by whit537** [comment]
The deep-links are horked. The target is `user-content-blah` but the href is `#blah`. I guess let's just hide them for now.

**Comment by whit537** [comment]
Aaaaaaaaaaah ... much better!

image

**Comment by whit537** [comment]
Might have to give the NFL a pull request to clean up their readme under npm (it looks fine on GitHub). ;-)

**Comment by whit537** [comment]
> see about the broken img src on http://localhost:8537/on/npm/react-router/

The raw README [has](https://raw.githubusercontent.com/ReactTraining/react-router/e06190e06a7cebcced96aa708be83174176186a0/README.md):

```markdown
<img src="/logo/vertical@2x.png" height="150"/>
```

**Comment by whit537** [comment]
It's coming through unchanged in `/on/npm/react-router/`, so we're trying to load (via 302):

http://localhost:8537/~logo/vertical@2x.png

**Comment by whit537** [comment]
npm properly [rewrites](https://www.npmjs.com/package/react-router) it to:

https://raw.githubusercontent.com/reacttraining/react-router/master/logo/vertical@2x.png

**Comment by whit537** [comment]
That's (more or less) the same as what's on GitHub itself.

There was an option for this in marky-markdown, iirc ...

**Comment by whit537** [comment]
> `serveImagesWithCDN: false,    // use npm's CDN to proxy images over HTTPS`

Maybe that's slightly inaccurate?

**Comment by whit537** [comment]
https://github.com/npm/marky-markdown

**Comment by whit537** [comment]
Looks like [this](https://github.com/npm/marky-markdown/blob/795ba73ec2112431f1b5b6c4d318f54695c95cdf/lib/plugin/github.js) is what we want to trigger.

**Comment by whit537** [comment]
We need to pass an [`opts.package.repository.url`](https://github.com/npm/marky-markdown/blob/795ba73ec2112431f1b5b6c4d318f54695c95cdf/lib/plugin/github.js#L13).

**Comment by whit537** [comment]
D'oh! I think that means we need to refetch or somehow reload all packages to get repository URLs out of the package.json.

**Comment by whit537** [comment]
Any other [plugin](https://github.com/npm/marky-markdown/tree/795ba73ec2112431f1b5b6c4d318f54695c95cdf/lib/plugin) options we should be aware of?

**Comment by whit537** [comment]
[CDN](https://github.com/npm/marky-markdown/blob/795ba73ec2112431f1b5b6c4d318f54695c95cdf/lib/plugin/cdn.js) would require version if we wanted it.

**Comment by whit537** [comment]
[Here](https://github.com/npm/marky-markdown/blob/795ba73ec2112431f1b5b6c4d318f54695c95cdf/lib/plugin/heading-links.js) is where we might find a solution to https://github.com/gratipay/gratipay.com/pull/4151#issuecomment-263027993.

**Comment by whit537** [comment]
I'm not entirely sure how the CDN plugin relates to the GitHub plugin, but so far on my read the latter is what we want. The two do similar things, and we don't have all versions so I'm not sure storing a version is what we want. Let's go with a repo URL and the GitHub plugin since that should fix the presenting case at any rate.

**Comment by whit537** [comment]
Should we throw the whole package JSON into a JSON field, or add a field for repo URL, or ... ?

**Comment by whit537** [comment]
Seems like we should figure out the CDN plugin as well, to avoid having to do this over again down the line.

**Comment by whit537** [comment]
When does that manifest? What is the order of plugins?

**Comment by whit537** [comment]
Gosh, this is all gonna change as GitHub [migrates](https://twitter.com/whit537/status/796187843508850688) to CommonMark.

**Comment by whit537** [comment]
This is such a giant security hole. :-/ And it doesn't scale. Let's say we trust npm ... are we going trust all N package managers on Libraries.io? I think we're going to need to wrap this in a service that is served on a different domain and iframed in. Or we can say heck with readmes. Do people really need the readme duplicated on Gratipay? They just need to know it's the right project. A link over to npm can solve that, right? We don't have any significant content on `/on/twitter/oprah/`.

**Comment by whit537** [comment]
Maybe some stats like downloads and/or ndependents would indicate quickly that this is the "right" project?

screen shot 2016-11-29 at 4 55 32 pm

**Comment by whit537** [comment]
I'm not finding stats in the API.

**Comment by whit537** [comment]
Closing. There's no sense adding inert *and* contentless pages.

**Pull request closed without merging**
