### PR TITLE
Work around content negociation bug

### PR DESCRIPTION
**Pull request by Changaco**
Temporary fix for #3210.

### CODE REVIEW

**Comment by whit537** [comment]
I believe search is the only other affected page:

```
$ find www -name \*.spt|grep -v \\..*\\.|xargs grep json_dump
www/about/stats.spt:[----------------------------------------------------------] application/json via json_dump
www/search.spt:[---] application/json via json_dump
$
```

**Comment by whit537** [comment]
Ready when you (and Travis) are, @Changaco.

**Comment by Changaco** [comment]
Added a commit to fix the failing test.

**Comment by whit537** [comment]
I don't understand why that test passed before.

**Comment by Changaco** [comment]
> I don't understand why that test passed before.

Because the test client doesn't send an `Accept` header, so it always gets the first page of a negotiated simplate when the requested path doesn't contain an extension.

**Comment by whit537** [comment]
Good call. Reticketed upstream as https://github.com/gratipay/aspen-python/issues/422.

**Pull request merged**
