### PR TITLE
streamline team review

### PR DESCRIPTION
**Pull request by whit537**
Our team review queue is quite frictive at the moment. Here's what I propose:

 - ~~As part of payday, we create a new milestone every week for the week following.~~
 - Applying for a team automatically creates a new GitHub issue ([`team-review` repo](https://github.com/gratipay/team-review/issues)~~`inside.gratipay.com` repo, `Review` label~~~~, the latest milestone~~)
 - We revise the [content we've been sending in emails](https://github.com/gratipay/inside.gratipay.com/issues/248#issuecomment-111585170), and, rather than sending it in an email, simply put it in the page we display to the user after POSTing to `teams/create.json`.
 - The notification email we send on approve/reject (#3564) should link back to their review issue.

### CODE REVIEW

**Comment by whit537** [comment]
https://developer.github.com/v3/issues/#create-an-issue

**Comment by whit537** [comment]
We should backfill `review_url` for existing teams.

**Comment by whit537** [comment]
Scrap milestones. You can only have one with the same title at a time. We'll just have it as our policy that a review ticket must be open at least seven days before it can be decided upon.

**Comment by whit537** [comment]
Seems like it would be good to set up a separate GitHub user for this.

**Comment by whit537** [comment]
!m @gratipay-gremlin :D

**Comment by whit537** [comment]
Actually, let's use a separate repo for team review:

https://github.com/gratipay/review

Advantages:

 - Less noise on IG
 - Fine-grained control for any community members who want to participate in team review: watch the repo!
 - We don't need to give @gratipay-gremlin any special permissions. He can create issues in a public repo with no problem.

**Comment by whit537** [comment]
Scratch that. We still need to give him explicit read permission. Still better than write (which is needed for labels).

**Comment by whit537** [comment]
Rebased on master.

**Comment by whit537** [comment]
Alright, I'm not sure what's up with these remaining failing tests. They fail for me locally, too, but when I run each individually it passes.

**Comment by mattbk** [comment]
Since this isn't complete yet, does someone need to manually add unreviewed teams from http://gratipay.com/explore/teams to https://github.com/gratipay/review?

Is there a protocol for telling people why they were rejected?

Team review seems important to have in place for https://github.com/gratipay/gratipay.com/issues/3539.

**Comment by whit537** [comment]
> [D]oes someone need to manually add unreviewed teams from http://gratipay.com/explore/teams to https://github.com/gratipay/review?

Yes.

> Is there a protocol for telling people why they were rejected?

The de facto protocol is to email them. We've rejected five so far (out of 69). Here are the emails we've sent so far:

https://github.com/gratipay/inside.gratipay.com/issues/210#issuecomment-106471300
https://github.com/gratipay/inside.gratipay.com/issues/234#issuecomment-109512620
https://github.com/gratipay/inside.gratipay.com/issues/234#issuecomment-111260032
https://github.com/gratipay/violations/issues/23#issuecomment-111239504 

The [one](https://github.com/gratipay/inside.gratipay.com/issues/287#issuecomment-123752820) we haven't emailed yet is https://github.com/gratipay/review/issues/8.

> Team review seems important to have in place for #3539.

Yes!

**Comment by whit537** [comment]
Here's the text of the email sent under https://github.com/gratipay/violations/issues/23#issuecomment-111239504: 

> Sorry I haven't gotten back to you sooner. We actually decided a few weeks ago that the fansub community as a whole isn't a good fit for Gratipay, for two reasons. First, the way different fansub groups characteristically relate to each other clashes pretty strongly with our [brand values](http://inside.gratipay.com/big-picture/brand/), particularly "kindness," and "collaboration." Second, we're not interested in being associated with the legal concerns that surround fansubbing.
>
You may be interested in https://github.com/liberapay/liberapay.com, an upcoming fork of Gratipay with more relaxed requirements.

**Comment by whit537** [comment]
Tentative rebase on master in https://github.com/gratipay/gratipay.com/compare/str.

**Comment by whit537** [comment]
Rebased on master. Old HEAD is https://github.com/gratipay/gratipay.com/commit/5d4fece7c1066ba355fafad0e344d502b4e673fa.

**Comment by whit537** [comment]
screen shot 2015-09-07 at 11 15 16 pm

**Comment by whit537** [comment]
I think this will fail on master, where we don't use VCR.

**Comment by whit537** [comment]
screen shot 2015-09-08 at 12 09 39 am

screen shot 2015-09-08 at 12 10 13 am

**Comment by whit537** [comment]
Backfilling `review_url` ... I've got URLs for all of the Teams in the [`team-review`](https://github.com/gratipay/team-review/issues) repo. Looks like that's 43 of them, leaving 55 from before we settled on that.

**Comment by whit537** [comment]
I think I'm gonna merge and deploy, and then backfill.

**Comment by whit537** [comment]
Ooh ... but is this gonna break on master since we try to create a GitHub ticket?

**Comment by whit537** [comment]
https://travis-ci.org/gratipay/gratipay.com/builds/79222169

**Comment by whit537** [comment]
Okay, interesting. The error fallback for GitHub URLs is working! :-)

Not sure what the other error in billing_payday is about tho ...

**Comment by whit537** [comment]
Hopefully cleaned up in #3761 ... https://travis-ci.org/gratipay/gratipay.com/builds/79222920.

**Comment by whit537** [comment]
Yesssssss.

**Comment by whit537** [comment]
The billing_payday error appears to have been spurious.

**Comment by whit537** [comment]
Alright, let's get this deployed and fill in the data ...

**Comment by whit537** [comment]
Round 1: https://gist.github.com/whit537/597a9b9b4f14c122e6f0.

**Comment by whit537** [comment]
Envvars set ...

**Comment by whit537** [comment]
Round 2: https://gist.github.com/whit537/7629e5fa5b1f97c33a23

**Comment by whit537** [comment]
Okay! We have review_urls, and a more streamlined application process. :-)

**Pull request merged**
