### PR TITLE
Relax open work requirement

### PR DESCRIPTION
**Pull request by whit537**
Ever since the Gratipocalypse, we've required the "Teams" receiving money on Gratipay to go through an application and approval process. One of our main criteria for approval has been that Teams provide what we called "open work":

> Open Work means that the Team provides a clear path for any individual to voluntarily begin contributing to the Team's work and to share in any revenue the Team generates.

Experience has shown this to be too restrictive. We still want to _encourage_ and _emphasize_ open work on Gratipay, but we don't want to _require_ it. The purpose of this project is to relax the open work requirement.

--------------------

✈️  **This is the flight deck for the [Relax Open Work Requirement](https://github.com/orgs/gratipay/projects/5?fullscreen=true.) project.** ✈️ 

--------------------

### Todo

- [ ] update the user interface
  - [x] merge #4117
  - [x] merge #4214
  - [x] merge #4130
  - [x] merge #4157
  - [ ] merge to `master`
- [ ] update the review repo
  - [ ] rename the `team-review` repo to `project-review`
  - [ ] update `TEAM_REVIEW_REPO` in the Heroku environment
  - [ ] merge https://github.com/gratipay/team-review/pull/281
- [ ] update Inside Gratipay
  - [ ] merge https://github.com/gratipay/inside.gratipay.com/pull/861
- [ ] blog post: https://gratipay.news/from-teams-to-projects-45c46718507b
  - [ ] update link to `terms-of-service.md` diff
  - [ ] publish
- [ ] announce on Twitter
- [ ] notify owners of projects that are accepted or under review
- [ ] put notice on website: #4229

### CODE REVIEW

**Comment by whit537** [comment]
[Looks like](https://github.com/orgs/gratipay/projects/5?fullscreen=true) we have two big pieces of work remaining before we can merge this branch to master: https://github.com/gratipay/gratipay.com/pull/4130 and https://github.com/gratipay/gratipay.com/pull/4157.

We should also figure out testing. Oooo! I have an idea ... ;-)

**Comment by whit537** [comment]
Yesssss ... now to make sure that propagates to PRs against this branch ...

**Comment by whit537** [comment]
👍 

Seeing Travis on #4130 ...

screen shot 2016-12-06 at 8 39 06 am

**Comment by whit537** [comment]
Cool. We'll just need to remove this branch from `.travis.yml` as part of our final merge to `master`.

**Comment by whit537** [comment]
New plan: build all branches after all, so that Travis will test PR chains ([e.g.](https://github.com/gratipay/gratipay.com/pull/4130#issuecomment-265154203))

**Comment by whit537** [comment]
Rebased on `master`, was c2644b5d076c6936f58adc9541e11ec0ba3871d9.

**Comment by whit537** [comment]
I squashed all of #4117 into a single commit, to make this integration PR easier to read and work with.

**Comment by whit537** [comment]
Blech. cf13cc62d68b5d5fa0545b71473e52f29bd07bb4 is hitting the #4224 bug again, even with Faker 0.7.3. 😞

https://travis-ci.org/gratipay/gratipay.com/builds/182073772

**Comment by whit537** [comment]
Lol ... and 25018dfcb38387acbd3a032f5fc1cb0e83aadbc1 hits the "13 failed" that we're _also_ seeing at https://github.com/gratipay/gratipay.com/pull/4130#issuecomment-265571928. That one at least goes away with a rerun.

**Comment by whit537** [comment]
> That one at least goes away with a rerun.

Which of course makes it harder to debug. :-/

**Comment by mattbk** [comment]
https://github.com/gratipay/gratipay.com/pull/4221/commits/25018dfcb38387acbd3a032f5fc1cb0e83aadbc1 passes now.

**Comment by whit537** [comment]
Rebased, was 25018dfcb38387acbd3a032f5fc1cb0e83aadbc1.

**Comment by whit537** [comment]
Blech. Gnarly commit message on that last one. :-/

**Comment by whit537** [comment]
In 69297ed1217ead7204e487d3a520e1ab28b8e96b I dated the new terms December 12: next Monday. Let's do it!

**Comment by whit537** [comment]
The "Apply for a project" button is broken for me now I think?

screen shot 2016-12-09 at 3 26 55 pm

**Comment by whit537** [comment]
I've updated the ticket with a sequence for deploying all of the final changes for this project.

**Comment by whit537** [comment]
@mattbk Reverting is different than rebasing. Reverting adds a second commit that is the inverse of the first. Rebasing lets you remove the first.

**Comment by whit537** [comment]
[slack](http://gratipay.slackarchive.io/gratipay/-/1481207581.000212/1481320878.00032/1481320262000310/)

**Comment by mattbk** [comment]
Rebased, was fd2c60a.

**Comment by whit537** [comment]
I'm drafting a blog post.

**Comment by whit537** [comment]
We need to figure out some sort of on-site notice, and maybe email.

**Comment by whit537** [comment]
Simple post: https://gratipay.news/from-teams-to-projects-45c46718507b.

**Comment by whit537** [comment]
Slight revision on the post: https://gratipay.news/from-teams-to-projects-45c46718507b.

**Comment by whit537** [comment]
Driving in [slack](http://gratipay.slackarchive.io/gratipay/-/1481289628.000291/1481567146.000395/1481566875000387/).

**Comment by whit537** [comment]
💃

**Comment by whit537** [comment]
We're live with the UI and repo changes and blog post! Waiting to announce until tomorrow.

screen shot 2016-12-12 at 6 14 08 pm

--------------------

screen shot 2016-12-12 at 6 13 13 pm

**Comment by whit537** [comment]
Regression:

screen shot 2016-12-12 at 6 20 11 pm

**Comment by whit537** [comment]
screen shot 2016-12-12 at 6 23 00 pm

**Comment by whit537** [comment]
Regression fixed in #4230.

**Comment by whit537** [comment]
Twittered: https://twitter.com/Gratipay/status/808702383282880516.

**Comment by whit537** [comment]
Alright ... email! Where did we do that before? How did we do it?

**Comment by whit537** [comment]
Me starts with https://github.com/gratipay/inside.gratipay.com/issues/376 ...

**Comment by whit537** [comment]
Here we go:

https://github.com/gratipay/inside.gratipay.com/issues/235
&rarr; https://github.com/gratipay/gratipay.com/issues/3385#issuecomment-100040443
&rarr; https://github.com/gratipay/gratipay.com/pull/3510

> I'm planning to write a script to queue this locally, with a production Mandrill key in local.env for sending.

**Comment by whit537** [comment]
Yeah, that's got the whole live-blog on it.

**Comment by whit537** [comment]
PR in https://github.com/gratipay/gratipay.com/pull/4232.

**Comment by whit537** [comment]
Congratulations, people! With https://github.com/gratipay/inside.gratipay.com/issues/972, we have relaxed our open work requirement! 🌝  👏 💃 🌻  🎆

**Pull request merged**
