### PR TITLE
Payments for open source receipt

### PR DESCRIPTION
**Pull request by kaguillera**
&larr; #4621 — #4600 &rarr; 

This is the stub for the receipts  for companies paying for open source.

### CODE REVIEW

**Comment by kaguillera** [comment]
Yet another of my push snaffoos 😦 . But I have to run.

**Comment by whit537** [comment]
Not a push snafu just needed to set the base branch to `new-homepage-wireup` instead of `master`. :)

**Comment by whit537** [comment]
Rebased onto #4621, was a7050f6c85828f1b39a851e85cafabc63f456c58.

**Comment by whit537** [comment]
screencapture-localhost-8537-browse-payments-9ebf8276f25b4630b577a880c4f87ab1-invoice-html-1505088293085

**Comment by whit537** [comment]
🚨  **[Self-merge license](https://github.com/gratipay/gratipay.com/pull/4598#issuecomment-328309598)** 🚨

**Pull request merged**
