### PR TITLE
fake-data, teams and subscriptions

### PR DESCRIPTION
**Pull request by rorepo**
Fake data script updated to create teams and subscriptions.

Fake data test script updated accordingly.

### CODE REVIEW

**Comment by whit537** [comment]
Thanks for the contribution, @rorepo! :dancer:

**Comment by rorepo** [comment]
Following on from the comment in the earlier #3573:

Leaving fake tips around until the migration has been verified seems to make sense. However, how is the migration intended to happen? Is it that new users will only be using subscriptions, while existing users will have their tips records migrated to subscriptions? Presumably, starting with a small batch of existing users?

On removal of tips from fake_data, this is the situation as I see it:
Methods:
fake_tip_amount - this is a generic function to give a dummy amount, the only relation to tips being the MIN_TIP and MAX_TIP values. I've used this function in fake_subscription, so this function itself can't be removed unless a new version is created for fake-subscription.

fake_tip - can be removed, subject to the 'Making tips' bit being removed from populate_db

populate_db - in this:
The 'Making tips' bit can be removed, subject to the usage of the tips collection being removed/replaced in the rest of the code
A small complication I see in doing this is that I'm unclear about the equivalence of tipper, tippee in tips to subscriber, team in subscriptions. If I have understood correct, both tipper and tippee were referring to participant instances, while in subscriptions, the team is obviously referring to a team. And the complication actually arises from the fact that tips.tippee refers to the participant username, while subscriptions.team refers to team.slug - so this will need to be worked around.

Additionally, there is the aspect of transfers - are these still from participant to participant?

Also, a question about methods like fake_tip_amount, (community) slugize - seems likely these (or versions of these) could be used by different modules. Is there a common module such methods could be added to?

**Comment by whit537** [comment]
> However, how is the migration intended to happen?

Migration happens with [a one-off script](https://github.com/gratipay/gratipay.com/blob/1858/bin/migrate-tips.py) every week during payday, e.g., https://github.com/gratipay/gratipay.com/issues/3566#issuecomment-113302914.

**Comment by whit537** [comment]
> Additionally, there is the aspect of transfers - are these still from participant to participant?

Yes, and, as with `tips`, these are historical. We replaced the `tips` and `transfers` tables with the `subscriptions` and `payments` tables in #3414.

**Comment by whit537** [comment]
> Also, a question about methods like fake_tip_amount, (community) slugize - seems likely these (or versions of these) could be used by different modules. Is there a common module such methods could be added to?

Maybe in `gratipay.utils`?

**Pull request merged**
