### PR TITLE
Persist email messages

### PR DESCRIPTION
**Pull request by whit537**
&larr; ~Factor out email tests (#4570)~ — Persist email verifications (#4573) &rarr;

------------------

Previously the email queue was ephemeral. We would delete messages from it after successfully firing them off to SES. That prevents us from doing several things:

- properly handling bounces and complaints (#4284)
- sending instantly while also throttling (#4545)
- limiting verification emails properly (#4557)

This PR:

- changes `email_queue` to `email_messages`, a table that we never delete from
- changes `emails` to `email_addresses` to disambiguate

### Todo

- [x] store `MessageId`

### CODE REVIEW

**Comment by whit537** [comment]
Ready for review, @rohitpaulk! :-)

**Comment by whit537** [comment]
As we start persisting messages, we should store the `MessageId` [returned](http://docs.aws.amazon.com/ses/latest/APIReference/API_SendEmail.html#API_SendEmail_ResponseElements) from SES for successful submissions. That'll be crucial to bounce handling (#4284), and in general is a Good Idea&trade; (cf. #4442).

**Comment by whit537** [comment]
Already, `MessageId` stored in 36c54650cdc73b79ae58dd988259fca6fea6efea.

**Comment by rohitpaulk** [comment]
Looks good to me. I'm a bit confused as to why `log_every` has to be patched for the test, but that isn't really important compared to the purpose of this patch itself. 

Waiting for Travis.

**Comment by whit537** [comment]
> I'm a bit confused as to why `log_every` has to be patched for the test

Good guestion! That might be noise. 😶

**Pull request merged**
