### PR TITLE
Fix takes when changing to individual

### LINKED ISSUE #2967: Handle takes properly when account is changed from team to individual
@benhc123 did some poking around and discovered this : 
 
> If you've joined something while it's a team and then it becomes an individual it goes wrong! You can't close the account of the joined member.

Details from Sentry: 

```
Stacktrace (most recent call last):

  File "site-packages/algorithm.py", line 288, in run
    new_state = function(**deps.as_kwargs)
  File "aspen/algorithms/website.py", line 97, in get_response_for_resource
    return {'response': resource.respond(request, dispatch_result)}
  File "aspen/resources/dynamic_resource.py", line 56, in respond
    exec self.pages[1] in context
  File "/app/www/%username/account/close.spt", line 23, in <module>
    participant.close(disbursement_strategy)
  File "gratipay/models/participant.py", line 304, in close
    self.clear_personal_information(cursor)
  File "gratipay/models/participant.py", line 412, in clear_personal_information
    self.clear_takes(cursor)
  File "gratipay/models/participant.py", line 404, in clear_takes
    t.set_take_for(self, Decimal(0), self, cursor)
  File "gratipay/models/_mixin_team.py", line 112, in set_take_for
    assert self.IS_PLURAL
```

### PR DESCRIPTION
**Pull request by rohitpaulk**
Fixes #2967.

### CODE REVIEW

**Comment by seanlinsley** [comment]
I'd prefer to have an error message that says to contact support.

**Comment by rohitpaulk** [comment]
> I'd prefer to have an error message that says to contact support.

Why contact support? The corrective actions are the kind that a user can do on her own.

**Comment by rohitpaulk** [comment]
@seanlinsley - ^^

**Comment by Changaco** [comment]
Added commits.

**Pull request merged**
