### PR TITLE
Add 401 response to about/me pages.

### LINKED ISSUE #4258: about/me/history does not match other pages that require login to view
`about/me/history` (not logged in):
image

`~whit537/history` (not logged in)
image

The latter is a 401 code, the former is not.

### PR DESCRIPTION
**Pull request by mattbk**
Closes #4258.

### CODE REVIEW

**Comment by mattbk** [comment]
The Travis failure is not because of something in this PR.
> tests/py/test_history.py::TestHistory::test_iter_payday_events FAILED

Must be related to https://github.com/gratipay/gratipay.com/pull/4252 et alii.

**Comment by whit537** [comment]
How about a test? :-)

**Comment by mattbk** [comment]
!

Either I got it right on the first try, or it didn't even test the right thing. Hmm.

**Comment by whit537** [comment]
> it didn't even test the right thing

It reads to me like you got it right on the first try, though the second test duplicates the first.

Good work! :-)

!m @mattbk

**Comment by mattbk** [comment]
> though the second test duplicates the first.

You are correct. I think I missed a small difference when I copied them and changed the URLs.

**Comment by whit537** [comment]
> I think I missed a small difference when I copied them and changed the URLs.

Well, from the test name it sounded like you intended to vary the user from anon to auth-no-admin or some such.

**Comment by whit537** [comment]
That wouldn't be bad to have. Also, do you think it'd be worth checking subpaths, too? `/about/me/history/` is the one I think we were starting with here?

**Comment by whit537** [comment]
Looks good to me. Blocking on #4252 though, to avoid `master` drifting further before getting back on track.

**Comment by mattbk** [comment]
#4252 is merged, unblocking.

**Comment by whit537** [comment]
Deployed!

screen shot 2016-12-31 at 8 32 47 am

**Comment by whit537** [comment]
!m @mattbk

**Pull request merged**
