### PR TITLE
Constrain payday payouts

### PR DESCRIPTION
**Pull request by rohitpaulk**
https://github.com/gratipay/gratipay.com/issues/3415#issuecomment-102459522

#3396

### CODE REVIEW

**Comment by whit537** [comment]
@rohitpaulk Is it obvious to you why 62fe52438a28fa4f3cc1780c12d0cb169e563345 is failing?

**Comment by whit537** [comment]
I get:

```
_____________________________________ TestPayout.test_payout_can_pay_out _____________________________________
Traceback (most recent call last):
  File "/Users/whit537/personal/gratipay/gratipay.com/env/lib/python2.7/site-packages/mock.py", line 1201, in patched
    return func(*args, **keywargs)
  File "/Users/whit537/personal/gratipay/gratipay.com/tests/py/test_billing_payday.py", line 523, in test_payout_can_pay_out
    Payday.start().payout()
  File "/Users/whit537/personal/gratipay/gratipay.com/gratipay/billing/payday.py", line 444, in payout
    self.db.self_check()
  File "/Users/whit537/personal/gratipay/gratipay.com/gratipay/models/__init__.py", line 31, in self_check
    check_db(cursor)
  File "/Users/whit537/personal/gratipay/gratipay.com/gratipay/models/__init__.py", line 37, in check_db
    _check_balances(cursor)
  File "/Users/whit537/personal/gratipay/gratipay.com/gratipay/models/__init__.py", line 120, in _check_balances
    assert len(b) == 0, "conflicting balances: {}".format(b)
AssertionError: conflicting balances: [Record(username=u'alice', expected=Decimal('-20.00'), actual=Decimal('0.00'))]
```

**Comment by rohitpaulk** [comment]
>Is it obvious to you why 62fe524 is failing?

Yes, we created a participant with a balance, but don't have a corresponding exchange...

**Comment by rohitpaulk** [comment]
Fixing...

**Comment by whit537** [comment]
> Ah, like pry for ruby :)

:)

**Comment by whit537** [comment]
!m @rohitpaulk 

Okay! Back to #3415 ...

**Pull request merged**
