### PR TITLE
Throttle better

### PR DESCRIPTION
**Pull request by whit537**
Our throttling algorithm is naive. Now that we have an isolated `queue_email` path (#4346), we should use that as a choke-point for throttling for all user-initiated email.

https://hackerone.com/reports/108645

### CODE REVIEW

**Comment by whit537** [comment]
This is somewhat complicated by the fact that we don't want to system-generated emails to affect throttling, only user-initiated messages.

**Comment by whit537** [comment]
Alright! All caught up after making upstream changes (see chain listed under "new email subflooring" pre-req on #4305). Ready to make progress again, I think ...

**Comment by mattbk** [comment]
!m @whit537!

**Comment by whit537** [comment]
Typo. 😊

**Comment by whit537** [comment]
Okay! With a204a43d3219101db91a5218b19e65fef0be9686, the email refactoring and bugfix chain is complete at a first pass. We've already started merging w/ #4343 and #4344, and #4345 is on deck now. Since we seem to be moving along at a good clip, I'm going to hold off on rebasing the whole chain right now.

**Comment by EdOverflow** [comment]
This HackerOne report is related: [h1:212880](https://hackerone.com/reports/212880).

**Comment by whit537** [comment]
Rebased onto `master` post-#4348, was a204a43d3219101db91a5218b19e65fef0be9686.

**Comment by whit537** [comment]
Self-merged per https://github.com/gratipay/gratipay.com/pull/4305#issuecomment-286796283 and https://github.com/gratipay/gratipay.com/pull/4360#issuecomment-287064268.

**Pull request merged**
