### PR TITLE
Teams to sidebar

### PR DESCRIPTION
**Pull request by mattbk**
Per my comment at https://github.com/gratipay/gratipay.com/issues/3560#issuecomment-123363444, I added the teams list to the sidebar of each participant profile.

### CODE REVIEW

**Comment by whit537** [comment]
Rebased on master.

**Comment by whit537** [comment]
This isn't a bad idea, but the green link on brown doesn't work:

screen shot 2015-08-22 at 8 36 36 am

**Comment by mattbk** [comment]
I know, but I was working within color scheme. 

On August 22, 2015 7:37:09 AM CDT, Chad Whitacre <notifications@github.com> wrote:
>This isn't a bad idea, but the green link on brown doesn't work:
>
>screen shot 2015-08-22 at 8 36 36
>am
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/gratipay/gratipay.com/pull/3672#issuecomment-133690360

-- 
Sent from a phone that, although intelligent, is not street smart.

**Comment by whit537** [comment]
Really? Do we use green links over brown anywhere else?

screen shot 2015-08-22 at 9 00 51 am

**Comment by whit537** [comment]
screen shot 2015-08-22 at 9 02 36 am


We do use a green button, but not a green link:

screen shot 2015-08-22 at 9 02 00 am

**Comment by mattbk** [comment]
I will take a look when I have a chance.

**Comment by whit537** [comment]
I think this is obsolete after #3718. Okay to close, @mattbk?

**Pull request closed without merging**
