### PR TITLE
rewrite payday

### PR DESCRIPTION
**Pull request by whit537**
Part of #3399.

### CODE REVIEW

**Comment by whit537** [comment]
I've printed out payday.py and started combing through it. The reason why https://github.com/gratipay/gratipay.com/issues/3399#issuecomment-101470445 doesn't result in escrow or complicated graph settling is that it ... doesn't do complicated graph settling: **b** can't feed their $1 back into the system. I think we should run with that, so that we can move towards #1383 with this.

**Comment by whit537** [comment]
I'm hoping we can also pick off #3378 while we're here, another part of #1383.

**Comment by whit537** [comment]
I believe since we're not cycling the graph multiple times per payday, we don't need to use the `is_funded` mechanism for distributing funds. We should just be able to use `card_hold_ok` directly.

**Comment by whit537** [comment]
Basically, the work here is to implement the prototype I wrote in Python, in the SQL inside prepare_db. Most of the Python shell around payday should be able to stay intact.

**Comment by whit537** [comment]
I'm starting with the `test_transfer_tips{_whole_graph}` tests, because that calls `settle_tip_graph()`, which is the heart of payday.

**Comment by whit537** [comment]
There some interaction between `participants.balance` and `payday_participants.card_hold_ok` that I need to understand. It relates to #1383 and how we're going to approach that here.

**Comment by whit537** [comment]
On the one hand it seems like we should avoid tackling the arrears issue (#3378) on this PR. On the other hand ...

**Comment by whit537** [comment]
Okay! I believe with that last commit we've gotten rid of the feedback. :microphone: :dizzy_face: *screeeeeeeeeeeeee*

Now to introduce teams ...

**Comment by whit537** [comment]
P.S. We still make payments from preexisting balances, which means we can avoid tackling #3378 here. Phew.

**Comment by whit537** [comment]
Wow. Caching is a :rabbit:-hole. I'm going to stub it out for now. We'll migrate caching of `receiving`, etc., later.

**Comment by whit537** [comment]
I'm also going to not worry about the payroll side this week. Gratipay is the only one of the half-dozen or so teams we're aiming to run with today that uses payroll. We'll just let the full amount clear to our bank account this week. Sorry, Gratipay team. :-/

**Comment by whit537** [comment]
I believe that's it for this PR.

**Comment by whit537** [comment]
Alright, Travis is green. :white_check_mark: 

Here we go! Nothing ventured, nothing gained!

**Comment by rohitpaulk** [comment]
:dancers:

**Pull request merged**
