### PR TITLE
update "About > Overview" for 2.0

### PR DESCRIPTION
**Pull request by whit537**
One step on #3398.

### CODE REVIEW

**Comment by whit537** [comment]
How's this look, @mattbk @tshepang et al.?

**Comment by whit537** [comment]
screen shot 2015-08-17 at 12 07 33 pm
screen shot 2015-08-17 at 12 07 47 pm

**Comment by whit537** [comment]
I'm going to self-merge this once Travis runs green. We have a lot to get done before Sept 1.

**Comment by mattbk** [comment]
👍

**Pull request merged**
