### PR TITLE
Split out identity verification from bank account connecting

### LINKED ISSUE #987: split out identity verification from bank account connecting
This would enable two things:

1. Connecting a bank account as a funding source, not a withdrawal sink (#777).
2. Verifying identity to be a team without connecting any bank account (#988).

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/409993-split-out-identity-verification-from-bank-account-connecting?utm_campaign=plugin&utm_content=tracker%2F85909&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F85909&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Changaco**
Closes #987.

### CODE REVIEW

**Comment by Changaco** [comment]
Tagging `TeamX ★` because I have other branches based on this.

**Comment by Changaco** [comment]
Screenshot of invalid form field:

**Comment by whit537** [comment]
On a fresh database, when I login and navigate to /about/me/identity, I get this traceback:

```
Traceback (most recent call last):
  File "/Users/whit537/personal/gratipay/gratipay.com/env/lib/python2.7/site-packages/algorithm.py", line 288, in run
    new_state = function(**deps.as_kwargs)
  File "/Users/whit537/personal/gratipay/gratipay.com/env/lib/python2.7/site-packages/aspen/algorithms/website.py", line 104, in get_response_for_resource
    return {'response': resource.respond(state)}
  File "/Users/whit537/personal/gratipay/gratipay.com/env/lib/python2.7/site-packages/aspen/resources/simplate.py", line 66, in respond
    response = self.get_response(context)
  File "/Users/whit537/personal/gratipay/gratipay.com/env/lib/python2.7/site-packages/aspen/resources/simplate.py", line 185, in get_response
    response.body = render(context)
  File "/Users/whit537/personal/gratipay/gratipay.com/env/lib/python2.7/site-packages/aspen/renderers/__init__.py", line 107, in __call__
    return self.render_content(context)
  File "/Users/whit537/personal/gratipay/gratipay.com/gratipay/renderers/jinja2_htmlescaped.py", line 15, in render_content
    return base.Renderer.render_content(self, context)
  File "/Users/whit537/personal/gratipay/gratipay.com/env/lib/python2.7/site-packages/aspen_jinja2_renderer.py", line 66, in render_content
    return self.compiled.render(context).encode(charset)
  File "/Users/whit537/personal/gratipay/gratipay.com/env/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/whit537/personal/gratipay/gratipay.com/env/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/whit537/personal/gratipay/gratipay.com/www/%username/identity.spt", line 1, in top-level template code
    import balanced
  File "/Users/whit537/personal/gratipay/gratipay.com/templates/base.html", line 88, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/whit537/personal/gratipay/gratipay.com/www/%username/identity.spt", line 31, in block "content"
    except ValueError:
  File "/Users/whit537/personal/gratipay/gratipay.com/env/lib/python2.7/site-packages/jinja2/environment.py", line 397, in getattr
    return getattr(obj, attribute)
UndefinedError: 'balanced.resources.Customer object' has no attribute 'address'
```

**Comment by whit537** [comment]
Identity should be included in the navigation. Right now the only way to get to it is through the bank account page.

**Comment by Changaco** [comment]
> Identity should be included in the navigation. Right now the only way to get to it is through the bank account page.

I think fixing Gratipay's navigation needs its own PR.

**Comment by Changaco** [comment]
> On a fresh database, when I login and navigate to /about/me/identity, I get this traceback:

The real problem here is that the browsing tests didn't detect that, I figured out why and am working on a PR to fix them.

**Comment by Changaco** [comment]
`UndefinedError` fixed.

**Comment by whit537** [comment]
> I think fixing Gratipay's navigation needs its own PR.

#3258

**Comment by whit537** [comment]
Needs a rebase.

**Comment by whit537** [comment]
>`UndefinedError` fixed.

Confirmed.

**Comment by whit537** [comment]
Tests passing locally. Reviewing UI ...

**Comment by whit537** [comment]
Are these tooltips new on this PR? Definitely a move in the right direction.

screen shot 2015-03-17 at 12 04 55 pm

**Comment by whit537** [comment]
Interesting that the tooltips I'm seeing on the Identity form are different than the ones screencapped from the credit card form at https://github.com/gratipay/gratipay.com/pull/3250#issuecomment-81556755.

**Comment by whit537** [comment]
When I post the identity form, I land back on the same page with no feedback. What just happened?

Refreshing the page indicates that my data persisted. But is my identity verified?

**Comment by whit537** [comment]
Now I'm presented with the bank account form. So I guess my identity *was* verified?

screen shot 2015-03-17 at 12 09 35 pm

**Comment by whit537** [comment]
*Now* I see the red tooltip:

screen shot 2015-03-17 at 12 10 24 pm

Why is being invalid so much worse than not having been filled in?

**Comment by Changaco** [comment]
> Are these tooltips new on this PR? Definitely a move in the right direction.

Those are your browser's tooltip, the red ones are Gratipay's.

**Comment by whit537** [comment]
> Those are your browser's tooltips, the red ones are Gratipay's.

Eep. That's not ideal. They should be consistent.

**Comment by whit537** [comment]
If I go back to the identity form by hitting the URL directly, I can change my information there. Is that good? What's happening when I do that?

**Comment by whit537** [comment]
Regardless, I can save my bank account details now:

screen shot 2015-03-17 at 12 22 47 pm

**Comment by whit537** [comment]
I don't see a way to remove my identity verification.

**Comment by whit537** [comment]
I think we should add this to the profile nav, between Widgets and Settings.

**Comment by whit537** [comment]
Next steps for me are to inspect what happens in Balanced when we post identity, and then read commits.

**Comment by whit537** [comment]
- [ ] 0360b58fe27ab3af123f21e9b465e137af0a8848
 - [ ] ef68732ff0d18f17b1613d1426e191160f0dffe0
 - [ ] 6545ff45976e49e12aed947d3a17d3e929a3a08b
 - [ ] 0ef26ec7d860c82187772c9738b396d20743b1e5
 - [ ] 902c2311987e76fa95311d0f610e2ec2c1fd0c3e
 - [ ] 0227177df83c6a9ee5d18d54dbd52939468b1b36
 - [ ] 6616ab390d63fe6adf2b075dbf517c32fa65801b
 - [ ] d8981ccb4d926ef75630dd0f11e426b7f44def6f
 - [ ] e18bb310b4743a0897e143451c74d98e527565cd
 - [ ] c305d7949687dbfc3ccf0eb55fc862c4f2a096fc
 - [ ] 18fb3817d4f606dd15f7c24e1174daf563044bc0

**Comment by whit537** [comment]
I'm reading about form validation:

http://designmodo.com/ux-form-validation/
http://alistapart.com/article/inline-validation-in-web-forms
https://www.google.com/search?q=form+error+ui

**Comment by whit537** [comment]
It's goofy to wrap the "You need to verify your identity first" text (which, btw, should have a period) when we're not wrapping the long intro paragraph.

screen shot 2015-03-17 at 2 58 03 pm

**Comment by whit537** [comment]
So ... the inline error reporting we've added here is good for pattern mismatches such as DOB, but it's bad for signaling required fields, because, whereas a pattern can be matched as soon as it's entered, we can't know that a required field is missing until the moment the form is submitted. But the moment the form is submitted, we can and should say when *all* required fields are missing, not just the first. 

Firefox has okay behavior here. They highlight the missing fields, with a tooltip on the first:

screen shot 2015-03-17 at 3 17 18 pm

Chrome, however, doesn't highlight the missing fields:

screen shot 2015-03-17 at 3 18 55 pm

Are we doing something in CSS that prevents Chrome from highlighting missing fields?

**Comment by whit537** [comment]
Can we use browser validation for *all* fields? It's shoddy to have some validation styled one way and some a different way.

**Comment by whit537** [comment]
> is it really so important to have all the tooltips look exactly the same?

Yes. Having some tooltips styled one way and others a different way is shoddy. Yes, we are quite shoddy in many ways. Let's not make our product worse.

**Comment by whit537** [comment]
@Changaco You can punt on further error reporting clean-ups if you want to, since the main purpose of this PR is to separate the identity form from the bank account form.

**Comment by whit537** [comment]
>> is it really so important to have all the tooltips look exactly the same?

>Yes. Having some tooltips styled one way and others a different way is shoddy.

In fact, this is a perfect example of the "wagging the dog" antipattern that we've [talked about before](https://github.com/gratipay/gratipay.com/issues/3222#issuecomment-77212230). To compete with closed companies, we "have to be as good or better on [...] features and UX" ([IRC](https://botbot.me/freenode/gratipay/2015-03-16/?msg=34281308&page=2)). We're not going to get there unless we really, truly own the difference between the product dog and the technology tail.

**Wrong:** "Hey, I've got this technology available. Where can I use it?"

**Right:** "Here's the experience I want my users to have. How do I deliver it?"

**Comment by whit537** [comment]
product-dog

**Comment by Changaco** [comment]
> Yes. Having some tooltips styled one way and others a different way is shoddy.

I really don't get that. Would you have noticed the difference if I hadn't posted a screenshot of the red tooltip? Do you think users really care that one tooltip is white/gray and the other red? I can make ours gray if you want.

> Yes, we are quite shoddy in many ways. Let's not make our product worse.

Compared to what we have now, this PR is still a big improvement even if the tooltips aren't of the same color.

**Comment by Changaco** [comment]
Is that better?

**Comment by whit537** [comment]
> Would you have noticed the difference if I hadn't posted a screenshot of the red tooltip?

Yes.

> Do you think users really care that one tooltip is white/gray and the other red?

Yes. Any competent product designer (by definition, so say I) will consciously care that the tooltips are not consistent, because it's a distinction without a difference. The distinction in the product's interface does not encode a difference in the product's mental model. Rather, it encodes a tooling limitation. The tooling limitation has no meaning to the user. The mental model of the product is where the user looks for meaning.

Most untrained users will [subconsciously care](http://www.peachpit.com/articles/article.aspx?p=1729265&seqNum=2):

>Can you guess the most frequently cited factor for evaluating the credibility of a Web site?
>
According to a 2002 study out of Stanford University, it is the “appeal of the overall visual design of a site, including layout, typography, font size, and color schemes,” (Fogg, et al., 2002). The look and feel of a site influenced judgments about credibility far more than other factors like structure, usefulness of the information, tone of the content, and name recognition!
>
04fig06
>
A different study found that “Web users form first impressions of Web pages in as little as 50 milliseconds (1/20th of a second).” What’s more, these initial attractiveness evaluations based on just a brief exposure “were very highly correlated with attractiveness evaluations of the same pages under unlimited exposure.*”

The Stanford study contributes to [these guidelines](https://credibility.stanford.edu/guidelines/), along with a number of other papers from the same era (1999-2002). Unfortunately, the links to the actual papers are broken. Admittedly, it's also old research, [as noted](http://captology.stanford.edu/projects/archived-projects.html):

> The Persuasive Tech Lab did early research on the factors that affect the credibility of websites. Since our investigations in the 1990s, we’ve found that online credibility has morphed. With the rise of Web 2.0 services, the focus of credibility evaluations extend beyond the page to the people represented. In other words, Credibiltity [*sic*, ironically] 2.0 has become more like reputation, or perceived reputation.

**Comment by whit537** [comment]
> I really don't get that.

Hrm. That's a bigger problem, since historically I haven't had much luck getting you to get things you don't get. ;-)

I suppose the best I can do for now is to flag problems as I notice them, explain myself as best I can, and correct problems myself as much as I'm able. Hopefully over time we're able to attract and retain competent product designers to balance out our team.

**Comment by whit537** [comment]
> Compared to what we have now, this PR is still a big improvement even if the tooltips aren't of the same color.

Yeah, and what's more, the changes to form validation aren't the point of this PR. Splitting Identity out from the bank account page is the point. I'm almost ready to merge, lemme go over it one more time ...

**Comment by whit537** [comment]
> Are we doing something in CSS that prevents Chrome from highlighting missing fields?

P.S. I am able to provoke Chrome to highlight all required fields, though I haven't yet figured out how to do so consistently.

screen shot 2015-03-18 at 3 13 09 pm

**Comment by whit537** [comment]
> Is that better?

Somewhat. I'm not going to worry about it further here, because honestly we need to look at our forms overall, just as we need to look at our tables/listings overall (#3222). Reticketed as #3267 and noted on #3220.

**Pull request merged**
