### PR TITLE
turn off taking

### PR DESCRIPTION
**Pull request by whit537**
Keep the files around, but move them underneath /team/ and disable them for now.

### CODE REVIEW

**Comment by whit537** [comment]
Incorporates #3405.

**Comment by rohitpaulk** [comment]
@whit537 - Even if you plan on merging PRs yourself, can we please stick to using the 'Review' label?

**Comment by rohitpaulk** [comment]
Looks like this is done, merging.

**Comment by whit537** [comment]
> Even if you plan on merging PRs yourself, can we please stick to using the 'Review' label?

Yes, sorry.

> Looks like this is done, merging.

Thanks.

**Pull request merged**
