### PR TITLE
plumb takes

### PR DESCRIPTION
**Pull request by whit537**
&#x2B11; #3994

&larr; #4070 — #4024 &rarr;

#### Punchlist 

- [x] `Takes determines` &rarr; `Takes determine`
- [x] There is no Membership mixin yet (docstring).
- [x] require working payout route
- [x] add `recorder` to both methods
- [x] upgrade `ntakes` to `bigint`
- [x] ~~prevent the owner from claiming takes (they get baseline and unclaimed)~~ https://github.com/gratipay/gratipay.com/pull/4023#issuecomment-218736015
- [x] update `participants.taking`
- [x] ~~move cacherinoes into Postgres (triggers)~~ nevermind &rarr; #4064
- [ ] prune the old _mixin_teams.py file
- [ ] handle takes during `take_over`
- [ ] remake against `master` once #4070 lands

### CODE REVIEW

**Comment by whit537** [comment]
> prevent the owner from claiming takes (they get baseline and unclaimed)

Actually, let's leave this up to the teams to decide, ya?

**Comment by whit537** [comment]
I want to handle takes during `take_over` as with identities: hard-failing (we really should already be failing for or otherwise handling the case where one account takes over another that owns one or more teams). The easiest way to handle this will be with a check for `other.ntaking_from > 0`, so that gets back to the other open item on the punchlist: updating `taking` and `ntaking_from`. Since takes are proportional now instead of absolute, changes to one person's takes affect the `taking` of all other members of the team, plus the owner. Working it through ...

**Comment by whit537** [comment]
`ntaking_from` is easy. It's `taking` that's difficult.

**Comment by whit537** [comment]
Bringing over here from https://github.com/gratipay/gratipay.com/issues/3994#issuecomment-218772237 ...

> I'm working on writing `update_taking` as a PL/pgSQL function, because I don't see how to write it in Python without too many database calls.

------------

> Looks like we can do it in Python and write back to the database once per team with [this mechanism](http://stackoverflow.com/a/18799497).

Now we're thinking we might try with trigger functions on `UPDATE` in Postgres.

**Comment by whit537** [comment]
What needs to change when?

###### on `INSERT` into `takes`

 - for the participant:
  - `ntaking_from`
  - `taking`
 - for team mates:
  - n/a
 - for the owner:
  - n/a
 - for the team:
  - `ndistributing_to`
  - `distributing`
  - `surplus`


###### on `UPDATE` of `teams.receiving`

 - for the owner:
  - `taking`
 - for all members:
  - `taking`
 - for the team:
  - `distributing`
  - `surplus`

**Comment by whit537** [comment]
Cached values updates in triggers is looking promising: 3fb940ad0810a8dda51951ac32dd3cac19ed76b1.

**Comment by whit537** [comment]
Following in the illustrious lineage of cached values work #3599, #3721, and #3729 ...

We're now experimenting with calling them "computed" values as opposed to ... what? "Primary" values? "Original" values? "Real" values? "Independent" values? "Assigned" values? "Root" values? "Input" values? "Raw" values? "Observed" values? "Given" values?

Here are the four given values:

| i | name | property&nbsp;of | description |
|---:|:--------|:-------|:-------------|
| 1 | **payment&nbsp;instruction** | participant | amount of money the participant intends to pay a given team, weekly |
| 2 | **takes&nbsp;issued** | team | total number of parts into which money available for weekly distribution will be divided |
| 3 | **baseline** | team | threshold below which no money will be distributed in any given week |
| 4 | **takes&nbsp;claimed** | participant | number of parts of a given team's weekly distribution of money that the participant intends to collect |

All the other numbers we care about can be computed from those four:

| i | name | property&nbsp;of | function |
|---:|:--------|:-------|:-------------|
| 1 | _giving_ | participant | sum of **payment instructions** from the given participant |
| 2 | _ngiving_to_ | participant | number of **payment instructions** from the given participant |
| 3 | _receiving_ | team | sum of **payment instructions** to the given team |
| 4 | _nreceiving_from_ | team | number of **payment instructions** to the given team |
| 5 | _claimed takes_ | team | sum of **takes claimed** from the given team |
| 6 | _unclaimed takes_ | team | **takes issued** - _claimed takes_ |
| 7 | _taking_ | participant | (**takes claimed** / **takes issued**) * (_receiving_ - **baseline**) |
| 8 | _ntaking_from_ | participant | count of **takes claimed** by the given participant |
| 9 | _distributing_ | team | sum of _taking_ for all members of the given team<br>=<br>(_claimed takes_ / **takes issued**) * (_receiving_ - **baseline**)|
| 10 | _ndistributing_to_ | team | count of **takes claimed** for the given team |
| 11 | _surplus_ | team | _receiving_ - **baseline** - _distributing_ |

-------------

**given values** are bold
*computed values* are in italics

**Comment by mattbk** [comment]
"Computed values" makes much more sense to me than "cached values" for this sort of thing, FWIW.

"Entered values"?

**Comment by whit537** [comment]
> "Computed values" makes much more sense to me than "cached values" for this sort of thing, FWIW.

Cool. 👍 

> "Entered values"?

Hmm, maybe ...

**Comment by whit537** [comment]
We may also want to work "take" into the chart, as the dollar amount a given participant is collecting from a given team.

**Comment by whit537** [comment]
> We may also want to work "take" into the chart, as the dollar amount a given participant is collecting from a given team.

Actually, that's just a payment in the `payments` table. That's not a value we need to compute and store somewhere in `participants` or `teams`.

**Comment by whit537** [comment]
Alright, I think the chart is good. ~users may express both "membership" (by participating in takes) and "ownership" (a priori) in a given team.

**Comment by whit537** [comment]
### Old

```
payment_instruction
    giving
    ngiving_to
    receiving
    nreceiving_from
takes_issued
    distributing
    taking
takes_claimed
    ndistributing_to
    taking
    ntaking_from
receiving
    distributing
    taking
owned
    ntaking_from

giving              payment_instruction
ngiving_to          payment_instruction
receiving           payment_instruction
nreceiving_from     payment_instruction
distributing        claimed_takes       takes_issued        receiving
ndistributing_to    takes_claimed
taking              takes_claimed       takes_issued        receiving
ntaking_from        takes_claimed       owned
```

### New

```
payment_instruction
    giving
    ngiving_to
    receiving
    nreceiving_from
baseline
    distributing
    surplus
    taking
takes_issued
    unclaimed_takes
    distributing
    taking
takes_claimed
    claimed_takes
    unclaimed_takes
    ndistributing_to
    taking
    ntaking_from
claimed_takes
    distributing
receiving
    distributing
    surplus
    taking
distributing
    surplus
surplus
    taking
owned
    ntaking_from


giving              payment_instruction
ngiving_to          payment_instruction
receiving           payment_instruction
nreceiving_from     payment_instruction
claimed_takes       takes_claimed
unclaimed_takes     takes_issued        takes_claimed
distributing        claimed_takes       takes_issued        receiving           baseline
ndistributing_to    takes_claimed
surplus             receiving           baseline            distributing
taking              takes_claimed       takes_issued        receiving           baseline    surplus
ntaking_from        takes_claimed       owned
```

**Comment by whit537** [comment]
### New

```
payment_instruction
    giving
    ngiving_to
    receiving
    nreceiving_from
baseline
    distributing
    surplus
    taking
takes_issued
    unclaimed_takes
    distributing
    taking
takes_claimed
    claimed_takes
    unclaimed_takes
    ndistributing_to
    taking
    ntaking_from
claimed_takes
    distributing
receiving
    distributing
    surplus
    taking
distributing
    surplus
surplus
    taking
owned
    ntaking_from


giving              payment_instruction
ngiving_to          payment_instruction
receiving           payment_instruction
nreceiving_from     payment_instruction
claimed_takes       takes_claimed
unclaimed_takes     takes_issued        takes_claimed
distributing        claimed_takes       takes_issued        receiving           baseline
ndistributing_to    takes_claimed
surplus             receiving           baseline            distributing
taking              takes_claimed       takes_issued        receiving           baseline    surplus
ntaking_from        takes_claimed       owned
```

**Comment by whit537** [comment]
The way to read those is that the bottom part lists the variables (out to the right) that are dependencies of the variables down the left. E.g., `surplus` has three dependencies:

```
surplus             receiving           baseline            distributing
```

Then the top part lists all variables that need to be updated when a given variable changes, so when `surplus` changes, one other variable needs to be updated:

```
surplus
    taking
```

I'm thinking that we should reimplement the "Old" variables as triggers, either in https://github.com/gratipay/gratipay.com/pull/4037 or in a new PR that we insert into the chain before this one. Then we should include triggers for the new variables on this PR.

**Comment by mattbk** [comment]
Something like this? (http://www.webgraphviz.com/)

image


`digraph G {  
"giving" -> "payment_instruction" [dir=back]  
"ngiving_to" -> "payment_instruction" [dir=back]  
"receiving" -> "payment_instruction" [dir=back]  
"nreceiving_from" -> "payment_instruction" [dir=back]  
"claimed_takes" -> "takes_claimed" [dir=back]  
"unclaimed_takes" -> "takes_issued" [dir=back]  
"unclaimed_takes" -> "takes_claimed" [dir=back]  
"distributing" -> "claimed_takes" [dir=back]  
"distributing" -> "takes_issued" [dir=back]  
"distributing" -> "receiving" [dir=back]  
"distributing" -> "baseline" [dir=back]  
"ndistributing_to" -> "takes_claimed" [dir=back]  
"surplus" -> "receiving" [dir=back]  
"surplus" -> "baseline" [dir=back]  
"surplus" -> "distributing" [dir=back]  
"taking" -> "takes_claimed" [dir=back]  
"taking" -> "takes_issued" [dir=back]  
"taking" -> "receiving" [dir=back]  
"taking" -> "baseline" [dir=back]  
"taking" -> "surplus" [dir=back]  
"ntaking_from" -> "takes_claimed"  [dir=back]  
"ntaking_from" -> "owned" [dir=back]  
}`

**Comment by whit537** [comment]
@mattbk Nice! @kaguillera and I were saying we should make a graph. :-)

Could also through it in http://interactive.blockdiag.com/?

**Comment by mattbk** [comment]
Not sure if [blockdiag](http://interactive.blockdiag.com/?compression=deflate&src=eJyVklsKwjAQRf9dRci_S9CNiIS8LEPTieShiLh3i5WSpGlo_wI9t3PmJsJY2SvgHXkfaAcPwI6S45nQO38NGgMD9MFFGcAiJRcF7iS47K-E4kSzYDcGnJZ614A5wG7ODhtT0nAYtGKB99pPmd-R_T_kdMRVHryPO_Dq7xWMliBimLcu8m14XWTJJu22QcG9NoC6KDsF5zttrOaju5vom8Mzpj43Q3LZFBtFilaqUkusVl5KrZinSF08JeYlskYnInm7DfElbJ9YQJ8vZQRDXQ) shows things the same way; the overlapping lines are confusing.

image

**Comment by whit537** [comment]
Yeah, that's definitely less clear.

**Comment by kaguillera** [comment]
!m @mattbk

**Comment by whit537** [comment]
Rebased, previous head was 3fb940ad0810a8dda51951ac32dd3cac19ed76b1.

**Comment by whit537** [comment]
Based on https://github.com/gratipay/gratipay.com/issues/3994#issuecomment-229796292, for simplicity's sake let's assume for now that a Team will always have enough to cover the amount they're making available for payouts each week. This should be sufficient for #3994, at least.

**Comment by whit537** [comment]
Scraping for parts.

**Pull request closed without merging**
