### PR TITLE
"Pay for Open Source" form on homepage

### PR DESCRIPTION
**Pull request by whit537**
&larr; #4616

Pursuant to https://github.com/gratipay/inside.gratipay.com/issues/987 and https://github.com/gratipay/gratipay.com/issues/4427, this PR moves the project listing off of the homepage and replaces it with a form to "Pay for Open Source."

## Todo

- [x] homepage form
  - [x] fix test suite
  - [x] link to blog post: #4602 
  - [x]  blippy blip: #4603
  - [x] batch some pre-reqs: #4606 
  - [x] implement JSON endpoint for basic form: #4604
  - [x] clean up JSON endpoint for basic form: #4617
  - [x] wire up form to hit endpoint: #4613 
  - [x] implement error checking: #4621
  - [x] ~~rationalize Optional sections~~ &rarr; #4609
  - [x] ~~"Choose an Ecosystem"~~ &rarr; #4610
  - [x] ~~"Invoice Details"~~ &rarr; #4612
  - [x] nice to have:
    - [x] ~~style credit card form~~: can't easily due to iframe ([slack](https://gratipay.slackarchive.io/gratipay/page-100/ts-1504804524000146))
    - [x] ~~fix css bug w/ radio~~: [slack](https://gratipay.slackarchive.io/gratipay/page-100/ts-1504803995000286)
- [x] receipt: #4611
- [x] update terms of service: (~~#4599~~ &) #4600
- [x] ~~`/browse/payments` page~~ &rarr; #4607
- [x] ~~make a charger to stub out Braintree in test? (a la ConsoleMailer, etc.)~~ Travis seems fine post-#4616?

## Deploy

- [x] wire up [custom field](https://articles.braintreepayments.com/control-panel/custom-fields#creating-a-custom-field) `pfos_uuid`

### CODE REVIEW

**Comment by mattbk** [comment]
Thoughts as a potential company:
- what sort of file do I upload?
- how do I know how many technical employees a project has?
- what would an example tweet look like?

**Comment by whit537** [comment]
2780b0fadc8eb4e7989742c163025e671391767e:

3blr3nawiv

**Comment by whit537** [comment]
> what sort of file do I upload?

I have a UI in mind for that section of the form, hinted at in 2780b0fadc8eb4e7989742c163025e671391767e.

screen shot 2017-09-06 at 7 52 06 pm

Stay tuned ...

> how do I know how many technical employees a project has? Or if I have a lot of projects to give to, is there an average number I can use?

That's actually supposed to be *your* technical employees. Clarified sufficiently in 6a3285af020d8fc645b2d9309e43e185f1c994de?

screen shot 2017-09-06 at 7 48 53 pm

> what would an example tweet look like?

Hmm ... I was trying to leave this vague because I have no idea, really. Maybe we automate tweets eventually but probably not for a while and maybe never? To start we'll just manually tweet things out based on customer input. Nice and natural and organic. Longer term I actually have https://github.com/gratipay/gratipay.com/issues/1513 in mind with this. Once we collect the info it should be pretty easy to spit out SVGs for READMEs.

**Comment by whit537** [comment]
Initial feedback from @jdorfman in private Slack chat:

- "I love the button, 'Pay for Open Source'"
- "the `N,NNN X N` is kinda confusing"
- "love it"

**Comment by whit537** [comment]
<details>
<summary>f557e1ebdb2f23f7de734b05ce311322a45fb6c8</summary>

</details>

**Comment by whit537** [comment]
<details><summary>8c02f8b516a5dd5d035f8044ce8253ac7723ae6a</summary>



</details>

**Comment by whit537** [comment]
Alright, once this is green I'm going to start using this as an integration branch for further work, ∆ is already 483 and we have a number of other things to do, not just on this form but that need to be deployed at the same time as the form.

**Comment by whit537** [comment]
Green! Rebasing on master ...

**Comment by whit537** [comment]
Rebased, was 3d5faf00494abb9fedfcb671e1f00d86177a658c.

**Comment by whit537** [comment]
Alright, that's four chunks of work remaining:

1. form wireup (big, includes db table(s), hold, & email dance), 
1. implement ecosystem chooser (`ecosystems` table prepoped like `countries` but with logos(?), plus table to hold CSV uploads w/ (`package manager`, `uid`, `weight`))
1. terms of service (thinking basically a separate section governing this form based on [VML](http://phk.freebsd.dk/VML/) vs. existing payments flow)
1. `/browse/payments` is our primary bragging outlet (besides Twitter) to start with, also where admins can see pending (no email verified) payments

**Comment by whit537** [comment]
Pushed off cancel homepage commits (moving those to a PR), was fe84e52831b478dc9e708f8026d412f3a2074f7e.

**Comment by whit537** [comment]
Also rebased on master.

**Comment by whit537** [comment]
Per [slack](https://gratipay.slackarchive.io/gratipay/page-100/ts-1504966628000005) w/ +1s from @clone1018 and @dowski I am planning to try to self-merge and deploy this work ahead of https://github.com/gratipay/inside.gratipay.com/issues/1044.

**Comment by whit537** [comment]
Rebased onto #4616, was ed46b9b3df64e2287a2e23c6a5001a85b7e8e47a.

**Comment by whit537** [comment]
Something tells me @jdorfman and I are going to deploy this tonight. 😀

**Comment by whit537** [comment]
I'm getting ready to merge the next and final chain: #4621 &rarr; #4611 &rarr; #4600.

**Comment by whit537** [comment]
Let's see what Travis does with this. If green I think we are ready to merge and deploy! 😱

**Comment by whit537** [comment]
Testing out locally on this here integration branch.

**Comment by whit537** [comment]
Once Travis is green I plan to go for it—merge and deploy!

**Comment by whit537** [comment]
Waiting for Travis again ...

**Pull request merged**
