### PR TITLE
Some UX cleanups for package claiming

### PR DESCRIPTION
**Pull request by whit537**
Part of #4305, follows on #4422.

- [x] gray out the wombat so it feels more like a default
- [x] add an npm indicator in project listings
- [x] knock out https://github.com/gratipay/gratipay.com/issues/4394 please

### CODE REVIEW

**Comment by whit537** [comment]
Working up a new default image (no wombat):

package-default-large &nbsp; &nbsp; &nbsp; image


Started with:

https://www.iconfinder.com/icons/730810/box_order_package_parcel_post_postage_shop_icon

**Comment by whit537** [comment]
In situ:

screen shot 2017-04-12 at 7 28 08 am

Now for npm indicator ...

**Comment by whit537** [comment]
More in situ:

screen shot 2017-04-12 at 7 30 33 am

screen shot 2017-04-12 at 7 30 48 am

**Comment by whit537** [comment]
With the npm indicator we're coming back up against the discrepancy between the social profile listings and the project listings. I'm still not going to worry about harmonizing those yet.

screen shot 2017-04-12 at 7 34 12 am

**Comment by whit537** [comment]
screen shot 2017-04-12 at 7 54 04 am

-----------------

screen shot 2017-04-12 at 7 53 30 am

-----------------

screen shot 2017-04-12 at 7 54 09 am

**Comment by mattbk** [comment]
:drooling_face:

**Comment by whit537** [comment]
a04acf4df71417be804af7dfdcb7330027f8d9a0

screen shot 2017-04-12 at 6 00 27 pm

**Comment by whit537** [comment]
# Short

screen shot 2017-04-12 at 6 03 35 pm

# Medium

screen shot 2017-04-12 at 6 03 19 pm

# Long

screen shot 2017-04-12 at 6 04 25 pm

**Comment by whit537** [comment]
```
gratipay=# select name, char_length(description) as len from packages order by len desc limit 10;
┌──────────────────┬─────┐
│       name       │ len │
├──────────────────┼─────┤
│ tower-view       │ 939 │
│ jquery-cropbox   │ 842 │
│ shubhadownloader │ 771 │
│ perstore         │ 749 │
│ schematic        │ 719 │
│ pomelo-protobuf  │ 689 │
│ resume-generator │ 615 │
│ clever-survey    │ 585 │
│ platformenv      │ 577 │
│ JSDev            │ 563 │
└──────────────────┴─────┘
(10 rows)

gratipay=#
```

**Comment by whit537** [comment]
# Lol

screen shot 2017-04-12 at 6 08 17 pm

**Comment by whit537** [comment]
Maybe we will need to vary text size based on content length?

screen shot 2017-04-12 at 6 09 02 pm

screen shot 2017-04-12 at 6 10 24 pm

**Comment by whit537** [comment]
For comparison: webpack 227, mysql 110, aspen 61.

**Comment by whit537** [comment]
56958854606b77d09e56821b344409f5fd1850ad

screen shot 2017-04-12 at 6 14 49 pm

**Comment by whit537** [comment]
The opposite case. a7f668ecc6a44e65357cf6bdb969ad571427490b

screen shot 2017-04-12 at 6 21 04 pm

**Comment by whit537** [comment]
Next up: styling unclaimed package for auth!

:nauseated_face: 

screen shot 2017-04-12 at 6 24 25 pm

**Comment by kaguillera** [comment]
!m @whit537 
Looks good so far.

**Comment by whit537** [comment]
screen shot 2017-04-13 at 4 31 54 pm

**Comment by whit537** [comment]
```
gratipay=# select name, array_length(emails, 1) as n from packages where array_length(emails, 1) is not null order by n desc limit 10;
┌───────────────────┬────┐
│       name        │ n  │
├───────────────────┼────┤
│ colonel-mercator  │ 68 │
│ mapbox-file-sniff │ 66 │
│ ec2mnt            │ 66 │
│ mbview            │ 65 │
│ cfn-config        │ 64 │
│ vector-tile-query │ 64 │
│ kine              │ 64 │
│ guidance-replay   │ 61 │
│ guidance-geojson  │ 60 │
│ guidance-sim      │ 60 │
└───────────────────┴────┘
(10 rows)
```

**Comment by whit537** [comment]
screen shot 2017-04-14 at 2 15 15 pm

**Comment by whit537** [comment]
Right, so in reality almost all addresses will be "Ready to link" for some time to come.

screen shot 2017-04-14 at 2 26 37 pm

**Comment by whit537** [comment]
Working on a dropdown component (also useful for add social profile and country selector in identity page and &hellip; ?)

xej5xem8as

**Comment by whit537** [comment]
07d7e81ae65bed943f1b3e54ce65be4e5a4ba774

p7qgv8l0gs

**Comment by whit537** [comment]
Okay! That was a bit of a rabbit hole, and we're not clear yet. :-)

Obviously this is still a ways from being finished, and this PR is getting big. I am thinking I will break this into multiple PRs, since there's still more to add. I'm also not sure what's going to happen when I look at his dropdown component on a phone. Could turn into a total mess.

**Comment by mattbk** [comment]
Normal dropdowns usually degrade to mobile-friendly versions (essentially what you have) on mobile; is there a way to force that, or is there no check-for-mobile anywhere on the site?

**Comment by whit537** [comment]
Okay, claim form styling (inc. custom dropdown) broken out into #4410. Slew of todos moved back up to #4305.

**Comment by kaguillera** [comment]
A little concern I have with the claiming of a package. Not sure if it should be stated her but just want to put it somewhere. 
Any one of the maintainer's can claim the package, what if it is a maintainer that does not do much work on the package? Would that not be unfair? Should we leave the resolutions of that unfairness to the group of maintainers to resolve?

**Comment by whit537** [comment]
Worked this through a bit w/ @kaguillera IRL.

- Package projects still go through a review process.
- If we notify all other maintainers then that mitigates the issue, especially if we link to the review ticket.

**Comment by whit537** [comment]
Rebased, was 7b71a4ffab0518a258d904caec29ad75fbc3fd63.

**Comment by mattbk** [comment]
>  Should we leave the resolutions of that unfairness to the group of maintainers to resolve?

I think we should, at least at this stage (crossposted at https://github.com/gratipay/gratipay.com/pull/4305#issuecomment-297416468).

**Comment by whit537** [comment]
I think we just proceed with merging if you're good, @dowski. If there's nothing downright dangerous going on here then I think we're within our risk tolerance. :)

**Pull request merged**
