### PR TITLE
ledger

### PR DESCRIPTION
**Pull request by whit537**
Redo of #3653.

Questions for Peter:

 - Under what circumstances would you delete an account from the chart of accounts?
 - Under what circumstances would you change an account name or number in the chart of accounts? (I have this impression that sometimes one will "recode" a chart of accounts, restructuring it.)
 - What's the difference between a Trial Balance and a Ledger Summary?
 - What's the most natural IA? Statements, Ledgers, Journals across the top? Or Statements, General, $Specific across the top?
 - How about using the week for our accounting period?

### CODE REVIEW

**Comment by whit537** [comment]
screen shot 2015-09-16 at 10 21 05 am

**Comment by whit537** [comment]
My thinking here is that we should approach this by building out a mini-application with a chart of accounts and a general ledger, where admins can filter, sort, search, browse, and CRUD accounts and ledger entries, and *then* once we have the tables and UI in place, start porting existing processes and data over to the ledger.

**Comment by whit537** [comment]
screen shot 2015-09-16 at 1 08 33 pm
screen shot 2015-09-16 at 1 10 44 pm

**Comment by whit537** [comment]
screen shot 2015-09-16 at 1 35 32 pm
screen shot 2015-09-16 at 1 35 29 pm

**Comment by whit537** [comment]
screen shot 2015-09-16 at 3 25 57 pm
screen shot 2015-09-16 at 3 26 08 pm

**Comment by whit537** [comment]
Getting a little ahead of myself, starting to think about chart of accounts structure (after realizing that we don't need a separate "type" field since the type is encoded in the number) ...

screen shot 2015-09-16 at 4 40 08 pm

**Comment by whit537** [comment]
We actually shouldn't need to *manually* add accounts that often, mostly when we set up a new bank account or payments vendor. I don't believe we'll ever want to delete an account that has any transactions on it (a question for Peter).

**Comment by whit537** [comment]
Alright, so let's get some accounts persisting, and then turn to transactions ...

**Comment by whit537** [comment]
screen shot 2015-09-16 at 9 26 54 pm

**Comment by techtonik** [comment]
That looks like rocket science from finance world to me. Is it possible to call it somehow differently for people who is not an expert in accounting? I have a natural interest in this stuff, so tried to watch a few videos on khan academy, but I expect that majority of users are not that involved to learn what this `ledger` is about.

How about?

  - ledger   --   moneylog
  - asset    --   debts to me
  - liability   --  my debts

And hey! It looks like we will be able to do this - https://sfconservancy.org/npoacct/

**Comment by whit537** [comment]
> Is it possible to call it somehow differently for people who is not an expert in accounting?

I think we should use standard accounting terminology, because eventually the goal is to have accountants on our Team, helping us manage our company. The point here is to build a system that accountants will be comfortable with. I'm meeting with an accountant next week to make sure we're achieving that.

**Comment by whit537** [comment]
I've started integrating HTML documentation with the new `/api/` endpoints.

screen shot 2015-09-17 at 12 05 15 pm

screen shot 2015-09-17 at 12 06 01 pm
screen shot 2015-09-17 at 12 06 06 pm
screen shot 2015-09-17 at 12 06 12 pm
screen shot 2015-09-17 at 12 06 14 pm

**Comment by whit537** [comment]
I really like how this is coming along, with the integrated API docs.

screen shot 2015-09-17 at 4 23 49 pm

**Comment by whit537** [comment]
The next step on this PR is to implement the general ledger. I believe the accounts schema/API will need to change to support what we want for the ledger. One of the things we want is auditability. We want to be able to know who changed accounts when.

**Comment by whit537** [comment]
We also need to keep track of the balance for each account. I'm thinking about implementing this using our `INSERT`-only pattern as with `payment_instructions`, etc. Then `balance` here would be like `is_funded` there.

**Comment by whit537** [comment]
Oooooooo ... multicurrency? I'm looking at http://www.ledger-cli.org/3.0/doc/ledger3.html#Keeping-a-Journal.

**Comment by whit537** [comment]
"Commodities" are pretty low down in Ledger's design: http://www.ledger-cli.org/3.0/doc/ledger3.html#Internal-Design.

**Comment by whit537** [comment]
I think currency/commodity attaches to an account, so for a Coinbase payout we'd have a 50 against a Gratipay account denominated in USD, and 0.1 against Gratipay's Coinbase account, which would be denominated in BTC.

**Comment by whit537** [comment]
"[Ledgers summarize the balances of the accounts in the chart of accounts.](http://www.myaccountingcourse.com/accounting-basics/accounting-ledger)"

**Comment by whit537** [comment]
"[Unlike other financial accounting statements, the general ledger is where all account activity is posted with debits and credits.](http://www.brighthub.com/office/finance/articles/113290.aspx)"

**Comment by whit537** [comment]
But, "[You will take the information from these journals and place the information into your general ledger.](http://www.brighthub.com/office/finance/articles/72981.aspx#imgn_0)" So confusing. :-/

**Comment by whit537** [comment]
"[Journal entries made into the general ledger [...]](http://www.brighthub.com/office/finance/articles/67624.aspx)" Not less confusing.

**Comment by whit537** [comment]
"[[T]his process of transferring data from journal to ledger is called posting.](http://www.accounting-tutorial.com/definition-format-accounting-ledger)"

**Comment by whit537** [comment]
accounting-ledger

**Comment by whit537** [comment]
> The process of gathering and storing Financial Transaction data in the Accounting System is accomplished through the use of both:
>
> - **Ledgers:** which maintain Account Balances
> - **Journals:** which maintain the line by line detail of each Transaction.

http://www.accountingunplugged.com/category/4-ledgers-and-journals/

**Comment by whit537** [comment]
> The General Ledger is the combination of the Chart of Accounts, Financial Transactions, Account Balances and Accounting Periods.  In practice, once the Chart of Accounts has been established, the term “Chart of Accounts” is considered more in terms of a report than as an object.  From this point forward, Accounts from the Chart of Accounts will be called General Ledger Accounts.

http://www.accountingunplugged.com/2008/09/03/general-ledger-accounting-periods/

**Comment by whit537** [comment]
> The General Ledger adds the essential organizational element of Time (Accounting Periods) to the Accounting System[.]

**Comment by whit537** [comment]
> Since the system requires that all financial transactions have an entry in the General Ledger, they must also have an entry in the General Journal. This requires some duplication of effort but it is necessary.

http://www.accountingunplugged.com/2008/09/19/accounting-journals-and-ledgers/

Most helpful site so far.

**Comment by whit537** [comment]
> The Path of entries for Financial Entries:
>
[...]
>
Subsidiary Journal –> Post to Subsidiary Ledger by its Account –> Post to General Journal —-> Summarize and post to General Ledger by GL Account.

**Comment by whit537** [comment]
We may want subsidiary ledgers for ~users and Teams, or maybe payins and payouts.

**Comment by whit537** [comment]
Phew! Okay! Head is full, but I think that site is going to be my go-to as I work on this.

**Comment by whit537** [comment]
The task here is to design an accounting system that uses the same basic building blocks as the generally accepted accounting system for managing a company's operations, but adapted for managing our escrow. We'll have general and subsidiary journals and ledgers, but the chart of accounts will be a bit different.

**Comment by whit537** [comment]
If we carve it right, we can show the general journal and ledger to anon along with the reports (trial balance, balance sheet, income statement), and restrict the subsidiary journals/ledgers to admins.

**Comment by whit537** [comment]
Rebased on master, old HEAD is 1a779a8983a0787346083eddee65c18cecbb1ef2.

**Comment by whit537** [comment]
Alright, so I've got a pretty good sense of how journals and ledgers are supposed to function within "normal" accounting ... let's call it? What are the right names for an escrow account vs. non-escrow?

> The total balance in escrow is shown on a company's balance sheet at the end of every period, either as a liability or in a section between liabilities and equity. The separate bank account that the escrow funds are held in is shown as a current asset outside of the company's operating account. In this way, the escrow funds are both an asset and a liability in the company and are a "wash." However, the accounts cannot be netted against each other because they must be visible as both asset and liability according to GAAP.

http://www.ehow.com/info_11384335_accounting-treatment-escrow-account.html

**Comment by whit537** [comment]
[Financial vs. management accounting](http://basiccollegeaccounting.com/2006/10/financial-accounting-versus-management-accounting/): we're talking about financial accounting.

I think "operational accounting" is right:

> Operational accounting is the practice of minding the financial aspects of running a business, whether small or large. Operational accountants are directors, controllers, and planners. They often plan a business’s financial operations, as well as mind a company’s ledger while working with executive management to create and control budgets. They’re also responsible for ensuring that actual business activities are in line with the organization’s plans. To do so they provide management with detailed financial reports that compare actual revenues and expenses with what the original estimations were.

http://www.accountingdegree.com/operational-accounting/

> Operational accounting is concerned with the financial aspects of running a company. The three main areas of focus are planning, directing and controlling. An operational accountant analyzes the impact of the company's daily activities on the balance sheet and reviews current accounting processes to find problem areas or inefficiencies. For future projections, the accountant can run reports to test possible scenarios before management makes any final decisions. Depending on the size of the company, the operational accountant may be an in-house employee or work as an independent contractor.

http://smallbusiness.chron.com/operational-accounting-80552.html

**Comment by whit537** [comment]
Alright, so we are implementing an escrow accounting system:

```
accounting 
  |
  +-- financial
  |     |
  |     +-- operational
  |     |
  |     +-- escrow     <- us, on this PR
  |
  +-- management
```

> **Escrow Accounting Formula**
>
Assets = Liabilities. There is no equity as in the normal accounting formula. 

http://www.tdi.texas.gov/title/documents/BASICS.pdf (used to be in our repo :-)

**Comment by whit537** [comment]
> Accounting has several subfields or subject areas, including financial accounting, management accounting, auditing, taxation and accounting information systems.

https://en.wikipedia.org/wiki/Accounting#Topics

**Comment by whit537** [comment]
Alright, so we're implementing an escrow accounting system. This will bubble up into Gratipay's operational accounting as a line-item in our global balance sheet, under liabilities (post-https://github.com/gratipay/inside.gratipay.com/issues/308).

**Comment by whit537** [comment]
Here's a couple YouTube videos explaining the process of "journalizing" transactions, i.e., entering them into an accounting system from source documents:

https://www.youtube.com/watch?v=QkgF1-6aOwQ (short)
https://www.youtube.com/watch?v=toNFWLPYaNE (long)
https://www.youtube.com/watch?v=hOW5l2Mtw54 (goofy)

**Comment by whit537** [comment]
Are we going to store just the journal entries? Or are we also going to store the summarized ledger entries?

**Comment by whit537** [comment]
That is, are we going to cache or compute the ledger entries?

**Comment by whit537** [comment]
We can use the `participants` and `teams` tables as the chart of accounts for our ~users and Teams subledgers. The `id` will be the account number, and the `username` or `name` can be the account name. We need a new table for general ledger accounts.

**Comment by whit537** [comment]
We've got three pieces to this puzzle:

 - accounting concepts
 - user interface
 - database schema

**Comment by whit537** [comment]
For UI IA here's what I'm thinking:

screen shot 2015-09-21 at 1 42 27 pm

"Reports" would include the balance sheet and the income statement.

"[Beginners' Guide to Financial Statements](http://www.sec.gov/investor/pubs/begfinstmtguide.htm)"

**Comment by whit537** [comment]
s/Reports/[Statements](https://en.wikipedia.org/wiki/Financial_statement)

**Comment by whit537** [comment]
screen shot 2015-09-21 at 1 52 29 pm

**Comment by whit537** [comment]
All of the specific screens should like an accountant will expect them to look. The purpose of the meeting on Wednesday is to ensure that they do.

**Comment by whit537** [comment]
We could also flip the axes (as it were), and have General, ~users and Teams be the top-level, and Ledger and Journal be the secondary level. My hunch is that this would be weirder to an accountant than Statements, Ledgers, Journals, but I guess we'll have to wait until Wednesday to find out. I'm going to proceed based on my hunch (which virtually guarantees that my hunch is wrong :).

screen shot 2015-09-21 at 2 00 09 pm

**Comment by whit537** [comment]
I like Statements, Ledgers, Journals because it goes from general to specific.

**Comment by whit537** [comment]
I'm trying to understand these three, how they relate, and where they fit:

 - Ledger Summary
 - Ledger Detail
 - [Trial Balance](http://www.accountingunplugged.com/2008/09/05/financial-statements-trial-balance/)
 - Comparison Trial Balance

**Comment by whit537** [comment]
> The listings above are Ledger Account summaries. Both the General Ledger and the Subledgers actually have a more detailed section for each Account. Those sections include summarized entries and balances along with references indicating which journals those entries originated in.

http://www.accountingunplugged.com/2008/09/19/accounting-journals-and-ledgers/

The YouTube videos show the detail view she's talking about.

**Comment by whit537** [comment]
Sorry, journalizing transactions means entering them into a journal based on an analysis of a source document. Recording transactions from a journal to a ledger is called "posting."

 1. Receive a source document for a transaction.
 1. Analyze the source document to determine which accounts to debit and credit for the transaction.
 1. Journalize the transaction (record it in a journal).
 1. Post the transaction (record it in a ledger).

**Comment by whit537** [comment]
Here's the vid that shows the ledger detail: https://www.youtube.com/watch?v=QkgF1-6aOwQ.

screen shot 2015-09-21 at 2 22 29 pm

**Comment by whit537** [comment]
See also: https://github.com/gratipay/gratipay.com/pull/3786#issuecomment-141234741.

**Comment by whit537** [comment]
> The General Ledger takes the information from transactions and summarizes it by Account and by Accounting Period.  The four basic Financial Statements present General Ledger (GL) Accounts and their balances by specific date ranges, usually accounting periods. The four basic financial statements are:

 - Trial Balance
 - Income Statement (Profit and Loss)
 - Balance Sheet
 - Cash Flow Statement

http://www.accountingunplugged.com/2008/09/05/financial-statements-trial-balance/

Alright, so I guess Trial Balance goes under Statements, and we handle Comparison Trial Balance with a time knob.

**Comment by whit537** [comment]
> Escrow Trial Balance - A list of all open individual escrow ledger record balances at the
end of the month. 

http://www.tdi.texas.gov/title/documents/BASICS.pdf

What are the implications of that?

**Comment by whit537** [comment]
What's the difference between a Trial Balance and a Ledger Summary?

**Comment by whit537** [comment]
Is the Ledger Summary pegged to "now," whereas the Trial Balance could be run for a different date?

**Comment by whit537** [comment]
Separate thought: if ~users give to and take from Teams, is it intelligible for those to be separate subledgers? Seems like they should be together in one subledger ... which brings us pretty close back around to `exchanges` (general ledger) and `payments` ("intra" ledger?). ;-)

**Comment by whit537** [comment]
Except that we want to expand the general ledger to include information about our bank accounts and payment processors.

**Comment by whit537** [comment]
What's our accounting period? The week?

**Comment by whit537** [comment]
That would seem the most natural fit given our history.

**Comment by whit537** [comment]
Let's say it's the week.

**Comment by whit537** [comment]
I like the typography on the ledger detail in the book used in https://www.youtube.com/watch?v=D96wao4iZn8:

screen shot 2015-09-21 at 2 51 51 pm

**Comment by whit537** [comment]
Alright, so let's show a ledger summary at:

`./ledgers/general`
`./ledgers/~users`
`./ledgers/Teams`

And a ledger account detail at:

`./ledgers/general/100`
`./ledgers/~users/1234` (maybe redirect `~username` to `1234` for convenience?)
`./ledgers/Teams/2345`

**Comment by whit537** [comment]
Let's not worry about a Trial Balance for this PR.

**Comment by whit537** [comment]
Let's move the account creation/modification to the general ledger summary. For ~users and Teams, account creation and modification happens in the course of ~user registration and Team application.

Do ~users and Teams subledgers make sense, though?

**Comment by whit537** [comment]
What are the GL control accounts that we would have? I suppose we'd have a "~user balances" and "Team balances."

**Comment by whit537** [comment]
The typical examples of subledgers are AR and AP, where the accounts in the former are customers, and the latter, vendors.

**Comment by whit537** [comment]
How do income and expense factor in? Seems like that gets us into Gratipay's operational accounting.

Braintree, etc.'s fees are expenses to Gratipay. We pass them through as fees to our ~users, which is income for us.

**Comment by whit537** [comment]
> Cash Disbursement Journal - The accounting subsidiary ledger on which are listed all
checks disbursed from the escrow trust account in sequential order.
>
> Cash Receipt Journal - The accounting subsidiary ledger on which are listed all funds
deposited to the escrow bank account. 

http://www.tdi.texas.gov/title/documents/BASICS.pdf

**Comment by whit537** [comment]
> Individual Escrow Ledger Record - Record maintained for accounting purposes to show
actual receipts and disbursements on a daily basis and determine the funds available in
a specific file at any given time.

**Comment by whit537** [comment]
What are our source documents?

**Comment by whit537** [comment]
I think "source document" in our case is blurred because we're so automated. The database record *is* the source document, or the source document is notional. E.g., we're going to generate a receipt from the database record, not the other way around.

**Comment by whit537** [comment]
Maybe we rename `exchanges` to `receipts`? Maybe we have triggers on `exchanges` and `journal_entries` that make records in `journal_entries` and `ledger`?

**Comment by whit537** [comment]
From the [goofy one](https://www.youtube.com/watch?v=hOW5l2Mtw54):

screen shot 2015-09-21 at 3 51 41 pm

**Comment by whit537** [comment]
Maybe we rename `payments` to `invoices`, to reflect that those are the source documents for transactions that move money between Teams and ~users? But the meaning of the payment from a Team to a ~user depends on the relationship: owner, employer, or contractor. It's only an invoice in that case for the contractor relationship.

**Comment by whit537** [comment]
It would be win and perhaps a more achievable one on this PR if we simply start with a general ledger that covers our escrow accounts, without necessarily having the drill-down yet.

**Comment by whit537** [comment]
But first I want to redo the `accounts` schema to keep track of changes over time.

**Comment by whit537** [comment]
Alright, it is seeming foolish to me to reimplement an entire accounting system inside of Gratipay. Per the above comments https://github.com/gratipay/gratipay.com/pull/3786#issuecomment-142042638 and https://github.com/gratipay/gratipay.com/pull/3786#issuecomment-142045973, I'm now thinking about how the work on this PR relates to [setting up accrual accounting for Gratipay as a whole](https://github.com/gratipay/inside.gratipay.com/issues/308). It seems that we want to use a proper accounting package (Xero!) for Gratipay-as-a-whole. In which case, gratipay.com effectively becomes a subledger for our escrow liability.

**Comment by whit537** [comment]
I'm looking back over http://www.tdi.texas.gov/title/documents/BASICS.pdf ...

**Comment by whit537** [comment]
Alright, thanks to @kaguillera we are off and running with https://github.com/gratipay/inside.gratipay.com/issues/308. There's some great work on this PR towards a literate, integrated API. Perhaps one day we can scavenge it for parts. :-)

**Pull request closed without merging**
