### PR TITLE
Fix travis failure

### PR DESCRIPTION
**Pull request by whit537**
In the grand tradition of #4129 and #4290 ...

### CODE REVIEW

**Comment by whit537** [comment]
https://travis-ci.org/gratipay/gratipay.com/builds/196760317

screen shot 2017-02-01 at 1 48 04 pm

**Comment by whit537** [comment]
@JessaWitzel Ready for review! :)

re: [slack](http://gratipay.slackarchive.io/gratipay/-/1485523935.003906/1485895180.004016/1485881580003934/)

**Comment by whit537** [comment]
For posterity:

> It’s not your fault, it’s a spurious test failure.
I tried fixing it once recently but I guess it wasn’t enough.
The ttw tests (the ones that actually load a browser and click around) are sensitive to subtle timing changes.
Like, how long does it take to load the response after clicking a certain button?
Writing those tests is a balancing act between loooong tests (wait ten seconds after clicking the button), and testing too quickly (wait 10 milliseconds after clicking the button).
And we haven’t found the balance point yet on the particular test that’s failing. 🙂

**Comment by nobodxbodon** [comment]
Wow this sounds flaky. I guess there's no easy way to create some 'wait' method to listen for element change, and then verify if time elapsed isn't too long?

**Comment by whit537** [comment]
I think that's a good idea, but can we just do this for now? :-)

**Comment by whit537** [comment]
Bump (and rebased, was 1157e0d5458dc4ddaa2d09deddf8d76f9dcf9834).

**Comment by mattbk** [comment]
I'm happy with this.

**Comment by whit537** [comment]
@mattbk I think you could merge?

**Comment by whit537** [comment]
💃

**Pull request merged**
