### PR TITLE
upgrade postgres.py from 2.1.2 to 2.2.0

### PR DESCRIPTION
**Pull request by whit537**

### CODE REVIEW

**Comment by techtonik** [comment]
So, where is the postgres.py changelog to know what to test here?

**Comment by techtonik** [comment]
Also it looks like downgrade.

**Comment by whit537** [comment]
> Also it looks like downgrade in issue title.

Sorry, fixed. :-)

> So, where is the postgres.py changelog to know what to test here?

I almost wrote one for you, but didn't. Sorry. :-(

You'll have to refer to the [commit log](https://github.com/gratipay/postgres.py/commits/master) for now.

**Comment by whit537** [comment]
@techtonik Here are the two significant changes between 2.1.2 and 2.2.0:

https://github.com/gratipay/postgres.py/issues/26
https://github.com/gratipay/postgres.py/commit/55c69c09339da2bece6baedbcf5aa2d64d87db90

**Comment by rohitpaulk** [comment]
No issues raised, and this is marked as Review - going to merge.

**Comment by whit537** [comment]
Thanks @rohitpaulk! :-)

**Comment by rohitpaulk** [comment]
Oops! Found a bug, opening a PR..

**Comment by rohitpaulk** [comment]
https://github.com/gratipay/postgres.py/pull/53

**Comment by rohitpaulk** [comment]
cc: @whit537 - ^^ Production is going to break without that.

**Comment by whit537** [comment]
Roger that.

**Comment by whit537** [comment]
Blech. I mistook https://github.com/gratipay/postgres.py/pull/53 for a gratipay.com PR. :-(

https://github.com/gratipay/gratipay.com/pull/3807#issuecomment-147012273

**Comment by whit537** [comment]
Rolled back ...

**Pull request merged**
