### PR TITLE
Update index.html.spt

### PR DESCRIPTION
**Pull request by kzisme**
Fix regarding #2396 based on comments to improve wording for native and non-native English speakers.

### CODE REVIEW

**Comment by techtonik** [comment]
Why the quotes?

**Comment by kzisme** [comment]
I added them since it was suggested to help non-native English speakers based on this comment: 

https://github.com/gratipay/gratipay.com/issues/2396#issuecomment-43101503

**Comment by techtonik** [comment]
Left my impression in #2396.

**Comment by techtonik** [comment]
I guess that was "let's not spend so much time on this" from @whit537. =) That's fine with me.

**Comment by whit537** [comment]
:-)

[!m](http://motivate.im/) @kzisme @techtonik

**Comment by kzisme** [comment]
Just figured I could address some of the smaller issues and get them closed - thanks for the support @techtonik @whit537

**Comment by whit537** [comment]
Thanks for jumping in! :)

**Comment by techtonik** [comment]
:+1:

**Pull request merged**
