### PR TITLE
Cache python dependencies across Travis builds

### PR DESCRIPTION
**Pull request by Changaco**
Alternative to #3264.

### CODE REVIEW

**Comment by techtonik** [comment]
This will cache gratipay application files also.

**Comment by Changaco** [comment]
Ready for review. Build time is around 2 min 30 sec, down from around 3 min 20 sec without caching.

**Comment by techtonik** [comment]
Do you guarantee that this won't cache any files that is installed by Gratipay?

**Comment by Changaco** [comment]
Caching parts of `env/` between builds is similar to what happens on my machine and those of the other developers where `env/` is almost never deleted. If it was problematic we would have noticed it a long time ago.

**Comment by techtonik** [comment]
I can't approve that, because I haven't finished WIP over #3264 yet

**Comment by whit537** [comment]
I'm fine with this on branches. On master we should make a clean build, just as on master we hit live API endpoints instead of using the VCR cache.

**Comment by whit537** [comment]
As I read this it would apply to master as well as other branches, correct? Can we scope this to branches other than master?

**Comment by Changaco** [comment]
> Can we scope this to branches other than master?

Done.

**Pull request merged**
