### PR TITLE
Better emphasize the amount field on the homepage

### PR DESCRIPTION
**Pull request by whit537**
Per @mcavage at https://github.com/gratipay/inside.gratipay.com/issues/1044.

# New

screen shot 2017-09-13 at 3 07 32 pm

# Old

screen shot 2017-09-13 at 3 09 17 pm

### CODE REVIEW

**Comment by whit537** [comment]
Eh, @mattbk @kaguillera et al.?

**Comment by rohitpaulk** [comment]
LGTM.

**Comment by whit537** [comment]
I just pushed another commit to clean up the "Payment complete!" part (plus an unrelated but tiny fix for Safari).

pab7bxqhhm

**Comment by whit537** [comment]
@dmk246 and I walked through this code together. Rebased and squashed, was 11f178f4fee055170e1bd62ff1ba4f51199099f9.

**Comment by dmk246** [comment]
Will merge when all green! Yay!

**Comment by whit537** [comment]
Uh-oh ... 😏

**Comment by dmk246** [comment]
Oh nowww its green! Here goes...  :)

**Pull request merged**
