### PR TITLE
fold charts into stats

### LINKED ISSUE #2740: Combine stats and charts into one page
There are a lot of links in the footer, this might help declutter a bit.

<bountysource-plugin>

---
Want to back this issue? **[Place a bounty on it!](https://www.bountysource.com/issues/4242484-combine-stats-and-charts-into-one-page?utm_campaign=plugin&utm_content=tracker%2F85909&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F85909&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by whit537**
Fixes #2740, and starts to simplify the IA of /about/, which is necessary to further rationalize our navigation following #2938 (see #3063).

### CODE REVIEW

**Comment by clone1018** [comment]
@whit537 We have some failing tests here. After that I'll merge.

**Comment by whit537** [comment]
@clone1018 Working on the last one ...

**Comment by whit537** [comment]
Note that this is actually a breaking API change because it changes the sort order of charts.json. We gonna care about that?

https://github.com/gratipay/gratipay.com/#api

**Comment by whit537** [comment]
Rebased on master.

**Comment by whit537** [comment]
Okay, really ready for review now. :-)

**Comment by clone1018** [comment]
We decided we were hesitant on merging this because there are potential users of it.

Can we rename the json endpoint for now, keeping the old one intact and then we'll get this merged in.

**Comment by Changaco** [comment]
The new tip distribution charts look terrible, and I'm not convinced that writing our own code instead of using d3 is a good idea.

**Comment by clone1018** [comment]
The code is already written though @Changaco. Also how does the chart look terrible? Is it the data or the actual design of the chart?

**Pull request merged**
