### PR TITLE
Add script to link packages to teams

### PR DESCRIPTION
**Pull request by rohitpaulk**
To be used for https://github.com/gratipay/project-review/issues/485 and https://github.com/gratipay/project-review/issues/482

### CODE REVIEW

**Comment by rohitpaulk** [comment]
Tested locally with [`yargs`](https://github.com/gratipay/project-review/issues/482).

**Comment by whit537** [comment]
Can we put this under `gratipay/cli/` and write a few tests?

**Comment by rohitpaulk** [comment]
> Can we put this under gratipay/cli/ and write a few tests?

Will do.

**Comment by rohitpaulk** [comment]
Closing as stale

**Pull request closed without merging**
