### PR TITLE
silently skip emails when we don't have an address

### PR DESCRIPTION
**Pull request by whit537**
This is a fix for #3343.

### CODE REVIEW

**Comment by whit537** [comment]
Alternate to #3345.

**Comment by whit537** [comment]
I considered skipping the `sleep` call when we don't actually make an API call, but if I'm reading the rest of the email infrastructure right that wouldn't actually speed up queue processing at all. It looks like we call `dequeue_mails` every 60 seconds with max 60 messages, so even if we only mailed 30 of them, we would still wait another ~30 seconds until proceeding to the next batch.

**Comment by whit537** [comment]
Apparently I botched that first commit. Oh well. :-/

**Comment by whit537** [comment]
Ready for review @rohitpaulk @Changaco et al.

**Comment by rohitpaulk** [comment]
> It looks like we call dequeue_mails every 60 seconds with max 60 messages, so even if we only mailed 30 of them, we would still wait another ~30 seconds until proceeding to the next batch.

That could change in the future, so I've changed it to only sleep if we're actually making an API call.

**Comment by rohitpaulk** [comment]
Email queue is down to 0 :dancer:

**Comment by whit537** [comment]
https://twitter.com/Gratipay/status/589073378016899072 :dancer:

**Pull request merged**
