### PR TITLE
UI for setting status_of_1_0_balance

### PR DESCRIPTION
**Pull request by whit537**

### CODE REVIEW

**Comment by whit537** [comment]
How's this for UI?

`unresolved`:

unresolved

And then `pending-payout`:

screen shot 2015-06-11 at 12 59 47 pm

`resolved` is empty/as normal.

**Comment by whit537** [comment]
You still around @rohitpaulk? Able to pick this up?

**Comment by rohitpaulk** [comment]
Aye aye, captain :anchor:

**Comment by whit537** [comment]
:dancer:

**Comment by whit537** [comment]
/me waits for the `Review` signal, goes back to #3540 ...

**Comment by whit537** [comment]
Perfect, thank you @rohitpaulk. !m

**Pull request merged**
