### PR TITLE
refund advances

### LINKED ISSUE #3763: refund advances
Reticketed from #3675.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/26543937-refund-advances?utm_campaign=plugin&utm_content=tracker%2F85909&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F85909&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by whit537**
Towards #3763.

### CODE REVIEW

**Comment by whit537** [comment]
Builds on #3807.

**Comment by whit537** [comment]
```
[gratipay] $ ./tally-refunds.py 
Hi-level
----------------------------------
 yes                          2700
 no                           1824
 BAD                            78
                              4602
Check
----------------------------------
^201\d-                       4602
                              4602
```

**Comment by whit537** [comment]
Need to resolve the BADs and then spot-check the yes/nos. Then it's time to rock.

I am doing this tonight. B-|

**Comment by whit537** [comment]
If someone pays in $9.41 and then receives $20.00 (with no intervening withdrawal), do we refund them the $9.41? We could, I suppose ...

**Comment by whit537** [comment]
At this point it looks like the total amount to refund here is $3,791.82 (that doesn't include the example in my last comment).

**Comment by whit537** [comment]
Here we are, with partial balance refunds (the "charged and then received" case), and also counts by network, not including the backfilling from #3807.

```
Hi-level
----------------------------------
 yes                          2778
 no                           1824
                              4602
Network
----------------------------------
balanced-cc                    620
braintree-cc                   299
<unknown>                     1859
                              2778
Check
----------------------------------
^.*$                          4602
                              4602
```

**Comment by whit537** [comment]
Sum there is $34,838.09. How much on Balanced, I wonder?

**Comment by whit537** [comment]
We should also note that Balanced is not refunding the fees associated with charges (https://github.com/gratipay/gratipay.com/issues/3377#issuecomment-110973277), so we in turn don't need to refund that portion of the charges.

**Comment by whit537** [comment]
I'm running `backfill-exchanges.py` against a local db ... and committing it.

**Comment by whit537** [comment]
```
Hi-level
----------------------------------
Linking                      45115
Already linked                2306
raise                          147
                             47568
Participants
----------------------------------
known customer               47564
raise UnknownCustomer            4
                             47568
Exchanges
----------------------------------
exchange_id in transaction   17796
triangulated an exchange     29765
raise UnknownExchange            3
                             47564
Routes
----------------------------------
exchange has a route          2306
card matches                 37510
customer matches              7113
created a route                492
raise AmbiguousRoute            60
raise AmbiguousCustomer         80
raise UnknownRoute               0
                             47561
Check
----------------------------------
^201\d-                      47568
                             47568
```

**Comment by whit537** [comment]
I would expect a re-run to have "Linking" 0 and "Already linked" 47,421.

**Comment by whit537** [comment]
Pretty good! Our method of backfilling exchanges resolves almost 99% of the refunds we'd like to do!

```
Hi-level
----------------------------------
 yes                          2778
 no                           1824
                              4602
Network
----------------------------------
balanced-cc                   2455
braintree-cc                   299
<unknown>                       24
                              2778
Check
----------------------------------
^.*$                          4602
                              4602
```

**Comment by whit537** [comment]
Of the 24 unknowns, 15 are from very early, July/August of 2012. The rest may bear processing manually.

**Comment by whit537** [comment]
How's that for close? :-)

```
<unknown>     4457.61
balanced-cc  27566.89
braintree-cc  2813.59
             34838.09
```

If all the `balanced-cc` refunds go through (they won't), we'll have only 1,035.73 remaining. :)

**Comment by whit537** [comment]
Ick, I'm not finding a ref in many of these exchanges, even though I'm getting a balanced-cc network ...

**Comment by whit537** [comment]
Ah. `backfill-exchanges.py` isn't setting that field for "Already linked."

**Comment by whit537** [comment]
Yay already linked! :-)

```
Hi-level
----------------------------------
Linking                          0
Already linked               47421
raise                          147
                             47568
Participants
----------------------------------
known customer               47564
raise UnknownCustomer            4
                             47568
Exchanges
----------------------------------
exchange_id in transaction   17796
triangulated an exchange     29765
raise UnknownExchange            3
                             47564
Routes
----------------------------------
exchange has a route         47421
card matches                     0
customer matches                 0
created a route                  0
raise AmbiguousRoute            60
raise AmbiguousCustomer         80
raise UnknownRoute               0
                             47561
Check
----------------------------------
^201\d-                      47568
                             47568
```

**Comment by whit537** [comment]
s/max/min O.O

```
<unknown>      806.61
balanced-cc   9345.09
braintree-cc   963.39
             11115.09
```

**Comment by whit537** [comment]
Okay!

To: Matin

> We are a week behind and are not planning on attempting to refund all $130,000 tomorrow. Attached is a CSV with timestamp, transaction (debit) id, and amount for the refunds we *are* planning for tomorrow. The sum is $9,345.09, and the breakdown of number of transactions by year is as follows:
>
```
         n
2015    990
2014    981
2013    412
2012     72
      2,455
```
Details are on https://github.com/gratipay/gratipay.com/pull/3810.

**Comment by whit537** [comment]
Tomorrow:

 - [ ] Merge and deploy #3807 to get `exchanges.ref`.
 - [ ] Run `backfill-exchanges.py` against production—make sure to commit! This will take a while. It takes ~15 minutes locally, could be an hour hitting the production db. Maybe worth spinning up a droplet?
 - [ ] Check the tallies.
 - [ ] Run `refund.py` to generate the CSV.
 - [ ] Check the tallies.
 - [ ] Run `actually-do-refunds.py` to actually do the refunds. Make sure we're getting good output before doing the whole run.
 - [ ] Write a script to post exchanges back to the db.
 - [ ] Download new refund transactions from Balanced.
 - [ ] Delete one-off scripts from master.
 - [ ] Done with refunds on Balanced!

**Comment by whit537** [comment]
:night_with_stars:

**Comment by whit537** [comment]
:godmode:

**Comment by whit537** [comment]
Alright, we have `exchanges.ref`.

**Comment by whit537** [comment]
I'm spinning up a droplet.

**Comment by whit537** [comment]
I'm taking a backup.

**Comment by whit537** [comment]
Droplet spun up and updated. I copied `run_dammit` to it. I'm going to run this with the rollback first:

```
whit537@refunds:~/gratipay.com$ heroku config -s | run_dammit /dev/stdin -c ./env/bin/python backfill-exchanges.py > backfill.log
```

If that works I'll kill it (should roll back).

Then I'll rerun with this patch:

```diff
diff --git a/backfill-exchanges.py b/backfill-exchanges.py
index b4047ef..c692693 100755
--- a/backfill-exchanges.py
+++ b/backfill-exchanges.py
@@ -350,5 +350,4 @@ with db.get_cursor() as cur:
         counts = Counts()
         walk(cur, lambda *a: link_exchange_to_transaction(*a, counts=counts, customers=customers))
     finally:
-        print('Rolling back ...')
-        cur.connection.rollback()
+        print('Committing ...')
```

**Comment by whit537** [comment]
I need to upload the `transactions/*.json` files to the droplet.

**Comment by whit537** [comment]
Uploaded. 10 MB.

**Comment by whit537** [comment]
Tried the script, log looks good. Killed it, spot-check of db indicates rollback.

**Comment by whit537** [comment]
Alright! Ready? :four_leaf_clover:

**Comment by whit537** [comment]
Patch applied.

**Comment by whit537** [comment]
Script is running. I'm `watch`ing the tally. About 10 seconds for 100-150 records.

**Comment by whit537** [comment]
Yeah, so for ~48k records we're looking at about an hour.

**Comment by whit537** [comment]
:clock1:

**Comment by whit537** [comment]
10,967 / 47,568 = 23%

Will we run into any problems committing a transaction that's been open for an hour?

**Comment by whit537** [comment]
85%

**Comment by whit537** [comment]
Eep! 100%!

```
Committing ...
```

**Comment by whit537** [comment]
```
Hi-level
----------------------------------
Linking                      45115
Already linked                2306
raise                          147
                             47568
Participants
----------------------------------
known customer               47564
raise UnknownCustomer            4
                             47568
Exchanges
----------------------------------
exchange_id in transaction   17796
triangulated an exchange     29765
raise UnknownExchange            3
                             47564
Routes
----------------------------------
exchange has a route          2306
card matches                 37510
customer matches              7113
created a route                492
raise AmbiguousRoute            60
raise AmbiguousCustomer         80
raise UnknownRoute               0
                             47561
Check
----------------------------------
^201\d-                      47568
                             47568
```

**Comment by whit537** [comment]
Spot-check shows the commit worked.

**Comment by whit537** [comment]
Okay! Next?

**Comment by whit537** [comment]
> Run `refund.py` to generate the CSV.

https://github.com/gratipay/gratipay.com/pull/3810#issuecomment-146754972

**Comment by whit537** [comment]
I downloaded the `backfill.log`. I suppose I may as well keep running from the droplet.

**Comment by whit537** [comment]
Rebased on master to pick up #3807. I'm going to run the rest of this process from this branch, and then I'll remove the scripts on this branch and we can merge to master to remove there as well.

**Comment by whit537** [comment]
```
whit537@refunds:~/gratipay.com$ heroku config -s | ./run_dammit /dev/stdin -c ./env/bin/python refund.py > refunds.csv 2> refund.log
```

```diff
diff --git a/refund.py b/refund.py
index 9ae09de..89c48c9 100755
--- a/refund.py
+++ b/refund.py
@@ -97,4 +97,4 @@ with db.get_cursor(back_as=dict) as cur:
             process_participant(cur, participant, counts)
         print(counts, file=sys.stderr)
     finally:
-        cur.connection.rollback()
+       pass
```

**Comment by whit537** [comment]
Pulled the trigger ...

**Comment by whit537** [comment]
```
Hi-level
----------------------------------
 yes                           584
 no                              7
                               591
Network
----------------------------------
balanced-cc                    495
braintree-cc                    84
<unknown>                        6
                               585
Check
----------------------------------
^.*$                           592
                               592
```

**Comment by whit537** [comment]
200 in 10 seconds.

**Comment by whit537** [comment]
Should be about three or four minutes.

**Comment by whit537** [comment]
How about some one-off refunds for the ones we couldn't match?

ref: https://github.com/gratipay/gratipay.com/pull/3810#issuecomment-146741678

**Comment by whit537** [comment]
Done!

```
Hi-level
----------------------------------
 yes                          2767
 no                           1820
                              4587
Network
----------------------------------
balanced-cc                   2455
braintree-cc                   290
<unknown>                       25
                              2770
Check
----------------------------------
^.*$                          4591
                              4591
```

**Comment by whit537** [comment]
I want to write the script the posts back to the db before running the actual refunds, because I want to satisfy myself that we're not going to send balances negative, but are rather going to take them to zero.

**Comment by whit537** [comment]
I want to see the result of this process on a history page locally before proceeding.

**Comment by whit537** [comment]
These are all going to be pending. How are we going to find out about the status change? We don't have a callback for refunds.

**Comment by whit537** [comment]
Blech. Can't use the `record-an-exchange` endpoint with invalidated routes, which we're almost certain to have in here.

**Comment by whit537** [comment]
First thing's first: let's get the refunds done. We can worry about posting them back later.

**Comment by whit537** [comment]
Well, next thing's next, at least. ;-)

**Comment by whit537** [comment]
Just ran a manual one:

screen shot 2015-10-09 at 11 12 36 pm

The date on that one is April 1, 2014.

**Comment by whit537** [comment]
Yinz ready?

**Comment by whit537** [comment]
Here goes nothin' ...

**Comment by whit537** [comment]
Getting 409s (too old) and 404s (for the early <unknowns>) ... still awaiting the first working one ..

**Comment by whit537** [comment]
```
whit537@refunds:~/gratipay.com$ python tally-codes.py 
404   49
409  665
     714
```

**Comment by whit537** [comment]
```python
#!/usr/bin/env python -u
from __future__ import print_function
import csv
from collections import defaultdict
inp = csv.reader(open('refunds.completed.csv'))
codes = defaultdict(int)
try:
        for row in inp:
                code = int(row[5])
                codes[code] += 1
except:
        pass
for code in sorted(codes):
        print("{} {:>4}".format(code, codes[code]))
print("    {:>4}".format(sum([n for n in codes.values()])))
```

(Entered in vim on the droplet.)

**Comment by whit537** [comment]
Target is 2454:

```
whit537@refunds:~/gratipay.com$ wc -l refunds.csv 
2454 refunds.csv
```

About 25 in 10 seconds.

Maybe another 10 minutes.

**Comment by whit537** [comment]
Well, I think it's safe to say that we wouldn't have come anywhere near to refunding $130,000. :-)

**Comment by whit537** [comment]
What's up with all these `404`s?

```
404  278
409 1300
    1578
```

**Comment by whit537** [comment]
There's way too many `None`s in `refunds.csv`. I've killed the `actually-do-refunds` script to investigate.

**Comment by whit537** [comment]
They escaped notice because they weren't part of a tally.

**Comment by whit537** [comment]
More db spot-checking makes it look like exchanges were linked. Backfill tally looks good.

**Comment by whit537** [comment]
It looks like `ref` isn't set for "Already linked," which I hit at https://github.com/gratipay/gratipay.com/pull/3810#issuecomment-146747860 but thought I'd fixed in https://github.com/gratipay/gratipay.com/commit/a85cc7e87c8f86e0dfb47463c96bf0d9c5e102b5. :disappointed:

**Comment by whit537** [comment]
This one I spot-checked *is* linked locally.

**Comment by whit537** [comment]
I'm re-running backfill. :(

**Comment by whit537** [comment]
A little faster, looking at 40 minutes.

**Comment by whit537** [comment]
We can get this done way faster. We already have the log lines ...

**Comment by whit537** [comment]
```python
#!/usr/bin/env python -u
import re
fp = open('balanced/refund/linked.log')
for line in fp:
    ref, exchange_id = re.search('Already linked: ([^ ]*) & ([^.]*).', line).groups()
    print("UPDATE exchanges SET ref='{}' WHERE id={};".format(ref, exchange_id))
```

**Comment by whit537** [comment]
```sql
=> \i link-exchanges.sql
```

Running ...

**Comment by whit537** [comment]
Done. Spot-check looks good. WTF? :weary:

**Comment by whit537** [comment]
Rerunning `actually-do-refunds` ...

**Comment by whit537** [comment]
Gonna take an hour at this rate.

**Comment by whit537** [comment]
Regenerating `refunds.csv`, then gonna try again with this `threaded_map`ped version of `actually-do-refunds.

**Comment by whit537** [comment]
Whoa! :dancer: 

```
201    5
409    7
      12
```

**Comment by whit537** [comment]
No new refunds showing up in the dashboard ...

**Comment by whit537** [comment]
Not in the transactions list, anyway, but maybe that's just successful refunds? If I navigate directly to a refund URL based on the output of the JSON request, I see it! :dancer: 

We're making refunds! :dancer: :dancers:

**Comment by whit537** [comment]
Buuuuuttttt not very many of them.

```
201   29
409  460
     489
```

**Comment by whit537** [comment]
Another 20 minutes?

**Comment by whit537** [comment]
Here they are, the date filter was off in the dashboard.

**Comment by whit537** [comment]
```
201   54
409 1040
    1094
```

**Comment by whit537** [comment]
Kind of surreal now that this is actually happening. Been workin' so hard to get here since https://medium.com/gratipay-blog/gratipay-2-0-2453d3c53077 and even before.

**Comment by whit537** [comment]
```
whit537@refunds:~/gratipay.com$ python tally-codes.py 
      n   %
201  294  15
409 1544  84
    1838  74
```

```python
#!/usr/bin/env python -u
from __future__ import division, print_function, unicode_literals
import csv
from collections import defaultdict
inp = csv.reader(open('refunds.completed.csv'))
codes = defaultdict(int)
try:
        for row in inp:
                code = int(row[5])
                codes[code] += 1
except:
        pass
total = sum([n for n in codes.values()])
print("      n   %")
for code in sorted(codes):
        print("{} {:>4} {:>3}".format(code, codes[code], int((codes[code]/total)*100)))
print("    {:>4} {:>3}".format(total, int((total/2454)*100)))
```

**Comment by whit537** [comment]
Looks like we're running at about 15% success on refunds.

**Comment by whit537** [comment]
```
      n   %
201  435  18
409 1968  81
    2403  97
```

**Comment by whit537** [comment]
Alright, folks! The Balanced refund is done!

```
      n   %
201  463  18
409 1991  81
    2454 100
```

**Comment by whit537** [comment]
It doesn't appear that posting back update user balances.

**Comment by whit537** [comment]
I don't understand why not, because `record_exchange` does call `propagate_exchange`, which does update the balance.

**Comment by whit537** [comment]
Well, that's a fitting end to a long slog of a barely making it kinda project. I have no idea why balances didn't go to zero, but they're zero now thanks to 1b1fc9ab2178c4341250aa586aab1ea3012b85fa.

I don't even have the energy left to close this ticket. I'm afraid to go anywhere near master at this point (deleting scripts there).

I think we made it? :-)

G'night. :-) :night_with_stars:

**Comment by whit537** [comment]
All told we refunded $2,211.62 to 463 people.

**Comment by rohitpaulk** [comment]
!m @whit537 :)

We don't need these scripts in the long term, correct? What's left on this PR?

**Comment by kaguillera** [comment]
!m @whit537

**Comment by whit537** [comment]
> We don't need these scripts in the long term, correct? What's left on this PR?

Correct. We have a few scripts from #3807 still on master. I figured we could use this PR to remove those. I intend to make another commit or two here and then submit it for review. :-)

**Comment by whit537** [comment]
Refunds are still all pending.

**Comment by whit537** [comment]
I suppose we should keep this PR around to use for advances refunds on braintree as well. We'll need to backfill the new `ref` column (see #3822), then proceed with a modified `refund.py` and `post-refunds-back.py`. Maybe we'll figure out what happened with balances.

**Comment by whit537** [comment]
Looks like at least most of the Balanced refunds have completed successfully.

**Comment by whit537** [comment]
Alright, next step is to backfill `ref` for `braintree-cc` transactions.

**Comment by whit537** [comment]
I show 1770 transactions in our db, but 1789 in Braintree.

**Comment by whit537** [comment]
```sql
=> select count(*) from exchanges e join exchange_routes er on e.route = er.id where network='braintree-cc';
┌───────┐
│ count │
├───────┤
│  1770 │
└───────┘
(1 row)
```

```bash
[gratipay] $ wc -l braintree.transactions.csv 
    1790 braintree.transactions.csv
```

(Includes a header row.)

**Comment by whit537** [comment]
The 19 extra in Braintree vs. our db are transactions that we voided: we didn't capture any of the hold. Fine, in other words.

**Comment by whit537** [comment]
I've got the backfill script ready to go for Braintree in 7adafdda999d2b232ee19ccad4a050b4deb13fba. Now for the others ...

**Comment by whit537** [comment]
I'm running backfill against production.

**Comment by whit537** [comment]
Done.

**Comment by whit537** [comment]
```sql
=> select count(*) from exchanges e join exchange_routes er on e.route = er.id where network='braintree-cc' and ref is not null;
┌───────┐
│ count │
├───────┤
│  1770 │
└───────┘
(1 row)
```

**Comment by whit537** [comment]
Alright, refund scripts are ready to go in 0e832873dd86d0ee29b6cc7decd847009bb8fed1. I'm currently running `refund.py` against production.

**Comment by whit537** [comment]
Eureka! I figured out why balances weren't updated during `post-refunds-back.py`: I'm passing in amount as a string instead of a decimal.

**Comment by whit537** [comment]
P.S. I used @clone1018 as a guinea pig for these scripts. You should see two 1¢ refunds in addition to the main refund, @clone1018. :)

**Comment by whit537** [comment]
`post-back-refunds.py` is running against production.

**Comment by whit537** [comment]
##### Number of Users by Balance Range

| range | users |
|----------|--------|
| 0.01 - 0.99 | 1060 |
| 1.00 - 9.99 | 1734 |
| 10.00 - 99.99 | 780 |
| 100.00 - 999.99 | 245 |
| 1000.00 - 9999.99 | 16 |
| 10000.00 - 99999.99 | 0 |

**Comment by whit537** [comment]
Picking up from https://github.com/gratipay/gratipay.com/pull/3810#issuecomment-147042507 ...

| platform | amount ($) | n |
|------------|------------:|----:|
| balanced | 2,211.62 | 463 |
| braintree | 877.61 | 289 |
|  | 3,089.23 | 752 |

**Comment by whit537** [comment]
Next step on this PR is to update the status to the refunds on Balanced. I guess we'll need to wait a few days for Braintree to settle.

**Comment by whit537** [comment]
I downloaded more transaction.json from Balanced. Looks like all the refunds succeeded! :-)

**Comment by whit537** [comment]
Alright, refund transactions update with status and ref in `exchanges`, using https://github.com/gratipay/gratipay.com/commit/d401f22cf8225bbddce6f0a1b15e9436031778f5.

**Comment by whit537** [comment]
Okay! I'm going to leave this open until the Braintree refunds complete and we update their status. I don't think we need to wait for that to get a blog post out, however.

**Comment by whit537** [comment]
Looks from the Braintree dashboard that all the refunds completed successfully. Need to post those back and then we can bring this PR in for a landing (updating to remove scripts and then merging).

**Comment by whit537** [comment]
@kaguillera and I just tested and ran this against production:

```sql
UPDATE exchanges SET status='succeeded' WHERE status='pending' AND ref is not null;
```

Spot-check looks good. Case closed!

**Comment by whit537** [comment]
Oops! Now to remove scripts from master ...

**Comment by whit537** [comment]
Already! Ready for review and merge, @kaguillera @rohitpaulk @rorepo @mattbk et al.

**Comment by mattbk** [comment]
Looks like I missed the boat.  Since I barely understand this, good job everyone!

**Pull request merged**
