### PR TITLE
Simplify the newsletter field

### LINKED ISSUE #4654: Simplify mailing list opt-in even further
In #4651 we dropped back to two mailing list options, quarterly and yearly. However, as I think through the way #BackTheStack is gonna wanna play out, we are going to want to send multiple updates over the course of the campaign. That's not consistent with a "quarterly" or "yearly" newsletter. I think our best bet is to just have a simple "Yes/No" on the mailing list.

### PR DESCRIPTION
**Pull request by whit537**
Closes #4654.

### CODE REVIEW

**Comment by whit537** [comment]
Ready for review @mattbk @rohitpaulk et al.

**Comment by dmk246** [comment]
@whit537 per our conversation, there is a logic bug in the sql in the beginning of the code changes

**Comment by whit537** [comment]
Rebased, was 6533d679a3cb4bd93861eff731dad1eb99bc2897.

**Comment by whit537** [comment]
Rebased and SQL syntax error fixed, was c28242337b1d797b2ee27481591df2ebf046beac.

**Comment by dmk246** [comment]
All green...its a go! Yay!

**Pull request merged**
