### PR TITLE
*use* the new test helpers

### PR DESCRIPTION
**Pull request by whit537**
Follow-on from #4092.

### CODE REVIEW

**Comment by whit537** [comment]
Rebased on #4092. Ready to go if Travis is happy ...

cc: @nashe et al.

**Comment by whit537** [comment]
Looks like Travis is happy. Ready for review! :-)

**Comment by nashe** [comment]
Looks good! Less readability but I think everybody will get used to it quickly :-) Merge?

**Comment by whit537** [comment]
We use them so much in tests, I think it's worth the trade-off. But yes, the argument can be made that it's confusing and less readable. Does anyone else object on those grounds? cc: @rohitpaulk @aandis

**Comment by whit537** [comment]
@nashe I'll leave it up to you to decide whether to merge this. :-)

**Pull request merged**
