### PR TITLE
#3924 remove inapplicable badges; adjust title

### PR DESCRIPTION
**Pull request by nobodxbodon**
Just noticed there are many test failures:
5 failed, 677 passed, 36 xfailed, 17 error
Is there something wrong with my local settings? Or they are just broken?

### CODE REVIEW

**Comment by whit537** [comment]
The xfailed are expected. Some of the other failures are going to be due to dependencies I introduced underneath https://github.com/gratipay/gratipay.com/issues/4148 (@kaguillera is seeing similar on #4128). Sorry—I will work on that. Not sure whether that'll be all of them, though.

**Comment by nobodxbodon** [comment]
Please review. It passes test now.

**Comment by whit537** [comment]
!m @nobodxbodon

**Comment by whit537** [comment]
Deployed! Thanks for the PR, @nobodxbodon! 💃 🌻 

screen shot 2016-11-06 at 8 39 55 pm

**Pull request merged**
