### PR TITLE
Upgrade Python

### PR DESCRIPTION
**Pull request by whit537**
Heroku is bugging us to upgrade to 2.7.11.

### CODE REVIEW

**Comment by whit537** [comment]
Ping @aandis @rohitpaulk @clone1018.

**Comment by rohitpaulk** [comment]
Deploying this could be risky.... Checking if I still have that test heroku app lying around

**Comment by rohitpaulk** [comment]
Yes, I do! http://paul-gratipay-copy.herokuapp.com/

**Comment by rohitpaulk** [comment]
Hmm.. Looks like deploying didn't work... 

screen shot 2016-06-07 at 6 03 37 pm

I'm going to try to deploy the commit just before this, to make sure it isn't specific to my instance

**Comment by rohitpaulk** [comment]
Trying with gratipay/gratipay.com@0ba2893dcbd4a0142f2683b333fab720f9ad9945..

**Comment by rohitpaulk** [comment]
Just noticed this in the previous deploy logs

screen shot 2016-06-07 at 6 07 12 pm

**Comment by whit537** [comment]
@rohitpaulk That's from the cryptography library ... searching for deploy notes ...

**Comment by whit537** [comment]
@rohitpaulk https://github.com/gratipay/inside.gratipay.com/issues/612#issuecomment-218121187

[Workaround](https://github.com/gratipay/inside.gratipay.com/issues/612#issuecomment-218136558) is to use a custom buildpack. 😞

**Comment by rohitpaulk** [comment]
Aha... Did that, build running.

**Comment by rohitpaulk** [comment]
Hmm... Heroku didn't pick the new config value the first time around, I've retried.

**Comment by rohitpaulk** [comment]
screen shot 2016-06-07 at 6 24 16 pm

**Comment by whit537** [comment]
@rohitpaulk Try pushing 8e72d03db5b78a05dec580283f167ded0c5da4dc instead of 0ba2893dcbd4a0142f2683b333fab720f9ad9945? ;-)

**Comment by rohitpaulk** [comment]
Looks like the command has changed - they have a dedicated command for this now. (`heroku buildpacks:set`)

https://devcenter.heroku.com/articles/buildpacks#using-a-custom-buildpack

Did that, now waiting again..

**Comment by rohitpaulk** [comment]
Worked. http://paul-gratipay-copy.herokuapp.com/

**Comment by rohitpaulk** [comment]
Deployed. :)

**Comment by whit537** [comment]
!m @rohitpaulk :-)

**Pull request merged**
