### PR TITLE
Homepage updates

### PR DESCRIPTION
**Pull request by whit537**
Batching three together:

- adding RtD (wuz #4659)
- moving the campaign above the fold
- whacking the "projects" field per https://github.com/gratipay/inside.gratipay.com/issues/1160#issuecomment-333257027

### CODE REVIEW

**Comment by whit537** [comment]
Rebased, was 14fd1fe8bd829b0fea6800a03b120bab93286841.

**Comment by whit537** [comment]
Rebased, was 0a44e685a3be589a7a9b5b81c6afb35cd0e66b01.

**Comment by whit537** [comment]
@JessaWitzel @mattbk @rohitpaulk Spare some cycles for this one? ☺️

**Comment by whit537** [comment]
Rebased, was 41ef3e32a09acd9e92769a5520795b2b10f583c3.

**Comment by mattbk** [comment]
Looks good.

**Comment by whit537** [comment]
Rebased, was 2e15afde5d4230b8b07beb8345147c51b25ab567.

**Comment by mattbk** [comment]
Still looks good.

**Comment by whit537** [comment]
💃

**Pull request merged**
