### PR TITLE
find friends

### PR DESCRIPTION
**Pull request by whit537**
Here's a proposal for how to implement #3183 (really, I'm looking at #536).

 - [ ] cache friend calls
 - [x] add pagination to table
 - [ ] add search filter to table
 - [ ] add sorting to table
 - [x] abstract for other elsewheres
 - [x] implement or stub other elsewheres
 - [x] figure out how to handle Facebook limitations
 - [x] add elsewhere logo as sidebar avatar
 - [x] link to attached networks from dashboard

### CODE REVIEW

**Comment by whit537** [comment]
Basically, the idea here is that `/on/twitter/` becomes the friend-finder for Twitter, etc. I'm thinking we use a table like we're using on Explore, Members, Receiving, Giving.

**Comment by whit537** [comment]
I've reopened #536 for this, because I think this address that more directly than #3183.

**Comment by whit537** [comment]
screen shot 2015-02-17 at 2 46 37 pm

**Comment by rohitpaulk** [comment]
That's awesome :)

**Comment by rohitpaulk** [comment]
screenshot from 2015-02-25 16 44 51

Hmm, maybe I should've used the sub-nav like we do on Explore?

screenshot from 2015-02-25 16 48 21

**Comment by rohitpaulk** [comment]
Here's how that'd look - 

screenshot from 2015-02-25 17 23 38

**Comment by whit537** [comment]
@rohitpaulk I like https://github.com/gratipay/gratipay.com/pull/3185#issuecomment-75948250!

**Comment by rohitpaulk** [comment]
This is what I'm aiming for: 

screenshot from 2015-02-26 11 08 13

**Comment by Changaco** [comment]
We can't show "x of them are on Gratipay" until we've fetched all the pages, and we can't quickly fetch all the pages for users who have lots of "friends" because of rate limiting.

**Comment by whit537** [comment]
+1 at https://twitter.com/nplainsathletes/status/570978480222969859.

**Comment by Changaco** [comment]
Ready for review.

I think caching, filtering and sorting can wait for #3222.

**Comment by Changaco** [comment]
Note: I've been unable to test the Facebook friend finder, it looks like our test app isn't setup properly.

**Comment by rohitpaulk** [comment]
> Note: I've been unable to test the Facebook friend finder, it looks like our test app isn't setup properly.

Doing that right now.

**Comment by whit537** [comment]
Twitter fails:

screen shot 2015-03-30 at 3 01 35 pm

**Comment by whit537** [comment]
Facebook fails:

screen shot 2015-03-30 at 3 02 48 pm

**Comment by whit537** [comment]
When I'm already signed in, the button should say "Connect with your Google account." When I'm anon it should stay "Sign in with Google."

screen shot 2015-03-30 at 3 03 41 pm

**Comment by whit537** [comment]
When I'm already signed in, the button should say "Connect your Google account." When I'm anon it should stay "Sign in with Google." Does the inline button really work with i18n?

screen shot 2015-03-30 at 3 03 41 pm

**Comment by whit537** [comment]
The Bitbucket logo is fuzzy and very low-contrast on the brown background. It should be more crisp and higher-contrast.

screen shot 2015-03-30 at 3 05 58 pm

**Comment by whit537** [comment]
Clicking the "Sign in with Google" button worked, in that I landed back on the same page after the oauth dance with a list of (what I presume to be) my Google+ connections (probably in my circles or something?). However, I'm confused by the "Google only allows us to see your friends who have already joined Gratipay" note, because all but one of the friends displayed *aren't* on Gratipay:

google-friends

**Comment by whit537** [comment]
If I disconnect and then reconnect Twitter and Facebook I don't get 50xs.

**Comment by whit537** [comment]
Paging seems to minimally work. What's up with the really long page identifiers in the querystring? Cardinals aren't sufficient?

screen shot 2015-03-30 at 3 42 55 pm

**Comment by whit537** [comment]
Columns after the first should be centered, but with numbers aligned over the decimal. Let's use a `-` (aligned over the decimal) for `Receives` and `Gives` for both users on Gratipay with amount hidden and users who haven't joined Gratipay yet (so `Supporters` will be non-zero with `-` `-` for users who haven't joined yet).

screen shot 2015-03-30 at 3 56 53 pm

**Comment by whit537** [comment]
We can bump table formatting to #3222.

**Comment by Changaco** [comment]
Ready for more review.

**Comment by Changaco** [comment]
@rohitpaulk 48c94212c88204a043cf584cb9b08cef7735108a

**Comment by whit537** [comment]
Button text for auth vs. anon looks good now:

screen shot 2015-04-01 at 12 34 51 pm

screen shot 2015-04-01 at 12 35 55 pm

**Comment by whit537** [comment]
This is so we can get `user_friends`, ya?

screen shot 2015-04-01 at 12 36 35 pm

**Comment by whit537** [comment]
Bitbucket logo still low-quality:

screen shot 2015-04-01 at 12 37 51 pm

**Comment by whit537** [comment]
Twitter still 502:

screen shot 2015-04-01 at 12 38 10 pm

**Comment by Changaco** [comment]
> Twitter still 502

I don't have that. Can you give me the log message (`twitter api responded with…`)?

**Comment by whit537** [comment]
```
twitter api responded with 401:
{"errors":[{"code":32,"message":"Could not authenticate you."}]}
```

**Comment by Changaco** [comment]
> Twitter still 502

Fixed.

**Comment by rohitpaulk** [comment]
Added a few commits. I think this is good to merge. cc: @Changaco

**Comment by rohitpaulk** [comment]
Screenshots for the pagination styling change (https://github.com/gratipay/gratipay.com/commit/11b94416732c8109440c39659dfb1f107f881a20)

Before: 

screenshot from 2015-04-08 11 37 26

After: 

screenshot from 2015-04-08 11 36 48

**Pull request merged**
