### PR TITLE
Reset dues to 0 when a subscription is cancelled

### PR DESCRIPTION
**Pull request by rohitpaulk**

### CODE REVIEW

**Comment by whit537** [comment]
Lgtm, but has conflicts?

**Comment by rohitpaulk** [comment]
Aha, must be the recent merges...

**Comment by rohitpaulk** [comment]
I'll rebase this in a while

**Comment by rohitpaulk** [comment]
> Lgtm, but has conflicts?

Rebased, tests passing. Going to merge..

**Comment by whit537** [comment]
!m @rohitpaulk

**Pull request merged**
