### PR TITLE
point user review dashboard to ~new place

### LINKED ISSUE #3496: logic is flipped on user review dashboard
Reticketed from https://github.com/gratipay/gratipay.com/issues/3486#issuecomment-106497752.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/18441515-logic-is-flipped-on-user-review-dashboard?utm_campaign=plugin&utm_content=tracker%2F85909&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F85909&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by whit537**
Fixes #3496.

### CODE REVIEW

**Comment by whit537** [comment]
Ping @rohitpaulk. I'll leave this for a bit in case you're around. Since it's small, obvious, not user-facing, and useful for #3540, I'll probably self-merge before proceeding with #3540.

**Comment by rohitpaulk** [comment]
We were allowing GET requests to toggle `is_suspicious`? Let me just fix that quick..

**Comment by whit537** [comment]
!m @rohitpaulk

**Comment by rohitpaulk** [comment]
Hmm, wonder how 16b029d passed on Travis.

**Comment by rohitpaulk** [comment]
Maybe the job started late and pulled the latest commit instead?

**Comment by rohitpaulk** [comment]
Anyways. Does fail on my local, so merging.

**Comment by whit537** [comment]
> Does fail on my local, so merging.

`s/Does/Doesn't`?

**Comment by whit537** [comment]
;-)

**Comment by rohitpaulk** [comment]
The first commit that **should've** failed **does** fail, @whit537 :P

**Pull request merged**
