### PR TITLE
Account for multiple teams when migrating tips

### PR DESCRIPTION
**Pull request by rohitpaulk**

### CODE REVIEW

**Comment by rohitpaulk** [comment]
We've migrated tips more than once for two participants. None of these have been paid out yet (the tips weren't funded in once case, and the other case - they were migrated after yesterday's payday).

**Comment by rohitpaulk** [comment]
I'm going to manually delete these subscriptions from the DB - and only keep the subscriptions to the team that was created first.

**Comment by rohitpaulk** [comment]
I'll wait a while for @whit537 to respond.

**Comment by whit537** [comment]
Sounds good, @rohitpaulk. Full steam ahead! :)

**Comment by rohitpaulk** [comment]
Done.

**Comment by rohitpaulk** [comment]
Deployed.

**Pull request merged**
