### PR TITLE
Refactor mixins

### PR DESCRIPTION
**Pull request by whit537**
Flat is better than nested.

### CODE REVIEW

**Comment by whit537** [comment]
Ready for review @nobodxbodon @kaguillera @mattbk et al. I'd like to get this in `master` and then rebase https://github.com/gratipay/gratipay.com/pull/4305 to build on this.

**Comment by whit537** [comment]
Redone to fix a test.

**Comment by kaguillera** [comment]
LGTM

**Comment by mattbk** [comment]
Don't wait for me.

**Comment by whit537** [comment]
@kaguillera Merge? :-)

**Comment by whit537** [comment]
Rebased, was 2d2b580127e03f8dfbfd7d8c37cd20d0e00908f6.

**Pull request merged**
