### PR TITLE
Nix the welcome popup

### LINKED ISSUE #4325: Retire welcome message
@hmig suggests [on Twitter](https://twitter.com/_hmig/status/829467538471997441) that the welcome popup constitutes an [intrusive interstitial](https://webmasters.googleblog.com/2016/08/helping-users-easily-access-content-on.html) and should be removed.

c4lcu0mwcaaimlj

### PR DESCRIPTION
**Pull request by whit537**
Closes #4325.

### CODE REVIEW

**Comment by mattbk** [comment]
I don't understand this error:
`The command "LD_LIBRARY_PATH=/usr/local/lib make bgrun test doc -j2" exited with 2.`.

**Comment by whit537** [comment]
It means the test run failed, and there should be a more specific traceback further up in the log output.

The problem here is that we need to remove the tests for the welcome popup. :)

**Comment by mattbk** [comment]
Python is grouchy, isn't it?

**Comment by whit537** [comment]
@mattbk Well, in all fairness, we do [ask](https://github.com/gratipay/gratipay.com/blob/ba144c900bb7f4c7fc2cf885ef29ce497ebf7c69/Makefile#L63) it to be grouchy. ☺️

**Pull request merged**
