### PR TITLE
Improve German translations.

### PR DESCRIPTION
**Pull request by EdOverflow**

### CODE REVIEW

**Comment by clone1018** [comment]
Awesome! Those files are computer generated though from Transifex, if you can, can you signup for an account and copy these over? 

You can find our docs here: http://inside.gratipay.com/howto/translate-gratipay

**Comment by whit537** [comment]
I'm pretty sure we can still accept this PR, though ... lemme check the last time around ...

**Comment by EdOverflow** [comment]
Oh, I see. I have requested to join.

**Comment by whit537** [comment]
https://github.com/gratipay/gratipay.com/pull/4134

**Comment by whit537** [comment]
Yeah, it looks in #4134 that if we accept this PR then our deployment machinery will overwrite it. Transifex is our source. Sorry for the duplicate effort, @EdOverflow! Checking Transifex now to make sure you're in ...

**Comment by EdOverflow** [comment]
No worries. I am currently translating everything on Transifex. :)

**Pull request closed without merging**
