### PR TITLE
send a Year Three email

### PR DESCRIPTION
**Pull request by whit537**
Picking up from #3508.

### CODE REVIEW

**Comment by whit537** [comment]
I'm planning to write a script to queue this locally, with a production Mandrill key in `local.env` for sending.

**Comment by whit537** [comment]
Alright, how's this?

screen shot 2015-06-01 at 6 02 14 pm

**Comment by whit537** [comment]
Subject: Gratipay, Year Three

**Comment by whit537** [comment]
screen shot 2015-06-01 at 6 07 23 pm

**Comment by whit537** [comment]
Okay! Ready?

**Comment by whit537** [comment]
I'm downloading a backup. I'll use that to populate the `participants` list, and I'll put a production Mandrill key in `local.env` for sending. After we're done I'll remove the production Mandrill key from `local.env`.

**Comment by whit537** [comment]
Backup loaded.

```
=# select count(*) from participants where email_address is not null and is_suspicious is not true and is_closed is not true and claimed_time is not null;
┌───────┐
│ count │
├───────┤
│  2812 │
└───────┘
(1 row)
```

**Comment by whit537** [comment]
Matches production. As I recall we mailed Gratipocalypse to ~2600 folks. We've picked up 200 email addresses since then, I suppose?

**Comment by whit537** [comment]
Indeed! :)

```sql
=> select count(*) from emails where verified and verification_end > 'may 7, 2015'::timestamptz;
┌───────┐
│ count │
├───────┤
│   239 │
└───────┘
(1 row)
```

**Comment by whit537** [comment]
Alright, list of participants ready to go in local db ...

**Comment by whit537** [comment]
Okay, my `local.env` is pointing to the backup database and production Mandrill. Code is at 0c841fdd1cfaeb5a50eda23900a8cf06cf1821ec. Here's my command line:

```bash
[gratipay] $ run_dammit defaults.env local.env -c ./env/bin/python bin/send-year-three.py
```

Here's [`run_dammit`](https://gist.github.com/whit537/8f114889c0a60b3b2e98).

**Comment by whit537** [comment]
I expect the next run to fail on the first assert.

**Comment by whit537** [comment]
For 2,812 emails at 1 per second, it's going to take 47 minutes to send all of these out. It'd be nice if that went faster. What are our rate limits at Mandrill?

**Comment by whit537** [comment]
Our hourly limit is 6,561.

**Comment by whit537** [comment]
What if I use `threaded_map` here?

**Comment by whit537** [comment]
Hmm ... would have to unroll/monkey around with `dequeue_emails` for that. Easier to just whack the `sleep`. What are the implications of that?

**Comment by whit537** [comment]
Why was it added in the first place?

**Comment by whit537** [comment]
https://github.com/gratipay/gratipay.com/blame/e0da32266ddc1532582f26613a0766d2d914d450/gratipay/models/participant.py

https://github.com/gratipay/gratipay.com/commit/d6f7989f62f57fd5a95a0e20cbb2ffdb7e8fb121

**Comment by whit537** [comment]
https://github.com/gratipay/gratipay.com/pull/3136

**Comment by whit537** [comment]
https://github.com/gratipay/gratipay.com/commit/d6f7989f62f57fd5a95a0e20cbb2ffdb7e8fb121#commitcomment-9828767

https://github.com/gratipay/gratipay.com/pull/3136#issuecomment-75126141

**Comment by whit537** [comment]
Yeah, I'm not finding an explanation for why we implemented throttling the way we did. I'm going to whack the sleep for this mail run.

**Comment by whit537** [comment]
Still might take a second per API call. We'll see. :)

**Comment by whit537** [comment]
The email queue doesn't look thread-safe to me, anyway.

**Comment by whit537** [comment]
So far so good ...

```bash
[gratipay] $ run_dammit defaults.env local.env -c ./env/bin/python bin/send-year-three.py 
2812
[snip]
Traceback (most recent call last):
  File "bin/send-year-three.py", line 37, in <module>
    assert len(participants) == 1
AssertionError
[gratipay] $

**Comment by whit537** [comment]
```diff
diff --git a/gratipay/models/participant.py b/gratipay/models/participant.py
index a8ae2f9..b20c04d 100644
--- a/gratipay/models/participant.py
+++ b/gratipay/models/participant.py
@@ -688,7 +688,7 @@ class Participant(Model, MixinTeam):
                 p = cls.from_id(msg.participant)
                 r = p.send_email(msg.spt_name, **pickle.loads(msg.context))
                 cls.db.run("DELETE FROM email_queue WHERE id = %s", (msg.id,))
-                if r == 1:
+                if 0 and r == 1:
                     sleep(1)
                 nsent += r
         return nsent
```

**Comment by whit537** [comment]
```diff
diff --git a/bin/send-year-three.py b/bin/send-year-three.py
index 698bb2b..1bd2363 100644
--- a/bin/send-year-three.py
+++ b/bin/send-year-three.py
@@ -34,8 +34,8 @@ print([(p.username, p.email_address) for p in random.sample(participants, 5 if N
 # ----------------------------------------- SAFETY BELT ----------------------------------------- #
 # ----------------------------------------- SAFETY BELT ----------------------------------------- #
 # ----------------------------------------- SAFETY BELT ----------------------------------------- #
-assert len(participants) == 1
-assert participants[0].email_address == 'chad@zetaweb.com'
+#assert len(participants) == 1
+#assert participants[0].email_address == 'chad@zetaweb.com'
 # ----------------------------------------- SAFETY BELT ----------------------------------------- #
 # ----------------------------------------- SAFETY BELT ----------------------------------------- #
 # ----------------------------------------- SAFETY BELT ----------------------------------------- #
diff --git a/gratipay/models/participant.py b/gratipay/models/participant.py
index a8ae2f9..b20c04d 100644
--- a/gratipay/models/participant.py
+++ b/gratipay/models/participant.py
@@ -688,7 +688,7 @@ class Participant(Model, MixinTeam):
                 p = cls.from_id(msg.participant)
                 r = p.send_email(msg.spt_name, **pickle.loads(msg.context))
                 cls.db.run("DELETE FROM email_queue WHERE id = %s", (msg.id,))
-                if r == 1:
+                if 0 and r == 1:
                     sleep(1)
                 nsent += r
         return nsent
```

**Comment by whit537** [comment]
Script started!

```bash
[gratipay] $ run_dammit defaults.env local.env -c ./env/bin/python bin/send-year-three.py > send-year-three.log
```

**Comment by whit537** [comment]
Queueing ...

**Comment by whit537** [comment]
Wish I turned off stdio buffering. :-/

**Comment by whit537** [comment]
Ack. I killed the script because I thought for a second that I had loaded up the production email queue, in which case the `dequeue_emails` in the script would compete with the one in thread in production. I've confirmed that I loaded up my local queue.

**Comment by whit537** [comment]
```sql
=# select count(*) from email_queue;                                                              
┌───────┐
│ count │
├───────┤
│  2628 │
└───────┘
(1 row)
```

**Comment by whit537** [comment]
Rerunning as ...

```python
#!/usr/bin/env python
"""This is a one-off script to send emails for #3510.
"""
from __future__ import print_function

import sys
class DevNull:
    def write(*a): pass
    def flush(*a): pass
sys.stdout = DevNull()
from gratipay.main import Participant
sys.stdout = sys.__stdout__


print("Flushing email queue ...")
nsent = Participant.dequeue_emails()
print("Sent {} email{}.".format(nsent, '' if nsent == 1 else 's'))
```

**Comment by whit537** [comment]
```bash
$ watch -n1 "psql gratipay-bak -c 'select count(*) from email_queue;'"
```

**Comment by whit537** [comment]
Definitely going faster than one per second. :)

**Comment by whit537** [comment]
Okay!

Emails 2315, Supper 1 :]

bbiab ...

**Comment by whit537** [comment]
```
Every 1.0s: psql gratipay-bak -c 'select count(*) from email_queue;'                  Mon Jun  1 20:05:51 2015

 count
-------
     0
(1 row)
```

**Comment by whit537** [comment]
:dancer:

**Comment by whit537** [comment]
Production Mandrill key removed from my `local.env`. :)

**Comment by whit537** [comment]
If I had it to do over again I would've emphasized the changes more: we're *not* "back to processing" for most users. :-(

**Comment by whit537** [comment]
Here is the only record we have of the Gratipocalypse mailing:

https://github.com/gratipay/gratipay.com/issues/3385#issuecomment-100043833

**Comment by mattbk** [comment]
> If I had it to do over again I would've emphasized the changes more: we're not "back to processing" for most users. :-(

I'd have to agree that there seem to be a fair number of people who didn't catch the team approval requirement.  Some have emailed support since then, some (as shown in these recent tweets) don't realize they aren't receiving anymore.

- https://twitter.com/EricMann/status/624284636823355393
- https://twitter.com/gregbell/status/623601380213850114

**Comment by whit537** [comment]
:-/

Let's try to do a better job of communicating with #3539.

P.S. Thanks for rep'ing on Twitter.

**Pull request closed without merging**
