### PR TITLE
Add a simple field to collect info re: projects

### PR DESCRIPTION
**Pull request by whit537**
One notch better than a note to email us. I think this is important to our pitch to companies, per https://github.com/gratipay/inside.gratipay.com/issues/987#issuecomment-304707443.

### CODE REVIEW

**Comment by whit537** [comment]
Ping @JessaWitzel @mattbk @dmk246 @rohitpaulk et al. for review!

**Comment by whit537** [comment]
I have an email ready to send to Yahoo once this is deployed.

**Comment by mattbk** [comment]
> Eep! Mind looking over your info for us?

None of the fields is highlighted...

**Comment by mattbk** [comment]
I get that error for all values above $1999.

Also can't enter decimals, even .00.

**Comment by mattbk** [comment]
> I get that error for all values above $1999.

Same for master.

**Comment by mattbk** [comment]
Just testing?

https://github.com/gratipay/gratipay.com/blob/aec50084e6a5bd28598ee417f4fa3e2e003225e4/gratipay/card_charger.py#L64

**Comment by whit537** [comment]
Yeah if you wire up a Braintree sandbox and turn the form on, then the CC form fields should highlight red when the amount is 2000+.

screen shot 2017-09-20 at 12 23 19 pm

**Comment by whit537** [comment]
Actually, I maybe lied ...

**Comment by whit537** [comment]
Alright, I see what you mean about the bad dollar amounts which simulate card charging problems not showing up with an error message in the UI. I don't think this PR introduces that problem though so can we reticket and proceed here?

**Comment by mattbk** [comment]
Not a problem for me.

**Comment by whit537** [comment]
Reticketed https://github.com/gratipay/gratipay.com/issues/4649.

**Pull request merged**
