### PR TITLE
implement UI for working with national identities

### PR DESCRIPTION
**Pull request by whit537**
&#x2B11; #3994

&larr; #4007 — #4009 &rarr;

#### Punchlist

- [x] remake against `master` once #4007 lands
- [ ] saving a verified identity should *also* be in the danger zone since it resets verification
- [ ] consider preventing even admins from seeing identity info
- [ ] write a test suite for `%countries.spt`
 - [x] I just noticed a test failure here already.

### CODE REVIEW

**Comment by whit537** [comment]
aff5bdd2a205f00777209e657f4dadcec6079cd8:

screen shot 2016-05-09 at 12 24 09 pm
screen shot 2016-05-09 at 12 25 59 pm
screen shot 2016-05-09 at 12 25 27 pm
screen shot 2016-05-09 at 12 25 42 pm

**Comment by whit537** [comment]
☺️ 

screen shot 2016-05-09 at 3 58 51 pm

**Comment by whit537** [comment]
df2b9b552f529768f480d7b3cc077dec27aeada3:

screen shot 2016-05-09 at 4 12 02 pm
screen shot 2016-05-09 at 4 12 10 pm

**Comment by whit537** [comment]
c45687a911e58427c0a392fe37b143d136e3e039:

screen shot 2016-05-09 at 4 37 04 pm

**Comment by whit537** [comment]
f50c3f995147eefe51f045ce6e0e7fe966cffee6:

screen shot 2016-05-09 at 5 25 56 pm

**Comment by whit537** [comment]
My thinking is that on the `/identities/` page where we have the list of identity cards, the "Add Identity" card/button will pop up a country chooser, and then clicking on the country will take you to `/identities/XX` where `XX` is a two-letter country code for a country we know about. That'll be where you can add, edit, and remove identity information.

**Comment by whit537** [comment]
Chooser into form in 506993d19d46591070a7e95c109be9d5f6dcd5a9:

77ku2ostmh

**Comment by whit537** [comment]
👍 

c483a6b67a9cc3787edd5c95dae0e1d9de3708ef:

hm0i8ueoaw

**Comment by whit537** [comment]
Alright, this one is far enough along for now.

**Comment by whit537** [comment]
I kinda like the cardy things. (I got them from PayPal, as I believe I mentioned somewhere.) We should use them for payment ~~routes~~ *methods* and maybe accounts elsewhere, too.

**Comment by rohitpaulk** [comment]
> I kinda like the cardy things.

Yh, uphold has them too

**Comment by whit537** [comment]
Alright, this one's gonna need a little attention first ...

**Pull request closed without merging**
