### PR TITLE
Add caching for pip

### PR DESCRIPTION
**Pull request by techtonik**
Container-based builds allow to cache files. There is support
for caching pip files with `cache: pip`, but because of
https://github.com/travis-ci/travis-ci/issues/3239 it gets disabled
if `.travis.yml` provides own install section. Therefore adding
cached dir manually.

### CODE REVIEW

**Comment by techtonik** [comment]
I don't see Travis kicking in to test that. Seems like #3262 needs to be merged first.

**Comment by Changaco** [comment]
I don't see how that would help. Almost all of the dependencies are in the `vendor/` dir, pip doesn't download them. It's compiling the C(++) libs that slows down our builds, we could try caching `env/lib/python2.7/site-packages`.

**Comment by Changaco** [comment]
Needs to be redone on top of master.

**Comment by techtonik** [comment]
How can I restore the branch to rebase on top?

**Pull request closed without merging**
