### PR TITLE
Soft-launch #BackTheStack!

### PR DESCRIPTION
**Pull request by whit537**
This evolves the "Wait ... What? Why?" section of the homepage into a "Campaign" section, hidden behind a querystring var until October 1.

screen shot 2017-09-27 at 12 01 29 pm

### CODE REVIEW

**Comment by whit537** [comment]
Ping @mattbk et al. Ready for review!

**Comment by whit537** [comment]
It also moves the credit card form into the banner with amount.

screen shot 2017-09-27 at 12 09 27 pm

**Comment by whit537** [comment]
[slack](https://gratipay.slackarchive.io/gratipay/page-100/ts-1506528108000431)

**Comment by mattbk** [comment]
http://localhost:8537/?i_am_fancy=yes works for me.

**Comment by whit537** [comment]
But not Travis ... :-/

**Comment by whit537** [comment]
lol left a set_trace! 😮 

https://travis-ci.org/gratipay/gratipay.com/builds/280502068#L1350

**Comment by whit537** [comment]
Green!

**Comment by mattbk** [comment]
Will merge this after #4651.

**Comment by JessaWitzel** [comment]
I just want to say YAY! and Looks Great!

**Pull request merged**
