### PR TITLE
Fix receiving page for anonymous users

### PR DESCRIPTION
**Pull request by rohitpaulk**
https://sentry.io/gratipay/gratipay-com/issues/122185928/

screen shot 2016-11-14 at 10 29 38 am

### CODE REVIEW

**Comment by rohitpaulk** [comment]
https://sentry.io/gratipay/gratipay-com/issues/122185928/

**Comment by whit537** [comment]
Over in #4197 we just started cleaning up our usage of 401 and 403. I've added a commit here to do the same. Ready to merge if you are, @rohitpaulk. 👍

**Comment by whit537** [comment]
(P.S. Previous head was 29108417b9b42e6d1b14b27b58f6a930cb6cd77d.)

**Comment by whit537** [comment]
Marked as resolved in Sentry.

**Pull request merged**
