### PR TITLE
Revise site copy to keep up with ToS changes

### PR DESCRIPTION
**Pull request by whit537**
Part of https://github.com/gratipay/inside.gratipay.com/issues/432.

### CODE REVIEW

**Comment by whit537** [comment]
@mattbk at https://github.com/gratipay/gratipay.com/issues/4148#issuecomment-255749892:

> If I get some time I'll dip into #4157 to move it along.

Cool, go for it. I started hacking locally but it's a mess.

**Comment by mattbk** [comment]
Sometimes I forget `make test`.

**Comment by mattbk** [comment]
Unfortunately I'm not sure what to do with the Aspen 302 errors.

**Comment by mattbk** [comment]
> tests/py/test_pages.py::TestPages::test_about_payments FAILED
> tests/py/test_pages.py::TestPages::test_about_payroll FAILED
> The command "LD_LIBRARY_PATH=/usr/local/lib make bgrun test doc" exited with 2.

**Comment by mattbk** [comment]
:turtle: :tada:

**Comment by mattbk** [comment]
Should we mention PayPal fees on pay _out_ under the following?

> WHAT ARE THE PAYMENT FEES? 

> Our credit card processor, Braintree, charges 2.9% + 30¢ per transaction. We upcharge ~users to cover this fee at cost, and Teams receive the face value of the payment. For example, we'll charge $20.91 to cover a $20 payment

**Comment by mattbk** [comment]
"Payments" is confusing to someone new--is it money I give? Is it money I receive?  Especially at `about/features/`, it goes from "giving" to "payments."

Can we use a different word? "Payins"?

**Comment by mattbk** [comment]
At the moment, "Features" reads like an FAQ and includes stuff that should be on "Pricing." Maybe "Features" could be "FAQ" (with pricing moved).

"Where do payments go?" is another confusing use of payments, because in this case it applies only to giving to the Gratipay Project.

**Comment by mattbk** [comment]
The discussion around "Payments" nomenclature was at https://github.com/gratipay/inside.gratipay.com/issues/117. I'm okay with it, but maybe we need a ticket on breaking site copy up into 
- what is helpful for givers and
- what is helpful for project owners

**Comment by mattbk** [comment]
If we're going to keep this copy, then [search should search projects as well](https://github.com/gratipay/gratipay.com/issues/3872):

> HOW DO I GIVE MONEY? 
> Browse or search for a project you want to give to, and then look for the prompt.

**Comment by whit537** [comment]
I noticed under #4217 that we mention "open work" on CONTRIBUTING.md. We should probably revise that here as well.

**Comment by mattbk** [comment]
Oops, crossed the streams there.

**Comment by mattbk** [comment]
Have to go, needs to be fixed more.

**Comment by whit537** [comment]
> crossed the streams there.

You said that was bad, Egon!

**Comment by mattbk** [comment]
Also mentioned in [readme](https://github.com/gratipay/gratipay.com/blob/master/README.md).

**Comment by whit537** [comment]
I changed the base to put this in line behind #4130 for #4221.

**Comment by whit537** [comment]
Rebased to remove merges and reversions; was 7648e980205926244b739cb94d154c2f7d2821d8.

**Comment by whit537** [comment]
Well that's a first—did we run out of entropy? 😳

screen shot 2016-12-06 at 1 30 07 pm

**Comment by whit537** [comment]
```
=================================== FAILURES ===================================
______________________________ TestHtml.test_200 _______________________________
self = <test_stats.TestHtml testMethod=test_200>
    def test_200(self):
>       fake_data.populate_db(self.db, 5, 5, 1)
tests/py/test_stats.py:84: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
gratipay/utils/fake_data.py:352: in populate_db
    payment_instructions.append(fake_payment_instruction(db, participant, team))
gratipay/utils/fake_data.py:173: in fake_payment_instruction
    ctime=faker.date_time_between(start_date)
env/lib/python2.7/site-packages/faker/providers/date_time.py:314: in date_time_between
    timestamp = random.randint(start_date, end_date)
/opt/python/2.7.12/lib/python2.7/random.py:242: in randint
    return self.randrange(a, b+1)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = <random.Random object at 0xcbe670>, start = 1481307351.0
stop = 1481043792.0, step = 1, _int = <type 'int'>
_maxwidth = 9007199254740992L
    def randrange(self, start, stop=None, step=1, _int=int, _maxwidth=1L<<BPF):
        """Choose a random item from range(start, stop[, step]).
    
            This fixes the problem with randint() which includes the
            endpoint; in Python this is usually not what you want.
    
            """
    
        # This code is a bit messy to make it fast for the
        # common case while still doing adequate error checking.
        istart = _int(start)
        if istart != start:
            raise ValueError, "non-integer arg 1 for randrange()"
        if stop is None:
            if istart > 0:
                if istart >= _maxwidth:
                    return self._randbelow(istart)
                return _int(self.random() * istart)
            raise ValueError, "empty range for randrange()"
    
        # stop argument supplied.
        istop = _int(stop)
        if istop != stop:
            raise ValueError, "non-integer stop for randrange()"
        width = istop - istart
        if step == 1 and width > 0:
            # Note that
            #     int(istart + self.random()*width)
            # instead would be incorrect.  For example, consider istart
            # = -2 and istop = 0.  Then the guts would be in
            # -2.0 to 0.0 exclusive on both ends (ignoring that random()
            # might return 0.0), and because int() truncates toward 0, the
            # final result would be -1 or 0 (instead of -2 or -1).
            #     istart + int(self.random()*width)
            # would also be incorrect, for a subtler reason:  the RHS
            # can return a long, and then randrange() would also return
            # a long, but we're supposed to return an int (for backward
            # compatibility).
    
            if width >= _maxwidth:
                return _int(istart + self._randbelow(width))
            return _int(istart + _int(self.random()*width))
        if step == 1:
>           raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
E           ValueError: empty range for randrange() (1481307351,1481043792, -263559)
/opt/python/2.7.12/lib/python2.7/random.py:218: ValueError
```

**Comment by whit537** [comment]
Not a loss of entropy, looks rather to be date-related in fake data ...

**Comment by whit537** [comment]
@kaguillera did warn me that we might hit something along these lines ...

**Comment by mattbk** [comment]
The first number is bigger than the second; that should be reversed.

**Comment by mattbk** [comment]
Related? https://github.com/joke2k/faker/issues/282

**Comment by mattbk** [comment]
Shouldn't `faker.date_time_between(start_date)` have an end date as well at https://github.com/gratipay/gratipay.com/blob/fb1f57ba737271d05c63b09b1a51b8a9b3dba34e/gratipay/utils/fake_data.py#L173? I guess it [defaults to `now`](http://faker.readthedocs.io/en/master/providers/faker.providers.date_time.html?highlight=date_time_between)?

If that's the case, is it generating future timestamps?

**Comment by whit537** [comment]
> Related? joke2k/faker#282

That could be the ticket: https://github.com/gratipay/gratipay.com/pull/4224#issuecomment-265289732.

**Comment by whit537** [comment]
Returning from #4224 ... aaaaaaaand we're green again here for some reason? ¯\\\_(ツ)\_/¯

**Comment by whit537** [comment]
Rebased, was 2d177269d619c2b09cd5d770d59c14ef55c0b395.

**Comment by whit537** [comment]
Rebased, was 8d6fb9df6356c7fde9459980af223677624b6980.

**Comment by mattbk** [comment]
I have moved my structural change ideas to different tickets in order to streamline this PR to just match up with ToS changes, including renaming teams to projects, and changing the direction of the marketing.

**Comment by mattbk** [comment]
I'm satisfied. Ready for review.

**Comment by whit537** [comment]
Base changed ... on deck! Rebased on new base, was 830a2e8d3001b43e7d2da3fdee0711d1d64e735a.

**Comment by whit537** [comment]
Alright @mattbk et al., you good with the latest commits? I'm ready to go if you are ...

**Comment by mattbk** [comment]
Looks good. I'm pushing the button.

**Comment by whit537** [comment]
AUP is messed up:

screen shot 2016-12-09 at 3 12 20 pm

**Comment by mattbk** [comment]
That happened to me at one point as well.

**Comment by whit537** [comment]
The "Apply for a project" button is broken for me now I think?

screen shot 2016-12-09 at 3 26 55 pm

**Comment by whit537** [comment]
> The "Apply for a project" button is broken for me now I think?

Due to bea29126964213a3b7f4b9f2d7d051cdb731874f, along with Travis failures. Backed that out.

**Comment by mattbk** [comment]
Good thing I didn't push the button.

**Comment by whit537** [comment]
:-)

I'm going over the ToS HTML formatting ...

**Comment by whit537** [comment]
My Vim wasn't formatting the Markdown lists properly.

http://superuser.com/questions/236138/how-can-i-get-vim-to-indent-all-the-lines-in-a-list-item-not-just-the-second

**Comment by whit537** [comment]
Okay, @mattbk. How about now? :-)

**Comment by whit537** [comment]
@mattbk Oh! Can you try "Squash and merge" with this one? Make sure you edit the commit message to remove all of the extra messages besides the first.

**Comment by whit537** [comment]
/me tries to stop tinkering ... 😊

**Comment by mattbk** [comment]
I tried in https://github.com/gratipay/gratipay.com/pull/4221/commits/d0f6b9403bf5218c11994f1e12f415a95105c9d7 via the command line because I didn't realize it could be done here...

**Comment by mattbk** [comment]
...so I'm not sure how to make this PR reflect that.

**Comment by whit537** [comment]
Ah, sorry, I should've been more clear. Maybe we should rebase d0f6b9403bf5218c11994f1e12f415a95105c9d7 off of #4221, and then redo the squash-and-merge using the GitHub UI, so GitHub knows what we did?

**Comment by mattbk** [comment]
Yeah, I'll see what I can do.

**Comment by whit537** [comment]
@mattbk Try `git rebase -i head^^` locally, on the `relax-open-work-requirement` branch? That should pop up an editor with further instructions. `head^^` specifies the commit two prior to `head`.

**Comment by whit537** [comment]
!m @mattbk

**Pull request merged**
