### PR TITLE
Fixed build issues on master. Fixes #3885

### LINKED ISSUE #3885: fix build on master
Reticketing from #3876.

https://travis-ci.org/gratipay/gratipay.com/builds/98361516

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/29592800-fix-build-on-master?utm_campaign=plugin&utm_content=tracker%2F85909&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F85909&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by aandis**

### CODE REVIEW

**Comment by aandis** [comment]
Haa!! It still failed. :open_mouth:

**Comment by aandis** [comment]
Checking

**Comment by aandis** [comment]
YES! :dancer: 
Ping @rohitpaulk . Does this look good?

**Comment by rohitpaulk** [comment]
Squash commits please? Other than that, this is ready to go :)

**Comment by aandis** [comment]
:+1:

**Comment by whit537** [comment]
!m @rohitpaulk @aandis 

Onboarding reticketed as https://github.com/gratipay/inside.gratipay.com/issues/465.

**Pull request merged**
