### PR TITLE
Echo the current branch in Travis

### PR DESCRIPTION
**Pull request by whit537**
This is helpful for understanding how Travis is interacting with commits pushed to a PR.

### CODE REVIEW

**Comment by whit537** [comment]
👍 

screen shot 2016-06-08 at 4 33 16 pm

https://travis-ci.org/gratipay/gratipay.com/builds/136260351#L167-L168

**Comment by whit537** [comment]
Ready for review/merge @rohitpaulk @aandis et al.

**Comment by rohitpaulk** [comment]
Wait.. How exactly is this helpful? Travis shows the commit hash in the UI. 

screen shot 2016-06-08 at 9 59 29 pm

**Comment by whit537** [comment]
@rohitpaulk That is the merge commit that GitHub automatically creates between the PR branch and `master`. However, what we were looking for is the commit on the PR branch that is being merged into `master`.

The scenario is that we were trying to rebase nine or ten commits (https://github.com/gratipay/gratipay.com/pull/4046#issuecomment-224719594) in such a way that Travis would test each of the new commits just as it had tested the old ones. We wanted to do this as fast as possible, meaning, we didn't want to wait for Travis to complete the test suite for one commit before pushing the next commit. What we discovered is that we could push the next commit as soon as Travis cloned the repo for a given commit—but not sooner. If we push too commits in too-quick succession, then the first build ends up cloning the second commit, and the test results are therefore inaccurate. Having the PR commit in the Travis log will enable debugging this kind of situation.

**Comment by rohitpaulk** [comment]
Aha! Gotcha.

**Comment by whit537** [comment]
!m @rohitpaulk

**Pull request merged**
