### PR TITLE
Fix CSP again

### PR DESCRIPTION
**Pull request by whit537**
Follow-on from #4250 ... here's one more, @EdOverflow.

(Rolled back again in Heroku.)

screen shot 2016-12-22 at 12 27 55 pm

### CODE REVIEW

**Comment by EdOverflow** [comment]
Since this is all sorted now, can we merge it into the `master` branch?

**Comment by whit537** [comment]
We're not out of the woods yet. This breaks local development, where everything is served on `localhost:8537`. Have you been able to stand up gratipay.com locally yet, @EdOverflow?

screen shot 2016-12-22 at 4 50 52 pm

**Comment by EdOverflow** [comment]
Sorry for not testing locally. I will do this first thing tomorrow and will report back.

**Comment by EdOverflow** [comment]
In order to fix this we must add `script-src 'self'` and `style-src 'self'`.

**Comment by EdOverflow** [comment]
Also I forgot to let you know that `img-src *` will block the `data:` URI. This should prevent malicious images from being embedded in a user's `STATEMENT` section (As seen on my page: https://gratipay.com/~EdOverflow/).

**Comment by whit537** [comment]
Okay, let's plan on cleaning this up tomorrow.

**Comment by whit537** [comment]
@EdOverflow Update: I need to focus on https://github.com/gratipay/inside.gratipay.com/issues/951 tomorrow morning, and then I need to go offline for the holiday. I expect to be around for two or three days next week, hopefully we can land this then.

**Comment by whit537** [comment]
I've registered for an account on report-uri.org (see https://github.com/gratipay/inside.gratipay.com/issues/952#issuecomment-269704557 for onboarding).

**Comment by whit537** [comment]
Alright, this is showing good results for me locally, and shouldn't throw errors anyway since it uses `-report-only`. Good to go, @EdOverflow?

**Comment by whit537** [comment]
Rebased, was be03f1fdf7f00831c6116c8b3061680ab67bb91f.

**Comment by whit537** [comment]
@EdOverflow You ready to merge here?

**Comment by whit537** [comment]
Merging without further ado to get `master` back on track.

**Comment by EdOverflow** [comment]
Thanks @whit537!

**Comment by whit537** [comment]
Deployed, looks like we're good! Now we can start monitoring report-uri.io for violations ...

**Pull request merged**
