### PR TITLE
Add user.participant to who can see giving numbers

### PR DESCRIPTION
**Pull request by mattbk**
https://github.com/gratipay/gratipay.com/issues/3783

Someone else should check this locally because I can't right now.

### CODE REVIEW

**Comment by whit537** [comment]
723392c52ed2c9c63dca17b8d76553a73d86652d will show for *any* authenticated user. We want something more like `user.participant == participant`.

**Comment by mattbk** [comment]
Looks good on local, ready for review.

**Comment by whit537** [comment]
Rebased on #3792 to pick up that fix, and then I inserted a couple commits with working tests for [hidden] behavior generally and failing tests for #3783. Original HEAD was bad66f95436ce66161907d02cabf1381d503689e.

**Comment by whit537** [comment]
Hmmm ... unrelated `UnicodeDecodeError`s ...

**Comment by whit537** [comment]
Alright, should be resolved. Let's see what Travis says ...

**Comment by whit537** [comment]
!m @mattbk

**Pull request merged**
