### PR TITLE
remove 'Other giving/receiving options'

### PR DESCRIPTION
**Pull request by nobodxbodon**
To address https://github.com/gratipay/gratipay.com/issues/4174#issuecomment-260133190, as we don't have any other giving/receiving options now, the whole section is removed.

### CODE REVIEW

**Comment by nobodxbodon** [comment]
Need some help here: which test case is failing? I don't see any "FAILED", and seems like a timeout?

**Comment by mattbk** [comment]
https://github.com/gratipay/gratipay.com/pull/4187

**Comment by nobodxbodon** [comment]
Sorry missed that. Gladly closing.

**Comment by mattbk** [comment]
Sorry, last night I couldn't do more than paste from my phone. It doesn't matter to me whose PR it is, I just wanted to let you know there was another one to draw from for inspiration.

**Comment by whit537** [comment]
All PRs belong to the whole team! 💃 

!m @nobodxbodon @mattbk

**Pull request closed without merging**
