### PR TITLE
replace communities leaderboards with a table

### LINKED ISSUE #3127: downgrade communities to tags
@wilkie on [Twitter](https://twitter.com/wilkieii/status/557594476563398656):

> I don't think @Gratipay can ever say they're for supporting worthwhile communities when the biggest receiver is 8chan 

b7z5oifiaaaaju4

I agree. For communities on Gratipay to be meaningful, they need to be curated. I've been thinking that we should partner with relevant organizations to curate each of the communities we have. So the [OSI](http://opensource.org/) would curate the "open source" community, jQuery Foundation -> jQuery, PSF -> Python, etc.

What should we do if we can't find a partner? Should we simply turn off communities that are large enough to matter but for which we can't find curators? Should we leave them as-is but clearly mark them as "uncurated"?

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/7904059-downgrade-communities-to-tags?utm_campaign=plugin&utm_content=tracker%2F85909&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F85909&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by whit537**
Partially addresses #3222, and sets us up for #3127.

### TODO

 - [ ] paging (cf. #3185)
 - [ ] clean up formatting a bit

### CODE REVIEW

**Comment by whit537** [comment]
screen shot 2015-03-23 at 6 29 11 pm

**Comment by Changaco** [comment]
This is about #3222, not #3127. I assume you're planning to make the table sortable, so it doesn't really fix #1928 either.

**Comment by whit537** [comment]
> This is about #3222, not #3127. 

The UI will need to change at least a little bit as part of #3127. For one, the sidebar doesn't make sense in the context of tags: one doesn't generally "organize" or "join" a tag; one isn't a "member" of a tag; the avatar no longer fits. We could simply drop the sidebar as on other pages (Search, Explore > Teams), but we also need to get the word "Member" out of "New Members."

However, I think #3127 actually requires a strong visual break from the current communities page. The point of #3127 isn't just to change `communities` to `tags` in our codebase, the point is to change the user's expectation from one of strongly identifying with others in the same *community* to weakly identifying with others using the same *tag*.

Since I've put #3222 out there as a general goal, I do see a chance to move us forward on both #3222 and #3127 at the same time by adopting a table layout for tags. Implementing #3222 for tags gives us a significant break from the current communities implementation.

It could make sense to do them as two separate PRs, but once the #3222 portion of this PR is done, the remaining work will largely be under the hood, and I think it won't bloat this PR too much to do it here.

> it doesn't really fix #1928 either.

Addressed on #1928.

**Comment by whit537** [comment]
I've narrowed the scope of this to be about #3222.

**Comment by whit537** [comment]
Turned off communities in #3706.

**Pull request closed without merging**
