### PR TITLE
Fix deadlock when trying to close an account

### LINKED ISSUE #3044: Cannot close (delete) my account
I works for a while but then I see an "Application Error" page from Heroku. Ostensibly the operation takes too long and Heroku kills the request.

### PR DESCRIPTION
**Pull request by Changaco**
Fixes #3044.

### CODE REVIEW

**Comment by clone1018** [comment]
@Changaco Would I need a fake payday for this to matter? It worked locally form I just want to make sure I'm testing it right.

**Comment by rohitpaulk** [comment]
When exactly does this happen? I'm trying to write a test for it, but can't seem to trigger that kind of behaviour. I created a team, added the person as a member, and then tried to close the account. What error should we be expecting?

**Comment by Changaco** [comment]
It happens when the participant has a non-zero balance and is part of a team. I've modified the tests to trigger the problem.

**Comment by Changaco** [comment]
Travis is green, the fix is trivial, I'm merging and deploying.

**Pull request merged**
