### PR TITLE
More idiomatic hooks

### PR DESCRIPTION
**Pull request by Changaco**
Split from #3189, requires more work. If I'm reading it right it breaks the CSRF check, yet tests are green, that's a problem.

### CODE REVIEW

**Comment by whit537** [comment]
@Changaco Is there a reason for 24b8cf51e7776618a6f8e829322953316db29701 that I'm missing? If you're good with 124e7221f226b83462ce4a80c4c75d4dd753e0f6 then I'm good to merge this.

**Comment by Changaco** [comment]
I've modified the tests to show why we can't use `return {}` for the CSRF hook.

**Comment by Changaco** [comment]
We were entirely skipping the CSRF stuff for `/assets/` and `/callbacks/`, with your version we're generating and returning tokens for these requests.

**Comment by whit537** [comment]
> We were entirely skipping the CSRF stuff for `/assets/` and `/callbacks/`, with your version we're generating and returning tokens for these requests.

Is that a big deal? Why?

**Comment by Changaco** [comment]
> Is that a big deal? Why?

It's bad for performance, but more importantly it could break asset caching because we're adding `Cookie` to the `Vary` header.

**Comment by Changaco** [comment]
Actually we don't, because `add_caching_to_response` overrides `Vary`. That's a bug.

**Comment by whit537** [comment]
> It's bad for performance

Its effect on performance is negligible, because we have a CDN in front of `/assets/`, and `/callbacks/` is low-traffic.

> but more importantly it could break asset caching because we're adding `Cookie` to the `Vary` header.

Fair enough. Fixed in e26b91a865c5bd0ab2ee7bcab56c2878e7ab0583.

**Comment by whit537** [comment]
> Actually we don't, because `add_caching_to_response` overrides `Vary`. That's a bug.

Is that a regression on this PR or is it a separate issue?

**Comment by Changaco** [comment]
> Is that a regression on this PR or is it a separate issue?

Separate issue, this PR doesn't modify `cache_static.py`.

**Comment by whit537** [comment]
Okay, I kicked Travis. We good here?

**Comment by Changaco** [comment]
> We good here?

I think so, yes.

**Pull request merged**
