### PR TITLE
Improve email subsystem

### PR DESCRIPTION
**Pull request by whit537**
https://github.com/gratipay/gratipay.com/pull/4335 turned up some dryrot. This is a start on cleaning it up.

### Todo

- [x] change base back to master

### CODE REVIEW

**Comment by whit537** [comment]
This one is ready next, @kaguillera @nobodxbodon.

**Comment by whit537** [comment]
Rebased, was 88cc37151b4cf5387298f01370f772fa643208d6.

**Comment by whit537** [comment]
I kicked Travis and we're green here again, @nobodxbodon et al.

**Comment by nobodxbodon** [comment]
Looks good and straightforward refactoring to me. Merging now.

**Comment by whit537** [comment]
Awesome, thanks @nobodxbodon!

**Pull request merged**
