### PR TITLE
Fix typo in German translation

### PR DESCRIPTION
**Pull request by pvorb**

### CODE REVIEW

**Comment by whit537** [comment]
Thanks, @pvorb! I've merged and deployed the change. Can you confirm whether it worked? If not we may have to [go through Transifex](http://inside.gratipay.com/howto/translate-gratipay).

**Comment by pvorb** [comment]
I can't see the change. It still says "Edieren".

**Comment by whit537** [comment]
Yeah, looks like your change was reverted in 13f9d8b0b77fb9c6653f4380d630c64736f5226e, meaning that Transifex is the source, and our po files are derived from there. I've fixed this in Transifex and redeployed. Mind checking one (hopefully) more time? :)

**Comment by pvorb** [comment]
The change went through.

image

**Comment by whit537** [comment]
Cool. Thank you! :-)

**Pull request merged**
